### ISSUE TITLE
Installation web page contains invalid URL for Debian

### ISSUE THREAD

**Issue by yngvark** [gopasspw/gopass#1010]
### Summary

https://www.gopass.pw/#install
tells me to download https://dl.bintray.com/gopasspw/gopass/pool/main/g/gopass/gopass-1.8.3-linux-amd64.deb. However that URL gives 404.  The latest version there is 1.8.0, https://dl.bintray.com/gopasspw/gopass/pool/main/g/gopass

### Steps To Reproduce

`wget https://dl.bintray.com/gopasspw/gopass/pool/main/g/gopass/gopass-1.8.3-linux-amd64.deb`

### Expected behavior

The URL to work.

### Additional info

Workaround, just go here to download: https://github.com/gopasspw/gopass/releases

**Comment by dominikschulz** [comment]
Indeed, sorry. Will need to fix the release workflow for good.

**Comment by djagoo** [comment]
[fixed](https://github.com/gopasspw/gopasspw.github.io/pull/6) (for now)

**Comment by dominikschulz** [comment]
👍
