### ISSUE TITLE
gopass otp should be able to search for a entry

### ISSUE THREAD

**Issue by lyze237** [gopasspw/gopass#1011]
### Summary
Hello!

It'd be neat if `gopass otp <entry>` could search for entries as well! (Same as `otp <entry>`)

### Steps To Reproduce

1. Create a entry: `/dev/cloudflare.com/<email>` with otp token.
2 Run `gopass cloudflare` and `gopass otp cloudflare` and look at the behaviour of both.

```
$ gopass cloudflare
Entry 'cloudflare' not found. Starting search...
Found exact match in 'dev\cloudflare.com\<email>'
```

```
$ gopass otp cloudflare

Error: failed to get entry 'cloudflare': Entry is not in the password store
```

Right now I need to run `gopass cloudflare` to get the full path and then copy paste the full path and enter `gopass otp <fullpath>` to get the otp token. I'd like to run gopass from windows search menu and just write `gopass otp -c cloudflare` and it'd copy the otp token into my clipboard, but this is not possible right now since it doesn't search and auto completes entries.

### Expected behavior

I expected that `gopass otp <entry>` should search for a entry the same way as `gopass <entry>` does:
* Match part of the filename and show the matching one
* If there are multiple matching ones, show a entry picker.

### Environment

- OS: Windows 10 Enterprise 64 bit
- gopass Version: gopass 1.8.3 (97ac44d93e48d378bfbb80180c54f76a8b1a5cef) go1.11.2 windows amd64
- Installation method: github release page binary zip file

**Comment by dominikschulz** [comment]
That sounds reasonable and easy to do. Will look into it ... some day.
