### ISSUE TITLE
otpauth links without exposing the TOPT secret

### ISSUE THREAD

**Issue by fgarcia** [gopasspw/gopass#1012]
Currently we can get TOPT authentication with just a link

otpauth://totp/github.com/me?secret=123123

Although the secret along the whole link will be kept safe, I would like to level up the security by just using a security key. I already use my Yubikey to unlock my gopass gpg session, but I would like to rely on it too to keep safe my TOPT secret too. So I could just write

otpauth://totp/yubikey/github.com/me

Would that be possible? What response from a like like that would need to integrate with gopass?

I've opened a issue at the Yubikey Authenticator repo

https://github.com/Yubico/yubioath-desktop/issues/321

**Comment by espoelstra** [comment]
If your TOTP is being handled by the yubikey you should retrieve the OTP code with `ykman oath codes --single Github`. It would be rather excessive to have gopass also try to handle interfacing with the Yubikey to pull these out or calling out to an external tool like `ykman`, especially considering the Yubico tools are mostly written in Python, while `gopass` is written in Golang.

**Comment by fgarcia** [comment]
Thanks, I am starting to realize that this feature goes too much into a minor detail / wish that might not justify the cost of supporting one more feature. I will close the issue myself.

However this seems to be part of a bigger use case I am facing with gopass (and any other password manager)

I love managing my passwords with gopass but I have extra content that I would like to keep out. For example I want to keep my Github backup codes separate, in my offline-offsite usb pendrive. Also I would not like to store my 2FA secret in the same place than my password. So now I have two things I want to link from my Github record: A link to the same record in my offline-pendrive and a link to my yubikey. 

I guess it is more a matter of making my own standard notation. I wonder if some type of yaml front matter like in Markdown would make things better.

**Comment by dominikschulz** [comment]
That's an interesting idea, but I agree with @espoelstra that interfacing with YubiKeys would make too much sense for gopass. Of course you can store your GPG keys on the YubiKey and use that with gopass, but using gopass directly is currently out of scope.
