### ISSUE TITLE
`gopass insert secret/that/exists key=value` wants to overwrite password instead of just adding new key/value pair

### ISSUE THREAD

**Issue by espoelstra** [gopasspw/gopass#1013]
### Summary
When initially creating a secret with `gopass generate secret/path/site username=someuser` I properly get prompted for password parameters. When attempting to add a new `key=value` with `gopass insert secret/path/site totp=totp://some/url/for/totp` it wants to overwrite the password, not simply add the key/value pair. If I had instead done `gopass generate secret/path/site newkey=newvalue` I would expect it to keep the existing keys around (PATCH in REST-like terms instead of a REPLACE).

I see in #503 and #192 there was some work around the Yaml parsing, one added the `---` separator that no longer appears to exist or be required? Not sure if any of those caused this weird behavior.

### Expected behavior
I would expect to be able to add or replace key=value information via `gopass insert` or `gopass generate` (if I'm intentionally replacing a password AND maybe updating a "PIN" or something) without having to `gopass edit secret/path/site` and mess with the entry in a text editor.

### Environment
- OS: Mac OS X High Sierra
- OS version: `Darwin MN-C02VT1MAHTD8 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin`
- gopass Version: 1.8.2
- Installation method: brew bottle

**Comment by dominikschulz** [comment]
You can update K/V entries using `gopass entry key` where you will be asked for the new value or `gopass generate entry key` where only the value of this key will be updated.

A syntax like `key=value` was never supported.

We can certainly consider adding this, if someone wants to work on it.

**Comment by shibumi** [comment]
@dominikschulz can you further explain what you mean with `Edit: Actually key=value is supported for additional metadata`? I want to add additional metadata to the key file without changing the password everytime. Any Idea?

**Comment by carnager** [comment]
Want to add to this too. While it *is* possible to add stuff via stdin with `echo "\nfoo: bar" | gopass insert -a entry` this is not a nice solution since one has to take care of the yaml syntax.

**Comment by shibumi** [comment]
Ok, the following works:

`printf "test" | gopass insert <entry> <key>`

**Comment by carnager** [comment]
> Ok, the following works:
> 
> `printf "test" | gopass insert <entry> <key>`

Ah yes, that's actually kind of good enough :+1:
