### ISSUE TITLE
gpg backend: document gpg-agent's auto-expand-secmem option

### ISSUE THREAD

**Issue by tagirb** [gopasspw/gopass#1016]
### Summary
gopass with GPG backend may fail in case of a large number of concurrent requests. GPG will return exit status 2 and an error message "gpg: decryption failed: No secret key".

The reason is that `gpg-agent` has insufficient secret memory for processing many concurrent requests. There is an option `auto-expand-secmem`, which fixes this behavior by auto increasing the secret memory as needed. The option needs to be set in `~/.gnupg/gpg-agent.conf` and followed by the `gpg-agent` restart (`killall gpg-agent` will suffice).

Please document this somewhere. This was the only major blocking issue we've had with gopass.

**Comment by dominikschulz** [comment]
Thanks a lot for providing this hint. I wasn't aware of this option. We'll put it in the documentation.

**Comment by tagirb** [comment]
I was just lucky to find a couple of similar bug reports: 
https://dev.gnupg.org/T4146
https://dev.gnupg.org/T3530

**Comment by dominikschulz** [comment]
I'll add a note to the FAQ. Unfortunately I don't see an easy way to do runtime checks, as this option is not available for all versions of GnuPG and checking it would be noisy and/or error prone.

**Comment by tagirb** [comment]
Good enough for me, thanks a lot! :)

**Comment by marco-m-pix4d** [comment]
@tagirb you saved many years of my life, thanks a lot! ❤️
