### ISSUE TITLE
create or new results in "Error: user aborted"

### ISSUE THREAD

**Issue by gkotian** [gopasspw/gopass#1032]
### Summary
Attempting to run `gopass create` or `gopass new` results in the error `Error: user aborted`

### Steps To Reproduce
Simply run `gopass create` or `gopass new`
```
➜ gopass create

Error: user aborted
➜ gopass new   

Error: user aborted
➜
```

### Expected behavior
Either proper functionality, or a better error message if the syntax of the create/new command was wrong.

### Environment

- OS: `Ubuntu 18.04`
- OS version: `Linux labs-319 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- gopass Version:
```
gopass 1.8.4 (47d1c43d 2019-01-02 14:30:40) go1.10.7 linux amd64
<root>     -  gpg 2.2.3 - noop 0.0.0 -   fs 0.1.0
Available Crypto Backends: gpgcli, openpgp, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
```
- Installation method: using docker

### Additional context
N/A

**Comment by dominikschulz** [comment]
Thanks for reporting this issue.

This does not happen when I try to reproduce it.
Maybe the curses UI isn't working properly in Docker? Could you try to run it outside of docker, please?

But the error message should definitely be better.

**Comment by gkotian** [comment]
Sorry I haven't had a chance to update on this. Unfortunately, my current setup is such that I can only run this in a docker container. I'll close this for now, and reopen in future if I manage to reproduce it outside of docker.
