### ISSUE TITLE
Clashing entries results in "Error: user aborted"

### ISSUE THREAD

**Issue by gkotian** [gopasspw/gopass#1033]
### Summary
Attempting to run `gopass show a` when there are multiple entries starting with "a" results in the error `Error: user aborted`.

### Steps To Reproduce
Suppose your gopass structure is as follows:
```
gopass
└── Privacy+Security
    ├── alpha
    └── apple
```
Then if you run `gopass show a`, it results in:
```
➜ gopass show a   
Entry 'a' not found. Starting search...

Error: user aborted
➜
```

### Expected behavior
A better error message telling me that "a" can match multiple entries.

### Environment

- OS: `Ubuntu 18.04`
- OS version: `Linux labs-319 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- gopass Version:
```
gopass 1.8.4 (47d1c43d 2019-01-02 14:30:40) go1.10.7 linux amd64
<root>     -  gpg 2.2.3 - noop 0.0.0 -   fs 0.1.0
Available Crypto Backends: gpgcli, openpgp, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
```
- Installation method: using docker

### Additional context
If I run `gopass show x` (note that there is no entry starting with "x"), then I get a better error message:
```
➜ gopass show x
Entry 'x' not found. Starting search...

Error: no results found
➜
```

**Comment by dominikschulz** [comment]
It seems something is wrong with your terminal. The curses UI doesn't seem to work.

**Comment by gkotian** [comment]
Just like #1032, I will close this for now; and reopen in future if necessary. Apologies for not having followed this up sooner.
