### ISSUE TITLE
-c after password name

### ISSUE THREAD

**Issue by lol768** [gopasspw/gopass#1035]
This is probably WAI but it's a bit annoying for users who've come from `pass` and the parity would be useful for the sake of muscle memory:

Previously, I could invoke `pass <name> -c` or `pass -c <name>`. With `gopass`, the former approach fails with a `Error: failed to retrieve key '-c' from '<name>': key not found in YAML document` message.

**Comment by dominikschulz** [comment]
Thanks for reporting this.

Unfortunately this is a limitation of the CLI library we use and the feature set we offer.
