### ISSUE TITLE
clone failing in v. 1.8.4

### ISSUE THREAD

**Issue by scottfwilliams** [gopasspw/gopass#1036]
### Summary
`gopass clone` is returning errors after first-time install using version 1.8.4.
The steps documented below worked successfully when used with version 1.8.3
`(gopass 1.8.3 (97ac44d93e48d378bfbb80180c54f76a8b1a5cef) go1.11.2 darwin amd64)`

### Steps To Reproduce
`$ brew install gopass (version 1.8.4)`  
`$ gopass`  
It seems you are new to gopass. Do you want to run the onboarding wizard? [Y/n/q]: `y`  
	`Local store`  
	[init] [local] Initializing your local store ...  
	Please select a private key for encrypting secrets:  
  [0] gpg - 0x7F48096E2B7FB4E0 - MyEmail (gopass) <my.email@company.com>  
	Please enter the number of a key (0-0, [q]uit) [0]: `0`  
	Use MyEmail (my.email@company.com) for password store git config? [Y/n/q]: `y`  
	[init] [local]  -> OK  
	[init] [local] Configuring your local store ...  
	[init] [local] Do you want to add a git remote? [y/N/q]: `n`  
	[init] [local] Do you want to always confirm recipients when encrypting? [y/N/q]: `n`  
	[init] [local]  -> OK  
	gopass
  
`$ gopass clone https://github.server.company.com/RUBIE/passwd.git rubie`

### Expected behavior
Remote repository is cloned as local sub-store named `rubie`

### Actual behaviour
Receive this error message: `Error: Failed to add mount: failed to add mount: 
failed to init sub store: password store rubie is not initialized. Try gopass init
 --store rubie --path gpgcli-gitcli-fs+file:///Users/myusername/.password-store-rubie`

### Environment
* OS: Mac OS X High Sierra
* OS Version:	`Darwin a45e60e47edd 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
macOS 10.13.6 (17G65)`
* gopass Version:  
```
gopass 1.8.4 (a5442953608c3380efdddcfe2f6d6d123fd5605f 2018-12-27 10:08:02) go1.11.4 darwin amd64
<root>     - gpg 2.2.12 - git 2.19.1 -   fs 0.1.0
Available Crypto Backends: gpgcli, openpgp, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
```
* Installation method: brew

### Additional context
Version 1.8.4 behavior is the same when installed using `go get`

**Comment by dominikschulz** [comment]
Thanks for reporting this issue. This was indeed broken with 1.8.4. Will be fixed in the next release.
