### ISSUE TITLE
Contact e-mail is broken

### ISSUE THREAD

**Issue by ptxmac** [gopasspw/gopass#1041]
From the homepage: 
```
Contact
Email: gopass@gopass.pw
```

I tried sending a mail, but got the following automatic reply:
> We're writing to let you know that the group you tried to contact (gopass) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:

**Comment by dominikschulz** [comment]
Thanks for reporting this. I need to ask @zwopir to have a look.
