### ISSUE TITLE
Question: Mobiles

### ISSUE THREAD

**Issue by gedw99** [gopasspw/gopass#1046]
There is a plugin for Browsers, but what about Mobiles.
Once a user has exported for example their passwords out of chrome into gopassword then on their laptop all is great, but then on their mobile they are now stuck.

One thing that come sot mind is to make a Flutter plugin for gopassword.
I use flutter with golang all the time where the plugins are programmed in golang runnng on the mobiles. SO its nice dev experience.

It woudl mean that anyone building an app can use it.
But the bigger question is where to get the passwords from ?
I see a few use cases:
1. The user has their passwords backed up to S3 and the flutter plugin has a Master key stored in the  TPM ( easy to do with flutter). The flutter plugin just keeps synced with S3.
2. The usr runs a raps Pi at home and this is their s3.

If you have any questions about flutter i can answer them.
But i am curious what the maintainers and people things about Mobile.
I have not at all touched on the other aspect of Browsers on Mobiles because they do not support extensions and so i currently see no way to support them.

**Comment by dewey** [comment]
You can just use the existing mobile apps, here's a bunch of [more clients](https://www.passwordstore.org/#other) too.

https://mssun.github.io/passforios/ iOS
https://github.com/zeapo/Android-Password-Store#readme Android

**Comment by gedw99** [comment]
thanks @dewey 

AH but none reusing the golang code then from what i saw in the links.
Wil have to do it myself i guess :)

**Comment by dewey** [comment]
Yes, but the app would checkout the git repository that contains the password store and would act as a client on it. Wouldn't that do exactly what you want?
