### ISSUE TITLE
Add ability to use passphrase

### ISSUE THREAD

**Issue by majkinetor** [gopasspw/gopass#1047]
It would be nice if gopass would allow using passphrase instead of public keys especially since it already works in such case but prompts all the time . In such case `gpg.exe` requires `--passphrase` option to be set and that is the only change.

I created a simple PowerShell version which works with both GPG keys and passphrase (it defaults to keys but you can set env var PASSPHRASE to use it instead).
* https://github.com/majkinetor/pass

This is easier to setup in certain situations, particularly with solo development work, small teams or teams where GPG knowledge is not present.

**Comment by dominikschulz** [comment]
Unfortunately I don't see how this would play well with gopass. Many of the features are built around the key-based gpg mode .

Using the symmetic passphrase would probably be possible, break with many existing features so I wouldn't recommend to implement it.

**Comment by majkinetor** [comment]
It wouldn't break any features if they explicitly do not work with passphrases. Some of the features actually do not make sense with it.

**Comment by rawtaz** [comment]
I have been looking for this as well. For those of us that don't use GPG and have no reason to do so, it makes a lot of sense to be able to use an awesome tool like `pass` or `gopass` without GPG. Having to add additional software and manage key files in a secure way just adds complexity and does not make sense for those of us that don't use GPG.

I understand everyone's use case is different and many people use GPG, but I'd just like to highlight that it would be great if `gopass` supported only passphrases as well.

**Comment by majkinetor** [comment]
I was talking about GPG passphrase but any option is OK.
Yes, the basic problem is that GPG key management is overkill and introduces uneeded complexity for small teams or projects.
