### ISSUE TITLE
'gopass binary cat' error with Jenkins pipeline

### ISSUE THREAD

**Issue by abessifi** [gopasspw/gopass#1051]
### Summary

I'm trying to use gopass inside a Jenkins Pipeline and I get an error (No public key) when I tried to read the content of a file (a token) with the `gopass binary cat test-gopass/foo/bar`.
The error I've got is the following:

```
[...]
+ gopass binary cat test-gopass/foo/bar
gpg: B5B4BE68301B70047EB8FE3B93CB409BD2322BD7: skipped: No public key
gpg: [stdin]: encryption failed: No public key
2019/01/21 23:40:13 Failed to encrypt
[...]
```

Other details:

- The command is executed in a Jenkins slave running as a container.
- Running the same command on my system works fine.
- `gopass show test-gopass/foo/bar`  works fine and displays the base64 encoded data.
- Runing the command in debug level gives the following output:

```
[...]
+ GOPASS_DEBUG=true
+ gopass binary cat test-gopass/foo/bar
[DEBUG] Trying to load config from /home/jenkins/.config/gopass/config.yml
[...]
[DEBUG] fs.Get(.gpg-id) - /home/jenkins/test-gopass/.gpg-id
[DEBUG] gpg.listKeys: /usr/bin/gpg [/usr/bin/gpg --with-colons --with-fingerprint --fixed-list-mode --list-secret-keys B5B4BE68301B70047EB8FE3B93CB409BD2322BD7]
[DEBUG] gpg.listKeys: /usr/bin/gpg [/usr/bin/gpg --with-colons --with-fingerprint --fixed-list-mode --list-public-keys B5B4BE68301B70047EB8FE3B93CB409BD2322BD7]
[DEBUG] gpg.listKeys: /usr/bin/gpg [/usr/bin/gpg --with-colons --with-fingerprint --fixed-list-mode --list-secret-keys B5B4BE68301B70047EB8FE3B93CB409BD2322BD7]
[DEBUG] gpg.Encrypt: /usr/bin/gpg [/usr/bin/gpg --quiet --yes --compress-algo=none --no-encrypt-to --no-auto-check-trustdb --encrypt --trust-model=always --recipient B5B4BE68301B70047EB8FE3B93CB409BD2322BD7 --recipient D19ACC69CCC4E1726D17034B19115B61E8F25EBA --recipient 0x19115B61E8F25EBA]
gpg: B5B4BE68301B70047EB8FE3B93CB409BD2322BD7: skipped: No public key
gpg: [stdin]: encryption failed: No public key
[DEBUG] Failed encrypt secret: exit status 2
2019/01/21 18:31:59 Failed to encrypt
```

- I seems like the command is receiving something from STDIN which changes the behavious of the `gopass binary cat` and instead of printing the decrypted and decored secret to STDOUT, gopass is trying to create new secret from the input data but as the public key is remaining, gpg sucks.

- When I disable the STDIN for the gopass command, as follow, the command runs correctly and I get the expected output:

```
gopass binary cat test-gopass/foo/bar < /dev/null
```

### Steps To Reproduce

I use the following Jenkins Pipeline with the `sh` groovy directive to execute the `gopass binary cat` command:

```
node ('jenkins-slave-gopass') {
  stage('Gopass Crypt Unlock') {
    withCredentials([file(credentialsId: 'jenkins-gpg-keys', variable: 'JENKINS_GPG_KEYS_FILE')]) {
      sh 'gpg --batch --import ${JENKINS_GPG_KEYS_FILE}'
    }
    sh '''
      echo "[INFO] Setting up global Git configuration"
      git config --global user.name jenkins
      git config --global user.email jenkins@foo.bar
      git config --global --list
    '''

    dir('/home/jenkins/test-gopass'){
      git credentialsId: 'jenkins-git-credentials', branch: 'master', url: 'https://foo.bar.baz/quax/test-gopass'
    }

    sh '''
      echo "[INFO] Init Gopass secrets store"
      gopass config autosync false
      gopass --yes init jenkins@foo.bar
      gopass --yes mounts add test-gopass /home/jenkins/test-gopass
      gopass binary cat test-gopass/serviceaccounts/tokens/builder
    '''
  }
}
```
### Expected behavior

`gopass binary cat test-gopass/foo/bar` should print the secret value and not updating it.

### Environment

- system / container image: Linux/RHEL 7.4
- gopass version: 1.8.3 (installed from a binary from github)
- gpg version: 2.0.22
- Jenkins version: 2.82.2

**Comment by martinhoefling** [comment]
You might need to set the trust level of your key correctly. Otherwise the key is not found by gpg.

**Comment by abessifi** [comment]
This issue is not related to the trust level of the public keys.
I add @dominikschulz to this issue.

To summarize, running the `gopass binary cat test-gopass/foo/bar` command into a Jenkins Slave Container (running into OpenShift) didn't work and rises the following error:

```
gpg: B5B4BE68301B70047EB8FE3B93CB409BD2322BD7: skipped: No public key
gpg: [stdin]: encryption failed: No public key
2019/01/21 23:40:13 Failed to encrypt
```

Now, running the same command with "blocking" STDIN, works fine:

```
$ gopass binary cat test-gopass/foo/bar </dev/null
```

In the first case, it seems like `gopass binary cat` is trying to read and encrypt something that it recieved from STDIN.

Is there a way to debug this by displaying what data gopass receive before calling GPG for encryption ?

**Comment by martinhoefling** [comment]
You can export GOPASS_DEBUG=1 in your pipeline, that could reveal some insights.

**Comment by abessifi** [comment]
I've already did that and nothing interested was revealed. In my first comment I've already put a chunck of the debug output message that concern gpg.
I'm not sure that his issue is related to gopass and just wanted to get some help from you guys.
@dominikschulz did you played a bit with gopass inside containers before in non interractive mode ?

**Comment by dragon788** [comment]
@abessifi What happens if you perform all your steps in a single `sh` step instead of spread across multiple steps within the `stage`?

**Comment by abessifi** [comment]
This seems to be a problem not related directly to Gopass but maybe to Jenkins and how it runs the shell commands.
