### ISSUE TITLE
Add project to Compatible Clients on the `pass` site

### ISSUE THREAD

**Issue by MartinBrugnara** [gopasspw/gopass#1071]
### Summary
This project should be listed in the _Compatible Clients_ on the [pass](www.passwordstore.org) site.

### Action
Request [Jason A. Donenfeld](mailto:Jason@zx2c4.com) to add the project to the list.

### Possible issues
There exists already an entry _gopass_ there, but does __not__ point to this project.
It does point to [cortex\'s](https://github.com/cortex/gopass) which is deprecated - UNMAINTANED .

**Comment by dominikschulz** [comment]
Good idea, feel free request inclusion of gopass to that list.
