### ISSUE TITLE
Explicitly creating a new store with PASSWORD_STORE results in a warning

### ISSUE THREAD

**Issue by prologic** [gopasspw/gopass#1075]
```
$ PASSWORD_STORE=$PWD gopass init
[init] Initializing a new password store ...
[init] WARNING: Store is already initialized
```

Is this expected? I'm concerned this will collide with my existing password-store in `$HOME` using the traditional `pass` utility. My use-case here is I'm trying to leverage the enhanced team-based features og `gopass` here and explicitly create a new team-based secrets store for some internal secrets.

**Comment by dominikschulz** [comment]
What are you trying to do?

If you just run gopass without any environment variable you should be able to interact with your existing password store right away.

**Comment by prologic** [comment]
I was trying to create a different store from my `$HOME/.password-store`. sorry if my OP was confusing.

**Comment by rEnr3n** [comment]
It doesn't allow creation of a parallel store. It just allows sub-store.
```
~/.password $ gopass init
[init] Initializing a new password store ...
[init] WARNING: Store is already initialized
Please select a private key for encrypting secrets:
[0] gpg - <REDACTED>
[1] gpg - <REDACTED>
Please enter the number of a key (0-1, [q]uit) [0]: 1

Error: failed to initialize store: failed to init store '' at '/home/user/.password-store': failed to initialize new sub store: Found already initialized store at /home/user/.password-store.
You can add secondary stores with gopass init --path <path to secondary store> --store <mount name>: Found already initialized store at /home/user/.password-store.
You can add secondary stores with gopass init --path <path to secondary store> --store <mount name>
```

**Comment by prologic** [comment]
That's sadly a very confusing behaviour :/ But thanks for clearing that up!

**Comment by spinningarrow** [comment]
I'm trying to do the same thing i.e. have my password stores in a directory different to the home directory. @rEnr3n can you explain what is happening or how to clone a password store to a directory other than the home directory? So far nothing I've tried works.

**Comment by rEnr3n** [comment]
I don't think it allows you to change your root store. It just allows you to mount substores from other directories. It will look similar to this.

```
gopass
├── NewStore (/home/vagrant/NewStore)
│   └── test1
└── test1
```
Root store has 1 secret. One substore with the same secret (copied over).

---
Here are the commands I ran on a clean vm
1. `gopass` (follow the wizard)
1. `gopass generate test1`
1. `mkdir NewStore`
1. `gopass mounts add NewStore ~/NewStore`
1. `cp .password-store/test1.gpg ~/NewStore`

**Comment by fire** [comment]
For future searchers of this issue:

> By default gopass setup will use gpg encryption and git storage. This will create a new password store in $HOME/.local/share/gopass/stores/root and a configuration in $HOME/.config/gopass/config using gpg encryption and git for versioned storage.

**Comment by AnomalRoil** [comment]
You can also specify another directory for the `.config` and `.local` folders using the env variable `GOPASS_HOMEDIR=/some/other/path`
