### ISSUE TITLE
Gopass does not clear the clipboard

### ISSUE THREAD

**Issue by ashfaqfarooqui** [gopasspw/gopass#1080]
When I use ``gopass -c <my-file>`` the password is copied to the clipboard and should be cleared in 45s. I get a notification that my password is cleared, and using ctrl+v ensures I cannot paste anything. However, if I open my clipboard (copyq) in my case I can still see and access the password.

### Steps To Reproduce

1) Copy the password using ``gopass -c <my-file>``
2) Wait for 45s to get notified that the password is deleted.
3) Open clipboard utility (copyq), the password hasn't been cleared.

### Environment

- OS: Manjaro linux, with i3 DM
- OS version:Linux 42 4.14.102-1-MANJARO #1 SMP PREEMPT
- gopass Version: 1.8.4.2
- Installation method: Package manager

**Comment by dominikschulz** [comment]
Thanks for reporting this issue.

Unfortunately gopass can not, and will not, support any possible clipboard manager out there.
We can't possibly detect any binary listening for clipboard changes. There is some discussion and work on avoiding the clipboard altogether, but if you choose to use the clipboard you need to be careful with such programs.

Feel free to submit a PR to support copyq.

**Comment by dastier** [comment]
The copyq declares "[Ignoring clipboard copied from some windows or containing some text](https://hluk.github.io/CopyQ/)" as one of its features.

**Comment by dominikschulz** [comment]
It shouldn't be too hard to implement this, but I'm not going to have time for that anytime soon:
https://copyq.readthedocs.io/en/latest/scripting-api.html#disable

**Comment by AnomalRoil** [comment]
@dastier @ashfaqfarooqui Doesn't this allow you to exclude gopass from the application `copyq` will copy from:  https://copyq.readthedocs.io/en/latest/faq.html#how-to-omit-storing-text-copied-from-specific-windows-like-a-password-manager

I'm thinking about closing this, since as @dominikschulz said, we cannot support all the different clipboard that exist and keep reducing our code complexity.
