### ISSUE TITLE
Fuzz code base

### ISSUE THREAD

**Issue by dewey** [gopasspw/gopass#1081]
Hey,

saw there's a fuzzing-as-a-service platform called Fuzzbuzz that supports Go that just launched on Hackernews: https://news.ycombinator.com/item?id=19265377

It's free in a limited version. Would that make sense for security critical software like gopass? Looks like it integrates nicely with Github.

**Comment by dominikschulz** [comment]
Fuzzying is mostly useful for parsing untrusted (binary) input, we don't have too many of those in gopass. But feel free to open an PR addressing all (or some) of the ones we have. There are definitely a few places where fuzzying could make sense

**Comment by everestmz** [comment]
Hey there! Saw this issue while trawling GitHub! Would be happy to help get this set up on Fuzzbuzz if needed :)
