### ISSUE TITLE
Gopass doesn't syncing with repository

### ISSUE THREAD

**Issue by sevenmaxis** [gopasspw/gopass#1091]
I've installed gopass on Ubuntu 18.04 host, everything is working fine except one thing.

When I run syncing command:

```
$ gopass sync                                                        
Sync starting ...
[<root>]
   WARNING: Mount uses RCS backend 'noop'. Not syncing!
All done
```

I didn't encountere such problem on Mac OS

Update:
When I'm creating/inserting password, it didn't add gpg file to repository, just put that file in `~/.password-store`

**Comment by Woile** [comment]
I think you need to set `gitcli` as the syncing backend.

If you type `gopass config` and check the `path`, I think it should say `noop` there, replace it with `gitcli`.

In linux the config is located in `~/.config/gopass/config.yml`.

**Comment by sevenmaxis** [comment]
Thanks
That is exactly what I needed

**Comment by bickman** [comment]
How to set path using gopass config command

**Comment by dominikschulz** [comment]
That's fixed in master, but not yet part of any release.
