### ISSUE TITLE
Created Cheatsheet + Presentation

### ISSUE THREAD

**Issue by Woile** [gopasspw/gopass#1092]
Hey folks I've just created a cheatsheet and a presentation. 

I would really appreciate if anyone could take a look and give some feedback.

I have only tested it on linux so far.

Feel free to use the presentation/cheatsheet to spread the word.
 
[Presentation](https://woile.github.io/gopass-presentation/) | [Github](https://github.com/Woile/gopass-presentation)

[Cheatsheet](https://woile.github.io/gopass-cheat-sheet/) | [Github](https://github.com/Woile/gopass-cheat-sheet)

**Comment by dominikschulz** [comment]
Wow, that is pretty cool. Thanks a lot!

Do you mind if we link to those?

**Comment by Woile** [comment]
Not at all, feel free to link it or anything. Just check I haven't screwed it somewhere. 

I've tested all the commands, played for quite some hours in multiple docker containers, but I'm not 100% I'm using everything as intended (I hope so haha).

Cheers!

**Comment by Woile** [comment]
Here's the [blog post](https://woile.github.io/posts/sharing-team-secrets/) again, feedback is welcome!

I'm closing the issue.

**Comment by dominikschulz** [comment]
Reopening, I still need to add the links.
