### ISSUE TITLE
`gopass git` doesn't actually allow any git command

### ISSUE THREAD

**Issue by tmccombs** [gopasspw/gopass#1093]
### Summary
`gopass git` only seems to accept a (pretty small) subset of git commands, despite the help message saying that it will "Run any git command inside a password store".

### Steps To Reproduce

Run a git command with gopass such as `gopass git status` or `gopass git log`.

### Expected behavior

Run the supplied git command in the directory for the password directory.

### Environment

- OS: Archlinux
- OS version: 5.0.1-arch1-1-ARCH #1 SMP PREEMPT
- gopass Version: 1.8.5
- Installation method: pacman

**Comment by dominikschulz** [comment]
Indeed, we need to update the documentation. It's no longer supposed to support any git command.

**Comment by guggens** [comment]
Yeah, stumbled upon that too. Additionally, I have not grasped the context why all git commands are proxied and why I cannot use the password store as a normal git repository, e.g. add an readme for the team how to setup gopass. Can you explain? Didn't find any documentation for that.

**Comment by tmccombs** [comment]
> why I cannot use the password store as a normal git repository

You can, you just have to run git commands directly in your password repository (usually ~/.password-store). Although I also don't understand why the git commands are proxied like they are.
