### ISSUE TITLE
`git push` default to origin & master

### ISSUE THREAD

**Issue by ewoutp** [gopasspw/gopass#1096]
### Summary
I expect `gopass git push` to default to `gopass git push origin master`.

I don't see why `gopass git pull` can default as expected, but `gopass git push` does not.

### Environment
- OS: MacOS 10.14.3
- gopass Version: gopass 1.8.5-git+HEAD go1.12 darwin amd64
- Installation method: go get -u

**Comment by metalmatze** [comment]
I don't see a reason either. Probably it simply wasn't implemented that way.

**Comment by dominikschulz** [comment]
Both should default to `origin master`. Will check that.

**Comment by ewoutp** [comment]
Humm.. bug still exists afaik. So closing (I know by bot) does not really work well

**Comment by nikaro** [comment]
Should not it be re-opened? It seems it is still not fixed.
