### ISSUE TITLE
JSON API does not search in mounts

### ISSUE THREAD

**Issue by AuspeXeu** [gopasspw/gopass#1097]
I have a second password store mounted as a substore. However, the firefox plugin would not find any entries from that store.

**Comment by martinhoefling** [comment]
@auspexeu, can you give some more details? 

- OS
- Gopass / Gopassbridge Version?
- Store Layout
- what are you searching? Working / non working case. 

Several people are using it with multiple stores without problems. Also, from an implementation perspective, the json api doesn’t know anything about stores and just processes the whole tree.

**Comment by AuspeXeu** [comment]
Gladly.

* OSX
* gopass 1.8.4
* Firefox plugin https://github.com/browserpass/browserpass
* Layout
- Rootstore
-- Substore
I cannot find any matches for entries located within the substore.

**Comment by martinhoefling** [comment]
no clue if browserpass uses the JSON API but gopassbridge extension with native messaging set up should work.

**Comment by AuspeXeu** [comment]
Okay, must be an issue with that extension. After switching to gopassbridge, everything is working just fine. Thanks!
