### ISSUE TITLE
Latest release is missing from the Debian repository (again)

### ISSUE THREAD

**Issue by moritzheiber** [gopasspw/gopass#1098]
### Summary

The latest release is missing from the Debian repository (yet again).

### Steps To Reproduce

1. Add the Debian repository from Bintray as mentioned in the documentation
2. Update your package definitions from `apt update`.
3. Run `apt policy gopass`
4. The version available is `1.8.4`.

### Expected behavior

The version available should be `1.8.5`.

### Environment

- OS: Ubuntu 18.04.2 LTS
- gopass Version: 1.8.4
- Installation method: Debian repository

### Additional information

Related to #871, #896

**Comment by moritzheiber** [comment]
@dominikschulz I'd be happy to sort out the Bintray links with this organization. I would need to be added to the organization though to investigate what's wrong with the current release flow.

**Comment by moritzheiber** [comment]
@dominikschulz Soo .. I'd be happy to help, but I need access. Would you be able to grant said access?

**Comment by desolat** [comment]
Any chance to get that sorted out?

**Comment by desolat** [comment]
Issue is still valid. The current documentation at https://github.com/gopasspw/gopass/blob/master/docs/setup.md#ubuntu--debian-1 still mentions the outdated package repository.
