### ISSUE TITLE
Migration vom pass

### ISSUE THREAD

**Issue by janbaer** [gopasspw/gopass#1100]
I'm a long time pass user and I wanted to migrate from pass to gopass, but without loosing all my stored passwords. I tried to init gopass with using the same directory for the password-store, but it failed. So my question is, if it is possible todo such a migration and if yes, how I could do this. Thank you in advance...

**Comment by metalmatze** [comment]
If you already have an initialized pass store at `.password-store` it should be no problem to use gopass as a drop-in replacement (as in simply use the gopass executable). Not sure what you tried.

**Comment by janbaer** [comment]
When I start gopass for the first time I'll be asked if I want to run the onboarding wizard. When I say yes, then at the point when the store should be create I get the following error

```bash
Error: failed to run onboarding wizard: failed to init local store: failed to init store '' at 'gpgcli-gitcli-fs+file:///~/.password-store': failed to initialize new sub store: failed to initialize store: failed to write recipients file: mkdir /~: permission denied: failed to write recipients file: mkdir /~: permission denied: failed to initialize store: failed to write recipients file: mkdir /~: permission denied: failed to write recipients file: mkdir /~: permission denied
```

Which makes sense because there's an existing password-store from using **pass** before.

**Comment by janbaer** [comment]
I was waiting for a feedback here, if it's possible to migrate from pass to gopass with using the password-store that was created by pass.

**Comment by metalmatze** [comment]
If you already have a `.password-store` folder in your home, then you can simply start using the `gopass` binary instead of pass. You don't need to run anything (like a wizard)
