### ISSUE TITLE
Error when adding recipients to empty password store

### ISSUE THREAD

**Issue by AuspeXeu** [gopasspw/gopass#1103]
### Summary
Adding new recipients to an empty store finishes with an error.

### Steps To Reproduce
1. Create an empty password store
2. Use `gopass recipients add --store MyStore 0xYZM`
3. Read `Error: failed to add recipient '0xYZM': failed to commit changes to git: git has nothing to commit`

### Environment
- OS: Mac OS X
- gopass Version: 1.8.5
- Installation method: brew

**Comment by metalmatze** [comment]
> 2. Use gopass recipients add --sore MyStore

Looking at your syntax there, I think you're missing the recipient's fingerprint or mail?!

**Comment by AuspeXeu** [comment]
Yeah sorry, just typed from the top of my head. Should've copied it from the command line. Going to fix this when I'm back at the computer. In the meantime you can still try adding a recipient to a freshly initialised store.

**Comment by AuspeXeu** [comment]
Still a problem when adding recipients to a freshly initialised store.

**Comment by evgeni** [comment]
Still present

**Comment by AuspeXeu** [comment]
Bump
