### ISSUE TITLE
Reencryption using a subkey

### ISSUE THREAD

**Issue by rvolosatovs** [gopasspw/gopass#1107]
### Summary

I want to be able to revoke and delete my old encryption subkey and use a new one.
Trying to add the subkey as a new recipient fails with `Recipient already in store`
`gopass recipients update` does not do anything either

### Steps To Reproduce

1. Create new encryption subkey
2. `gopass recipients add <id-of-subkey>`

### Expected behavior

Passwords reencrypted

### Environment

- OS: NixOS 19.03
- OS version: Linux neon 4.14.113 #1-NixOS SMP Sat Apr 20 07:15:10 UTC 2019 x86_64 GNU/Linux
- gopass Version:
```
gopass 1.8.5-git+HEAD go1.10.8 linux amd64
<root>     - gpg 2.2.15 - git 2.21.0 -   fs 0.1.0
Available Crypto Backends: gpgcli, openpgp, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
```
- Installation method: `nix`

**Comment by dominikschulz** [comment]
Yes, I agree that our handling of subkeys is ... poor.
This must be fixed eventually.

**Comment by tennox** [comment]
I worked around that problem with `gopass recipients add 08E33517FEDD43BCEF2A4C4037F4E8B81DE452FE`, but I have loads of problems with failing to decrypt now. I will open a separate issue when I figured out what is happening...
Thought to share that option here though
