### ISSUE TITLE
Windows : Failed to retrieve secret in mounted store

### ISSUE THREAD

**Issue by juliengb** [gopasspw/gopass#1111]
### Summary

When using windows, secrets within a folder within a mounted store cannot be retrieved correctly.

### Steps To Reproduce

* Set up a mounted store in Windows (named "pro" in this example)
* Insert passwords
```
> echo OK | gopass insert pro/leaf
> echo OK | gopass insert pro/foo/leaf
```
* Try to retrieve passwords
```
> gopass show leaf
+---------------------------------------
|gopass
|Found secrets - Please select an entry
+---------------------------------------
 pro/leaf
 pro\foo/leaf
```
 * Selecting `pro\foo/leaf` results in
```
Error: failed to retrieve secret 'pro\foo/leaf': Entry is not in the password store
```

### Expected behavior
* Entry listed as `pro/foo/leaf` instead of `pro\foo/leaf`
* Retrievable entry

### Environment
- OS: Windows 7
- gopass Version: 1.8.5
- Installation method: Download and unzip windows binaries from github
- Mount config :
```yaml
mounts:
  pro:
    askformore: false
    autoclip: true
    autoprint: false
    autoimport: true
    autosync: false
    check_recipient_hash: false
    cliptimeout: 45
    concurrency: 1
    editrecipients: false
    nocolor: false
    noconfirm: true
    nopager: false
    notifications: true
    path: gpgcli-gitcli-fs+file:///D:%5CPath%5CTo%5CPassword%5CStore
    safecontent: false
    usesymbols: false
```

### Additional context
* Secret can be retrieved when using forward slashes
```
> gopass show pro/foo/leaf
OK
```
* Secrets that are not in a mounted store can be retrieved properly
```
> echo OK | gopass insert foo/leaf
> echo OK | gopass insert foo/bar/leaf
> gopass show leaf
+---------------------------------------
|gopass
|Found secrets - Please select an entry
+---------------------------------------
 foo/leaf : OK
 foo\bar/leaf : OK
 pro/leaf : OK
 pro\foo/leaf : Error: failed to retrieve secret 'pro\foo/leaf': Entry is not in the password store
```
* The problem also affects jsonapi, rendering the browser add-on useless for me
* The listing of secrets also show slash handling problems :
```
> echo OK | gopass insert foo/bar/baz/leaf
> echo OK | gopass insert foo/bar/baz/qux/leaf
> gopass ls -f foo
foo/bar\baz\qux/leaf
foo/bar\baz/leaf
foo/bar/leaf
foo/leaf
> echo OK | gopass insert pro/foo/bar/leaf
> echo OK | gopass insert pro/foo/bar/baz/leaf
> gopass ls -f pro
pro/foo\bar\baz/leaf
pro/foo\bar/leaf
pro/foo/leaf
pro/leaf
```

**Comment by cymruu** [comment]
Can confirm that this issue is present on compiled version too. 
`gopass 1.8.5-git+HEAD go1.10.3 windows amd64`

**Comment by cymruu** [comment]
I did small research and figured out that the problem is located in `pkg\store\root\mount.go` file in MountPoint method which doesn't find store if its followed by backslash. 

I made a pull request which solves the issue, but I'm not sure if my approach is good because I didn't dig that deep.
#1138
