### ISSUE TITLE
gopass-users mailing list seemingly gone?

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [gopasspw/gopass#1112]
Even though I'm not supposed to ask here, I'll just do it anyways, because the mailing list is gone.

Why would I have a commit named "Exported public keys ...," where now my public keys folder now has 2 identical files, with different names, one starting with 0x...?

**Comment by ThatNerdyPikachu** [comment]
bump, as the group is mentioned in documentation.

**Comment by ThatNerdyPikachu** [comment]
bump

**Comment by ThatNerdyPikachu** [comment]
bump

**Comment by dominikschulz** [comment]
gopass-users seems to work for me.
