### ISSUE TITLE
Automatically import public keys for noop backends

### ISSUE THREAD

**Issue by AuspeXeu** [gopasspw/gopass#1113]
### Summary
Judging from the documentation, if one wants to use Google Drive to synchronize one's passwords across devices, the `noop` backend is the correct way to do this. However, when setting this password store up on a new machine, there is no way to import the public keys but doing it manually using `gpg`. It seems like the automated import is part of the `sync` command which is completely omitted for `noop` backends. Did I miss something here? Can this import still be done automatically?

### Steps To Reproduce
1. Follow the instructions to use Google Drive for synchronization
2. Add a recipient to the store
4. Synchronize with a second machine and run `gopass recipients`
5. It will tell you that the recipients' public keys are missing

### Expected behavior
Automatically import missing public keys even if a `noop` backend is used.

### Environment
- OS: Mac OS X Mojave
- OS version: Darwin MacBookAir 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
- gopass Version: 1.8.5
- Installation method: brew

**Comment by dominikschulz** [comment]
That sounds like a good idea. Quite possible that we're only checking for missing keys with the git backend.
The noop backend is probably rarely used at all.

**Comment by dominikschulz** [comment]
So, turns out key import and export was explicitly skipped for the noop backend.
