### ISSUE TITLE
gopass delete throws incorrect error message and auto-sync does not occur

### ISSUE THREAD

**Issue by ronaldscott** [gopasspw/gopass#1115]
### Summary

Removing an entry throws an incorrect error message, and auto-sync does not occur.

### Steps To Reproduce

With this structure...

```
gopass
├── websites
│   └── station
│       └── myemail@email.com
```

...executing `gopass rm websites/station/myemail@email.com` results in the following output:

```shell
C:\Users\MyName> gopass rm websites/station/myemail@email.com
Are you sure you would like to delete websites/station/myemail@email.com? [y/N/q]: y

Error: Can not delete 'websites/station/myemail@email.com': remove C:\Users\MyName\.password-store\websites: The directory is not empty.
```

The error is incorrect. The entry actually is deleted. But the error prevents autosync from happening, so I have to go to the folder and commit and push manually.

### Expected behavior

In the example above, I would expect no error message, and for auto-sync to occur.

### Environment

- OS: Windows 10
- OS version: 10.0.17763 Build 17763
- gopass Version: gopass 1.8.5
- Installation method: [scoop](https://scoop.sh/)

**Comment by dominikschulz** [comment]
This might be related to the fact that you're running gopass on Windows.
Unfortunately I still don't have any means to test on Windows.
But I agree that it should not fail.

**Comment by qwc** [comment]
Just as a sidenote, I just added a test entry to my store, which was directly cloned with `gopass clone <url>` it said "Pushed changes to git remote" but the change in the local repo isn't even commited locally and never reached the remote end.

Also noticed that on deletion of entries, but there didn't even appear a message about pushing (might relate to the original bug described here).

Here my installed version:
```
gopass 1.8.5 (2019-03-13 17:51:51) go1.12 linux amd64
<root>     - gpg 2.2.16 - noop 0.0.0 -   fs 0.1.0
Available Crypto Backends: gpgcli, openpgp, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
```
Btw. what does that <root> mean? Installed globally, or what? (is a bit misleading)
Installed gopass through the repo on Arch Linux.

**Comment by AnomalRoil** [comment]
This was solved at some point and I cannot reproduce it on the latest master. 👍
