### ISSUE TITLE
Have you ever considered using sequoia as a crypto backend?

### ISSUE THREAD

**Issue by doronbehar** [gopasspw/gopass#1116]
Hey,

While putting my efforts in trying to stop depend on GnuPG, I read your [`docs/backends.md`](https://github.com/gopasspw/gopass/blob/8adabdb/docs/backends.md) and I was wondering whether you've heard of / considered using [sequoia-pgp](https://sequoia-pgp.org/) for the crypto backend.

I find this project very exciting. It's the only project I know of that is quiet stable and that finally provides a modern approach to PGP cryptography. Most importantly, it has a comfortable and modern CLI syntax but I guess you'd use it in gopass as a library.

EDIT:

I know it's written in Rust. It has C bindings with FFI: https://docs.sequoia-pgp.org/sequoia_openpgp_ffi/index.html

**Comment by dominikschulz** [comment]
Thanks for pointing this out. I did never look into this so far.
While I'd prefer to have a (pure Go) libarary, a sane and stable CLI would be also OK.

**Comment by doronbehar** [comment]
Hi again, just wanted to share a piece of news you may find very interesting:

https://protonmail.com/blog/openpgp-golang/
