### ISSUE TITLE
Improve git error messages

### ISSUE THREAD

**Issue by fho** [gopasspw/gopass#1119]
### Summary
I do `gopass clone fho@<IP>:/home/fho/git/gopass-work.git work`
and it fails with:
 `error: failed to clone repo 'fho@<IP>:/home/fho/git/gopass-work.git' to '/home/fho/.password-store-work'`

When I do the same with `git clone` it succeeds.

The error message from gopass gives no information what the reason for the failure could be.
It makes it very hard to debug and fix issues.
gopass should provide enough informations when errors happen to allow fixing problems

**Comment by dominikschulz** [comment]
Yes, indeed. These error messages should provide enough information to resolve the issue.
