### ISSUE TITLE
recipients management for subpaths

### ISSUE THREAD

**Issue by jerger** [gopasspw/gopass#1120]
One of the cool gopass / pass-features is to manage recipients for subpaths by adding a `.gpgid` file to the subpath directory. 

Would be nice, if this feature is supportet by `gopass recipient` commands also :-)

**Comment by dominikschulz** [comment]
Good idea.
This would involve some UX work.

**Comment by dominikschulz** [comment]
Currently we have no plans to work on this.
Suggested workaround: Use mounts / substores.
