### ISSUE TITLE
Enable jsonapi also for Vivaldi

### ISSUE THREAD

**Issue by qwc** [gopasspw/gopass#1122]
### Summary
`gopass jsonapi configure` allows to easily configure your browsers to support gopass with the gopassbridge plugin. But the browser Vivaldi (based on chromium) is missing.

### Expected behavior
Be able to select vivaldi when executing the configure step/tutorial.

### Environment

Not really relevant, but for completeness
- OS: Ubuntu 16.04
- OS version: Linux 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- gopass Version: 1.8.5-git+HEAD
- Installation method: `go get -u github.com/gopasspw/gopass`

### Additional context
Maybe provide a workaround for the meantime. 
e.g. Is it save to just copy the config of chromium to vivaldi?

**Comment by qwc** [comment]
The temporary workaround is of course to copy
`$HOME/.config/chromium/NativeMessagingHosts/com.justwatch.gopass.json`
to
`$HOME/.config/vivaldi/NativeMessagingHosts/com.justwatch.gopass.json`

**Comment by martinhoefling** [comment]
This has been closed via #1133
