### ISSUE TITLE
key migration fails with `gopass init $NEWKEYID`

### ISSUE THREAD

**Issue by glowinthedark** [gopasspw/gopass#1123]
### Summary
Unlike `pass` it is not possible to migrate to a new GPG key by running the following command on an already initialized repo:

```bash
gopass init $NEW_GPG_KEY
``` 

### Steps To Reproduce
1. Initialize a new repo with `gopass init <KEY_ID_A>.
2. Populate the repo with records.
3. Run `gopass init <KEY_ID_B>`

### Actual behavior
```bash
[init] Initializing a new password store ...
[init] WARNING: Store is already initialized

Error: failed to initialize store: failed to init store '' at ~/.password-store': failed to initialize new sub store: Found already initialized store at ~/.password-store.
You can add secondary stores with gopass init --path <path to secondary store> --store <mount name>: Found already initialized store at ~/.password-store.
You can add secondary stores with gopass init --path <path to secondary store> --store <mount name>
```

### Expected behavior
Expected same result as `pass init <KEY_ID_B>`, i.e.
/example.com: reencrypting to <KEY_ID_B>
/anotherexample.com: reencrypting to <KEY_ID_B>
...

**Comment by dominikschulz** [comment]
This behaviour is intentional. I find `init` to add a key terrible UX, so this is not supported here.
Use ´gopass recipients add KEYID´.
