### ISSUE TITLE
gopass clone needs additional unintuitive parameter to set the RCS backend

### ISSUE THREAD

**Issue by qwc** [gopasspw/gopass#1125]
### Summary
I have cloned my pass repository with `gopass clone <url>` and wondered about the fact that the backend is `noop` and my repo isnt synced at all.

So there are IMHO three problems:

1. If you use clone, you probably want to sync so the backend and the configuration to sync should be automatically set IMO. There should then exist an option to explicitly NOT sync, of course, like `--no-sync` or similar.
2. To sync or not to sync is one thing. The other is that gopass documentation states it only supports git as RCS backend, why does a *noop* backend even exist?!
3. **No command exists to set the backend after password store initialization!**
  a. Yes you may edit the configuration, but there's another problem with it, `gopass config` just prints the configuration and doesn't start the editor defined in `$EDITOR` (will open separate issue for that... see #1126 )
  b. Printing the config is basically okay, but when no option exists to actually edit, the documentation is god damn wrong.

### Steps To Reproduce
Do a `gopass clone` from whatever repo you want, without additional options and then check via `gopass version` what is set and what not.

### Expected behavior
- Default setting to git as backend (of course there may be an option to set gitcli or gogit....)
- Clone does set a backend and sync enabled per default.

### Environment

- OS: Arch Linux
- OS version: Linux valinor 5.1.7-arch1-1-ARCH #1 SMP PREEMPT Tue Jun 4 15:47:45 UTC 2019 x86_64 GNU/Linux
- gopass Version: gopass 1.8.5 (2019-03-13 17:51:51) go1.12 linux amd64
<root>     - gpg 2.2.16 - noop 0.0.0 -   fs 0.1.0
Available Crypto Backends: gpgcli, openpgp, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
- Installation method: arch linux repo

### Additional context
By the way, does gopass honor options set for `pass` ?
Because at work it did sync automatically, when trying out pass i've set the backend explicitly. Or was this just some coincidence... O.o

**Comment by qwc** [comment]
Hmm, a bot is allowed to put "wontfix" to issues? o.O

**Comment by cburgmer** [comment]
Looking at the clone action it seems gitcli is already used as default (https://github.com/gopasspw/gopass/blob/db722a047dd40bf39692f7382f991ed4dd44173c/pkg/action/clone.go#L65), so I guess it's safe to store as well?

**Comment by toreanderson** [comment]
As of gopass 1.9.2 this issue is only partially fixed.

When cloning mounts, the backend is set to `gitcli` as expected. However, when cloning a root repo, it is still unexpectedly set to `noop`.

See #1220 for details.

**Comment by dominikschulz** [comment]
Yes, sorry. This is possible.
Unfortunately the code is a mess. My fault.
I'm trying to radically simplify this at the moment.
Part of these simplifications have already landed. Others are being worked on.

If you feel adventurous you could try with the latest HEAD from the master branch.
There might be other issues, so please handle with care.
