### ISSUE TITLE
Feature request: generate username ala LastPass

### ISSUE THREAD

**Issue by Spass1966** [gopasspw/gopass#1131]
In the interest of privacy I've begun generating unique usernames for all new logins. It would be neat if `gopass generate` presented an option for generating a unique username too.

See:
https://www.lastpass.com/username-generator

**Comment by Spass1966** [comment]
Thanks for making this happen @dominikschulz!

I've been experimenting with ways of generating memorable, anonymous usernames since I first opened this request and LastPass' usernames are, in general, pretty poor, since they are hard to pronounce and not memorable.

Then I found a-type/adjective-adjective-animal, a library that generates usernames randomly using two adjectives and an animal. Can this be considered as an alternative to generation just like we have the `-x` flag for generating xkcd-style usernames?

**Comment by dominikschulz** [comment]
If we have a Go library do this, it's easy. Otherwise someone will have to contribute such a library.
