### ISSUE TITLE
Better shows git error message.

### ISSUE THREAD

**Issue by Magicloud** [gopasspw/gopass#1132]
### Summary
When the repo is on Github, it may have turned on the email protection, which returns error when the receipt uses a clear email address. Without error message, it is quite hard to figure out why.

### Steps To Reproduce
Choose my personal gmail "for password store git config", pushing would fail with exit status 1.
Using the "number+name@users.noreply.github.com", it worked.

### Expected behavior
Pushing succeeds.

### Environment

- OS: Archlinux
- OS version: 5.1.15-arch1-1-ARCH
- gopass Version: 1.8.5-git+HEAD
- Installation method: via go command

**Comment by dominikschulz** [comment]
We could improve how we propagate Git error messages, but I don't understand the actual problem.
Which kind of "email protection" are you talking about?
If have properly setup SSH auth w/ GitHub your email shouldn't matter.

**Comment by Magicloud** [comment]
"Personal settings" -> "Emails" -> "Block command line pushes that expose my email". With this option on, when I use my actual email (registered in Github) in password-store, `git push` will be denied with certain error prompting this case.
