### ISSUE TITLE
HIBP API used in leak checker deprecated

### ISSUE THREAD

**Issue by dewey** [gopasspw/gopass#1145]
Hey,

the API used in https://github.com/gopasspw/gopass/blob/master/pkg/hibp/api/client.go will be deprecated in a month and won't work without a (paid) API key:

https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/

**Comment by dominikschulz** [comment]
Yeah, that is unfortunate.
Once this becomes effective this feature will stop working.
We may want to provide a way to supply an API key, but that's terrible UX compared to the current state.

**Comment by dewey** [comment]
Actually I just read up on it in detail and the HIBP changes only affect lookups by *email* while gopass only does lookup by partial password hashes which are not affected by the changes.

**Comment by dominikschulz** [comment]
Oh, thanks a lot. I did only skim over that post.
In that case we should be fine.
Feel free to close this issue if you agree.

**Comment by dewey** [comment]
I missed it on my first read too, apparently he made it clearer in an edit later on. Closing this.
