### ISSUE TITLE
otp --password, -o

### ISSUE THREAD

**Issue by UnicodeAlt255** [gopasspw/gopass#1150]
### Summary

`gopass otp` has no flag to output only the password, like `gopass show --password`

### Steps To Reproduce

```sh
$ gopass otp ...
123456 lasts 4s 	|--------------------------====|
```

### Expected behavior

```sh
$ gopass otp -o ...
123456
```

### Environment

- OS: Arch Linux
- OS version: 5.2.1-arch1-1-ARCH
- gopass Version:
```
gopass 1.8.5 (2019-03-13 17:51:51) go1.12 linux amd64
<root>     - gpg 2.2.17 - git 2.22.0 -   fs 0.1.0
Available Crypto Backends: gpgcli, openpgp, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
```
- Installation method: pacman

### Additional context

Currently I am using regex to extract the OTP, but I think this should be built-in.

**Comment by dominikschulz** [comment]
Indeed, that sounds useful and easy to implement.
