### ISSUE TITLE
Create more useful AWS Access Key entry from `gopass create`

### ISSUE THREAD

**Issue by espoelstra** [gopasspw/gopass#1160]
### Summary
The `gopass create` flow is fantastic, and I was excited about the AWS Secret Key option, but after interacting with it a bit, I realized that it captures either extra unnecessary information, or it needs tweaked slightly to be properly useful without modifying the entry again.

The flow prompts for your username (often an email address), which isn't necessary at all if you are using the ACCESS_KEY and SECRET_KEY from the CLI. The username is saved as `username` but the SECRET_KEY is saved as the first line secret `password` and this combination doesn't actually work to login via web or CLI.

I first ran into this when trying to use the entry via `gopass-bridge`, and that's when I realized what was happening. After some [discussion over in their GH issues](https://github.com/gopasspw/gopassbridge/issues/34#issuecomment-519233547) it dawned on me that having the SECRET_KEY in the first line of the entry was also potentially "hazardous", because if I ran `gopass generate aws/accountid/myaccount` it would wipe out the SECRET_KEY and put a random password, the problem is, AWS supplies both the ACCESS_KEY and SECRET_KEY together, and in order to generate new ones you need to use the CLI or web console, so the SECRET_KEY should be treated as "static data" and the password field used for the actual account password.

### Steps To Reproduce
`gopass create` and select AWS Access Key
Follow the wizard and then `gopass edit aws/accountid/youraccount` and see the SECRET_KEY is stored where a password normally goes, even though it isn't a value you should change with `gopass generate`. 

### Expected behavior
I would expect `gopass create` and the AWS Access Key option to maybe say "AWS Account Access (Web/CLI)" and then gather all the information it currently does PLUS the password, and save the password in the normal spot and put the SECRET_KEY in a `secret_key:` in the YAML so the entry can be used from the CLI with `env AWS_ACCESS_KEY_ID=$(gopass show -o aws/account_id/myaccount access_key) AWS_SECRET_ACCESS_KEY=$(gopass show -o aws/account_id/myaccount secret_key) aws s3 ls` or just export those variables by sourcing an `aws_env_creds.sh` script.

### Environment
- OS: macOS Mojave
- OS version: Darwin Kernel 18.7.0
- gopass Version: 1.8.6
- Installation method: brew

**Comment by dcai** [comment]
hi @dominikschulz thanks for working on gopass.

I couldn't find aws and gcp service account options from `create` command in latest release 1.12.x anymore, are these options removed? I couldn't find anything from changelog.

**Comment by dominikschulz** [comment]
Yes, they have been removed because they didn't add much value.
Sorry for missing that in the release notes.

**Comment by AnomalRoil** [comment]
If we once refactor the whole create thing, I think we should add support for "templates" in a specific `.dotfolder` in the password-store, and so we could have as many as we want and have other people or separate repo adding more templates or so.

WDYT @dominikschulz? That could simplify the codebase while decoupling the templates from the logic. It would make things more generic.

**Comment by dominikschulz** [comment]
Yes, that sounds great. I don't want to maintain application/provider specific wizards, but if we could have a generic extensible one that'd be nice.
