### ISSUE TITLE
[FR] Use flag to select identity when using gopass clone

### ISSUE THREAD

**Issue by M-Gregoire** [gopasspw/gopass#1162]
First of all, thank you for the awesome tool that Gopass is!

### Summary
I'd like to clone an existing password store (git) using one command without the need for extra input.

### Steps To Reproduce
```
gopass clone git@my-git-repo.git
Configuring git repository ...
Use Identity (my@email.com) for password store git config? [Y/n/q]: Y
Your password store is ready to use! Have a look around: `gopass list`
```

### Expected behavior
```
gopass clone --id my@email.com git@my-git-repo.git
Configuring git repository ...
Your password store is ready to use! Have a look around: `gopass list`
```

A flag that would allow to specify either:
- The email address associated with the GPG key
- The 8 character ID found by typing "gpg --list-keys" and looking at the "pub" line
- The GPG key fingerprint found by typing "gpg --fingerprint" and removing all of the spaces

just like `gopass init` would be awesone.

### Note
I've been looking through the documentation and the source code, it seems like it's note implemented but might have missed it.

**Comment by M-Gregoire** [comment]
Just noticed one can simply do the following:
```
gopass --yes clone git@my-git-repo.git
```
To clone the repo in one line. However, this doesn't allow to choose which key to use if said repo has multiple recipients and you have multiple keys associated with the repo.

I don't see any real use case for this so closing this issue but feel free to open it again if needed.

**Comment by M-Gregoire** [comment]
Sorry for this long post, seems like I'm a bit confused about the use of `git clone`.
I'm trying to create `~/.password-store` based on an already existing store on git.

I first tried 
```
gopass --yes clone git@my-git-repo.git
```
this returns
```
Configuring git repository ...
Your password store is ready to use! Have a look around: `gopass list`
```

But nothing gets created (I guess this is an issue, an error message should probably be returned). 

I then noticed the docs says:
> Please note that all cloned repositories must already have been initialized with gopass. (See the previous section for more details.)

So I tried the following:
```
# This commands works fine and create an empty password store at ~/.password-store
gopass --yes init <key-id>

gopass --yes clone git@my-git-repo.git
```
But this last commands returns: `Error: Can not clone git@my-git-repo.git to the root store, as this store is already initialized. Please try cloning to a submount: `gopass clone git@my-git-repo.git sub`

I'm confused, the docs says 
> all cloned repositories must already have been initialized 


and this commands says


> Can not clone ... to the root store, as this store is already initialized

Am I missing something?  
Does the `gopass clone` only allows to clone to a submount but not the root password store?

# Note
I can simply use `git` directly:
```
git clone git@my-git-repo.git /home/$USER/.password-store
```
which works perfectly.

I'm just wondering whether this is an issue in Gopass, the documentation or whether I missed something.

Thanks a lot for reading (and sorry again for those long posts)

**Comment by yannfill** [comment]
I reopen this issue as there's no answer to the "store is already initialized" error.

Following the documentation I did

```
gopass init <key-id>
gopass clone git@my-git-repo.git
```
and got the same error as OP.

**Comment by dominikschulz** [comment]
Can you point me at the location in the documentation that does suggest this, please? @yannfill 

init followed by clone is wrong. clone should take care of everything already.

**Comment by yannfill** [comment]
In https://github.com/gopasspw/gopass/blob/master/docs/features.md#cloning-an-existing-password-store il says
> Please note that all cloned repositories must already have been initialized with gopass. (See the previous section for more details.)

If I just clone the repo and add a secret, then when I `gopass sync` I get

```
🚥 Syncing with all remotes ...
[<root>]
   git pull and push ... OK (no changes)
   importing missing keys ... OK
   exporting missing keys ... nothing to do
   done
✅ All done
```
and the remote repo is not updated.

**Comment by dominikschulz** [comment]
That piece of documentation is correct but definitely misleading. What I meant was: The remote repo must have been initialized / created before, otherwise clone will fail.

Just cloning the repo and adding a repo should work.

Are you sure the newly created secret does not show up on the remote?
Or are you only worried about it not showing up in the sync output?

I'm asking because gopass started to default to autosync some time ago.

**Comment by yannfill** [comment]
I checked the remote repo and it hasn't been updated.

**Comment by AnomalRoil** [comment]
I just tested using the following:
```
~ $ GOPASS_HOMEDIR=test1162 gopass init
[...]

~ $ GOPASS_HOMEDIR=test1162 gopass generate test2 15
✅ Password for entry "test2" generated
Not printing secrets by default. Use 'gopass show test2' to display the password.

~ $ GOPASS_HOMEDIR=test1162 gopass git remote add origin git@github.com:AnomalRoil/pwstore-1162.git

~ $ GOPASS_HOMEDIR=test1162 gopass git push
✅ Pushed to git remote
```

And then I tried cloning it (noticed I changed the HOMEDIR to have a "clean" setup):
```
~ $ GOPASS_HOMEDIR=test1162-clone gopass clone git@github.com:AnomalRoil/pwstore-1162.git
[...]
Your password store is ready to use! Have a look around: `gopass list`

~ $ GOPASS_HOMEDIR=test1162-clone gopass list
⚠ You haven't checked for updates in a while. Run 'gopass version' or 'gopass update' to check.
gopass
└── test2

~ $ GOPASS_HOMEDIR=test1162-clone gopass generate test-afterclone 15
✅ Password for entry "test-afterclone" generated
Not printing secrets by default. Use 'gopass show test-afterclone' to display the password.
⚠ Failed to pull before git push: exit status 128: From github.com:AnomalRoil/pwstore-1162
 * branch            master     -> FETCH_HEAD
hint: You have divergent branches and need to specify how to reconcile them.
hint: You can do so by running one of the following commands sometime before
hint: your next pull:
hint: 
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint: 
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
fatal: Need to specify how to reconcile divergent branches.
```
This might look like it failed, but it's just git complaining a little bit.
I checked the remote and everything actually worked and the new password was uploaded...

We might just want to correct the way we are initializing the cloned repo, to apply the same fix as when we init the git repo in the first place. 
But it's kinda strange since it should have ran already:
https://github.com/gopasspw/gopass/blob/bbf17512936f85f9a051e75bc21c5e3f9fdc9a2a/internal/action/clone.go#L101

But still, that seems to be an unrelated git issue, compared to your current issue.

**Comment by AnomalRoil** [comment]
Running `gopass fsck` correctly fixes the issue of lack of proper git config of the password store after having used `gopass clone ...`

**Comment by yannfill** [comment]
After deleting `~/.config/gopass/`, `~/.local/share/gopass/` and `~/ .cache/gopass/` I tried

```
gopass init <key-id>
```
then

```
gopass git remote add origin git@my-git-repo.git
```

and then `gopass git pull` failed with

```
exit status 128: From repo
 * branch            master     -> FETCH_HEAD
fatal: refusing to merge unrelated histories
```

`gopass sync` failed too:

```
🚥 Syncing with all remotes ...
[<root>]
   git pull and push ... ⚠ Failed to pull before git push: exit status 128: From repo
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master
fatal: refusing to merge unrelated histories
❌ Failed to push "<root>" to its remote: exit status 1: To repo.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'repo.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
✅ All done
```

**Comment by AnomalRoil** [comment]
Don't do the `gopass init` at all. 

Delete everything again and try directly with:
```
gopass clone git@my-git-repo.git
gopass fsck
```
That fsck step should check that everything is working properly.

**Comment by yannfill** [comment]
Still not working. `gopass fsck` returned no error. I added a secret and `gopass sync`:

```
🚥 Syncing with all remotes ...
[<root>]
   git pull and push ... OK (no changes)
   importing missing keys ... OK
   exporting missing keys ... nothing to do
   done
✅ All done
```
`gopass git push` return

```
✅ Pushed to git remote
```

But the remote repo is still not updated.

**Comment by AnomalRoil** [comment]
If you go to the password store folder, typically `~/.local/share/gopass/root` and you use git there directly, what does the following tell you:
```
git status
git log
git remote -v
```

**Comment by yannfill** [comment]
`git status`:

```
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	new file:   secret.gpg
```

`git log` shows past commits, no new one.

`git remote -v`:

```
origin	my-repo/gopass.git (fetch)
origin	my-repo/gopass.git (push)
```

**Comment by AnomalRoil** [comment]
What does `git branch -a` tell you?

**Comment by jensklose** [comment]
Ok, I think something got mixed up there.
@yannfill 
First, the documentation can be misleading. If you want to start from zero, then you have to choose between 2 ways. 
- Remote git is always initialized with gopass => gopass setup
- Empty git remote => gopass init && gopass git remote add origin ... && gopass sync

Your other issue is a broken git run. I can reproduce it with incorrect connection of Repo (filled) with the `gopass init` initialization.

The reason is that "init" creates a new local repo and does the first commits there.

```bash
.local/share/gopass/stores/root$ git log --graph
* commit d46a07b2057c0efb52fa41985cef3fcaf3bcb065 (HEAD -> master)
| Author: jens <jens.klose@googlemail.com>
| Date:   Wed Dec 22 20:02:13 2021 +0000
|
|     Add current content of password store
|
* commit 1515ba7cba4581511292b2d2e4d25f4acf124e18
  Author: jens <jens.klose@googlemail.com>
  Date:   Wed Dec 22 20:02:13 2021 +0000

      Configure git repository for gpg file diff.
```

And that's why the error message:
`fatal: refusing to merge unrelated histories`

**Comment by yannfill** [comment]
I did `gopass setup`, choose the same GPG key used on the remote repo, add the remote repo et get the same error (why would gopass push before pull at init when adding an existing store ?)

So I cloned my repo and rsync the directory with the local store and everything is now working. Issue resolved for me, even if the gopass internal steps are still failing.

**Comment by dominikschulz** [comment]
The original issue (specifying the identity used for the cloned repo) can be solved by specifying `--name` and `--email` to `gopass clone`. The other issues discussed here I can't reproduce.
