### ISSUE TITLE
Use jsonapi configure non-interactively

### ISSUE THREAD

**Issue by M-Gregoire** [gopasspw/gopass#1164]
### Summary
I'm trying to specify all the needed parameters for `gopass jsonapi configure` directly through flags in order to use it non-interactively. As far as I know, this is currently not possible (without using the `--yes` flag, which wouldn't allow me to say "No" to `Install for all users? `)

### Steps To Reproduce

```
gopass jsonapi configure --browser firefox --path /home/$USER/.config/gopass
Install for all users? (might require sudo gopass) [y/N/q]: N

<Snip>

Install manifest and wrapper? [Y/n/q]: Y
```

### Expected behavior
```
gopass jsonapi configure --browser firefox --path /home/$USER/.config/gopass --current-user-only --install
```
or something similar that would achieve the same purpose.

Thank you

**Comment by Project0** [comment]
Did you tried `--global=false`?
https://github.com/gopasspw/gopass/blob/master/commands.go#L530
https://github.com/gopasspw/gopass/blob/master/pkg/action/jsonapi.go#L44

**Comment by M-Gregoire** [comment]
Oh, seems like I missed it! Works perfectly
Thank you
