### ISSUE TITLE
Cannot crosscompile latest version

### ISSUE THREAD

**Issue by AuspeXeu** [gopasspw/gopass#1167]
I am left with this error message when I try crosscompiling from the latest source. I installed dependencies using `dep ensure` and am running go version `1.12.9`.

![image](https://user-images.githubusercontent.com/2115696/63277679-c09c3100-c273-11e9-8f40-40695fb7f982.png)

**Comment by dominikschulz** [comment]
Can't reproduce from master with go 1.12.9.

**Comment by AuspeXeu** [comment]
I just tried it with a clean clone of the repo. Works flawless.
