### ISSUE TITLE
gopass copy fails to commit

### ISSUE THREAD

**Issue by GrumpyDave** [gopasspw/gopass#1168]
I'm a pass user trying out gopass for the ability to use store mounts.  I initialized a new mount and tried to copy an entry to it from the main store.  The entry does get copied but the commit fails.  The error message is simply "Error: failed to copy from 'Logins/N' to 'Shared/N'".  Running a copy within the mount works, but copying from the main repo to the mount fails.  Using the debug flag I see that the gitAdd step is done in the destination's working directory where the change was made but the gitDiffIndex step is done in the source's working directory which causes it to fail:

>[DEBUG] backend/rcs/git/cli/git.go:109 store.gitAdd: /usr/bin/git [git add --all --force N.gpg] (/home/dave/.password-store-Shared)
>[DEBUG] backend/rcs/git/cli/git.go:109 store.gitDiffIndex: /usr/bin/git [git diff-index --quiet HEAD] (/home/dave/.password-store)
>[DEBUG] action/errors.go:60 Stacktrace: git has nothing to commit

When I copy an entry within the same store the two lines reference the same working directory and the copy works.

- OS: Gentoo Linux
- OS version: Linux bob 4.19.57-gentoo #1 SMP Thu Jul 11 14:07:40 MST 2019 x86_64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz GenuineIntel GNU/Linux
- gopass Version:
gopass 1.8.6 (d5b0d3b906cdd9f16ad3f21e366845af7f2c22f3) go1.12.7 linux amd64
<root>     - gpg 2.2.17 - git 2.21.0 -   fs 0.1.0
Available Crypto Backends: gpgcli, openpgp, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem

- Installation method: from source

**Comment by dominikschulz** [comment]
Thank you very much for reporting this issue.
