### ISSUE TITLE
Git status?

### ISSUE THREAD

**Issue by wxcafe** [gopasspw/gopass#1170]
### Summary
`pass git` allows every git subcommand because it simply invokes the git binary.
`gopass git` only allows `init`, `remote`, `push` and `pull`, which is okay for basic work but it'd be great to get `status` to see the local repo's status

### Environment

- OS: Linux (Debian)
- OS version: `Linux cwh 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux` (Debian bullseye/sid)
- gopass Version: `1.8.6-git+HEAD go1.12.9`
- Installation method: `go get`

### Additional context
(it would also be great to get `gopass git pull --rebase`...)

**Comment by dominikschulz** [comment]
The goal is to eventually replace shelling out to a git binary, so we won't be able to support arbitrary git subcommands.

But having git status would be useful, and also we might add a command to just an an arbitrary command in the password store, e.g. `gopass run git pull --rebase`.
