### ISSUE TITLE
Fix wayland clipboard regression bug

### ISSUE THREAD

**Issue by skaldesh** [gopasspw/gopass#1177]
### Summary
On Wayland, copy password to clipboard does not work

### Steps To Reproduce
- Execute gopass -c <entry> on Wayland
- Nothing in the clipboard

### Expected behavior
Password is stored in clipboard

### Environment
- OS: Arch Linux
- OS version: 5.2.11-arch1-1-ARCH x86_64
- gopass Version: gopass 1.8.6 (2019-08-16 07:10:47) go1.12.8 linux amd64
- Installation method: Official arch package 

### Additional context
The problem had been fixed already in this [PR](https://github.com/gopasspw/gopass/pull/1118). However, now it is broken again.

**Comment by vatcher** [comment]
Hi @skaldesh,
do you really sure it is a Wayland problem?
I am using Wayland on Fedora an it works fine.

### My environment
* OS: Fedora
* OS Version: Fedora release 30 (Thirty)
* gopass Version: gopass 1.8.6-git+HEAD go1.12.7 linux amd64
* Installation method: fedora copr repo  daftaupe/gopass

**Comment by skaldesh** [comment]
@vatcher hm I thought so, I am personally using Sway. But your gopass version is -git+HEAD, are there differences to my version? I installed it from the official arch package

**Comment by skaldesh** [comment]
no longer an issue

**Comment by aayan-w** [comment]
> no longer an issue

Hey @skaldesh how did you fixed it? I have the same issue. 

My environment: 

    OS: Arch Linux, Wayland, Sway
    OS version: 5.4.6-arch3-1
    gopass Version: gopass 1.8.6 (2019-10-14 12:43:03) go1.13.1 linux amd64
    Installation method: Official arch package

Thanks
