### ISSUE TITLE
request: flag for Clipboard + username in single command

### ISSUE THREAD

**Issue by benyanke** [gopasspw/gopass#1178]
In the majority of times I use this tool, I find myself typing:

```
$ gopass site
Entry 'site' not found. Starting search...
Found exact match in 'path/to/site'
j4f9gfj438
login: jdoe
email: jdoe@doeinc.com
```
Here I would grab username, or url and username with cursor, or if it's a memorable username (as they usually are), just visually look and quickly retype it.

```
$ gopass -c site

Entry 'site' not found. Starting search...
Found exact match in 'path/to/site'
✔ Copied path/to/site to clipboard. Will clear in 45 seconds.
```

I would then paste the password from clipboard.

It would be really neat to have an option (perhaps capital C? `-C`) which would display the full normal output, as occurs when there's not a clipboard call, but also dumps password to clipboard. That way, the user can run one gopass, see visually what the username is, type it, and then paste the password.

For example:

```
$ gopass -C site

Entry 'site' not found. Starting search...
Found exact match in 'path/to/site'
✔ Also copied path/to/site to clipboard. Will clear in 45 seconds.
j4f9gfj438
login: jdoe
email: jdoe@doeinc.com
```

**Comment by skaldesh** [comment]
Yes, I would like to see this feature as well

**Comment by benyanke** [comment]
Marking unstale.
