### ISSUE TITLE
Docker install is broken

### ISSUE THREAD

**Issue by kondanta** [gopasspw/gopass#1179]
### Summary

When I try to install gopass through docker image, it does not initiate build prompts error message.
### Steps To Reproduce

run -> docker build -t gopass github.com/gopasspw/gopass#master
<img width="1356" alt="image" src="https://user-images.githubusercontent.com/16501501/64638658-e057ec80-d40e-11e9-973e-2e7513ed3dbf.png">

### Expected behavior

Proceeds the actual docker image building.

### Environment

- OS: Centos7
- OS version: 3.10.0-957.12.2.el7.x86_64
- gopass Version: latest
- Installation method: via docker build

**Comment by mkesper** [comment]
Seems to work again:
```
$ docker build -t gopass github.com/gopasspw/gopass#master
Sending build context to Docker daemon  13.73MB                                                                                           
Step 1/12 : FROM golang:1.12-alpine AS builder
...
```
