### ISSUE TITLE
Git credential helper always shows warning

### ISSUE THREAD

**Issue by worldofpeace** [gopasspw/gopass#1183]
### Summary
Anytime I make push to github I see this warning
```
gopass: did not store "git/github.com/worldofpeace" because it already exists. If you want to overwrite it, delete it first by doing: "gopass rm git/github.com/worldofpeace"
```

The warnings comes from [here](https://github.com/gopasspw/gopass/blob/91975d8e5a95ae63a669bce4c1782221f6d1be78/pkg/action/git-credential.go#L169-#L184)

### Steps To Reproduce

1. Have the following in your git config
```ini
[credential]
helper=!gopass git-credential $@
```
2. Push to something over https

This will cause gopass to create a new secret at `git/$domain/$something`
when you submit your credentials.

3. Push to something again, now with your secret stored.

See the aforementioned warning.

### Expected behavior
Not see this message.

### Environment

- OS: NixOS
- gopass Version: 1.8.6-git+HEAD go1.12.9 linux amd64
- Installation method: nixpkgs

**Comment by worldofpeace** [comment]
Uhhhnnn.... stalebot. Stop cramping my style.

**Comment by neezer** [comment]
This has been bugging me for months too, just been too lazy to post about it here.

**Comment by worldofpeace** [comment]
This issue is still here.

**Comment by neezer** [comment]
With gopass correctly configured as the helper, I ran `GIT_TRACE=true git pull` in a repo of mine, authenticated with my GPG password, and saw the following just before the warning was printed:

```
12:47:44.829913 run-command.c:663   trace: run_command: ‘gopass git-credential $@ get’
12:47:44.493825 run-command.c:663   trace: run_command: ‘gopass git-credential $@ store’
gopass: did not store “git/github.com/neezer” because it already exists. If you want to overwrite it, delete it first by doing: “gopass rm git/github.com/neezer”

```

I can’t seem to find any definitive guide about the lifecycle of when `git-credential` calls `store`, but it appears that it still calls `store` even after `get` returns valid credentials. If so, then I don’t see much of a reason for that warning at all.

Would it be possible to simply delete it?

**Comment by neezer** [comment]
In case this is specific to git version, I’m using `2.25.1`.
