### ISSUE TITLE
Re-word "Cryptic Password" to be more clear on functionality

### ISSUE THREAD

**Issue by WPettersson** [gopasspw/gopass#1184]
### Summary
When generating passwords using `gopass create`, the user is asked if they want a "Cryptic Password", which seems not very clear to me. I actually searched for a while to find out how to create xkcd-style passphrases for a system where I might be expected to read the password over the phone, before finally stumbling onto the fact that gopass uses "non-cryptic" to mean a passphrase style password of English words.

### Steps To Reproduce

Run `gopass create` and read the test

### Expected behavior

A more clear explanation of what "Cryptic Password" means

### Environment
- OS: Gentoo
- OS version: Linux 4.19.71-gentoo, 
- gopass Version: 1.8.5
- Installation method: Installed via Gentoo's portage

### Additional context
I didn't want to submit this issue until I had some ideas on what could replace "cryptic passphrase", so here are my best ideas on what could replace it. Note that the previous line will be "Generate Password?" so the intent is that users should already be aware that password generation is happening

* \- by concatenating randomly selecting words?
* \- consisting of words?
* Generate human-pronounceable passphrase? 

I don't know if any of these are best, but I at least wanted to talk about newer wording for this feature.

**Comment by dominikschulz** [comment]
Good suggestions, thanks. This feature is indeed poorly named.

**Comment by WPettersson** [comment]
This has been fixed in  #1194 so closing.
