### ISSUE TITLE
Memorable password generator backend

### ISSUE THREAD

**Issue by tomkel** [gopasspw/gopass#1192]
I sure do love this feature in MacOS

![](https://i.imgur.com/gGCuXhk.png)

It has a few benefits over the current xkcd backend

1) You can include symbols. `-s` flag doesn't work with xkcd generation

2) You can generate a password based on total length, not just number of words

3) Doesn't have spaces by default. The help text from `gopass generate -h` doesn't seem to match up with the current behavior here. If I omit the `-xs` flag, spaces are included.

Trying to transfer passwords in meat-space (e.g. writing them on stickies) that were generated by the default backend Is a major pita.

**Comment by dominikschulz** [comment]
This sounds like a good idea. We need to find a suiteable wordlist, but otherwise this should be fairly straight forward.

**Comment by tomkel** [comment]
re-open

**Comment by martint17r** [comment]
FWIW I use GOPASS_EXTERNAL_PWGEN environment variable with a [diceware](https://theworld.com/~reinhold/diceware.html) word list.

**Comment by dominikschulz** [comment]
Maybe we could use [tyler-smith/go-bip39](https://github.com/tyler-smith/go-bip39)

**Comment by tomkel** [comment]
Thank you!!
