### ISSUE TITLE
Multiline strings in yaml

### ISSUE THREAD

**Issue by patrickpichler** [gopasspw/gopass#1206]
### Summary
Multiline string in yaml fields are not working as expected. 

### Steps To Reproduce
Create a new gopass entry like:
entry1
```yaml
super_secure_password
---
notes: |
  Line1
  Line2
```

When querying this entry with `gopass show entry1 notes` it will ouptut only `|`.

### Expected behavior
The whole multiline string should be shown.

### Environment
- OS: VoidLinux
- gopass Version: gopass 1.8.6-git+HEAD go1.12.7 linux amd64
- Installation method: os package manager

**Comment by nikaro** [comment]
Same here.

**Comment by dominikschulz** [comment]
Thank you for reporting this issue.
Unfortunately I can not reproduce it locally.
Using your example I get the correct output:

```
Line1
Line2
```

Please run the show command with GOPASS_DEBUG=true set and look for a line like `decodeKV() - mayBeYAML` or `decodeKV() - simple KV`. This might indicate that the parser is falling back to the non-YAML parser for some reason.

**Comment by patrickpichler** [comment]
I guess it is using the non YAML parser.

Here are the log lines:
```
[DEBUG] decodeKV() - mayBeYAML - err: %!s(<nil>)
[DEBUG] decodeKV() - simple KV
```

**Comment by patrickpichler** [comment]
It seems like the bug no longer exists. :+1:

**Comment by dominikschulz** [comment]
Thanks for reporting back. Glad to hear.

**Comment by strongholder** [comment]
@dominikschulz I am still having this issue on MacOS with the latest gopass version `gopass 1.9.2 (2020-05-14 04:58:18) go1.14.2 darwin amd64`
