### ISSUE TITLE
Support for custom SSH config

### ISSUE THREAD

**Issue by ohpe** [gopasspw/gopass#1208]
### Summary
_This is not a bug but a feature request._

Is there any way to specify a custom SSH configuration file or `GIT_SSH_COMMAND`?
I often use gopass with several mounts and most of them require custom `ssh_config` files which are not in the default path.

I tried several combos of configurations but I didn't find anything I can use for this purpose.

**Comment by metalmatze** [comment]
I don't think anything like that is supported.
