### ISSUE TITLE
Getting "Failed to clear clipboard history" on GNOME

### ISSUE THREAD

**Issue by ndrewtl** [gopasspw/gopass#1209]
### Summary
When using `gopass --clip [item]`, the item copies as normal. But after 45 seconds, I get a notification:

```
gopass - clipboard
Failed to clear clipboard history
``` 

### Steps To Reproduce
Copy a secret using `gopass --clip`. Wait for it to attempt to clear.

### Expected behavior
The password should clear, with no problem notification

### Environment

Fedora 31

```
$ gopass --version
gopass 1.8.6-git+HEAD go1.13.3 linux amd64
$ gnome-shell --version
GNOME Shell 3.34.1
$ go version
go version go1.13.3 linux/amd64
$ dnf info wl-clipboard
Installed Packages
Name         : wl-clipboard
Version      : 1.0.0
Release      : 0.2.20181215git7e5103c.fc31
Architecture : x86_64
Size         : 107 k
Source       : wl-clipboard-1.0.0-0.2.20181215git7e5103c.fc31.src.rpm
Repository   : @System
From repo    : fedora
Summary      : Command-line copy/paste utilities for Wayland
URL          : https://github.com/bugaevc/wl-clipboard
License      : GPLv3+
Description  : Command-line Wayland clipboard utilities, `wl-copy` and `wl-paste`,
             : that let you easily copy data between the clipboard and Unix pipes,
             : sockets, files and so on.
```

### Additional context
N/A

**Comment by ndrewtl** [comment]
![Screenshot from 2019-11-12 11-48-03](https://user-images.githubusercontent.com/3442998/68705165-6a711e00-0542-11ea-8baf-ee5ffd5a9801.png)

**Comment by simonkrenger** [comment]
Seeing the same issue on my machine.

In https://github.com/gopasspw/gopass/blob/master/pkg/clipboard/unclip_linux.go#L18 it currently looks like on Linux only `klipper` is supported for clearing the clipboard.

In the clipboard module that is used by `gopass`, there is a workaround described here (just copying an empty string): https://github.com/atotto/clipboard/issues/23
