### ISSUE TITLE
Use gopenpgp instead of golang.org/x/crypto/openpgp

### ISSUE THREAD

**Issue by doronbehar** [gopasspw/gopass#1210]
Continuing from https://github.com/gopasspw/gopass/issues/668 and https://github.com/gopasspw/gopass/issues/1068, There's the openpgp implementation by Protonmain called gopenpgp: https://github.com/ProtonMail/gopenpgp

Is it feasible to replace the current use of `golang.org/x/crypto/openpgp` with `github.com/ProtonMail/gopenpgp`? Also, I wonder whether that will bring any improvement and / or GnuPG 2.2 compatibility which currently `golang.org/x/crypto/openpgp` lacks.

**Comment by dominikschulz** [comment]
I haven't looked closely at gopenpgp, but feel free to try it out and send a PR if it works.

**Comment by doronbehar** [comment]
Well first of all, ProtonMail's version is not a drop in replacement. Moreover, according to this issue:

https://github.com/ProtonMail/gopenpgp/issues/15

It doesn't connect to the gpg-agent by default. It's not impossible to implement this and call the `pinentry` programs etc but I doubt I'll ever find the motive to do that..
