### ISSUE TITLE
gopass doesn't seem to work with PASSWORD_STORE_DIR

### ISSUE THREAD

**Issue by darthdeus** [gopasspw/gopass#1213]
### Summary

`gopass` doesn't respect the `PASSWORD_STORE_DIR` env variable, and even incorrectly documents it as `PASSWORD_STORE` here https://github.com/gopasspw/gopass/blob/master/docs/config.md. Following is an example with `pass` and `gopass`, where a store is created with `pass` and then `gopass` fails to access it.

### Steps To Reproduce

```
[nix-shell:~]$ cd /tmp
[nix-shell:/tmp]$ mkdir foobar
[nix-shell:/tmp]$ cd foobar
[nix-shell:/tmp/foobar]$ PASSWORD_STORE_DIR=. pass init XXX
Password store initialized for XXX
[nix-shell:/tmp/foobar]$ PASSWORD_STORE_DIR=. pass add foo
Enter password for foo:
Retype password for foo:

[nix-shell:/tmp/foobar]$ PASSWORD_STORE_DIR=. pass ls
Password Store
└── foo

[nix-shell:/tmp/foobar]$ PASSWORD_STORE_DIR=. gopass ls
gopass

[nix-shell:/tmp/foobar]$ PASSWORD_STORE=. gopass ls   # for completeness
gopass
```

### Expected behavior

The same behavior as `pass`, use the `PASSWORD_STORE_DIR` variable.

### Environment

- OS: NixOS
- OS version: Linux xxx 4.19.84 #1-NixOS SMP Tue Nov 12 18:21:46 UTC 2019 x86_64 GNU/Linux ... NixOS 20.03pre201791.c1966522d7d
- gopass Version: `gopass 1.8.6-git+HEAD go1.13.4 linux amd64`
- Installation method: [nixpkgs](https://github.com/NixOS/nixpkgs)

**Comment by darthdeus** [comment]
I'm confused, this seems like a clear bug, yet the bot marks as wontfix.

**Comment by danielmorlock** [comment]
+1

**Comment by AlexeyDemidov** [comment]
It seems that `PASSWORD_STORE_DIR` envrionment variable is ignored if `.config/gopass/config.yml` is present. I can repeat the same behavior with the steps from the original report.

gopass 1.14.3 go1.18.2 linux amd64 (installed from [gopass_1.14.3_linux_amd64.deb](https://github.com/gopasspw/gopass/releases/download/v1.14.3/gopass_1.14.3_linux_amd64.deb))

**Comment by dominikschulz** [comment]
I don't think we touched that code in a long time. Let's check.

**Comment by dominikschulz** [comment]
Confirmed. Should have been fixed by #2272 .

Could you see if that works for you?

**Comment by AlexeyDemidov** [comment]
Yes, it fixed the issue. Thank you.

**Comment by dominikschulz** [comment]
Excellent. Thanks.
