### ISSUE TITLE
TOTP doesn't work if too long, lowercase, or contains spaces

### ISSUE THREAD

**Issue by swt30** [gopasspw/gopass#1218]
### Summary
`gopass totp` doesn't seem to support secrets longer than 16 characters, with lowercase characters, or containing spaces. Amazon is one example of a site that provides secrets longer than 16 characters, and many sites report the secret with spaces or in lowercase.

### Steps To Reproduce
Create a new entry (e.g. `gopass create --edit test/totp`) with the content
```
password
---
totp: VERYLONGTOTPHERE
```

and use `gopass totp` to verify that a TOTP code can be generated.

Then change to any of these:
```
totp: VERYLONGTOTPHERE2
totp: VERY LONG TOTP HERE
totp: verylongtotphere
```
and re-run `gopass totp test/totp`, which fails to generate a TOTP code. The error is 
```
Error: No OTP entry found for test/totp: illegal base32 data at input byte N
```
at the first non-base32 character (byte 0 if lowercase, byte 4 if spaced in groups of 4), or at byte 16 if the secret is longer than 16 characters. 

### Expected behavior
A TOTP code should be generated (i.e. the generator should strip spaces, convert to uppercase, and use all the characters)

### Environment

- OS: OSX High Sierra
- OS version: `Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64`
- gopass Version: 1.8.6
- Installation method: brew

**Comment by swt30** [comment]
I also realised while testing this that error messages aren't printed if gopass needs to search for a match e.g. if you do `gopass totp test` instead of `gopass totp test/totp`. I was doing this, so I wasn't seeing the error message. I'll add it above.

**Comment by swt30** [comment]
It might be sufficient to update the gokyle/twofactor dependency to the tagged version 1.0.1 – https://github.com/gopasspw/gopass/blob/3f958a71d8853dc696be0cdc4037718917a92941/go.mod#L19

**Comment by dguihal** [comment]
totp field must be base 32 encoded

`echo -n 'VERYLONGTOTPHERE' | base32`

https://github.com/gopasspw/gopass/blob/master/docs/features.md#adding-otp-secrets

**Comment by swt30** [comment]
For anyone else with the same problem - I've been getting around this by manually converting totp secrets to uppercase, removing spaces, and adding ==== padding at the end to make the secret's length a multiple of 8. The next release might also fix this, as the gokyle dependency has been updated
