### ISSUE TITLE
Do not store user files in root of home

### ISSUE THREAD

**Issue by Magissia** [gopasspw/gopass#1225]
### Summary

When starting gopass, it tries to create a .password-store file directly at the root of $HOME
### Steps To Reproduce

Start gopass

### Expected behavior

FIle .password-store should be stored at $XDG_CONFIG_HOME, if it does not exist, it should default to $HOME/.config/gopass on unix and %appdata%/gopass on Windows.
### Environment

Windows 10 1809
Linux Mint 19
gopass 1.8.6
Installation from github packages/binaries

### Additional context

While far away from critical, let's try to not clutter users' root directory, you cannot predict what will be displayed or not to users when they browse their files.

Please take a look at https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by dominikschulz** [comment]
This is a compatibility thing. We can certainly consider to change it when creating new stores.

**Comment by Magissia** [comment]
Was it considered ?

**Comment by dominikschulz** [comment]
Reading the freedesktop spec it seems like we should rather consider usign $XDG_DATA_HOME for the password store, but as I said: it will break compability. This is something we're considering for an eventual 2.0 release anyway, but this won't happen in the 1.x series.

**Comment by dominikschulz** [comment]
We should probably at least consider this for newly created substores. These aren't compatible anyway.
