### ISSUE TITLE
selection dialog hangs on FreeBSD wiht go >=1.13

### ISSUE THREAD

**Issue by aperum** [gopasspw/gopass#1226]
### Summary

The secret selection screen hangs, cursor movement or cancelation do not work, and has to be killed.

### Steps To Reproduce

When opening the selection dialog with `gopass searchstring` the selection screen is drawn and then hangs and must be killed.

### Expected behavior

Entries can be selected from the list or the dialog can be canceled

### Environment

OS:  FreeBSD 12.1
gopass: 1.8.6
golang: 1.13.5

Compiled from source

### Additional context

I did alot of tests and could narrow it down to the following:

Compiling gopass with go 1.12.x results in a working dialog but compiling with go >= 1.13 exhibits the faulty behaviour. The culprit seems to be termbox-go which in turn is used by gocui. It depends heavily on the syscall package which has been deprecated by the go team in favour of x/sys/unix.
It seems to hang in the mainloop when waiting for SIGIO events. As the termbox-go README states the package is now "somewhat unmaintained" so opening a bug report there may not result in a fix. The gocui package also seems to be unmaintained as the last commit is from April, 2018.

I tried a dirty hack by replacing the termbox-go dependency in gocui with github.com/gdamore/tcell/termbox which then also results in a working dialog.

As a side note: The github binary release works. I think it may be build with golang <1.13?

**Comment by aperum** [comment]
Bump issue as i get more and more reports from people using the FreeBSD port about this

**Comment by mbeck-** [comment]
Seems to work for me now when building from ports. The port does have a few patches now.

**Comment by aperum** [comment]
Yes, we committed a patch based on my ugly hack described in this ticket. This works for now but also replaces termbox-go with tcell/termbox. Going forward this might not be compatible with future versions, so a fix in the project would be preferable.
