### ISSUE TITLE
[feat] gopass env command (export keys as environment variables)

### ISSUE THREAD

**Issue by marco-m** [gopasspw/gopass#1227]
Hello,

I would like to propose a `gopass env` command, in the same spirit of the [envchain](https://github.com/sorah/envchain) or [aws-vault](https://github.com/99designs/aws-vault) utilities.

For example, assuming a password store:

```
scaleway
    ├── SCW_ACCESS_KEY
    └── SCW_SECRET_KEY
```

Running
```
gopass env scaleway -- terraform apply
```
would execute the command `terraform apply` making available as environment variables they keys found below the `scaleway` directory.

If the argument to `env` is not a directory but a key, then gopass would export only that key.
If the argument is a directory that contains subdirectories, then the invocation would fail.

I think that this feature would greatly simplify the usage of gopass for certain cases, such as the terraform example or any example where the utility to be invoked supports environment variables.

For example, the example above today requires something like

```
env SCW_ACCESS_KEY=$(gopass scaleway/access_key) \
    SCW_SECRET_KEY=$(gopass scaleway/secret_key) \
    terraform apply
```

or something like

```
terraform apply \
  -var="access_key=$(gopass scaleway/access_key)" \
  -var="secret_key=$(gopass scaleway/secret_key)"
```

If this feature is considered useful, I would like to propose a PR.

Thanks!

**Comment by martinhoefling** [comment]
That's an interesting idea, I personally use summon in combination with gopass to achieve environment variable injection but that would be even simpler with your suggestion.

**Comment by marco-m** [comment]
Hello stalebot please leave it open
