### ISSUE TITLE
[feat] Support for AWS KMS asymmetric encryption

### ISSUE THREAD

**Issue by danmx** [gopasspw/gopass#1229]
AWS KMS now support asymmetric encryption. Support in gopass would be very useful for some automation tasks or to restrict access to secrets based on AWS IAM.

**Comment by worldofgeese** [comment]
@dominikschulz can we reopen this issue? I think its inclusion would make gopass palatable for corporate use

**Comment by dominikschulz** [comment]
I'm afraid I'll need more information.

I've never used AWS KMS.

Could someone please give a detailed description (incl. Links to Docs) of how this should look like?

**Comment by dominikschulz** [comment]
gopass is designed to be offline first. A dependency on a cloud service doesn't fit that very well.
If with `palatable for corporate use` you mean strict auditing and access control then, I'm afraid, you shouldn't use gopass.

If you want a reliable and low-dependency store for personal use, small teams and disaster recovery then I suggest using gopass.
