### ISSUE TITLE
[feat] gopass run shell scripts

### ISSUE THREAD

**Issue by edsoncsouza** [gopasspw/gopass#1234]
### Summary
I use gopass to run bash scripts for more complex authentications.
For this, I have a function that overlaps gopass 
```
gopass () {
        GOPASSCMD="${commands[gopass]}"
        case $1 in

                (exec) bash -i -c "$($GOPASSCMD "${@:2}")" ;;
                (*) command "${GOPASSCMD}" "$@" ;;
        esac
}
```

With this, I can have records similar to this
```
---
totp: ABCDEFGHIJ

login: |-
  token=$(AWS_ACCESS_KEY_ID="AK000000000000000000" \
  AWS_SECRET_ACCESS_KEY="abcabcabcabcabcabcabcabcabc" \
  aws sts get-session-token \
  --serial-number "arn:aws:iam::77123123123:mfa/user1" \
  --token-code "$(gopass otp aws/role1 --password)" --duration-seconds 3600 | jq -c)
  cat <<EOF > ~/.aws/credentials
  [default]
  aws_access_key_id     = $(jq -r '.Credentials.AccessKeyId' <<< $token)
  aws_secret_access_key = $(jq -r '.Credentials.SecretAccessKey' <<< $token)
  aws_session_token     = $(jq -r '.Credentials.SessionToken' <<< $token)
  aws_security_token    = $(jq -r '.Credentials.SessionToken' <<< $token)

  EOF
  cat <<EOF > ~/.aws/config
  [profile default]
  region=us-east-1
  output=json
  role_arn = arn:aws:iam::78123123123:role/role1
  EOF
```

So I can run the gopass this way to run the shell script
```
gopass exec aws/role1 login
```

This can be very useful as it makes it easier to automate some more complex logins
I think it would be an interesting feature for gopass

**Comment by dominikschulz** [comment]
We already have the `env` subcommand and your shell function also seems to be a nice workaround.

But we're actively trying to trim down the number of non-essential features.
So unless this gets a lot of support and a clean implementation I think we won't support this use case.
