### ISSUE TITLE
gopass removes second line if it's an empty line

### ISSUE THREAD

**Issue by evgeni** [gopasspw/gopass#1235]
### Summary
When storing (or reading) secrets with `gopass`, the second line of a multiline file is erased, if it's an empty line.

### Steps To Reproduce
`gopass insert --multiline test`

enter the following:
```
this

is

a

test
```

`gopass show test` returns

```
this
is

a

test
```

### Expected behavior
`gopass show test` returns

```
this

is

a

test
```

### Environment

- OS: Fedora 31
- OS version: Linux yatsu 5.3.16-300.fc31.x86_64 #1 SMP Fri Dec 13 17:59:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- gopass Version:
```
gopass 1.8.6-git+HEAD go1.13.3 linux amd64
<root>     - gpg 2.2.18 - git 2.24.1 -   fs 0.1.0
Available Crypto Backends: gpgcli, openpgp, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
```
- Installation method: copr

### Additional context
* Original `pass` handles this correctly.
* The newline is removed on `insert` *and* `show`, so even secrets created with `pass` show up wrongly.
* Might be related to #1204 and #1121

**Comment by dominikschulz** [comment]
Yes, this is indeed related to #1121. 
For this case there might be a fix possible, but it all boils down to the heuristic we apply about the content of a secret.

We should probably stop doing that. Maybe secrets show have a content type.
And if they don't have one they are just handled as plain text.

Or they are always plain text. Not sure. I will try to fix this, if it doesn't break other workflows.
