### ISSUE TITLE
Duplicate / redundant public key files in sub-stores

### ISSUE THREAD

**Issue by jraygauthier** [gopasspw/gopass#1238]
### Summary

gopass stores redundant public key files in a sub-store `.public-keys` when
those files can be found in their parent store's `.public-keys` folder.

These files take about 5K each, this becomes a concern when using
sub-stores to store secrets for multiple devices accessible by multiple
gpg users. In fact, the public keys ends up taking as much space as the
secrets themselves.

 -  Complete example at: [nixos-sf-demo-device-secrets].

    Duplicate public keys sample:

     -  [.public-keys/0x15188BCAC872FFAF](https://github.com/jraygauthier/nixos-sf-demo-device-secrets/blob/master/.public-keys/0x15188BCAC872FFAF)

        The parent key.

     -  [device/demo-virtual-box-vm/.public-keys/0x15188BCAC872FFAF](https://github.com/jraygauthier/nixos-sf-demo-device-secrets/blob/master/device/demo-virtual-box-vm/.public-keys/0x15188BCAC872FFAF)

        A first duplicate.

     -  [device/another-demo-virtual-box-vm/.public-keys/0x15188BCAC872FFAF](https://github.com/jraygauthier/nixos-sf-demo-device-secrets/blob/master/device/another-demo-virtual-box-vm/.public-keys/0x15188BCAC872FFAF)

        Another duplicate.

### Steps to reproduce

I have the following `minimal-script-to-reproduce.sh`:

```bash
#!/usr/bin/env nix-shell
#!nix-shell -p gopass -p gnupg -i bash
printf "Removing whole gopass home (root store + config) and substores.\n"
yes | rm -fr "$PWD/.my-gopass-home" "$PWD/nixos-sf-demo-device-secrets"

export GOPASS_HOMEDIR="$PWD/.my-gopass-home"
export GOPASS_CONFIG="$GOPASS_HOMEDIR/.config/gopass/gopass.yaml"

export GNUPGHOME="$PWD/.gnupg"


printf "\nInit root store:\n"
gopass --yes init 'nixos-secure-factory@gmail.com'

printf "\nMounting 1st level substore 'nixos-sf-demo-device-secrets':\n"
gopass mounts add -i 'nixos-secure-factory@gmail.com' 'nixos-sf-demo-device-secrets' "gpgcli-gitcli-fs+file://$PWD/nixos-sf-demo-device-secrets"

printf "\nMounting 2nd level substore 'nixos-sf-demo-device-secrets/device/demo-virtual-box-vm':\n"
gopass mounts add -i 'nixos-secure-factory@gmail.com' 'nixos-sf-demo-device-secrets/device/demo-virtual-box-vm' "gpgcli-gitcli-fs+file://$PWD/nixos-sf-demo-device-secrets/device/demo-virtual-box-vm"

printf "\nMounting another 2nd level substore 'nixos-sf-demo-device-secrets/device/another-demo-virtual-box-vm':\n"
gopass mounts add -i 'nixos-secure-factory@gmail.com' 'nixos-sf-demo-device-secrets/device/another-demo-virtual-box-vm' "gpgcli-gitcli-fs+file://$PWD/nixos-sf-demo-device-secrets/device/another-demo-virtual-box-vm"

printf "\nPrinting recipients list:\n"
gopass recipients
```

which when I execute yields:

```bash
$ ./minimal-script-to-reproduce.sh

Removing whole gopass home (root store + config) and substores.

Init root store:
[init] Initializing a new password store ...
[init] Initializing git repository (gitcli) ...
[init] git initialized at /home/rgauthier/dev/my-nixos-secure-factory/.my-gopass-home/.password-store
[init] git configured at /home/rgauthier/dev/my-nixos-secure-factory/.my-gopass-home/.password-store
[init] Git initialized
[init] Password store /home/rgauthier/dev/my-nixos-secure-factory/.my-gopass-home/.password-store initialized for:
[init]   0x15188BCAC872FFAF - SecureFactory Nixos <nixos-secure-factory@gmail.com>

Mounting 1st level substore 'nixos-sf-demo-device-secrets':
Password store gpgcli-gitcli-fs+file:///home/rgauthier/dev/my-nixos-secure-factory/nixos-sf-demo-device-secrets initialized for:
8CFE2147789A4566A9869DA615188BCAC872FFAF
Mounted nixos-sf-demo-device-secrets as gpgcli-gitcli-fs+file:///home/rgauthier/dev/my-nixos-secure-factory/nixos-sf-demo-device-secrets

Mounting 2nd level substore 'nixos-sf-demo-device-secrets/device/demo-virtual-box-vm':
Password store gpgcli-gitcli-fs+file:///home/rgauthier/dev/my-nixos-secure-factory/nixos-sf-demo-device-secrets/device/demo-virtual-box-vm initialized for:
8CFE2147789A4566A9869DA615188BCAC872FFAF
Mounted nixos-sf-demo-device-secrets/device/demo-virtual-box-vm as gpgcli-gitcli-fs+file:///home/rgauthier/dev/my-nixos-secure-factory/nixos-sf-demo-device-secrets/device/demo-virtual-box-vm

Mounting another 2nd level substore 'nixos-sf-demo-device-secrets/device/another-demo-virtual-box-vm':
Password store gpgcli-gitcli-fs+file:///home/rgauthier/dev/my-nixos-secure-factory/nixos-sf-demo-device-secrets/device/another-demo-virtual-box-vm initialized for:
8CFE2147789A4566A9869DA615188BCAC872FFAF
Mounted nixos-sf-demo-device-secrets/device/another-demo-virtual-box-vm as gpgcli-gitcli-fs+file:///home/rgauthier/dev/my-nixos-secure-factory/nixos-sf-demo-device-secrets/device/another-demo-virtual-box-vm

Printing recipients list:
Hint: run 'gopass sync' to import any missing public keys
gopass
├── nixos-sf-demo-device-secrets (/home/rgauthier/dev/my-nixos-secure-factory/nixos-sf-demo-device-secrets)
│   ├── device
│   │   ├── another-demo-virtual-box-vm (/home/rgauthier/dev/my-nixos-secure-factory/nixos-sf-demo-device-secrets/device/another-demo-virtual-box-vm)
│   │   │   └── 0x15188BCAC872FFAF - SecureFactory Nixos <nixos-secure-factory@gmail.com>
│   │   └── demo-virtual-box-vm (/home/rgauthier/dev/my-nixos-secure-factory/nixos-sf-demo-device-secrets/device/demo-virtual-box-vm)
│   │       └── 0x15188BCAC872FFAF - SecureFactory Nixos <nixos-secure-factory@gmail.com>
│   └── 0x15188BCAC872FFAF - SecureFactory Nixos <nixos-secure-factory@gmail.com>
└── 0x15188BCAC872FFAF - SecureFactory Nixos <nixos-secure-factory@gmail.com>
```

Now, when I look at the generated files:

```bash
$ tree -s -h -a nixos-sf-demo-device-secrets
nixos-sf-demo-device-secrets
├── [4.0K]  device
│   ├── [4.0K]  another-demo-virtual-box-vm
│   │   ├── [  19]  .gpg-id
│   │   └── [4.0K]  .public-keys
│   │       └── [4.6K]  0x15188BCAC872FFAF
│   └── [4.0K]  demo-virtual-box-vm
│       ├── [  19]  .gpg-id
│       └── [4.0K]  .public-keys
│           └── [4.6K]  0x15188BCAC872FFAF
├── [  19]  .gpg-id
└── [4.0K]  .public-keys
    └── [4.6K]  0x15188BCAC872FFAF

6 directories, 6 files
```

I can see there are 3 identical copies of the `0x15188BCAC872FFAF` public key of about 5K each.

That might seems fine for this simple case, but now as I expect to store secrets for many devices (i.e: many sub-stores) and authorize multiple users to each sub-stores, this redundancy becomes quite annoying. Here's the actual listing of files taken from [nixos-sf-demo-device-secrets] which is closer to our goal:

```bash
$ tree -I '.git' -s -h -a nixos-sf-demo-device-secrets
nixos-sf-demo-device-secrets
├── [4.0K]  device
│   ├── [4.0K]  another-demo-virtual-box-vm
│   │   ├── [4.0K]  etc
│   │   │   └── [4.0K]  ssh
│   │   │       ├── [2.2K]  ssh_host_ed25519_key.b64.gpg
│   │   │       ├── [1.8K]  ssh_host_ed25519_key.pub.b64.gpg
│   │   │       ├── [6.1K]  ssh_host_rsa_key.b64.gpg
│   │   │       └── [2.6K]  ssh_host_rsa_key.pub.b64.gpg
│   │   ├── [ 123]  .gpg-id
│   │   ├── [4.0K]  .public-keys
│   │   │   ├── [4.6K]  0x15188BCAC872FFAF
│   │   │   ├── [4.6K]  8CFE2147789A4566A9869DA615188BCAC872FFAF
│   │   │   ├── [4.6K]  BBC8F046A7E47B2C9D325D30EAFCBBEA44A1FADC
│   │   │   └── [4.6K]  CC6A025C9620195AF81141AD0C3EB41A4A4E9D8A
│   │   └── [4.0K]  root
│   │       ├── [4.0K]  _gnupg
│   │       │   ├── [1.8K]  gpg-otrust.b64.gpg
│   │       │   └── [8.6K]  subkeys.gpg-keys.b64.gpg
│   │       └── [4.0K]  _ssh
│   │           ├── [6.1K]  id_rsa.b64.gpg
│   │           └── [2.6K]  id_rsa.pub.b64.gpg
│   └── [4.0K]  demo-virtual-box-vm
│       ├── [4.0K]  etc
│       │   └── [4.0K]  ssh
│       │       ├── [2.2K]  ssh_host_ed25519_key.b64.gpg
│       │       ├── [1.8K]  ssh_host_ed25519_key.pub.b64.gpg
│       │       ├── [6.0K]  ssh_host_rsa_key.b64.gpg
│       │       └── [2.6K]  ssh_host_rsa_key.pub.b64.gpg
│       ├── [ 123]  .gpg-id
│       ├── [4.0K]  .public-keys
│       │   ├── [4.6K]  08E65A21FA20E76B336E2732A2D39F41CCBA5A84
│       │   ├── [4.6K]  0x15188BCAC872FFAF
│       │   ├── [4.6K]  3177342A2FF4AC78D986EA01383296D774073EE9
│       │   └── [4.6K]  8CFE2147789A4566A9869DA615188BCAC872FFAF
│       └── [4.0K]  root
│           ├── [4.0K]  _gnupg
│           │   ├── [1.8K]  gpg-otrust.b64.gpg
│           │   └── [8.6K]  subkeys.gpg-keys.b64.gpg
│           └── [4.0K]  _ssh
│               ├── [6.0K]  id_rsa.b64.gpg
│               └── [2.6K]  id_rsa.pub.b64.gpg
├── [  19]  .gpg-id
├── [ 11K]  LICENSE
└── [4.0K]  .public-keys
    └── [4.6K]  0x15188BCAC872FFAF

16 directories, 29 files
```

As you can see, the overall size of the public keys in a sub-store take about
the same size as the encrypted secrets themselves. And, in this example, only 2
gpg users are allowed to device sub-stores (the device itself and another user).

### Expected behaviour

Would it be possible to prevent such duplication for similar cases either by a
configuration option, a flag or even by default when detected?

Some ideas:

 -  Not storing the public key in the sub-store at all and assuming
    the sub-store *inherits* from the store's public keys.

 -  Using symlinks for sub-store keys already in parent store.

    `nixos-sf-demo-device-secrets/device/demo-virtual-box-vm/.public-keys/0x15188BCAC872FFAF`
    -> `nixos-sf-demo-device-secrets/.public-keys/0x15188BCAC872FFAF`

Thanks for the great tool by the way.

### Environment

```bash
$ uname -a
Linux rgauthier 4.14.154 #1-NixOS SMP Tue Nov 12 18:19:08 UTC 2019 x86_64 GNU/Linux

$ gopass --version
gopass 1.8.6-git+HEAD go1.12.9 linux amd64

$ gpg --version
gpg (GnuPG) 2.2.17
libgcrypt 1.8.5
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/rgauthier/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

[nixos-sf-demo-device-secrets]: https://github.com/jraygauthier/nixos-sf-demo-device-secrets

**Comment by dominikschulz** [comment]
Thank you very much for the execellent bug report. This makes it very easy to reproduce and understand your use case.

The gopass substore support was designed to support a small number of mounted stores with a usually small number of recipients each. We did not anticipate using a very large number of mounted stores with a lot of recipients.

Is this a real issue, e.g. due to limited resources, or more a theoretical concern?

If this is a real problem the best I could offer would be a config option to disable exporting these keys at all (per mount).

Inheriting or linking keys across mounts doesn't seem to be feasible to me, some of my use cases rely on the fact of substores being completely independent.

**Comment by ibot3** [comment]
> If this is a real problem the best I could offer would be a config option to disable exporting these keys at all (per mount).

This would be an helpful option. I have a mounted store where the public keys are in an other folder than ".public-keys" and also have other names. I would just like to be able to disable key syncing for this mount.

**Comment by jraygauthier** [comment]
@dominikschulz :

> Is this a real issue, e.g. due to limited resources, or more a theoretical concern?

Theoretical for the time being, however we were afraid it might eventually come to become a real issue as devices were added.

> If this is a real problem the best I could offer would be a config option to disable exporting these keys at all (per mount).

This seems like a reasonable option to solve our problem.

> Inheriting or linking keys across mounts doesn't seem to be feasible to me, some of my use cases rely on the fact of substores being completely independent.

Indeed such an inheritance scheme might get tricky, much more so across repositories. I understand why you hesitate to add this kind of complexity.

Thanks for the fix.
