### ISSUE TITLE
Gopass colors not shown > 45-ish entries

### ISSUE THREAD

**Issue by RayOei** [gopasspw/gopass#1244]
<img width="219" alt="Screenshot 2020-01-27 at 17 07 39" src="https://user-images.githubusercontent.com/10501445/73191481-dae21100-4127-11ea-927f-4b20c080747e.png">
<img width="233" alt="Screenshot 2020-01-27 at 17 07 55" src="https://user-images.githubusercontent.com/10501445/73191482-db7aa780-4127-11ea-933a-cc20f54a7ae0.png">

### Summary

Gopass doesn't display the tree overview with colors after a certain number of entries

### Steps To Reproduce

I have created a new store with 1 entry (test) with 2 passwords
I have added 46 additional passwords (all copies of the same one)
When I add entry 47 the colors of the `gopass-->test` tree entry are no longer shown.
When I remove the last entry the `gopass-->test` tree entry are shown in color again.

Note: I also tried this with additional stores, same thing. At some points the colors disappear.

### Expected behavior

I expect the color to be shown of the tree entries regardless of the number of passwords stored.

### Environment

Mac OS X Catalina. Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
Gopass version info: gopass 1.8.6 (d5b0d3b906cdd9f16ad3f21e366845af7f2c22f3 2019-10-11 18:54:23) go1.13.1 darwin amd64
Installed with Brew 2.2.4

### Additional context

Pass shows the colors

<img width="237" alt="Screenshot 2020-01-27 at 20 18 17" src="https://user-images.githubusercontent.com/10501445/73205992-59e44300-4142-11ea-88ed-ba96c03f5f16.png">

**Comment by dominikschulz** [comment]
I'm afraid, this is not a bug but a feature.
By default gopass will redirect the output to a pager if it's longer than the current terminal.
Some pagers don't handle ANSI color codes, so the output would be broken if colored.
This is why we turn colors off in such cases.

However we can do better and not disable colors if `$PAGER` is not defined.
