### ISSUE TITLE
gopass doesn't commit when using concurrency > 1

### ISSUE THREAD

**Issue by yann-soubeyrand** [gopasspw/gopass#1246]
### Summary

When configuring gopass concurrency option to a value greater than 1, gopass doesn't commit in Git when creating a new entry.

### Steps To Reproduce

```
gopass init --store test
gopass recipients update
cd .password-store-test/
git status
```

Output shows a clean state.

```
gopass insert test/test
git status
```

Output shows a clean state.

```
gopass config --store test concurrency 2
gopass insert test/test2
git status
```

Output shows a dirty state (`test2.gpg` is not committed).

### Expected behavior

Setting concurrency to 2 should not prevent gopass from committing new passwords in Git.

### Environment

- OS: Linux
- OS version:
```
Linux work-laptop 5.4.13-201.fc31.x86_64 #1 SMP Tue Jan 21 17:21:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
- gopass Version:
```gopass 1.8.6 (d5b0d3b906cdd9f16ad3f21e366845af7f2c22f3) go1.12.7 linux amd64
<root>     - gpg 2.2.18 - git 2.24.1 -   fs 0.1.0
Available Crypto Backends: gpgcli, openpgp, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
```
- Installation method: binary from Github release

**Comment by madonius** [comment]
I am seeing the same issue.

**Comment by dominikschulz** [comment]
Yes, this is obviously a bug. Should be easy to fix ...
