### ISSUE TITLE
gopass failed to install from source

### ISSUE THREAD

**Issue by rfc2119** [gopasspw/gopass#1248]
### Summary
On installing gopass with latest go version (go1.13.7.linux-386), the following error messages appear:
```
# github.com/gopasspw/gopass/pkg/completion/fish
../go/src/github.com/gopasspw/gopass/pkg/completion/fish/completion.go:42:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.BoolFlag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/fish/completion.go:44:8: undefined: cli.BoolTFlag
../go/src/github.com/gopasspw/gopass/pkg/completion/fish/completion.go:46:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.Float64Flag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/fish/completion.go:48:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.GenericFlag (IsSet method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/fish/completion.go:50:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.Int64Flag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/fish/completion.go:52:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.Int64SliceFlag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/fish/completion.go:54:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.IntFlag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/fish/completion.go:56:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.IntSliceFlag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/fish/completion.go:58:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.StringFlag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/fish/completion.go:60:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.StringSliceFlag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/fish/completion.go:60:3: too many errors
# github.com/gopasspw/gopass/pkg/completion/zsh
../go/src/github.com/gopasspw/gopass/pkg/completion/zsh/completion.go:25:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.BoolFlag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/zsh/completion.go:27:8: undefined: cli.BoolTFlag
../go/src/github.com/gopasspw/gopass/pkg/completion/zsh/completion.go:29:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.Float64Flag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/zsh/completion.go:31:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.GenericFlag (IsSet method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/zsh/completion.go:33:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.Int64Flag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/zsh/completion.go:35:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.Int64SliceFlag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/zsh/completion.go:37:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.IntFlag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/zsh/completion.go:39:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.IntSliceFlag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/zsh/completion.go:41:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.StringFlag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/zsh/completion.go:43:3: impossible type switch case: f (type cli.Flag) cannot have dynamic type cli.StringSliceFlag (Apply method has pointer receiver)
../go/src/github.com/gopasspw/gopass/pkg/completion/zsh/completion.go:43:3: too many errors
```

### Steps To Reproduce

1. install [golang binaries](https://dl.google.com/go/go1.13.7.linux-386.tar.gz) on an i386 linux machine, preferably with debian 9 (stretch)
2. run `go get github.com/gopasspw/gopass`

### Expected behavior
`gopass` should build successfully

### Environment

- OS: Debian 9
- OS version: Linux 4.9.0-11-686-pae #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) i686 GNU/Linux
- gopass Version: latest commit [here](https://github.com/gopasspw/gopass/commit/443198d9662ed9f03e4f8c250d9e3c31c8c46dc3)
- Installation method: from source

**Comment by dhjgithub** [comment]
Seeing exactly the same thing on Macos 10.14.6 using go1.13.7

**Comment by acheron2302** [comment]
#1214

**Comment by staticnotdynamic** [comment]
> #1214 i did make a pull request. The problem is when you install go get outside of the go folder it will download the latest version of urfave/cli which is v2 but the v1 is what we want so we need to change github.com to gopkg.in . The temporary solution now is go to go folder and manually install with git clone

Thank you, this worked. The latest working version of urfave/cli supporting current gopass code is v1.19.1. Here are the steps that you mentioned (in case anyone needs guidance):
```
cd $GOPATH/src/github.com/    # $GOPATH is by default your home directory
mkdir urfave && cd urfave
git clone https://github.com/urfave/cli
cd cli
git checkout v1.19.1
```

I'll try to provide a fix later, leaving this issue open for now

**Comment by staticnotdynamic** [comment]
I am new to golang, and I am wondering what is wrong. The specified version in `go.mod` should be correct:
https://github.com/gopasspw/gopass/blob/443198d9662ed9f03e4f8c250d9e3c31c8c46dc3/go.mod#L51

Could you please instruct me how to fix the issue ?

**Comment by acheron2302** [comment]
> I am new to golang, and I am wondering what is wrong. The specified version in `go.mod` should be correct:
> 
> https://github.com/gopasspw/gopass/blob/443198d9662ed9f03e4f8c250d9e3c31c8c46dc3/go.mod#L51
> 
> Could you please instruct me how to fix the issue ?

You don’t actually need to downgrade urfave/cli you can just go into the gopasspw/gopass folder and run `go get`

The reason when you run inside gopass folder it works but when you do it outside that folder it won’t because when you run go get outside the gopass folder it doesn’t have the go.mod file, which tell go the version it suppose to get. So without the go.mod to tell which version it default behavior is to get the latest and greatest version which is v2 but it is not compatible with v1. 

So the solution is just manually install gopass to the GOPATH folder and then manually run go get in that folder (that is a temporary solution until they accept my pull request so that it will read v1 regardless of the location you install from

**Comment by staticnotdynamic** [comment]
> > I am new to golang, and I am wondering what is wrong. The specified version in `go.mod` should be correct:
> > https://github.com/gopasspw/gopass/blob/443198d9662ed9f03e4f8c250d9e3c31c8c46dc3/go.mod#L51
> > 
> > Could you please instruct me how to fix the issue ?
> 
> You don’t actually need to downgrade urfave/cli you can just go into the gopasspw/gopass folder and run `go get`
> 
> The reason when you run inside gopass folder it works, but when you do it outside that folder it won’t. Because when you run go get outside the gopass folder, it doesn’t have the go.mod file, which tell go the version it suppose to get. So without the go.mod to tell which version it default behavior is to get the latest and greatest version which is v2 but it is not compatible with v1.
> 
> So the solution is just manually install gopass to the GOPATH folder and then manually run `go get` in that folder (that is a temporary solution until they accept my pull request so that it will read v1 regardless of the location you install from) #1242

I see. Thank you for your explanation! I'll be closing this issue then
