### ISSUE TITLE
Can gopass be used as a drop-in replacement of pass binary ? (excluding extensions)

### ISSUE THREAD

**Issue by Magissia** [gopasspw/gopass#1250]
Hi,

Can gopass be used as a drop-in replacement of pass binary ? (excluding extensions)
Same as how mariadb was back in the time a drop-in replacement of MySQL and the client couldn't know without searching it was not MySQL, for example by symlinking gopass to pass ?

If not, would it be considered to allow gopass to masquerade as pass if called from "pass" ?
It could still silently git push changes.

**Comment by martinhoefling** [comment]
The ability to be used as a drop-in replacement depends on the usage. I have successfully used it in qtpass. As mentioned in https://github.com/gopasspw/gopass#features, gopass brings its own set of additional features but does not support pass extensions.

**Comment by wakatara** [comment]
I've been using it that way and have symlinked `pass` to `gopass` without problems though I use it mostly as a cli password manager, in my browser to replace things like lastpass/dashlane, and using Pass for iOS. I have a [blog post outlining that process if it's helpful](https://daryl.wakatara.com/password-management-with-gopass-password-store-gopass-bridge-and-pass-for-ios).

Very happy with `gopass`. So far my only issue is trying to figure out how to re-encrypt the entire password store to.a new key like in class `pass`

**Comment by metalmatze** [comment]
From the beginning, the idea was to be compatible. We have thought about breaking that in a v2 release, to maybe even introduce some new features that are blocked by today's compatibility, but we're no where close to that.

**Comment by dominikschulz** [comment]
At the moment the answer is: yes.
However this might change in the future.
Depending on pending design discussions.
