### ISSUE TITLE
HOTP returning always the same code

### ISSUE THREAD

**Issue by Fale** [gopasspw/gopass#1253]
### Summary
I have an HOTP stored in a secred, as follow:

```
fale@x250:~ $ gopass test/hotp
otpauth://hotp/OATH343174AA?secret=quokk1gtLnt2HplCHcyajSKD&counter=1&digits=6&issuer=MyCompany
```

### Steps To Reproduce
Execute multple times:

```
gopass hotp test/hotp
```

### Results
```
fale@x250:~ $ gopass hotp test/hotp
067379 lasts 25s 	|-----=========================|
fale@x250:~ $ gopass hotp test/hotp
067379 lasts 18s 	|------------==================|
fale@x250:~ $ gopass hotp test/hotp
067379 lasts 12s 	|------------------============|
fale@x250:~ $ gopass hotp test/hotp
067379 lasts 7s 	|-----------------------=======|
fale@x250:~ $ gopass hotp test/hotp
067379 lasts 2s 	|----------------------------==|
fale@x250:~ $ gopass hotp test/hotp
067379 lasts 28s 	|--============================|
```

### Expected behavior
Have different hotp at every run

### Environment
- OS: Fedora 31(Linux x250.fale.io 5.5.5-200.fc31.x86_64 #1 SMP Wed Feb 19 23:28:07 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux)
- gopass Version: gopass 1.8.6-git+HEAD go1.13.3 linux amd64
- Installation method: copr repo

### Additional context
I would expect the secret to change at every run, to account for the counter increase, while this does not happens

PS: Also, the count down has no sense in an HOTP

**Comment by martinhoefling** [comment]
I am not sure to what extend hotp is supported. Maybe only totp is supported (which the output would indicate). In order to support hotp, the counter (which is set to 1 in your example) would need to be incremented and stored in every hotp call.

**Comment by Fale** [comment]
In the Readme, the HOTP is stated as supported: https://github.com/gopasspw/gopass/blame/master/README.md#L60

An idea could also be changing the README to remove this declaration as well as throwing an error if an HOTP token is requested

**Comment by martinhoefling** [comment]
I have tested HOTP support and it seems to work, if you manually increment the counter. I will create a PR that clarifies this in the documentation.

**Comment by Fale** [comment]
I think that if we want to say that gopass supports it, gopass should increase the counter
