### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by rafasc** [gopasspw/gopass#1261]
### Summary
Gopass seems to be using absurd amounts of memory.

### Steps To Reproduce
Run `go pass audit`. It consistently uses more than 3GiB or RAM, which in my case is enough to trigger the kernel oom killer.

I've seen other operations, e.g. `gopass edit ...` sometimes work, sometimes explode. But `audit` reproduced it 100% of the times I tried.

### Expected behavior
Do not use 3GiB of memory.

### Environment
- OS: ArchLinux
- OS version: Linux rigel 5.5.13-arch2-1 # 1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux
- gopass Version: gopass 1.8.6 (06d43f3b 2020-04-03 18:11:56) go1.14.1 linux amd64
<root>     - gpg 2.2.20 - git 2.26.0 -   fs 0.1.0
Available Crypto Backends: gpgcli, openpgp, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
- Installation method: Installed arch linux official repo.

**Comment by rafasc** [comment]
Having big dictionaries in `/usr/share/dict` will trigger this.

The issue is technically from the muesli/crunchy dependency, but depending how it gets solved there, changes to gopass might be necessary. 

https://github.com/muesli/crunchy/pull/7 should help, but it is not a solutio. So I suggest leaving this issue open until the issue gets solved.

**Comment by dominikschulz** [comment]
We're already using v0.4.0 which includes your fix.

**Comment by rafasc** [comment]
I am not against closing the issue, and while that fix might help, the problem still exists for users with large files at `/usr/share/dict`. 

But upstream is already aware of it, and since I misattributed it to gopass I think it is a fair close.

Thanks.

**Comment by lafriks** [comment]
It's still an issue with latest version
