### ISSUE TITLE
Specifiying a relative path breaks the store

### ISSUE THREAD

**Issue by dragetd** [gopasspw/gopass#1262]
If you specify --path (e.g. when using init) with a relative directory, it will mess up the config.

`gopass init --store test --path .mystores/test` will correctly create `/home/draget/.mystores/test` but save into the config `//.mystores/test`.

This results in the incorrect/misleading error message, that the store is already initialized and breaks everything else badly.

A workaround is to use an expanded, absolute path `~/.mystores/test`.

A simple fix would be to always expand to an absolute path or forbid relative paths with a better error message. (which I would not prefer).

But I would rather prefer:
- Expand to absolute path
- Check if the users HOME-directory is a prefix of the absolute path
- Replace the prefix with `~`

gopass 1.8.6-git+HEAD go1.12.13 linux amd64

**Comment by dominikschulz** [comment]
The `~` discussion is tracked as part of #872

**Comment by dominikschulz** [comment]
Fixed by #1451
