### ISSUE TITLE
No longer maintained Termbox is causing a panic error

### ISSUE THREAD

**Issue by doronbehar** [gopasspw/gopass#1264]
I'm getting this error with `gopass create`:

```
panic: termbox: error while reading terminfo data: termbox: unsupported terminal

goroutine 1 [running]:
github.com/gopasspw/gopass/pkg/cui.GetSelection(0xda1c60, 0xc0002a6480, 0xc938ce, 0x39, 0xc95c47, 0x41, 0xc0002ab0e0, 0x5, 0x5, 0x0, ...)
        /var/src/gopass/pkg/cui/cui.go:184 +0x58f
github.com/gopasspw/gopass/pkg/action/create.Create(0xda1c60, 0xc0002a6480, 0xc0002fa160, 0xd9ebe0, 0xc0002a6420, 0xad6e36, 0xc0002bb260)
        /var/src/gopass/pkg/action/create/create.go:57 +0x374
main.getCommands.func28(0xc0002fa160, 0x0, 0xc0002bb260)
        /var/src/gopass/commands.go:293 +0x86
github.com/urfave/cli.HandleAction(0xb4f840, 0xc000296340, 0xc0002fa160, 0xc0002fa160, 0x0)
        /var/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:526 +0x11a
github.com/urfave/cli.Command.Run(0xc406ec, 0x6, 0x0, 0x0, 0xc000294440, 0x1, 0x1, 0xc7e2df, 0x1c, 0x0, ...)
        /var/go/pkg/mod/github.com/urfave/cli@v1.22.4/command.go:174 +0x57a
github.com/urfave/cli.(*App).Run(0xc0002d4000, 0xc0000ba000, 0x2, 0x2, 0x0, 0x0)
        /var/go/pkg/mod/github.com/urfave/cli@v1.22.4/app.go:279 +0x7c7
main.main()
        /var/src/gopass/main.go:67 +0x314
```

Which is what's reported in https://github.com/gopasspw/gopass/issues/1072.

This issue is due to a termbox issue (https://github.com/nsf/termbox-go/issues/215) which I suggested to fix in https://github.com/nsf/termbox-go/pull/216 but `@nsf` said that termbox is no longer maintained and that [tcell](https://github.com/gdamore/tcell) is a recommended replacement. Gopass uses termbox inderectly - via [gocui](https://github.com/jroimartin/gocui) which also acts as unmaintained according to [it's PRs](https://github.com/jroimartin/gocui/pulls?q=is%3Apr+is%3Aopen). Because of all that, I patched termbox in my own fork and patched gocui and gopass to use my own fork at https://github.com/doronbehar/gopass/tree/doronbehar-termbox and I experience this error no more.

Would you be willing to consider switching to my fork of termbox until a replacement for it will be written? I can send a PR straight from https://github.com/doronbehar/gopass/tree/doronbehar-termbox .

Regards.

**Comment by dominikschulz** [comment]
That sounds good. Feel free to send a PR.
