### ISSUE TITLE
Must not overwrite config is PASSWORD_STORE_DIR is set

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#1286]
Since https://github.com/gopasspw/gopass/pull/1284 gopass overwrites it's configuration if PASSWORD_STORE_DIR is set.

This must not happen.

**Comment by sigio** [comment]
In my case, PASSWORD_STORE_DIR was only set in some directories (direnv).
I've worked around this to always set PASSWORD_STORE_DIR in my shell, instead of switching between (default/empty when in my homedir and set to a non-default when in a 'work' dir).
