### ISSUE TITLE
Gopass doesn't load config when PASSWORD_STORE_DIR is set

### ISSUE THREAD

**Issue by frebib** [gopasspw/gopass#1322]
### Summary
Since 5dc6b7b9e7a1207270b41126cf6811a88de6d920, gopass isn't loading my config, and therefore my mounts. I have the `PASSWORD_STORE_DIR` value set to the root repo for backwards compatibility with `pass` but now that no longer works.

### Steps To Reproduce
1. Configure gopass (add a mount)
2. Set `PASSWORD_STORE_DIR` to some value
3. Observe that the config/mounts are not loaded

### Expected behavior
1. Mounts are still loaded, as before

**Comment by dominikschulz** [comment]
You are right. Supporting PASSWORD_STORE_DIR requires an awful lot of workarounds.
This doesn't really fly with the gopass config model.

I'll just drop PASSWORD_STORE_DIR support for anything but the first use (when no config exists, yet).
