### ISSUE TITLE
Inconsistent package file name structure with 1.9.0

### ISSUE THREAD

**Issue by desolat** [gopasspw/gopass#1331]
### Summary
With release 1.9.0 the package file names (deb, rpm) use underscores as separators instead of dashes (as the other assets and also the previous releases).

This brakes (our) existing deployment automation.

### Expected behavior
File naming structure stays consistent over releases.

### Environment
- gopass Version: 1.9.0

**Comment by dominikschulz** [comment]
Hmm, indeed. We have switched from a extremely outdated, patched release of goreleaser to the current upstream version and they seem to have changed that.

It's been a while since I did Debian packaging. Are both kinds of separators valid?

**Comment by desolat** [comment]
> Are both kinds of separators valid?

Maybe, but that my primary problem is with the inconsistency in naming: I'm using config automation for the installation of gopass and thus need to have a predictable filename structure. 

And I'm consuming the Debian package from GitHub as the Debian repository as documented in https://github.com/gopasspw/gopass/blob/master/docs/setup.md#ubuntu--debian-1 does not contain the latest releases. But I'll open a separate issue for this.

**Comment by dominikschulz** [comment]
Thanks, the documentation has been updated.

Debian hosting is painful. We don't have the resources to do that properly at the moment.

I understand your concerns wrt. automation, but before trying to fix this I need to understand if there is some official recommendation or not. If there is none I'd expect automation to be able to handle both variants.

If there is some, we'll try to comply.

**Comment by dominikschulz** [comment]
I'm sorry for breaking your automation, but I believe the new naming is correct wrt. the Debian Policy (see the example [here](https://www.debian.org/doc/debian-policy/ch-controlfields.html#checksums-sha1-and-checksums-sha256)).
