### ISSUE TITLE
More detailed error message for the show action

### ISSUE THREAD

**Issue by kristianmitk** [gopasspw/gopass#1332]
### Summary

My path to the pinentry-program in `gpg-agent.conf` was broken, causing gpg failing with:

```sh
gpg: public key decryption failed: No pinentry
gpg: decryption failed: No secret key
```
when trying to decrypt with `gpg -d ...`.

When calling `gopass show ...` I get:

```sh
Error: failed to retrieve secret '...': Failed to decrypt
```
which itself is totally fine, but could provide more information - like the error message from gpg - which would hint me directly to the problem.

### Steps To Reproduce
1. Break the path to `pinentry-programm` in your `gpg-agent.conf` and kill the gpg agent
2. Call `gopass show <pass-entry>`
3. Call `gpg -d <path-to-entry-file>`

### Expected behavior
Provide more detailed information on the error.

### Environment

- OS: Mac OS Mojave (10.14.6)
- gopass Version: gopass 1.8.6 (d5b0d3b906cdd9f16ad3f21e366845af7f2c22f3 2019-07-26 13:43:34) go1.12.7 darwin amd64
- Installation method: `go get ...`

### Additional context
gpg (GnuPG) 2.2.17
libgcrypt 1.8.5

**Comment by dominikschulz** [comment]
Thank you for reporting this issue.
This seems like a good ux improvement.

**Comment by dominikschulz** [comment]
`cmd.Stderr` is already hooked up to `os.Stderr` so you should be able to see anything that gpg prints to STDERR.
