### ISSUE TITLE
gopass insert in Windows cmd/powershell - error: not a terminal

### ISSUE THREAD

**Issue by tetrodoxin** [gopasspw/gopass#1333]
### Summary
In windows, if I try to insert a password via `gopass insert somepass` there's an error stating:
```
Error: failed to ask for password: not a terminal
```
This happens regardless of using `cmd.exe` or powershell.
However, `gopass edit newpass` works, opening notepad.

### Steps To Reproduce

1. Download windows binary (Release 1.9.0 windows amd64)
2. Copy binary to C;\Program Files\gopass
3. Add this directory to PATH-variable
4. Run gopass init process
5. Insert `gopass insert somepass`

### Expected behavior
A prompt asking for the password.

### Environment
- OS: Windows 10 Pro Build 18363 on x64 ((also tried Windows 2019, 1909, x64),
- gopass Version: gopass 1.9.0 (fd53119c353b4cee01b582bb40d7ba3f9a7a8ade) go1.14.2 windows amd64
- Installation method: binary release `gopass.exe-1.9.0-windows-amd64.zip`

**Comment by kurrata** [comment]
I can confirm. I have the same issue when trying to insert password thought powershell and cmd on windows
```
PS C:\Users\martins.briedis> gopass.exe insert tmp

Error: failed to ask for password: not a terminal

PS C:\Users\martins.briedis> gopass.exe version
gopass 1.9.2+e2d1549f452a0df1fc52e42e7d0f654334d7144e (e2d1549f452a0df1fc52e42e7d0f654334d7144e) go1.14.2 windows amd64
<root>     - gpg 2.2.19 -  git 0.0.0 -   fs 0.1.0
Available Crypto Backends: age, gpgcli, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
```

**Comment by nrr** [comment]
I can confirm that this is still a problem, but I have a workaround that I've gotten good mileage out until this can get fixed. First, just pipe something to stdin when you attempt to do a `gopass insert`.

```text
PS> echo "foo" | gopass insert your-name-here
Pushed changes to git remote
```

After that, you can invoke `gopass edit your-name-here` and make that particular secret reflect the reality you want using Notepad.

```text
PS> gopass edit your-name-here
gopass: Encrypting your-name-here for these recipients:
- DEADBEEFCAFEBABEABAD1DEAFACEB00CADEADCA7 - 0xFACEB00CADEADCA7 - Tom Bobsmith <tom@bobsmith.online>

Do you want to continue? [Y/n/q]: y
Pushed changes to git remote
```

It's clumsy compared to the experience on Unix-alikes like Linux and macOS, but I'll take this over not being able to insert new secrets at all.

**Comment by drwulsen** [comment]
Same here, on binary release _gopass 1.10.1+377d2ab8507ed6d0025a1d18acf390d38680d0aa (377d2ab8507ed6d0025a1d18acf390d38680d0aa) go1.14.2 windows amd64_
Windows 10, 2004 / 19041.329

Running gopass.exe within:
- cmd / 
- powershell / 5.1.19041.1
- git bash / GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
- Linux on Windows Subsystem / Ubuntu / GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)

returns **not a terminal**

Is there a chance for this to get fixed?
I've set up gopass and github synchronization between my phone and PC via a git repository on a local server,
now I got it running and syncing in Windows 10 with the Windows-built-in OpenSSH binary,
PGP4Win and all is well; only adding secrets does not work.

I'd love to set this up for my girlfriend as well, I think I can get her to use the command line or wait for the browser add-on to allow adding secrets; but sure I can't get here to use the "echo-pipe" approach....

**Comment by AnomalRoil** [comment]
I'll try to take a look.

It seems it's just the password prompt which is causing the issue.

**Comment by drwulsen** [comment]
Yes, it is - I've commented out everything but 
```
func promptPass(ctx context.Context, prompt string) (string, error) {
		return AskForString(ctx, prompt, "")
	}
```
from gopass/internal/termio/promptpass_windows.go

And the input is working. However, I can see the password I insert (twice) whilst typing.
I'm unfamiliar with go; just learned how to generate a binary for windows from go code;
but it was sufficient for testing purposes :)

Looking forward to see what caused the issue.

**Comment by drwulsen** [comment]
Thank you for quickly fixing this issue, I've built and tested it on windows - just works (TM)
Could you please provide a binary release for windows including this fix, as it was a real showstopper?

Thanks again!

**Comment by AnomalRoil** [comment]
Yes, we'll include it in 1.10.2, it should be released in the upcoming
weeks.
