### ISSUE TITLE
`gopass recipients` doesn't display recipients in stores

### ISSUE THREAD

**Issue by hankem** [gopasspw/gopass#1334]
First of all, thanks for `gopass` and the recent updates in version 1.9.0! 😃

Unless I'm using it in the wrong way, I might have found a regression:

### Summary
`gopass help recipients` claims _"This command displays all existing recipients for all mounted stores."_, but gopass 1.9.0 doesn't actually display them to me anymore.

### Steps To Reproduce
Preparation:
```sh
mkdir priv; gopass init --store priv --path `pwd`/priv
mkdir team; gopass init --store team --path `pwd`/team
gopass recipients add --store team dominik.schulz
```
Using `gopass 1.9.0 (fd53119c353b4cee01b582bb40d7ba3f9a7a8ade) go1.14.2 linux amd64`,
```
gopass recipients
```
only gives me:
```
gopass
├── priv (…/priv)
└── team (…/team)
```

### Expected behavior
Using `gopass 1.8.6 (2020-02-29 13:42:01) go1.14 linux amd64`,
```
gopass recipients
```
gives me:
```
gopass
├── priv (…/priv)
│   └── 0xAC641D56A2A0F2CA - Manfred Hanke <Manfred.Hanke@tngtech.com>
└── team (…/team)
    ├── 0xAC641D56A2A0F2CA - Manfred Hanke <Manfred.Hanke@tngtech.com>
    └── 0xD31FA054C85AEFAC - Dominik Schulz <dominik.schulz@gmail.com>
```

### Environment
- OS: Manjaro Linux
- OS version: 
    ```
    Linux 5.6.8-1-MANJARO #1 SMP PREEMPT Wed Apr 29 19:05:17 UTC 2020 x86_64 GNU/Linux`
    ```
- gopass Version:
  * previous:
    ```
    gopass 1.8.6 (2020-02-29 13:42:01) go1.14 linux amd64
    <root>     - gpg 2.2.20 - git 2.26.2 -   fs 0.1.0
    Available Crypto Backends: gpgcli, openpgp, plain, xc
    Available RCS Backends: gitcli, noop
    Available Storage Backends: fs, inmem
    ```
  * new:
    ```
    gopass 1.9.0 (fd53119c353b4cee01b582bb40d7ba3f9a7a8ade) go1.14.2 linux amd64
    <root>     - gpg 2.2.20 - git 2.26.2 -   fs 0.1.0
    Available Crypto Backends: gpgcli, plain, xc
    Available RCS Backends: gitcli, noop
    Available Storage Backends: fs, inmem
    ```

- Installation method:
  * 1.8.6: `pacman -S gopass`
  * 1.9.0: https://github.com/gopasspw/gopass/releases/download/v1.9.0/gopass-1.9.0-linux-amd64.tar.gz

**Comment by dominikschulz** [comment]
Thank you for reporting this issue.
Indeed, displaying recipients for sub-stores seems to be broken in the current master.
Recipients for the root store are still shown for me.
