### ISSUE TITLE
gopass show doesn't display password, even with -C

### ISSUE THREAD

**Issue by muesli** [gopasspw/gopass#1353]
### Summary
Latest release doesn't `show` the password anymore, even when called with `-C`.

- OS: Arch
- OS version: Latest
- gopass 1.9.1

**Comment by dominikschulz** [comment]
Sorry, I can't reproduce this.
For me it's working with either autoclip true or false.

Do you have more information to reproduce?

**Comment by metalmatze** [comment]
I can reproduce it and actually came here because of the same problem.
```
$ pass twitter.com/MetalMatze 
✔ Copied twitter.com/MetalMatze to clipboard. Will clear in 10 seconds.
$ pass show twitter.com/MetalMatze
✔ Copied twitter.com/MetalMatze to clipboard. Will clear in 10 seconds.
$ pass show -o twitter.com/MetalMatze                                                                                                                                                
✔ Copied twitter.com/MetalMatze to clipboard. Will clear in 10 seconds.
XXX
```
As you can see only `show -o` actually outputs the contents of the password.
This is also a breaking change in the API, which I noticed because I started piping `Copied twitter.com/MetalMatze to clipboard. Will clear in 10 seconds.` into my password fields:
```
gopass ls --flat | dmenu | xargs --no-run-if-empty gopass show | head -n 1 | xdotool type --clearmodifiers --file -
```

**Comment by skaldesh** [comment]
After updating on Arch to  
`gopass 1.9.1 (2020-05-10 11:42:40) go1.14.2 linux amd64`  
My `autoclip` settings was suddenly set to `true`. After changing it, it works as expected and does not print the password when issuing `gopass my/secret`

**Comment by chama-chomo** [comment]
Same here, -c stopped working with latest update I got 
 1.9.0-2

**Comment by skaldesh** [comment]
@chama-chomo you do not have the latest version. The latest is 1.9.1, where the issues you are describing have been solved

**Comment by snuffop** [comment]
> After updating on Arch to
> `gopass 1.9.1 (2020-05-10 11:42:40) go1.14.2 linux amd64`
> My `autoclip` settings was suddenly set to `true`. After changing it, it works as expected and does print the password when issuing `gopass my/secret`
This was My case as well the autoclip was set true in *$XDG_CONFIG"  config.yml

**Comment by mapperr** [comment]
Had exactly the same problem, flipped autoclip to false and passwords showed up again.
In the meantime it broke my scripts too, not a big deal, but I was quite perplexed at first xD

**Comment by dominikschulz** [comment]
Thank you all for reporting on this issue.

In https://github.com/gopasspw/gopass/issues/1323#issuecomment-623656339 I have listed the intended behaviour and verified that HEAD still works that way. So the current implementation is working as intended.

However there seem to be two issues here:

* the default for `autoclip` used to be `true` and was only recently changed to `false`. Whoever started using between 1.4 and 1.8 likely has `autoclip` set to `true`. In #1327 the previously inconsistent behaviour of autoclip was fixed leading to surprising behaviour for some users. This was definitely not intended, I'm afraid. However now I don't see any clean way to go back.
* `autoclip` interacts poorly with non-interactive usage. This can probably be improved. This should be tracked in #1352.

For now please make sure to use `gopass show -f` in your scripts.
