### ISSUE TITLE
gopass show clips when not asked to, doesn't show passwords

### ISSUE THREAD

**Issue by brennane** [gopasspw/gopass#1356]
### Summary

Latest changes to "gopass show" now make the command behave strangely.

### Steps To Reproduce

~~~
% gopass show -h
NAME:
   gopass show - Display a secret

USAGE:
   gopass show [command options] [arguments...]

DESCRIPTION:
   Show an existing secret and optionally put its first line on the clipboard. If put on the clipboard, it will be cleared after 45 seconds.

OPTIONS:
   --clip, -c        Copy the first line of the secret into the clipboard (default: false)
   --alsoclip, -C    Copy the first line of the secret and show everything (default: false)
   --qr              Print the first line of the secret as QR Code (default: false)
   --force, -f       Display the password even if safecontent is enabled (default: false)
   --password, -o    Display only the password (default: false)
   --sync, -s        Sync before attempting to display the secret (default: false)
   --revision value  Show a past revision
   --help, -h        show help (default: false)
   
% gopass show misc/misc_test
✔ Copied misc/misc_test to clipboard. Will clear in 45 seconds.

% gopass config
root store config:
  askformore: false
  autoclip: true
  autoimport: true
  autoprint: false
  autosync: true
  check_recipient_hash: false
  cliptimeout: 45
  concurrency: 1
  editrecipients: false
  exportkeys: false
  nocolor: false
  noconfirm: false
  nopager: false
  notifications: true
  path: gpgcli-gitcli-fs+file:///******/.password-store
  safecontent: false
  usesymbols: false
~~~

### Expected behavior

1.  default behavior is "false"  but data is clipped (how do I not clip now?).

see: `Copy the first line of the secret into the clipboard (default: false)`

2. data is not shown unless forced

see: `gopass show`  implied by command name.

### Environment

- OS: macOS
- OS version: 10.15.5
- gopass Version: 1.9.1
- Installation method: brew

**Comment by uberjay** [comment]
Yeah, I'm seeing the same here. It appears as though the `show` command isn't respecting the `safecontent` config value. (Also, this seems a bit confusing, as the behavior of `show` is supposed to change based on a global configuration parameter, and the only mention of this is in the help for a `force` flag.)

This unfortunately broke a bunch of shell automation I've got in place. (ahh, the excitement of upgrading packages with `brew`... 😂)

**Comment by dominikschulz** [comment]
This is likely a duplicated of #1353 and should be fixed by now.
