### ISSUE TITLE
Password clearing restores old clipboard contents

### ISSUE THREAD

**Issue by wxcafe** [gopasspw/gopass#1361]
### Summary

When I copy a password to the clipboard, once the set `cliptimeout` has passed, instead of restoring what was in my clipboard before, gopass restores some old clipboard contents (always the same, in my case it's a 1200-lines-long puppet agent run log. It's probably what was in the clipboard the first time I ran `gopass -c` since last reboot or something). This is a pain because not only do I lose my clipboard contents, sometimes I'll just paste this in the console of a machine instead of what was in my clipboard that I actually wanted to paste there...

### Steps To Reproduce

Try to copy something into the clipboard (Ctrl-C), check that you can paste it out again (Ctrl-V), run `gopass -c`, wait 45 seconds until you get a notification the clipboard has been cleared, try to paste. You should not get the same thing that you copied before. 

### Expected behavior

You should get back what was in the clipboard

### Environment

- OS: Debian testing
- OS version: Linux cwh 5.3.0-3-amd64 #1 SMP Debian 5.3.15-1 (2019-12-07) x86_64 GNU/Linux
- gopass Version: gopass 1.9.1-git+HEAD go1.14.2 linux amd64
- Installation method: `go get -u` on  05-13-2020

**Comment by dominikschulz** [comment]
Gopass does not restore any clipboard content. It just clears it.

Possibly this is the effect of some clipboard manager?

**Comment by wxcafe** [comment]
Hey! Thanks for taking the time to answer. I don't have any clipboard manager installed, so it must be something else, but I guess it clearly isn't gopass's fault then :) thanks and sorry for the mistake

**Comment by dominikschulz** [comment]
Please be sure to reopen in case you manage to trace it back to gopass.
But looking at our clipboard implementation I really don't see how this could be happening.
We [don't retain](https://github.com/gopasspw/gopass/blob/master/pkg/clipboard/clipboard.go#L24) any old clipboard content and we just overwrite it with an [empty string](https://github.com/gopasspw/gopass/blob/master/pkg/clipboard/unclip.go#L30) later.

On some platforms we [try to interact](https://github.com/gopasspw/gopass/blob/master/pkg/clipboard/unclip_linux.go#L12) with a possibly running clipboard manager. This could lead to all kind of weird behaviour, depending on their implementation. But that's almost impossible for me to test.
