### ISSUE TITLE
Cannot set alternative database path in Windows

### ISSUE THREAD

**Issue by fgarcia** [gopasspw/gopass#1367]
### Summary

Cannot configure gopass to use an alternative store location

### Expected behavior

```
gopass config path D:\tmp\x
Error: Error setting config value
```

### Environment

- OS: Windows 10
- OS version: 1909
- gopass Version: 1.9.2
- Installation method: direct download from releases page

**Comment by dominikschulz** [comment]
Changing the path is currently not supported.
We should probably support that, too.
However this might be trickier than it looks.
We'll need to think about this.

**Comment by fgarcia** [comment]
I could solve this temporally with a Windows symbolic link from the default location (mklink). That only works for one repository, but it is almost enough for my needs
