### ISSUE TITLE
Gopass wizard aborts with an Error message

### ISSUE THREAD

**Issue by Nuc1eoN** [gopasspw/gopass#1370]
I just stumbled upon gopass and wanted to try it out (archlinux).
I run `gopass` and select to run the onboarding wizard. Then I select "Local store".

The wizard aborts with an error message and no information on how to proceed:
```
Error: failed to run onboarding wizard: failed to init local store: failed to read user input: no useable private keys found
```

EDIT: Btw I have also looked through the documentation and found no info on this.

**Comment by dominikschulz** [comment]
Are you asked to create a new private key?
Do you have a valid GnuPG keypair?

If the answer to both is no, could you please run gopass as "GOPASS_DEBUG=true gopass" and provide the output here?

**Comment by Nuc1eoN** [comment]
> Are you asked to create a new private key?

The answer is no.

> Do you have a valid GnuPG keypair?

The answer is yes, I have two valid GnuPG keypairs under `~.gnupg/`

**Comment by dominikschulz** [comment]
Thanks for providing more information.

Unfortunately I can't neither see the issue in the debug output nor reproduce the issue.

I need to think about this some more.

**Comment by Nuc1eoN** [comment]
Upon trying out various stuff it appears to be an issue with the "Trust" value of my key.
After setting it to 5 I can proceed the wizard.

So while my initial problem is solved, I still think the general user experience needs to be improved here.
In my opinion there are several options:
1. Give the user a better, more explanatory error message
2. Improve the documentation
3. Give the user an option to make a new key
4. Let the user modify the trust level

In any case just aborting the "wizard" is the worst user experience.

And the trust level thing is something most users have probably not been aware of, nor that it is required by gopass, while the key totally works for other use cases like github etc.

**Comment by dominikschulz** [comment]
1 and 2 sound good.
4 is already implemented but it doesn't seem to properly take the trust level into account.

I think I'll take option 5: Kill GPG. Eventually.

For now we should do 1, 2 and maybe 4. I won't even try 3.

**Comment by Nuc1eoN** [comment]
> 1 and 2 sound good.

Fixing that would definitely help stranded users

> 4 is already implemented but it doesn't seem to properly take the trust level into account.

If it's already there, the wizard should definitely not abort there :smile: 
If no suitable keys have been found the user should be given the option to create a new one.
Optionally, list the keys that have been found but are not "suitable" (users will probably wonder why their current ones don't work).

> I won't even try 3.

Wait wouldn't it be like one command line argument? Of course while warning the user that he should *actually* trust the key when he does this.

> I think I'll take option 5: Kill GPG. Eventually.

Wait what? :rofl: Isn't like the whole concept of the project to use gpg? Are there even any alternatives??

Tbh since I didn't want to waste my time and GPG confuses me anyways I just dowloaded a gpg GUI and changed it there.
