### ISSUE TITLE
New feature: Usage of variables

### ISSUE THREAD

**Issue by waldauf** [gopasspw/gopass#1393]
Hello,

I would like to ask you if there is a possibility to use variables for the user or password? One/two examples are better than thousands of words:

In the company are tens/hundreds of services that use LDAP for authentication/authorization. That means I use many different services with the same user (almost) and password. In password-storage in Accounts dir, I have different GPG files with the same user/password (because of browser extension). If I change the password in LDAP (expiration) I have to change it in all files. 

Another example - for some unimportant web services I'm using the same user. It will be great to have this user like variable and reuse it. 

Thanks for your answer. 

I would like to say many thanks for your tool. I'm using it every day. :]

**Comment by dominikschulz** [comment]
I'm not sure I understand exactly what you're asking for, but this mostly sounds like a duplicate of #682.

This would make it easier to work with multiple different URLs for the same credentials.
However either of these is difficult to implement with the current implementation.

**Comment by waldauf** [comment]
Yep, there is better description and they asked for the same feature as me. In fact, I thought that the implementation will not be easy. But I wanted to ask. :] 

Thx the quick response.
