### ISSUE TITLE
Command jsonapi configure not working

### ISSUE THREAD

**Issue by Chrisx0385** [gopasspw/gopass#1394]
### Summary

I tried to run the command 'gopass jsonapi configure' on my fresh installed gopass version 1.9.2 but it seems that the command isn't present anymore. Instead of creating native messaging scripts it tries to find a password entry. So I've installed gopass 1.8.6 where that command works as expected.

### Steps To Reproduce
- Install newest gopass version 1.9.2 with `go get github.com/gopasspw/gopass`
- run wizard, mount store
- run `gopass jsonapi configure`

gopass now tries to find a password entry 

### Expected behavior
gopass should run the Native Messaging Setup Wizard

### Environment

- OS: Ubuntu 20.04 LTS
- gopass Version: 1.9.2
- Installation method: go get github.com/gopasspw/gopass

**Comment by dominikschulz** [comment]
This command has been removed from the main gopass binary.

Workaround: Use `cmd/gopass-jsonapi`.

**Comment by ferdizmn** [comment]
This is how I tried to run the gopass jsonapi. Unfortunatelly, I also ran into this bug. I solved it by editing the `gopass_wrapper.sh`.

**Steps to reproduce** 

The new version (1.9.2-git+HEAD go1.14.3 linux amd64) comes without the `jsonapi` command. It is now provided by `gopass-jsonapi` which has to be created first
```
$ cd ~/gopasspw/gopass/cmd/gopass-jsonapi/
$ make
```
Now, configure the gopass-jsonapi in that folder:
```
$ ./gopass-jsonapi configure
```
 which will also display the gopass_wrapper.sh:
 ```
 Wrapper Script (/home/user/.config/gopass/gopass_wrapper.sh):
#!/bin/sh

if [ -f ~/.gpg-agent-info ] && [ -n "$(pgrep gpg-agent)" ]; then
	source ~/.gpg-agent-info
	export GPG_AGENT_INFO
else
	eval $(gpg-agent --daemon)
fi

export PATH="$PATH:/usr/local/bin" # required on MacOS/brew
export GPG_TTY="$(tty)"

/home/user/go/src/github.com/gopasspw/gopass/cmd/gopass-jsonapi/gopass-jsonapi jsonapi listen

exit $?


Manifest File (/home/user/.mozilla/native-messaging-hosts/com.justwatch.gopass.json):
{
    "name": "com.justwatch.gopass",
    "description": "Gopass wrapper to search and return passwords",
    "path": "/home/user/.config/gopass/gopass_wrapper.sh",
    "type": "stdio",
    "allowed_extensions": [
        "{0815-0815-0815-0815}"
    ]
}

 ```
 The line ending with `gopass-jsonapi jsonapi listen` contains a bug, as the `jsonapi` is redundant. Removing it solved the problem (resulting in: `... gopass-jsonapi listen`)

**Comment by dominikschulz** [comment]
Thank you for pointing out this issue.
The wrapper output will be fixed soon.

**Comment by teezett** [comment]
> This command has been removed from the main gopass binary.
> 
> Workaround: Use `cmd/gopass-jsonapi`.

how can this be used?

**Comment by teezett** [comment]
> This command has been removed from the main gopass binary.
> 
> Workaround: Use `cmd/gopass-jsonapi`.

I wondered how i can use this.
Then I realized that you mean this directory in the sources you get from https://github.com/gopasspw/gopass.
There going to `cmd/gopass-jsonapi`
But a normal make does not work there; it need root privileges

**Comment by dominikschulz** [comment]
You don't need root privileges for any part of gopass.
And you shouldn't use it as root - at least not build it as root.

**Comment by teezett** [comment]
of course build as root is not good, but it does not work else:
`$ make`
`go: finding github.com/urfave/cli v1.22.4`
`go: finding golang.org/x/net latest`
`go: finding github.com/blang/semver v3.5.1+incompatible`
`go: writing stat cache: mkdir /usr/go/pkg/mod/cache/download/github.com/urfave/cli/@v: permission denied`
`...`

**Comment by dominikschulz** [comment]
That seems like an issue with your Go installation.

Running as root is not the proper solution.
Of course you can do what you like, but I discourage building as root.

**Comment by teezett** [comment]
I dont know, I am not a go developer. I just installed go to install gopass and just used the normal apt package of golang on my ubuntu.
it seems like solving dependencies, but the installer tries to install it globally, not for the actual user.

**Comment by dominikschulz** [comment]
I'm afraid I can't help you debug this, but I strongly suggest getting some advice to fix your go installation.
Or you could just use our binary packages.

**Comment by teezett** [comment]
It is hard to get an advice, if I don't know enough about go language to describe the problem. I do not even know, what i can google for.
I already tried the binary packages, but they don't contain the jsonapi command.

**Comment by varac** [comment]
> This command has been removed from the main gopass binary.
> 
> Workaround: Use `cmd/gopass-jsonapi`.

Can you please document this in the release notes, because I can't find any mentioning of the api deprecation for 1.9.2 (https://github.com/gopasspw/gopass/releases). Thanks !
