### ISSUE TITLE
Panic when cloning pwstore

### ISSUE THREAD

**Issue by gnosthi** [gopasspw/gopass#1407]
### Summary
When cloning a password store on a fresh install using `gopass clone` with gopass v1.9.2 on Ubuntu 18.04 gopass throws a segfault.
```
➜  ~ gopass clone git@github.com:<repo>
Configuring git repository ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x838bd7]

goroutine 1 [running]:
github.com/gopasspw/gopass/internal/cui.AskForGitConfigUser(0xd5b200, 0xc0002122d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x28, 0x0)
	/home/gnosthi/go/src/github.com/gopasspw/gopass/internal/cui/recipients.go:243 +0x37
github.com/gopasspw/gopass/internal/action.(*Action).cloneGetGitConfig(0xc000218000, 0xd5b200, 0xc0002122d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/redacted/go/src/github.com/gopasspw/gopass/internal/action/clone.go:134 +0xaa
github.com/gopasspw/gopass/internal/action.(*Action).clone(0xc000218000, 0xd5b200, 0xc0002122d0, 0x7fffc693c429, 0x26, 0x0, 0x0, 0xc00020e1e0, 0x2d, 0xc000210601, ...)
	/home/redacted/go/src/github.com/gopasspw/gopass/internal/action/clone.go:93 +0x605
github.com/gopasspw/gopass/internal/action.(*Action).Clone(0xc000218000, 0xc000082580, 0x0, 0xc00020a1b0)
	/home/redacted/go/src/github.com/gopasspw/gopass/internal/action/clone.go:43 +0x2bf
github.com/urfave/cli.(*Command).Run(0xc00021e6c0, 0xc000082400, 0x0, 0x0)
	/home/redacted/go/src/github.com/urfave/cli/command.go:163 +0x4b9
github.com/urfave/cli.(*App).RunContext(0xc0001f0480, 0xd5b200, 0xc0002122d0, 0xc000098150, 0x3, 0x3, 0x0, 0x0)
	/home/redacted/go/src/github.com/urfave/cli/app.go:306 +0x790
main.main()
	/home/redacted/go/src/github.com/gopasspw/gopass/main.go:81 +0x3ae
```

### Steps To Reproduce
Starting from fresh install from src, setup git, (with commit signing), and clone a remote password store.

### Expected behavior
Password store should be cloned and setup

### Environment

- OS: Ubuntu 18.04
- OS version:  5.3.0-53-generic #47~18.04.1-Ubuntu SMP
- gopass Version: 1.9.2-git+HEAD
- Installation method: gopass repo (from source)

**Comment by TM2500** [comment]
Your `gopass version` and stacktrace indicates, that you are running from `master` which is currently unreleased and not in any state for use in production.
Personally I can't reproduce this with v1.9.2.

But thank you for submitting this issue.

If you have to use gopass in production and want to build it from the github-sources, then please use the commit tagged with "v1.9.2" ( `git checkout v1.9.2`)

**Comment by dominikschulz** [comment]
Indeed, thanks for reporting this issue.
Actually I just hit a similar issue when writing new tests.
I'll try to dig into this soon.
