### ISSUE TITLE
segfault on setup

### ISSUE THREAD

**Issue by termnews** [gopasspw/gopass#1409]
### Summary

after following gopass/docs/setup.md I run gopass and choose "Y":

```
It seems you are new to gopass. Do you want to run the onboarding wizard? [Y/n/q]: Y
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x43110c]

goroutine 1 [running]:
github.com/gopasspw/gopass/internal/action.(*Action).InitOnboarding(0x40001e7420, 0x400008f000, 0x7b2fd4, 0x49)
        /home/stefan/go/src/github.com/gopasspw/gopass/internal/action/init.go:209 +0x3e4
github.com/gopasspw/gopass/internal/action.(*Action).Initialized(0x40001e7420, 0x400008f000, 0x20, 0x643a00)
        /home/stefan/go/src/github.com/gopasspw/gopass/internal/action/init.go:42 +0x1d4
main.setupApp.func2(0x400008f000, 0x40000afa00, 0x6)
        /home/stefan/go/src/github.com/gopasspw/gopass/main.go:121 +0x34
github.com/urfave/cli.(*App).RunContext(0x4000081200, 0x89ff00, 0x4000146fc0, 0x400009c1c0, 0x1, 0x1, 0x0, 0x0)
        /home/stefan/go/src/github.com/urfave/cli/app.go:315 +0x514
main.main()
        /home/stefan/go/src/github.com/gopasspw/gopass/main.go:81 +0x310
```

### Steps To Reproduce

Do the same, but perhaps it's architecture-dependend, since this is ubuntu 20.4 in WSL version 1 on Windows 10, arm64. Here the output of `uname -a`:

```
Linux glarm64dos 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 aarch64 aarch64 aarch64 GNU/Linux
```

### Expected behavior
 
normal initialisation-process

### Environment

- OS: Ubuntu 20.04
- OS version: Linux glarm64dos 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 aarch64 aarch64 aarch64 GNU/Linux
- gopass Version: no output, since it tries to initialise instead of outputting the version.
- Installation method: from source: `go get -u github.com/gopasspw/gopass`

### Additional context

It worked in WSL 2, but Microsoft downgraded me, since there seems to be a bug in the Hyper-V code on arm64.

**Comment by dominikschulz** [comment]
Thanks for reporting this.
It seems like this was caused by a recent refactoring.
master isn't really stable at the moment. In doubt use the latest release.

I'll try to dig into this and get it fixed soon.

**Comment by tskinn** [comment]
Seeing this as well. Seems like we need to check for nil return value at https://github.com/gopasspw/gopass/blob/422e032632b6e1d45504836e8ffcfdaeb507f490/internal/action/init.go#L207 because it is referenced in debug message https://github.com/gopasspw/gopass/blob/422e032632b6e1d45504836e8ffcfdaeb507f490/internal/action/init.go#L209
