### ISSUE TITLE
Wrong characters displayed

### ISSUE THREAD

**Issue by kmmndr** [gopasspw/gopass#1414]
### Summary

I've freshly installed gopass on another device. On this device, wrong characters are displayed when listing entries.

```
$ gopass list
gopass
<E2><94><9C><E2><94><80><E2><94><80> store1 (/home/user/.local/share/gopass/stores/store1)
<E2><94><82>   <E2><94><9C><E2><94><80><E2><94><80> foo
<E2><94><82>   <E2><94><82>   <E2><94><9C><E2><94><80><E2><94><80> bar
...
```

### Steps To Reproduce

Simply run `gopass list` and see `<E2><94><9C><E2><94><80><E2><94><80>` characters.

### Expected behavior

No `<E2><94><9C><E2><94><80><E2><94><80>` characters, beautiful ascii tree.

```
gopass
├── bar
│   └── baz
...
```

### Environment

- OS: archilinux
- OS version: Linux foo 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux
- gopass Version: gopass 1.9.2 (2020-05-13 21:14:02) go1.14.2 linux amd64
- Installation method: from archlinux package `gopass`

### Additional context

The only difference here between my other computers (all running archlinux) is that I'm running kde and konsole. I've tried kitty and rxvt-unicode, but it is the same behavior.

**Comment by kmmndr** [comment]
I've found ! The bug was due to a bad kde configuration. In the settings menu, it is possible to override system language. And in my case, it was set to a default ansi value, resulting all applications to have LANG environment variable set to "C".

**Comment by dominikschulz** [comment]
Thanks for reporting back! Good to know.
