### ISSUE TITLE
gopass git push should use Git's default behavior

### ISSUE THREAD

**Issue by d4mation** [gopasspw/gopass#1431]
### Summary

When running `gopass git push`, if you do not explicitly define a Remote and Branch it returns an error instead of falling back to Git's `push.default` behavior. 

By default, Git is configured to use `simple` for its default push behavior in Git v2.x+ and before that it was `matching`. Both are likely what people intend if they are only typing `gopass git push`.

https://git-scm.com/docs/git-config#Documentation/git-config.txt-pushdefault

https://github.com/gopasspw/gopass/blob/b2ac17677d18cb87f3a4fb47df5158c12721ea8d/internal/action/git.go#L132-L143

### Steps To Reproduce

1. Run `gopass git push`
2. Hits the error

### Expected behavior

1. Run `gopass git push`
2. Pushes the current Branch to the appropriate Upstream.

### Environment

- OS: Windows 10
- OS version: 1909
- gopass Version: 1.9.1 (which is apparently outdated, but it is what showed for me in `choco`)
- Installation method: `choco`

### Additional context

Apparently Git support is getting dropped? https://github.com/gopasspw/gopass/issues/1365

That's a huge letdown. I really liked how this was mostly a drop-in replacement for `pass`. I even aliased `gopass` via `doskey` to `pass` so I could use the same command across machines.

**Comment by dominikschulz** [comment]
Could you clarify your preference, please?
Do you suggest to just drop lines 139-141 from the snippet above? (+ possibly adjust RCSPush)

Please note that I don't want to encourage using `gopass git ...`. They (still) exist mostly for compatibility reasons.
I'm more inclined to remove the subcommand than for change it's behaviour. Users should mostly use `gopass sync`.

As for the discussions in #1365: Nothing has been decided, yet. Right now I'd say it's more likely that GPG might get dropped than git. It really depends on a number of factors, e.g. user feedback, code contributions, us finding proper alternatives to both of GPG and git and the question if we need to support mobile apps.

**Comment by d4mation** [comment]
> Could you clarify your preference, please?

I think that the checks for Remote and Branch in the arguments are fine (In case someone does want to define them) but if they are not set it should work as `git push` normally does based on the Git Config for `push.default`. 

Perhaps `gopass git <command>` should just run `git` directly with `--git-dir` set to define the location of the Store's Repo? That may make supporting Git simpler in the future. (`--work-tree` may also be required. I have not tested these options myself)

https://git-scm.com/docs/git#Documentation/git.txt-codeGITDIRcode

> Users should mostly use `gopass sync`

Is this out of Beta? The Readme indicates that it is Beta functionality. I wouldn't mind using it as that would mean I wouldn't need to manually run `gopass git pull` or `gopass git push`.
