### ISSUE TITLE
Please consider re-adding support for docker

### ISSUE THREAD

**Issue by gkotian** [gopasspw/gopass#1432]
### Summary
It is no longer possible to build a docker image to run gopass within an isolated container.

### Steps To Reproduce
Run `docker build -t gopass github.com/gopasspw/gopass#master`

### Expected behavior
A new docker image containing the gopass binary should be built.

### Environment
ArchLinux (but any machine with docker installed would do).

- OS: [ArchLinux]
- OS version: [Linux medusa 5.7.4-arch1-1 #<dummy-text>1 SMP PREEMPT Thu, 18 Jun 2020 16:01:07 +0000 x86_64 GNU/Linux]
- gopass Version: [1.9.2]
- Installation method: [docker]

### Additional context
The Dockerfile was removed in https://github.com/gopasspw/gopass/pull/1309. Please consider adding it back.

**Comment by dominikschulz** [comment]
We've never actively used Docker nor do we have the time to support it.
Feel free use the removed Dockerfile to build your containers.

**Comment by gkotian** [comment]
That's a shame, but fair enough. Here's some cleanup: https://github.com/gopasspw/gopass/pull/1433.
