### ISSUE TITLE
gopass defaults to copy rather than show even if --clip, -c is NOT specified

### ISSUE THREAD

**Issue by glowinthedark** [gopasspw/gopass#1441]
### Summary 
`gopass somesite` copies the password rather than `show`-ing the entry which should be the default EVEN if `show` is specified explicitly.

### Steps To Reproduce
Execute:
`gopass somesite`

OR

`gopass show somesite`

### Expected behavior
The entry contents are displayed, ie:
```
secure-password
username: some-user
notes .etc
...
```

### Actual behavior
The password is copied to the clipboard and the contents are not shown EVEN IF `gopass show xxxx` is used.
```
somesite
✔ Copied sitesite to clipboard. Will clear in 45 seconds.
```

### Environment

> OS version:
```
❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G13033

❯ uname -a
Darwin mb2016.local 17.7.0 Darwin Kernel Version 17.7.0: Mon Apr 27 20:25:53 PDT 2020; root:xnu-4570.71.80~1/RELEASE_X86_64 x86_64
```
> - gopass Version:
```bash
gopass 1.9.2 (2020-06-04 20:35:38) go1.14.3 darwin amd64
<root>     - gpg 2.2.20 - git 2.25.0 -   fs 0.1.0
Available Crypto Backends: age, gpgcli, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
Version check timed out

### for the source version
 /Users/vio/projects/go/bin/gopass version
gopass 1.9.2-git+HEAD go1.14 darwin amd64
<root>     - gpg 2.2.20 - git 2.25.0 -   fs 0.1.0
Available Crypto Backends: age, gpgcli, plain
Available RCS Backends: gitcli, noop, ondisk
Available Storage Backends: fs, inmem, ondisk
```
- Installation method: `brew` (same behaviour with the version installed from source with `go get -u -v github.com/gopasspw/gopass`)

## Comments
This is extremely inconvenient because in order to see the full contents one needs to use `gopass edit somesite` which opens the contents in edit mode which is NOT the best user experience since it takes much longer than just printing the data to the terminal. If somebody needs to just copy the password they can either pass `-c` or create an alias. Please return the previous `show` behaviour!

**Comment by dominikschulz** [comment]
Can you please check the value of `gopass config autoclip`?
It's probably set to `true`. Setting it to `false` will restore your desired behaviour.

**Comment by rolfbachmann** [comment]
I had the same issue after update to 1.9.2. Set `autoclip` to `false` works for me. Same behavior as before.

But a combination of the two would be nice too, so I see the username (my second line) in the terminal and the password gets copied to the clipboard:
```
gopass show -c foo
```
Currently I always have to call gopass twice:
```
gopass show foo
gopass -c foo
```
But that's maybe an improvement/feature.

**Comment by dominikschulz** [comment]
Yes, that is rather a feature request. We had this discussion before and I'd also like this feature.
But so far I haven't come up with a good implementation.

**Comment by glowinthedark** [comment]
@dominikschulz: `autoclip` was indeed set to `true` although I don't remember having set that value. Running `gopass config autoclip false` restored the expected behaviour. Thanks!

**Comment by dominikschulz** [comment]
Yes, sorry. I think this a regression.
I'll try to fix that, but not sure if that's possible.

**Comment by AnomalRoil** [comment]
I can confirm that this is impacting some of my colleague as well.

I believe it happens to people who have a legacy config file without the `autoclip` option listed inside.

**Comment by AnomalRoil** [comment]
Actually this seems to have stem from a change in the code that changed the way the `autoclip` option behave: according to the doc it should only "Always copy the password created by `pass generate`" but now it also affects the way `gopass show` behaves.

I've opened a new issue to track how the different options and flags should influence the way Gopass behaves: https://github.com/gopasspw/gopass/issues/1488
