### ISSUE TITLE
Custom configuration not possible for non-remote substores

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1459]
It seems that #1391 introduces a "regression" in the sense that it is not possible any more to set different options than for our main store for sub-store that are mounted and are non-remote.

There was the introduction of the notion of "remote config", this seems to still support custom options for a remote store, but for local stores, it appears that now the `gopass config --store` flag is ineffective.

Is this a decision that was made to drop custom configuration per-mounted substores, or is this an unwanted side effect?

This allows to "refactor" a bit the code, I'll drop a PR about it soon.

**Comment by dominikschulz** [comment]
Yes, you are correct. This was a deliberate decission to reduce the complexity. I don't recall why we introduced these per-store options in the first place, but as from the users as from the developers perspective this only adds complexity for very little legitimate use cases. Thus the decission to drop this feature.

Thanks for cleaning up some of the missing parts.
