### ISSUE TITLE
The list cmd handles shadowing incorrectly

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1460]
### Summary
When mounting a substore on a path that already exists in the password store, the philosophy was to behave like unix's `mount`, which means all gopass commands should behave like if the previously existing path did not exist anymore until the mount is unmounted.

Currently the `edit`, `insert`, `generate`, `remove` and `show` command seem to work as they should.
But the `list` command is still displaying the initial entry instead of the mounts' content. 

### Steps To Reproduce
```
gopass init
gopass generate foo/bar 20
gopass generate foo/baz 20
gopass generate bar/baz 20
gopass mounts add foo
gopass generate foo/bar 20
gopass show foo/baz
gopass ls
```

And then see the problems:
 - `gopass ls` is not displaying the mount as it should (in blue with the path in parentheses)
 - `gopass show foo/baz` is triggering search and is _finding_ `foo/baz`, whereas it shouldn't since it should be shadowed by the mount. But then it is correctly failing to decrypt it, saying `Error: failed to retrieve secret 'foo/baz': Entry is not in the password store`
 - `gopass insert/edit/rm/generate` seem to work as they should on the mount only.  

### Expected behaviour
```
> gopass show foo/baz
Entry 'foo/baz' not found. Starting search...
Error: no results found
```
or maybe a message about having found it but it being shadowed by a mount, instead of the current :
```
> gopass show foo/baz
Entry 'foo/baz' not found. Starting search...
Found exact match in 'foo/baz'

Error: failed to retrieve secret 'foo/baz': Entry is not in the password store
```

And also having:
```
> gopass ls
gopass
├── bar
│   └── baz
└── foo (/path/to/the/mount)
    └── bar
``` 
instead of 
```
gopass
├── bar
│   └── baz
└── foo
    ├── bar
    └── baz
```

### Environment
- gopass Version: gopass 1.9.3-rc.0
- Installation method: from source

### Additional context
I am going to add a new test in a PR very soon. 
Notice that this test is currently failing and as such skipped in the integration test.
But it allows to detect this problem for `gopass ls`.

**Comment by AnomalRoil** [comment]
I used the new test to git bisect and find the commit that introduced the error:

```
668dd0a486bf2df92231b0e03734240b8d0d0e57 is the first bad commit
commit 668dd0a486bf2df92231b0e03734240b8d0d0e57
Author: Dominik Schulz
Date:   Fri May 29 21:59:35 2020 +0200

    Rewrite tree implementation (#1395)
    
    This commit slightly rewrites the tree implementation and removes
    another unnecessary indirection.
    
    RELEASE_NOTES=[ENHANCEMENT] Rewrite tree implementation.
```

**Comment by dominikschulz** [comment]
Amazing. Thank you. This helps a lot.
