### ISSUE TITLE
gopass installation fails via go get with golang 1.14.3 on POP OS 20.04 

### ISSUE THREAD

**Issue by wakatara** [gopasspw/gopass#1466]
### Summary

Fresh install on POPOS and go configured for environment with viable GOROOT and GOPATH. Install fails with missing src for MINIO package.

### Steps To Reproduce

Using 1.14.3 Go lang on POP OS 20.04 install, 

```
go get -u github.com/gopasspw/gopass
```

fails with:

```
package github.com/minio/minio-go/v6: cannot find package "github.com/minio/minio-go/v6" in any of:
	/usr/lib/go-1.14/src/github.com/minio/minio-go/v6 (from $GOROOT)
	/home/daryl/Code/go-nix/src/github.com/minio/minio-go/v6 (from $GOPATH)
```

I did try to install minio-go/V6 separately, but that also did not take. It appers that dependency has moved in the last month to a V7 so unsure if that's related. 

### Expected behavior

gopass should be installed.

### Environment

- OS: POP OS
- OS version: Linux elcano 5.4.0-7634-generic #38~1592497129~20.04~9a1ea2e-Ubuntu SMP Fri Jun 19 22:43:37 UTC  x86_64 x86_64 x86_64 GNU/Linux
- gopass Version: 1.9.3
- Installation method: go get
- Go version 1.14.3 installed via apt

### Additional context

``` bash
λ  ~ echo $GOROOT
/usr/lib/go-1.14
λ  ~ echo $GOPATH
/home/daryl/.go-nix
```

**Comment by dominikschulz** [comment]
Uhm, that's weird.

Can you please try with `GO111MODULE=on`?

**Comment by wakatara** [comment]
Worked like a charm. Thank you! (I am embarassed I did not think of it.).
