### ISSUE TITLE
Cannot update root RCS backend after store creation

### ISSUE THREAD

**Issue by antoyo** [gopasspw/gopass#1467]
### Summary

I have an existing store (coming from pass) that, I believe, does not have an associated git repository (is there a way to check that?).
I want to initialize one (i.e. switch it to the gitcli RCS backend) to do synchronization, but it doesn't work.

### Steps To Reproduce

1. Run `gopass git init`. (This gives `Initializing git repository (noop) ...` and `Git initialized`, but I can re-run the same command and get the same result, so I'm not sure it works.)
2. Run `gopass git remote add origin …` (This prints nothing.)
3. Run `gopass sync`. (This prints `WARNING: Mount uses RCS backend 'noop'. Not syncing!` even though my path contains `gpgcli-gitcli-fs+file://…`.

### Expected behavior

Git repository should be initialized and synced.

### Environment

- OS: ArchLinux
- OS version: Linux antoyo-laptop 5.7.8-arch1-1 #1 SMP PREEMPT Thu, 09 Jul 2020 16:34:01 +0000 x86_64 GNU/Linux
- gopass Version:
```
gopass 1.9.2 (2020-07-13 14:34:42) go1.14.4 linux amd64
<root>     - gpg 2.2.21 - noop 0.0.0 -   fs 0.1.0
Available Crypto Backends: age, gpgcli, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
```
- Installation method: ArchLinux repository

The line `<root>     - gpg 2.2.21 - noop 0.0.0 -   fs 0.1.0` seem to indicate that the root mount is using the `noop` backend, but I cannot figure out how to change it to `gitcli`.
### Additional context

If it's not possible to change the RCS backend of the root mount, how can I workaround this issue?

**Comment by dominikschulz** [comment]
Thanks for reporting this. That sounds like a bug (`gopass git init` doesn't seem to override the RCS noop backend and performs a no-op git init).

Will try to reproduce it.

As a workaround you can always initialize git yourself in the password store directory and gopass should detect that on the next run.

**Comment by dominikschulz** [comment]
So, I've tested this and it seems to work with the current master.

Roughly what I did:

```
$ mkdir testhome
$ export GOPASS_HOMEDIR=testhome
$ gopass setup
# not adding a git remote
$ mkdir testrepo
$ cd testrepo && git init --bare
$ gopass git init
$ gopass git remote add origin testrepo
$ gopass git push
```
