### ISSUE TITLE
gopass-jsonapi unclear on docs

### ISSUE THREAD

**Issue by icyd** [gopasspw/gopass#1471]
the binary gopass-jsonapi is not installed with the releases packages as far as I tried, and is unclear on the docs how to *use/generate* it.

**Comment by dominikschulz** [comment]
Which release? 1.9.3-rc.0?

**Comment by icyd** [comment]
Sure... maybe... Since jsonapi is a *additional* command, because it have to be build separately, and is not included with the release files as a binary. Documentation has reference to *gopass jsonapi* instead of *gopass-jsonapi*, both here and in the gopassbridge docs. Maybe I can give you a hand with that, but have to clearout how should that work as compilation and release of that command goes.

**Comment by dominikschulz** [comment]
I'm trying to clarify which release package you used.
Because with our latest stable release `gopass jsonapi` should still work.
For the upcoming 1.9.3 release we should indeed update the docs and possibly include the additional binaries in the release package.

**Comment by icyd** [comment]
Is the latest *stable* the 1.9.2? If that's the case, then the command `gopass jsonapi` is not available.

**Comment by dominikschulz** [comment]
1.9.2 still has `gopass jsonapi`. I just checked.

**Comment by icyd** [comment]
Yeah, you're right, I tested this morning and didn't work, for sure did something wrong!. Sorry about that. In that case, for the new release the docs need that clarification. Maybe you need help with that, just let me know.

**Comment by Pharb** [comment]
@dominikschulz I guess the biggest problem for the users here will be how to setup and install a separate `gopass-jsonapi` binary. It will probably take some time to get that into the popular package managers, which are not maintained by the team here AFAIK.

Would it be an option to at least maintain compatibility for the v1.9.x releases? We could already publish the new `gopass-jsonapi` binary in parallel and update official documentation, while keeping the `gopass jsonapi` command temporarily.
Would the be much effort?

If this is the direction we want to go, I could spent some time on it over the next weeks.
Any community help would be very much appreciated, e.g. to figure out who maintains the popular package repos, and if they would accept an additional `gopass-jsonapi` binary there.

**Comment by dominikschulz** [comment]
I was planning to include it in the regular gopass release tarball until this is resolved.

**Comment by dominikschulz** [comment]
@Pharb Could you please have a look at 1.9.3-rc.1: https://github.com/gopasspw/gopass/releases/tag/v1.9.3-rc.1

That should include the additional binaries. If these are included in downstream packages, then we should be good.

**Comment by Pharb** [comment]
Thanks @dominikschulz.

There is an error about the store initialization, we can track that here: https://github.com/gopasspw/gopass/issues/1480
