### ISSUE TITLE
gopass env crashes when missing command to execute

### ISSUE THREAD

**Issue by marco-m** [gopasspw/gopass#1474]
### Summary

The `env` subcommand (described in #1227, implemented in #1231) crashes when the command-line is missing the command to execute.

Assuming that:

* `foo` is an existing secret
* `packer` is an existing executable

This works:

    gopass env foo packer

This crashes (this is a mistake in the invocation, but it should not crash):

    gopass env foo

### Steps To Reproduce

See section above.

### Expected behavior

gopass should return an usage error, since this is a user mistake in composing the command-line.

### Environment

- OS: N/A
- OS version: N/A
- gopass Version: latest release (1.9.2) and build from today's master branch (commit 45a34f44d7).
- Installation method: N/A

### Additional context

PR #1475 adds tests and fixes the crash.

**Comment by dominikschulz** [comment]
Yes, indeed. This is a bug. Thanks for providing a fix!
