### ISSUE TITLE
Single match on inexact query does not generate OTP

### ISSUE THREAD

**Issue by Rubonnek** [gopasspw/gopass#1477]
### Summary
Using `gopass otp` with an inexact string that matches a single entry does not generate an OTP password on the terminal.

### Steps To Reproduce
1. `gopass edit --create PascalCase`
2. Append a dummy totp line (but one that works obviously), for example:
```
---
totp: AAAAAAAAAAAAAAAAA
```
3. Try the following:
```
gopass otp PascalCase # works as expected
gopass otp pascalCase # does not show OTP on the terminal
```

### Expected behavior
OTP shows on the terminal.

### Environment

- OS: Arch Linux
- OS version: Linux harmonia 5.4.55-1-lts #1 SMP Fri, 31 Jul 2020 17:38:35 +0000 x86_64 GNU/Linux
- gopass Version: 
```
gopass 1.9.2 (2020-07-13 14:34:42) go1.14.4 linux amd64
<root>     - gpg 2.2.21 - git 2.28.0 -   fs 0.1.0
Available Crypto Backends: age, gpgcli, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
```
- Installation method: Arch Linux community repository

**Comment by dominikschulz** [comment]
I tried to reproduce but couldn't.
If you want, you can run gopass with `GOPASS_DEBUG_LOG=/tmp/gopass.log` set.

There might be credentials being logged, so be sure to redact anything confidential before providing the output.

**Comment by Rubonnek** [comment]
Oh... what is happening here is related to #1473 -- the secret must also yield the error:
```
Error: No OTP entry found for Test: illegal base32 data at input byte 48
```
when the correct character casing is used (i.e. `PascalCase` as in the original example).

I just didn't that OTP error message, and using `GOPASS_DEBUG_LOG=/tmp/gopass.log` did not generate a log either.
