### ISSUE TITLE
panic: store not initialized [1.9.3-rc.1]

### ISSUE THREAD

**Issue by Pharb** [gopasspw/gopass#1480]
### Summary

`gopass-jsonapi` panics when being run with any parameter. Same happens `gopass-hibp`, maybe also the other binaries.

### Steps To Reproduce

```
gopass-1.9.3-rc.1-darwin-amd64 ./gopass-jsonapi
panic: store not initialized. run gopass init first

goroutine 1 [running]:
main.main()
	/home/tex/src/go/src/github.com/gopasspw/gopass/cmd/gopass-jsonapi/main.go:39 +0x9da
```

### Expected behavior

Command works as expected.

### Environment

- OS: macOS Catalina
- OS version: [uname -a]
- gopass Version: gopass 1.9.3-rc.1+a39aeeb9bdc304526dd9af477ffa0713a727d446 (a39aeeb9bdc304526dd9af477ffa0713a727d446) go1.14.2 darwin amd64
- Installation method: gopass repo binary and from source

**Comment by dominikschulz** [comment]
Interesting. Thanks for trying.

Does gopass itself work as expected?

Also I wonder why -trimpath doesn't seem to work.

**Comment by dominikschulz** [comment]
We will definitely need more graceful error handing for the next release. Right now we just panic. There should be at least a helpful error message.
