### ISSUE TITLE
The new secret format is not well integrated with `edit` 

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1484]
### Summary
The gopass `show` command will sometimes display "GOPASS-SECRET-1.0" instead of the password now.

### Steps To Reproduce
```
$ gopass generate bar
$ gopass show bar 
Password: ZREIx5ieOoyMioficPIbNcEb

$ gopass show -o bar
ZREIx5ieOoyMioficPIbNcEb

$ gopass edit bar 
[add some random text on the second line without any key-value formatting]

$ gopass show bar 
Password: ZREIx5ieOoyMioficPIbNcEb
some text on the second line

$ gopass show -o bar
GOPASS-SECRET-1.0
```

### Expected behavior
It should still display the password assuming the first entry is a value "password" if it has the header.

### Environment
Git master tip

**Comment by dominikschulz** [comment]
Yes, if it doesn't look like a MIME message it's not treated as such.
Separating "header" and body with an empty line would "fix" this.
Not sure how to improve the user experience.

**Comment by dominikschulz** [comment]
But it's actually something we should handle better. At least parsing a known secret (with the well-known header) should fail and not just fall back to another secrets parser.

**Comment by AnomalRoil** [comment]
And the gopass edit command should not let us save an entry that is not compatible with its current format, or offer us to edit it / convert it to another format instead.

**Comment by dominikschulz** [comment]
Yes, I just realized that, too.
