### ISSUE TITLE
Gopass `insert -a` is not working

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1486]
### Summary
The `-a` flag is supposed to append data to an entry, but it is currently replacing the "Password" key with a new value instead just like it does if one is not specifying any flag and provide an existing entry to `insert`.

### Steps To Reproduce
```
gopass insert foo
<type "bar">
gopass insert -a foo
<type "baz">
gopass show -f foo
<displays "Password: baz">
```

### Expected behaviour
This is a good question. Is a password is already set (non empty entry), then the `-a` flag should maybe ask for a "key" and then ask for its "value".
Otherwise it could just append the stuff at the bottom?

### Environment
Gopass master tip

**Comment by dominikschulz** [comment]
Should we just drop this flag for the insert command?

**Comment by AnomalRoil** [comment]
The `-a` flag makes sense only if :
- we are using plaintext format, so that it would append stuff at the end
- we were fully overwriting the entries without it, which is not the case since we only update the Password key currently in the case of an overwrite.

Currently the `gopass insert entry key` command allows to add new key-value lines to an entry, that's effectively appending them already.

I agree this can and should be deprecated and dropped.

**Comment by dominikschulz** [comment]
Sorry, that was a bit too quick. We need this flag (only) for reading from STDIN.

I will clarify the help text instead.

**Comment by AnomalRoil** [comment]
Ah good to know, I didn't check in the code what it was doing and wasn't expecting this, but it makes sense!
