### ISSUE TITLE
The `editrecipients` option does nothing and could be deprecated

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1487]
### Summary
It seems that currently the `editrecipients` option does nothing when using the command  insert, generate or edit.

Plus its description "Modify recipients when creating and editing passwords" hints at a lot of added complexity to handle multiple recipients per entry.

### Steps To Reproduce
```
gopass config editrecipients true
gopass recipients add sometest
gopass insert newentry
gopass edit newentry
```

### Expected behaviour
I guess it should offer us to "modify recipients when creating and editing passwords", which it does not currently.

I'm in for deprecation since this seems to have gone unnoticed so far.

### Environment
Gopass master tip

**Comment by dominikschulz** [comment]
Yes, I agree.

I think the worst about this option is that it's very easy to misuse in practice and either open up access too much or restrict it unintended.

I will likely remove it.
