### ISSUE TITLE
Clarify if Vim’s tmp files are a security issue

### ISSUE THREAD

**Issue by Brixy** [gopasspw/gopass#1489]
This is a great project! Thank you for your efforts.

I am not sure, whether Vim is a security issue: Many users use Vim’s backup and undo files, e.g. like this:

```
set backup
set undofile
set backupdir=~/tmp/vim/backups
set undodir=~/tmp/vim/undo
```

When you `gopass edit password` the password is stored in Vim’s tmp folders.

Can gopass prevent Vim from storing backup and undo files—even with the settings shown above?

Thank you!

**Comment by AnomalRoil** [comment]
I think this is covered here:
https://github.com/gopasspw/gopass/blob/ab8ad3089da9adba75936a7272b1a6d950613b84/docs/setup.md#securing-your-editor 

You should add this to your .vimrc file:
```
au BufNewFile,BufRead /dev/shm/gopass.* setlocal noswapfile nobackup noundofile
```

**Comment by Brixy** [comment]
Excellent. Thank you. I somehow missed that.

For MacOS (gopass installed with homebrew) I just added this line:

```
au BufNewFile,BufRead /private/**/gopass** setlocal noswapfile nobackup noundofile
```

**Comment by dominikschulz** [comment]
This is certainly easy to miss.
Maybe we want to warn users if they have set $EDITOR to vim and these options are not present in their 
vimrc?

Likely a bit error prone, but might be worth it.

**Comment by AnomalRoil** [comment]
A warning would be nice, indeed.

**Comment by svenXY** [comment]
Hi, I know this is closed, but what about people that use neovim? They do not usually use ~/.vimrc and even if you look into ~/.config/nvim/init.vim, this does not have to include the settings mentioned here as neovim suggests to use this file to import others.

On the other hand, there is e.g. `nvim --clean` and such, so it might be a better idea to have a config item for editor or editor parameters

**Comment by kifirkin** [comment]
@dominikschulz Also would be nice to reflect this https://github.com/gopasspw/gopass/issues/1489#issuecomment-671356496 in docs

**Comment by dominikschulz** [comment]
Good point. Done.
