### ISSUE TITLE
Behaviour of the `show --revision=rev` flag

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1499]
Currently the command
`gopass show --revision=rev entry` 
allows to fetch a past revision of a given entry.

It supports git revision, so it can be invoked on a specific commit or using a relative name such as `HEAD~~` to get the before last revision for example.
However notice that it is not working relatively to the specified entry: it will fetch the entry as it was when the whole password store was in the given revision.

So, in the end the `--revision` flag is working but is useless in my opinion.
For it to be useful we might want to include a shortcut to query the "previous N-th revision" of a given secret. 

Currently to display the last change to a secret, one has to manually use `gopass history entry` or `git log path/to/file.gpg` to find the correct revision, which makes it cumbersome. Plus if using git, we could also just checkout that file directly using git... 

## Proposal
I would expect that there is easier way to fetch the last N-th revision of a given entry than running:
```
gopass history entry
gopass show -revision=rev entry
```

So that we could query the 3rd to last change to that entry for instance using `gopass show -rev=+3` or some other keyword that wouldn't clash with git.

This would also be useful if we were to move away from git to another storage system that's not really using references like git, to keep the ability to query past revisions of a given entry.

**Comment by AnomalRoil** [comment]
This is a child of #1488

**Comment by dominikschulz** [comment]
Thanks for filing this FR.
Not sure how hard it is, but if it's easy to do, I'll implement it soon.

**Comment by dominikschulz** [comment]
Looks quite easy to do. Will give it a shot.
