### ISSUE TITLE
Behaviour of the `show -qr` flag

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1500]
The `gopass show` command has a `-qr` flag that displays a QR code on the terminal to allow one to easily copy a password from its password store to its mobile phone using it.

##Expected behaviour

If the `-qr` flag is set, it should print a QR code containing the first secret value, but it should display the rest of the entry like gopass show would. 

The `-o` flag should prevent it from displaying the rest of the entry, just like it does with the regular `show` command.

The `-f` flag should force it to display all the entry below the QR code, including the password on the first line. 

The `-c` and `-C` flags should do exactly as they usually do but with the secret printed in both case as a QR code on top of being copied. Notice the `-c` flag should in theory copy the password to the clipboard without displaying the rest of the entry, while the `-C` flag should copy the password, and display the rest of the entry.  
NB: It is not clear to me if these should copy the password or copy the QR code. I'm not sure the QR code is using characters that can be usefully pasted into another display than a terminal (it's using unicode escapes to display it, no?)

This is coming from #1488.

**Comment by dominikschulz** [comment]
Thanks for filing this issue.

Not sure if this is something I want to do before we have properly documented all the flags.

Your suggestions sound good to me, so we should implement it as you described.

I don't think -c should copy the qr code, but the password itself.
