### ISSUE TITLE
otp option is not shown when running with --help option

### ISSUE THREAD

**Issue by ncmans** [gopasspw/gopass#1501]
### Summary
`gopass otp`

### Steps To Reproduce

1. `gopass --help`

### Expected behavior

See `otp` as a top level command.

### Environment

- OS: Arch Linux
- OS version: `Linux niagara 5.7.11.a-1-hardened #1 SMP PREEMPT Wed, 29 Jul 2020 19:25:17 +0000 x86_64 GNU/Linux`
- gopass Version:
  ```
  gopass 1.9.2 (2020-07-13 14:34:42) go1.14.4 linux amd64
  <root>     - gpg 2.2.21 - git 2.28.0 -   fs 0.1.0
  Available Crypto Backends: age, gpgcli, plain, xc
  Available RCS Backends: gitcli, noop
  Available Storage Backends: fs, inmem
  ```
- Installation method: `pacman`

**Comment by dominikschulz** [comment]
I was planning to deprecate it, but we decided against. It's probably just hidden from the output and needs to be revealed. Will do that.
