### ISSUE TITLE
Remove autoclip for gopass show

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#1502]
The `autoclip` config option was introduced for `gopass generated` and extended to cover `gopass show` as well at some point. However this leads to confusing and complex effects on the different flags and switches with no clear benefit.

We should remove the `autoclip` implementation in `gopass show` (only).
For `gopass generate` we'll likely want to keep it.

This is a child issue of #1488

**Comment by slokhorst** [comment]
I kind of like this feature. Maybe add it as an additional configuration option? `autoclip-show`, which defaults to `false`?
