### ISSUE TITLE
Error reading config from ~/Library/Application Support/gopass/config.yml: config not parseable

### ISSUE THREAD

**Issue by glowinthedark** [gopasspw/gopass#1537]
### Summary

```bash
# running command
gopass mounts

# generates this output:
Error reading config from ~/Library/Application Support/gopass/config.yml: config not parseable
```

### The actual contents of file `~/Library/Application Support/gopass/config.yml`

```
autoclip: false
autoimport: true
cliptimeout: 300
confirm: false
editrecipients: true
exportkeys: false
nocolor: false
nopager: false
notifications: true
path: ~/.password-store
safecontent: false
mounts:
  nc: ~/password-store-nc
```

> NOTE1: in the actual config file absolute paths are used; i replaced with `~` for brevity. 

> NOTE2: As can be seen from the config file I am using two stores, with an additional mount at `nc`

> NOTE3: I did _not_ edit the config file manually.

> NOTE4: The issue first appeared after reinstalling from latest git master, latest commit dc65f6e8179884db1d4ae08bea01926b7edc6ead .

> NOTE5: The command succeeds, ie the entry is displayed, etc.

### Steps To Reproduce
run any gopass command, e.g.

```bash
gopass somesite
```

### Actual behaviour

Outputs:
```
Error reading config from ~/Library/Application Support/gopass/config.yml: config not parseable
```

### Expected behavior
Normal operation

### Environment

- OS: [e.g. Mac OS X 10.15.5 (19F101)]
- OS version: Darwin macbook20.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
- gopass Version: gopass 1.10.0-git+HEAD go1.14.2 darwin amd64
- Installation method: `go get -u -v github.com/gopasspw/gopass`

**Comment by dominikschulz** [comment]
I guess you ran manually compiled version before?
If so: Sorry, you'll have to fix your config yourself.
An upgrade path is only offered for released versions.

**Comment by glowinthedark** [comment]
@dominikschulz: yes, i was running master; what is wrong with the config? it looks like valid yaml

**Comment by dominikschulz** [comment]
We did remove some config keys recently.
We should handle this correctly when upgrading from the latest release, but not within different commits in master.

The config parser does not only check for valid YAML but also that all keys are parsed and none is left "unparsed".
That's what happens if we remove keys. It's not really feasible to cover these scenarios.

We don't try to break the configs very often, but since the previous release a lot has changed.

**Comment by glowinthedark** [comment]
@dominikschulz: but maybe it wouldn't be too complex to display the name of the unrecognized keys? Then the error message would have been a lot more useful and would allow to quickly fix it by manual editing.

**Comment by dominikschulz** [comment]
Yes, that is a good idea. We might be able to do that.
