### ISSUE TITLE
Remove external dependencies - git

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#155]
It would be nice if we could get rid of our external dependencies some day.
This would allow for a nicer workflow, better error and cross platform support.
This issue is meant to track any progress / discussions on that matter for git.

**Comment by dominikschulz** [comment]
* https://github.com/libgit2/git2go - CGO bindings to the official libgit2 C library
* https://github.com/src-d/go-git - Pure CGO, low level, probably missing a few necessary features (like merging)
* https://github.com/gogits/git - Hybrid between Go and shell out to Git. Not a real option, but could be useful as a reference

**Comment by lunny** [comment]
https://github.com/src-d/go-git is pure Go not CGO

**Comment by dominikschulz** [comment]
@lunny Indeed, I mentioned that fact in my previous comment. But this library seems to be under heavy development and is only offering a rather low-level API. If this lib continues a planned this may be a viable option soon.

**Comment by Fale** [comment]
https://github.com/keybase/go-git is a fork of https://github.com/src-d/go-git which seems to have taken a different path

**Comment by tionis** [comment]
Just a note:
The [Community Fork](https://github.com/go-git/go-git) of go-git is being actively maintained, but still does not support all git features, specifically not merging.   
More details are at https://github.com/go-git/go-git/blob/master/COMPATIBILITY.md

**Comment by dominikschulz** [comment]
As long as there is no merge support it's unusable for our use case.

**Comment by dominikschulz** [comment]
#1443 introduced a potential alternative to git. I will need (a lot of) polishing, but it offers path leading away from git - if we choose to do so. Closing this issue.
