### ISSUE TITLE
Config error message is misleading

### ISSUE THREAD

**Issue by xorander00** [gopasspw/gopass#1551]
### Summary
Misleading error message when root key is in config.yml.  Fixing that and adding a paragraph in the docs on dealing with it would probably help to reduce confusion.  See: #1549 

### Steps To Reproduce
Use a config.yml with a root key/map.

### Expected behavior
A warning message more along the lines of, "Warning while loading config *config.Config. unknown fields: [root]"

### Environment
- OS: FreeBSD
- OS version: 12.1-RELEASE-p5
- gopass Version: 1.10.0+a6031515d0cbc0c24cc6a3792c4757489a764d4d
- Installation method: Binary release from github.com

### Additional context
Not a huge deal, but the error message is rather confusing.  The first time I ran this new version, I thought it might not be loading my config.  Then when I saw that it was actually loading my config, I wanted to try to update it for the new version.  However, I wasn't able to find any migration/docs on how to go about dealing with the root key (and I don't have time to read through the source right now).  I saw that it does fallback to legacy, so a more concise warning message would be much better here.

**Comment by number5** [comment]
Got same error on MacOS 10.14.6 with the Homebrew version, trying to remove the old config and create a new config couldn't get it work 😞 so stick with the old config and the error message now.

**Comment by dominikschulz** [comment]
Yes, indeed. This is confusing, we'll change that to only display the warning if parsing finally fails.
