### ISSUE TITLE
Can't configure jsopnapi after update to gopass 1.10

### ISSUE THREAD

**Issue by XenGi** [gopasspw/gopass#1552]
### Summary

Connection between gopass and gopass bridge is lost and I can't configure it with gopass-jsonapi utility.

### Steps To Reproduce

- update from gopass 1.9 to 1.10.

### Expected behavior

It should just continue to work or at least the binary should be able to reconnect the browser addon.

### Environment

- OS: Arch Linux
- OS version: Linux lucy 5.8.3-arch1-1 #1 SMP PREEMPT Fri, 21 Aug 2020 16:54:16 +0000 x86_64 GNU/Linux
- gopass Version:
  ```
  $ gopass version
  gopass 1.10.0 (2020-08-24 16:30:10) go1.15 linux amd64
  <root>     - gpg 2.2.21 - git 2.28.0
  Available Crypto Backends: age, gpgcli, plain
  Available Storage Backends: fs, gitfs, ondisk
  ```
- Installation method: [Arch community repo](https://www.archlinux.org/packages/community/x86_64/gopass)

### Additional context

When I try to configure the json api this happens:

```
$ gopass-jsonapi configure                                                                                                                                                            
DEPRECATION WARNING: Use gopass show
Entry 'configure' not found. Starting search...
[ 0] some_password0
[ 1] some_password1
[ 2] some_password2
[ 3] some_password3
[ 4] some_password4

Found secrets - Please select an entry [0]: 
```

**Comment by dominikschulz** [comment]
That will be fixed once #1550 is released.
