### ISSUE TITLE
How to use templates? (or: Can't remove unnamed template)

### ISSUE THREAD

**Issue by dAnjou** [gopasspw/gopass#1562]
### Summary
It's very unclear how to use templates. The feature description and the command's help output don't describe a workflow.

Additionally, I somehow managed to create an unnamed template that I can't remove because a name is required.

### Steps To Reproduce
```
gopass templates edit
```

### Expected behavior
It tells me to provide a name.

### Environment
- OS: macOS Catalina Version 10.15.6
- OS version: Darwin XV15-2.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
- gopass Version: gopass 1.9.2+e2d1549f452a0df1fc52e42e7d0f654334d7144e (e2d1549f452a0df1fc52e42e7d0f654334d7144e) go1.14.2 darwin amd64
<root>     - gpg 2.2.20 - git 2.28.0 -   fs 0.1.0
Available Crypto Backends: age, gpgcli, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
- Installation method: binary release

### Additional context
Instead, it opens my editor and lets me edit a template which then gets saved.
```
$ gopass templates
gopass
├── otr (/Users/max/.password-store-otr)  <- This is my custom store
└── .pass-template  <- This is the "unnamed" template
```
And if I can have multiple templates with names, how are they chosen? Or do I have to choose them myself somehow?

**Comment by dAnjou** [comment]
I was able to delete the unnamed template, I had to guess this though:
```
gopass templates rm /
```
Another question would be how I can create and use templates for my custom store, the flag `--store` doesn't seem to be supported.

**Comment by dominikschulz** [comment]
Indeed, the information how templates are applied is missing from the docs. We need to add that.

**Comment by dAnjou** [comment]
Found a bit more info here but it also doesn't seem complete: https://github.com/gopasspw/gopass/blob/master/docs/commands/templates.md

**Comment by dominikschulz** [comment]
No, that doc isn't complete, yet. We'll continue to improve documentation in the short term.

**Comment by insanerwayner** [comment]
Anyone have a sample template they could show here? Even something as basic as just password and login username.

**Comment by dominikschulz** [comment]
https://github.com/gopasspw/gopass/blob/master/internal/tpl/template_test.go#L20

This is the best I have right now.
