### ISSUE TITLE
Wrong version exposed via Json Api

### ISSUE THREAD

**Issue by kristiankostadinov** [gopasspw/gopass#1563]
### Summary
The version exposed via the json api is 0.0.0. 

### Steps To Reproduce
Use https://github.com/gopasspw/gopassbridge/blob/master/test-client/query-jsonapi.sh with 
```
echo '{"type":"getVersion"}' | ./test-client | gopass-jsonapi listen
```

### Expected behavior
Returns the same version as in `gopass-jsonapi --version`

### Environment
OS: Ubuntu 18.04
OS version: 18.04.04 LTS, 4.15.0-112-generic
gopass Version: 1.10.1-git+HEAD go1.15 linux amd64
Installation method: from source

### Additional context
Related issue from gopassbridge: https://github.com/gopasspw/gopassbridge/issues/171

Looks like the version is not correctly set for the API object. 
https://github.com/gopasspw/gopass/blob/ef72769301fc4cacf98d13f409c7fd00ee8336e6/cmd/gopass-jsonapi/jsonapi.go#L35
"v1.10.1" is not a [valid semantic version](https://semver.org/#is-v123-a-semantic-version) so `semver` fails during parsing. The version is then set to "0.0.0"
The error message is `Invalid character(s) found in major number "v1"`

**Comment by dominikschulz** [comment]
Thanks for reporting. I believe this was reported before.

**Comment by donnex** [comment]
Unable to use the browser extension as well because of this. Hoping for a quick fix :+1:
