### ISSUE TITLE
team management and recipients subset

### ISSUE THREAD

**Issue by deadc0de6** [gopasspw/gopass#1564]
Does gopass support the creation/management of password entries for a subset of the recipients. As I can see the list of recipients is displayed when creating a new entry however I'd like to be able to select the user(s) for which I'm creating the new entry.

I've seen some solutions that involve either creating a substore (which might not be optimal) or adding a `.gpgid` file in subdirectory (which looks hacky). Is there a built-in way of doing this? Do gopass support this? Will it?

Thanks!

related issues

* #1487: editrecipients
* #1120: .gpgid
* #439: substore

**Comment by AnomalRoil** [comment]
@dominikschulz I guess we could achieve the same functionality we had with the gpg-id stuff while being encryption backend agnostic by either :

 - using the substore functionality in a transparent way for the user
 - improving the template functionality to allow to have a subset of recipients

In that way we could avoid the gpg specific handling.

Ideally we might actually combine the two : have a template for a subset of recipients that is actually a substore.

**Comment by dominikschulz** [comment]
We do have minimal support for `.gpg-id` files placed in sub-folders but very little tooling around that. You can try it if you want.

The recommended approach is to use one sub-store per team.
