### ISSUE TITLE
[FR] Check for missing public keys before editing

### ISSUE THREAD

**Issue by deadc0de6** [gopasspw/gopass#1565]
### Summary

I am missing one recipient's public key in my gopass setup. I guess I always did but maybe due to the recent update, it suddently refused to encrypt a multi-line new entry and just discarded it and I lost it.
```bash
$ gopass insert -m some-entry
gpg: <SOME-PUBLIC-KEY>: skipped: No public key
gpg: [stdin]: encryption failed: No public key

Error: failed to store secret 'some-entry': Failed to encrypt
```

I would expect gopass to either warn me before starting to edit the new entry or fully block me but not letting me start creating an entry and then blindly discarding it.

### Steps To Reproduce

* insert a new recipient
* remove the public key from your keyring
* add a new multi-line entry

### Expected behavior

I would expect gopass to either warn me before starting to edit the new entry or fully block me but not letting me start creating an entry and then blindly discarding it.

### Environment

- OS: linux
- gopass Version: 1.10.1

**Comment by dominikschulz** [comment]
Yes, that sounds very reasonable.
These kind of issues are extremely annoying and we certainly want to protect you from loosing data.

However I'm not so sure how difficult it is to implement this, but we'll definitely try.
