### ISSUE TITLE
Edit Secret: ERROR: Can not parse Gopass native Secret.

### ISSUE THREAD

**Issue by r0l1** [gopasspw/gopass#1570]
### Summary
Since updating gopass to the latest release my workflow with this tool is a total pain. My latest problem is a broken edit function. Trying to edit and extend a secret causes the following error:

```
ERROR: Can not parse Gopass native Secret. Retry? [Y/n/q]: y
```

### Steps To Reproduce
Edit a secret and add an entry as `key: value`

### Environment
OS: Arch Linux
gopass Version:  1.10.1

**Comment by r0l1** [comment]
Setting `mime` to `false` solves this issue. This should be better documented and a warning should be placed on the README. The new mime format should also be documented and a link in the Changelog would be helpful.

Finally breaking changes should be moved to a new major version.

**Comment by dominikschulz** [comment]
Hmm, sorry to hear that.

Could you elaborate what you try to put into the secret that it fails to parse?
This should only happen when editing native secrets.

The new behaviour and the workaround are documented in the changelog: `If you are using different Password Store implementations to access your secrets, e.g. on mobile devices, you might want to run gopass config mime false before performing any kind of write operation on the password store.`.

**Comment by dominikschulz** [comment]
On a second thought I guess this should be a warning offering to reopen the editor.
Not a hard failure. That's not good for the UX.

**Comment by r0l1** [comment]
Hi Dominik,
sorry for the rant. I was quite upset while working on a different task and suddenly my ecosystem didn't work as expected after a quick update (minor versions only).

> Could you elaborate what you try to put into the secret that it fails to parse?
This should only happen when editing native secrets.

I just added valid yaml data to the secret. For example: `key: vakue`

> The new behaviour and the workaround are documented in the changelog: If you are using different Password Store implementations to access your secrets, e.g. on mobile devices, you might want to run gopass config mime false before performing any kind of write operation on the password store..

This was not initially clear. Maybe setting mime to false by default when breaking changes occur would deliver a better user experience. :+1:

**Comment by AnomalRoil** [comment]
Which exact commands were you using? I'd try to reproduce this error as it shouldn't happen if you've been using Gopass and only gopass.

**Comment by dominikschulz** [comment]
@r0l1 No worries, I understand your frustration. The default for this feature wasn't a clever choice. If we can without breaking more users we'll change the default.

**Comment by AnomalRoil** [comment]
Okay, I was able to reproduce it: the problem comes if the last line of the edited secret is not an empty newline.

I don't see why we are expecting an empty new line, we should probably remove this check.

**Comment by r0l1** [comment]
@r0l1 thanks.
@AnomalRoil Seams to be the issue. My default editor is nano which causes this behavior. Thanks for digging into this.

**Comment by dominikschulz** [comment]
Yes, that seems like something that should be easy to fix.
Thanks for bringing this to our attention @r0l1
