### ISSUE TITLE
Having multiple Password fields causes strange behaviour

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1576]
### Summary
Using the `mime: true` setting and having multiple key-value with the same key causes unexpected behaviour, with the ordering of the different key being lexicographical instead of as per the actual order in the entry.

### Steps To Reproduce
 Create an entry containing:
```
Password: rockyou
Password: 1
Password: 2
Password: test
Password: 0

```
(Make sure to include the new line at the end so that it's using the new native secret format.)

And then show it using :
```
$ gopass edit fo9
Warning: Password is too short
$ gopass show -f fo9 
Password: 0
Password: 1
Password: 2
Password: rockyou
Password: test

$ gopass show -o fo9
0
``` 

As you can see the entries are display in another order than what we inserted in the edit mode.

And then test changing the config `mime` to false and show or edit it: all the other keys with "password" will have disappeared!

```
$ gopass config mime false
mime: false
$ gopass show -u fo9
0

$ gopass edit fo9
```

This is really not the behaviour we want with mime set to false, we'd like to have all the content displayed rather than the Password fields being squashed into a single one.

The worst is that if you start editing it or generating a new password for the Password field, it will misbehave even more !
Notice this can cause loss of data:

```
$ gopass show -f fo11
Password: 123
Password: 124
Password: 124

$ gopass generate fo11 password 4 
Password for fo11:password generated              
$ gopass show -u fo11
Password: A0Ni

```

### Expected behaviour
We should clarify the expected behaviour.

IMO:
 1. we should display entries in the order they are written in the secret file
 1. we should error out or ask the user when there are multiple entries with the same key and they do a generate or insert on that key
 1. we should make sure the mime setting is not causing strange stuff if we switch it `on` and `off` (maybe specify how the transition is supposed to happen for all the existing types of secrets?)

**Comment by AnomalRoil** [comment]
The workaround for 1.10.2 will be to be able to disable parsing altogether. 

But we still need to implement proper support for key-valueS instead of key-value.

**Comment by dominikschulz** [comment]
By definition we only exactly one password field (the first line) now.
This issue might still apply to the key-value part, but not the password line.

**Comment by AnomalRoil** [comment]
Yes, I kept it open wrt to the key-value part, in order to implement key-valueS
