### ISSUE TITLE
The retry dialog drops unwritten changes

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1593]
### Summary
When we `edit` a secret and it fails, the "Retry" dialog proposes to retry and re-open the editor, but it does so while dropping all the changes, which is a terrible UX.

### To reproduce 
```
gopass generate test 5
echo "testing" | gopass insert test user
gopass edit
```
This should display:
```
Password: Gv1rX
User: testing
```

Now edit it to look like:

```
Password: Gv1rX
User: testing
This is a nice body text without a new line between the key-value part and the body.
```
And save&exit your editor.
--> gopass complains about the secret not being in Native format (i.e. good Mime format) and proposes to "Retry: Y/n/q".
if you retry, it will re-open to:
```
Password: Gv1rX
User: testing
```
Having discarded all the changes.

This is really a bad UX, leading to frustration on the user side.

This is maybe related or maybe a duplicate of #1565 but triggered by another code path.

**Comment by dominikschulz** [comment]
Oh no. Yes, indeed. This almost as bad as before the last "fix".
On retry we should certainly try to preserve anything that has been entered.
