### ISSUE TITLE
Non-interactive mode not working

### ISSUE THREAD

**Issue by dcardellino** [gopasspw/gopass#1595]
### Summary
I try the following with GoPass 1.10.1 on MacOS Catalina:
`gopass --yes insert --force secrets/test username: test password: test`

and i receive the following error message:
Incorrect Usage. flag provided but not defined: -yes

I remember in older versions the flag **--yes** worked fine. Was there any change?

### Expected behavior
Inserting secrets non interactively!

### Environment
- OS: MacOS X Catalina
- OS version: 10.15.6
- gopass Version: gopass 1.10.1 go1.15 darwin amd64
- Installation method: brew

**Comment by dominikschulz** [comment]
That might be a regression. We'll investigate.

**Comment by AnomalRoil** [comment]
I confirm, it was dropped by mistake. I'll add it back in a minute.

But what is the expected behaviour of this line? 
It does not respect the syntax that `insert` is expecting, which is: `gopass insert name/of/entry nameofkey`.

I just tested it and it seems to work if we use this syntax:
`gopass insert name/of/entry nameofkey:valueofkey` without space after the colons.

**Comment by dcardellino** [comment]
> I confirm, it was dropped by mistake. I'll add it back in a minute.
> 
> But what is the expected behaviour of this line?
> It does not respect the syntax that `insert` is expecting, which is: `gopass insert name/of/entry nameofkey`.
> 
> I just tested it and it seems to work if we use this syntax:
> `gopass insert name/of/entry nameofkey:valueofkey` without space after the colons.

The expected bevaiour is to insert (externally) generated password automatic.
The actual behaviour is, that even if i do:
`gopass insert secrets/test username:test password:test`
GoPass asks me for a password to be inserted in the entry.

**Comment by AnomalRoil** [comment]
@dominikschulz We might want to update the documentation about how insert behaves, I guess xD
