### ISSUE TITLE
entry fields disappear

### ISSUE THREAD

**Issue by deadc0de6** [gopasspw/gopass#1601]
### Summary

When creating a multiline entry with more than one field with the same key, only the last entry is kept, the rest is entirely discarded.

### Steps To Reproduce

create a new multiline entry
```bash
$ gopass insert -m badtest2
```

insert the following
```
thepassword
user: a user
web: test.com
user: second user 
```

save and show the entry
```bash
$ gopass show badtest2          
thepassword
user: second user
web: test.com
```

### Expected behavior

entered text do not get altered.

### Environment

- OS: linux
- gopass Version: 1.10.1

### Additional context

see also #1600

**Comment by AnomalRoil** [comment]
This is related to  #1576, since it's not just the password fields that disappear if there are collisions.

This will require a refactoring since we are relying on hashmaps, or we could hashmap to arrays instead of

**Comment by dominikschulz** [comment]
This somehow collides with the feature of interpreting secrets at all.
I understand the request.
But also I don't want to miss the K/V feature.

**Comment by AnomalRoil** [comment]
I was able to come up with a fairly easy fix for the Mime type.
But for the older KV type, I'm afraid the best we could do would be to add a warning that prompts the user back to the editor.

What do you think would be best ?

**Comment by AnomalRoil** [comment]
Notice this is worked around thanks to the new config field `parsing` which avoids it when set to `false`.

But we still need to implement key-values with plural to values as per #1576 to avoid this issue when `parsing` is `true`.
