### ISSUE TITLE
add a config option to disable entry parsing

### ISSUE THREAD

**Issue by deadc0de6** [gopasspw/gopass#1602]
### Summary

I'd like to be able to freely edit entries using gopass and not get parts of the entered text discarded or re-ordered (#1600, #1601). Please provide a config option to disable any kind of parsing on the content of an entry (for `insert -m` or `edit`).

**Comment by lsowen** [comment]
I think this would be a useful feature.  Maybe a CLI flag or environment variable to disable all parsing, and treat any `insert` / `show` as just an "opaque" string.

**Comment by AnomalRoil** [comment]
This is pushed to 1.11 when we will re-introduce the (optional) parsing for Mime secrets.

For 1.10.2 we will disable input parsing altogether.
