### ISSUE TITLE
Duplicated field in entry

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1607]
### Steps To Reproduce
`gopass edit test` and add the following:

```
secret
password: oth3rpa4ss
``` 
and then `gopass show -u test` will display:

```
secret
password: oth3rpa4ss
password: oth3rpa4ss

``` 
instead, with a duplicated password entry!

### Expected behavior
Do not duplicate any field.

### Environment

- OS: Ubuntu 18.04
- gopass Version master tip
- Installation method: from source

Probably related to #1601 and/or #1600

**Comment by dominikschulz** [comment]
This is actually a symptom of a more fundamental problem: How do we want to handle structured (K/V) secrets.

This issue specifically is a bug that is easy to fix, but while looking at it I noticed several other possible corner cases that might not be possible to fix.
