### ISSUE TITLE
adding secret with colon in name fails

### ISSUE THREAD

**Issue by lsowen** [gopasspw/gopass#1609]
### Summary
A secret name with a colon is interpreted as a K/V pair, instead of a secret name.

### Steps To Reproduce
```bash
 ~$ gopass insert test:test

Error: Usage: gopass insert name
```

### Expected behavior
If only  a single element is specified, then it should be taken as the secret name, even if it successfully parses as a K/V pair.

### Environment

- OS: Fedora 32
- gopass Version: gopass 1.9.2+e2d1549f452a0df1fc52e42e7d0f654334d7144e (e2d1549f452a0df1fc52e42e7d0f654334d7144e) go1.14.2 linux amd64

### Additional context
Causes problems with using gopass as the backend for the lastest version of `aws-vault`, which stores the OIDC token as `gopass insert -f -m oidc:<hostname>`

**Comment by dominikschulz** [comment]
Thank you for reporting this and sending a fix.

Could you also point me at information on how to use gopass with aws-vault? I'd love to learn more about this integration.

**Comment by lsowen** [comment]
hi @dominikschulz thanks for taking a look at it.

`aws-vault` uses https://github.com/99designs/keyring/blob/master/pass.go to interface with "pass-like" systems.  To use with `aws-vault` I have the following in my `~/.bashrc`:

```bash
export AWS_VAULT_BACKEND=pass                                                                                                                                                                                       
export AWS_VAULT_PASS_CMD=gopass
```

**Comment by dominikschulz** [comment]
Thank you! We might want to point at it from our docs.
