### ISSUE TITLE
Did gopass recently start reordering lines within secrets?

### ISSUE THREAD

**Issue by dragetd** [gopasspw/gopass#1612]
### Summary

Next to login details, I like to take notes in my secret for some additional or convenience stuff. One example is that for docker auth credentials, I save the token also:

```
password
login: user

# Somoe note

# JSON:
{
  "auths": {
    "x": {
      "auth": "x"
    }
  }
}
```

But saving it, it reorders the secrets completely:

```
password
"auth": "x"
"auths": {
"x": {
login: user

# Somoe note

# JSON:
{
    }
  }
}
```

I guess it collects entries with a colon at the top. Can I prevent this from happening somehow?

### Steps To Reproduce

Try storing

```
password
login: user

# Somoe note

# JSON:
{
  "auths": {
    "x": {
      "auth": "x"
    }
  }
}
```

### Expected behavior

Having the order of infos I put into the store intact.

### Environment
gopass 1.10.0 
gentoo linux

**Comment by dominikschulz** [comment]
Yes, this is a known issue. I did not anticipate the impact of this change.
The change itself was intentional, the impact was not.
We're currently considering how to fix this or roll it back without causing more confusion.

**Comment by whs-dot-hk** [comment]
Hi @dragetd I found that for v1.10.1 it will remove the comments after `gopass edit`

**Comment by AnomalRoil** [comment]
Closing in favour of #1600 since this is already tracked there.
