### ISSUE TITLE
Usernames which are numbers are pasted in scientific notation

### ISSUE THREAD

**Issue by zuntik** [gopasspw/gopass#1614]
### Summary

if I have a "user" component in the gpg file, and it's a number, the gopass brige in windows pastes it in scientific 

### Steps To Reproduce

Example, if I have
```
user: 043513
```
it gets pasted in the field in firefox as "4.3513e+4"
### Expected behavior

I expet to see "043513"
### Environment

Windows 10
gopass version 1.9.2
go version (as stated in ```gopass -v``` : 1.14.2

### Edit with second part of the bug

If I click the show details button on gopass brige the leading zeros in a username get omited

**Comment by dominikschulz** [comment]
I don't see how this could happen within gopass.
Is this maybe a Windows issue?
How do you copy the value?

**Comment by zuntik** [comment]
> 
> 
> I don't see how this could happen within gopass.
> Is this maybe a Windows issue?
> How do you copy the value?

I don't copy the value. I have the website I want open, click on the gopass logo on firefox on the top right corner, search for the desired secret, click on it and it gets auto pasted as explained. The password gets pasted correctly.

**Comment by zuntik** [comment]
I've added another bug on this issue

**Comment by AnomalRoil** [comment]
Is this a parsing issue? 😮 
The missing leading 0 is probably a parsing issue.

Unless it's a gopass brige issue.

**Comment by AnomalRoil** [comment]
This is probably caused by yaml parsing actually.

Did you test it in a secret that looked like:
```
yamltest
---
user: 043513
```

If so, it's somewhat related to #1585.
It could be worked around with the "no parsing" config option I plan to add soon.

**Comment by AnomalRoil** [comment]
So, the proper way to encode a username using Gopass YAML format is using string delimiters on the YAML value:

```
secret
---
user: "043513"
```
will always be parsed as being 043513 and not some strange octal or scientific value by the YAML parser.
