### ISSUE TITLE
Gopass exits with stack trace while processing config.yml after upgrade to 1.10

### ISSUE THREAD

**Issue by leogott** [gopasspw/gopass#1615]
### Summary

After upgrading gopass from 1.9.x to 1.10.x, gopass was broken in the commandline but continues to work fine with gopass bridge
```
PS > gopass
Error: Failed to initialize store: failed to initialized stores: failed to initialize the root store at '/C:\Users\leogott\.password-store': failed to init storage backend: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.: failed to init storage backend: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.: failed to initialize the root store at '/C:\Users\leogott\.password-store': failed to init storage backend: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.: failed to init storage backend: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.
```
modifying path in the config located at ~\.config\gopass\config.yml does not appear to change the behavior at all. Neither does gopass config --store path different/path

Renaming the store makes gopass open a seperate window for part of a second, but not return *anything* in the original window.

I am not aware of a method to learn if gopass is actually aware of the location of the config.

I tried providing the location via environment variables but was unsuccessful. Though it's possible i missed something.

### Steps To Reproduce

upgrade an existing gopass installation on windows from 1.9 to 1.10

### Expected behavior

gopass lists the contents of the store

### Environment

- OS: Windows 10 Pro
- OS version: 19041.508
- gopass Version: gopass 1.10.1+377d2ab8507ed6d0025a1d18acf390d38680d0aa (377d2ab8507ed6d0025a1d18acf390d38680d0aa) go1.14.2 windows amd64
- Installation method: scoop

**Comment by leogott** [comment]
(Also "failed to initialized stores" looks like a typo to me)

**Comment by DonBranson** [comment]
I may be seeing the same thing - just upgraded to 1.10.1 on mac, and lost everything.

**Comment by leogott** [comment]
I was able to repair gopass locally by renaming another config.yml I didn't know about yet.

By using `$Env:GOPASS_DEBUG_LOG="path/to/logfile"` I was able to determine that a config.yml existed at `~\AppData\Roaming\gopass\` and that there was an issue with it.
Most likely the only problem with it is the "protocol" part of the path entry, that was previously accepted(?) and no longer is.
```
root:
...
  path: gpgcli-gitcli-fs+file:///C:\...
```
After removing the broken config, gopass worked as expected. I created a new config with the output of `gopass config`.

<details><summary>Click for logfile ...</summary>
<pre><code>2020/11/22 19:59:42.520554 pwrules/aliases.go:52	pwrules.loadCustomAliases	no custom aliases found at C:\Users\leogott\AppData\Roaming\gopass\domain-aliases.json
2020/11/22 19:59:42.706555 config/io.go:37	config.loadConfig	Trying to load config from C:\Users\leogott\AppData\Roaming\gopass\config.yml
2020/11/22 19:59:42.714555 config/io.go:114	config.decode	Trying to unmarshal config into *config.Config
2020/11/22 19:59:42.716554 config/io.go:120	config.decode	Extra elements in config: unknown fields: [root]
2020/11/22 19:59:42.716554 config/io.go:114	config.decode	Trying to unmarshal config into *config.Pre193
2020/11/22 19:59:42.716554 config/io.go:126	config.decode	Loaded config: *config.Pre193: &{Path: Root:0xc00016df00 Mounts:map[] XXX:map[]}
2020/11/22 19:59:42.716554 config/io.go:129	config.decode	Loaded legacy config. Should rewrite config.
2020/11/22 19:59:42.716554 config/io.go:45	config.loadConfig	Loaded config from C:\Users\leogott\AppData\Roaming\gopass\config.yml: &config.Config{AutoClip:true, AutoImport:true, ClipTimeout:45, ExportKeys:false, MIME:true, NoColor:false, NoPager:false, Notifications:true, Path:"/C:\\Users\\leogott\\.password-store", SafeContent:false, Mounts:map[string]string{}, configPath:"C:\\Users\\leogott\\AppData\\Roaming\\gopass\\config.yml", XXX:map[string]interface {}(nil)}
2020/11/22 19:59:42.720555 root/init.go:17	root.(*Store).Initialized	initializing store and possible sub-stores
2020/11/22 19:59:42.720555 root/init.go:65	root.(*Store).initialize	initialize - /C:\Users\leogott\.password-store
2020/11/22 19:59:42.721554 leaf/store.go:51	leaf.New	Instantiating  at /C:\Users\leogott\.password-store
2020/11/22 19:59:42.722555 backend/storage.go:74	backend.DetectStorage	Trying gitfs for /C:\Users\leogott\.password-store
2020/11/22 19:59:42.724555 fsutil/fsutil.go:49	fsutil.IsDir	failed to check dir \C:\Users\leogott\.password-store\.git: CreateFile \C:\Users\leogott\.password-store\.git: The filename, directory name, or volume label syntax is incorrect.
2020/11/22 19:59:42.724555 backend/storage.go:76	backend.DetectStorage	failed to use gitfs for /C:\Users\leogott\.password-store: no .git
2020/11/22 19:59:42.724555 backend/storage.go:74	backend.DetectStorage	Trying ondisk for /C:\Users\leogott\.password-store
2020/11/22 19:59:42.724555 fsutil/fsutil.go:64	fsutil.IsFile	failed to check file \C:\Users\leogott\.password-store\index.gp1: CreateFile \C:\Users\leogott\.password-store\index.gp1: The filename, directory name, or volume label syntax is incorrect.
2020/11/22 19:59:42.724555 backend/storage.go:76	backend.DetectStorage	failed to use ondisk for /C:\Users\leogott\.password-store: not supported
2020/11/22 19:59:42.724555 backend/storage.go:74	backend.DetectStorage	Trying fs for /C:\Users\leogott\.password-store
2020/11/22 19:59:42.724555 fsutil/fsutil.go:49	fsutil.IsDir	failed to check dir /C:\Users\leogott\.password-store: CreateFile /C:\Users\leogott\.password-store: The filename, directory name, or volume label syntax is incorrect.
2020/11/22 19:59:42.724555 backend/storage.go:76	backend.DetectStorage	failed to use fs for /C:\Users\leogott\.password-store: dir not found
2020/11/22 19:59:42.725573 action/errors.go:58	action.ExitError	Stacktrace: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.
unknown storage backend
github.com/gopasspw/gopass/internal/store/leaf.(*Store).initStorageBackend
	src/github.com/gopasspw/gopass/internal/store/leaf/storage.go:16
github.com/gopasspw/gopass/internal/store/leaf.New
	src/github.com/gopasspw/gopass/internal/store/leaf/store.go:59
github.com/gopasspw/gopass/internal/store/root.(*Store).initialize
	src/github.com/gopasspw/gopass/internal/store/root/init.go:66
github.com/gopasspw/gopass/internal/store/root.(*Store).Initialized
	src/github.com/gopasspw/gopass/internal/store/root/init.go:18
github.com/gopasspw/gopass/internal/action.(*Action).Initialized
	src/github.com/gopasspw/gopass/internal/action/init.go:29
main.setupApp.func2
	src/github.com/gopasspw/gopass/main.go:144
github.com/urfave/cli/v2.(*App).RunContext
	pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315
main.main
	src/github.com/gopasspw/gopass/main.go:95
runtime.main
	go/src/runtime/proc.go:203
runtime.goexit
	go/src/runtime/asm_amd64.s:1373
failed to init storage backend: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.
github.com/gopasspw/gopass/internal/store/leaf.New
	src/github.com/gopasspw/gopass/internal/store/leaf/store.go:60
github.com/gopasspw/gopass/internal/store/root.(*Store).initialize
	src/github.com/gopasspw/gopass/internal/store/root/init.go:66
github.com/gopasspw/gopass/internal/store/root.(*Store).Initialized
	src/github.com/gopasspw/gopass/internal/store/root/init.go:18
github.com/gopasspw/gopass/internal/action.(*Action).Initialized
	src/github.com/gopasspw/gopass/internal/action/init.go:29
main.setupApp.func2
	src/github.com/gopasspw/gopass/main.go:144
github.com/urfave/cli/v2.(*App).RunContext
	pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315
main.main
	src/github.com/gopasspw/gopass/main.go:95
runtime.main
	go/src/runtime/proc.go:203
runtime.goexit
	go/src/runtime/asm_amd64.s:1373
failed to initialize the root store at '/C:\Users\leogott\.password-store': failed to init storage backend: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.
github.com/gopasspw/gopass/internal/store/root.(*Store).initialize
	src/github.com/gopasspw/gopass/internal/store/root/init.go:68
github.com/gopasspw/gopass/internal/store/root.(*Store).Initialized
	src/github.com/gopasspw/gopass/internal/store/root/init.go:18
github.com/gopasspw/gopass/internal/action.(*Action).Initialized
	src/github.com/gopasspw/gopass/internal/action/init.go:29
main.setupApp.func2
	src/github.com/gopasspw/gopass/main.go:144
github.com/urfave/cli/v2.(*App).RunContext
	pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315
main.main
	src/github.com/gopasspw/gopass/main.go:95
runtime.main
	go/src/runtime/proc.go:203
runtime.goexit
	go/src/runtime/asm_amd64.s:1373
failed to initialized stores: failed to initialize the root store at '/C:\Users\leogott\.password-store': failed to init storage backend: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.: failed to init storage backend: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.: unknown storage backend: mkdir /C:: The filename, directory name, or volume label syntax is incorrect.
github.com/gopasspw/gopass/internal/store/root.(*Store).Initialized
	src/github.com/gopasspw/gopass/internal/store/root/init.go:19
github.com/gopasspw/gopass/internal/action.(*Action).Initialized
	src/github.com/gopasspw/gopass/internal/action/init.go:29
main.setupApp.func2
	src/github.com/gopasspw/gopass/main.go:144
github.com/urfave/cli/v2.(*App).RunContext
	pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315
main.main
	src/github.com/gopasspw/gopass/main.go:95
runtime.main
	go/src/runtime/proc.go:203
runtime.goexit
	go/src/runtime/asm_amd64.s:1373
</code></pre>
</details>

**Comment by AnomalRoil** [comment]
Windows users should make sure their path config entry looks like this:
`path: c:\path\to\your\password-store`
without `gpgcli-gitcli-fs+file:///` prepended.

I guess the migration path from previous config might have failed on Windows at some point in the past.

When a broken config file is causing issues, the prompt should now tell what settings are the issue and where the config file is located, thus helping with the resolution of such issues.

All tests passes on Windows since #1680 so hopefully Gopass works better on Windows now than it used to.

Closing since it seems solved to me. Let us know if it's failing again with the future releases, and we'll dig into it.
