### ISSUE TITLE
Can't insert new key-value secrets

### ISSUE THREAD

**Issue by worldofgeese** [gopasspw/gopass#1623]
@worldofgeese What do you mean by "structured secrets"?

The key-value secrets and the YAML secrets should still work as they used to before we introduced the MIME format.
If they don't work with `mime false`, then it's probably a bug and please open an issue :sweat_smile:

_Originally posted by @AnomalRoil in https://github.com/gopasspw/gopass/issue_comments/709249705_

`gopass version`:
```
gopass 1.10.1+v1.10.1 (v1.10.1) go1.15.1 linux amd64
<root>     - gpg 2.2.21 - git 2.28.0
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs, ondisk
```

```
:~$ gopass generate test
How long should the password be? [24]: 
Password for test generated
✔ Copied test to clipboard. Will clear in 45 seconds.
:~$ gopass insert test wolf
test:wolf []: wolf
:~$ gopass show test
s29f6rBOnX9LdbkRe8NSWybm

```

**Comment by AnomalRoil** [comment]
Confirmed on master tip, definitively a bug.

**Comment by AnomalRoil** [comment]
This is currently solved on master tip, probably thanks to the `mime` removal.
