### ISSUE TITLE
Disable macOS notifications

### ISSUE THREAD

**Issue by spinningarrow** [gopasspw/gopass#1625]
### Summary

Whenever I run a command like `gopass show` I see a notification that looks something like this:

![image](https://user-images.githubusercontent.com/1797328/96450717-da8a2880-1216-11eb-9dc7-56c9a7d4923e.png)

The same thing also seems to be shown when the clipboard is cleared after doing a `gopass show -c`.

Is there a way to disable these notifications from gopass? They're not very useful for me. I can disable them globally via macOS's notification settings but that disables all terminal-notifier notifications which is not ideal.

### Steps To Reproduce

1. Run a command like `gopass show` on macOS.

### Expected behavior

An option to disable notifications.

### Environment

- OS: [e.g. Mac OS X High Sierra, Ubuntu 18.04, Windows 10, ...]
- OS version: [uname -a] Darwin Kernel Version 19.6.0
- gopass Version: [gopass version] gopass 1.10.1 go1.15 darwin amd64
- Installation method: [e.g. from source, brew, gopass repo] brew

**Comment by zant** [comment]
Hi! I was looking for issues to grab but I think this one is already implemented within [configuration](https://github.com/gopasspw/gopass/blob/master/docs/config.md) options.

This command did it for me:
```
gopass config notifications false
```

**Comment by spinningarrow** [comment]
@zant you're right - that works, thanks! I must have totally missed it.
