### ISSUE TITLE
documentation: select a local starage for otp

### ISSUE THREAD

**Issue by jerger** [gopasspw/gopass#1626]
### Summary
At the moment doc for otp is quite unclear.
1. https://github.com/gopasspw/gopass/blob/master/docs/features.md says it's going to be deprecated
2. https://github.com/gopasspw/gopass/blob/master/docs/commands/otp.md says nothing about deprectaion
3. there is no clear advise WHERE to store otp tokens.

### Expected behavior
1. document a secure way to store otp tokens (my proposal is an additional, dedicated & local store for otp)
2. clear decision about deprecation (my hope is that otp support continues :) 

If you, the community & the disscussion agree I will do the PR :-)

**Comment by AnomalRoil** [comment]
I'd welcome a PR, but I've never used the OTP stuff, so that requires input from @dominikschulz

**Comment by jerger** [comment]
:-)
