### ISSUE TITLE
Deprecation warnings breaks Summon provider

### ISSUE THREAD

**Issue by desolat** [gopasspw/gopass#1627]
### Summary
The deprecation warning text `DEPRECATION WARNING: Use gopass show` is prefixed to the secret value when using the gopass Summon provider.

### Steps To Reproduce
Run the gopass Summon provider with gopass 1.10.1.

### Expected behavior
When using the gopass Summon provider only the secrets value is in the environment variable value.

### Environment
- OS: Ubuntu 18.04
- gopass Version: 1.10.1
- Installation method: Github release

**Comment by worldofgeese** [comment]
Just encountered this today.

**Comment by AnomalRoil** [comment]
I'm not sure how the Summon provider is supposed to work, so that would be on @ckolumbus or @dominikschulz  I guess.

The deprecation warning should show only if you are using `gopass name/of/entry` instead of `gopass show name/of/entry`, but afaict, the Summon provider is using our internal API directly and is not a wrapper around our CLI, so that's strange.

**Comment by ckolumbus** [comment]
@desolat I'll have a look!

**Comment by ckolumbus** [comment]
I checked `gopass/v1.10.1` on `go1.15.2 linux/amd64` and `go1.15.3 windows/amd64` and after the build I executed the following

```
gopass init
gopass generate x/y
gopass-summon-provider x/y
```
No deprecation warnings showed. @desolat could you provide some more detailed information on how you can reproduce this error?

**Comment by desolat** [comment]
Actually I was not using `gopass-summon-provider` but `gopass` as is being described here in the documentation: https://github.com/gopasspw/gopass/blob/master/docs/summon-provider.md. So probably that documentation is outdated.

For completeness here is an example summon call when using `gopass` (with stripped-down output): 

```
$ SUMMON_PROVIDER=/usr/local/bin/gopass summon env
SECRET_ENV=DEPRECATION WARNING: Use gopass show
Password: secret value
```

**Comment by ckolumbus** [comment]
Ok, so I forgot to update the docs when I implemented the new summon provider command :-(. Could you please verify that it works with the `gopass-summon-provider` program? Then we could close this one and open a new issue to update the doc.

**Comment by desolat** [comment]
Yes, it works as expected with `gopass-summon-provider`. @ckolumbus You're opening the doc issue?

**Comment by ckolumbus** [comment]
> You're opening the doc issue?
yes!
