### ISSUE TITLE
Please help - unexperienced with git, trying to sync with a remote at home

### ISSUE THREAD

**Issue by drwulsen** [gopasspw/gopass#1630]
### Summary
I'm too stupid to set up a remote for synchronization
### Steps To Reproduce
Install gopass. Follow setup assistant (multiple times)
Try to set up some local git folder, which should be synchronized with the gopass store.
Add it as remote.
### Expected behavior
I thought that my local changes would be pushed to my "remote" directory.
### Environment
- OS: Linux
- OS Gentoo
- gopass Version: gopass 1.10.0 (2020-10-23 20:43:18) go1.15.3 linux amd64
<root>     -     <none> -   fs 0.1.0
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs, ondisk
- Installation method: from source

### Additional context
I'm new to the git stuff, all I do on github is use the webinterface.
What I'd want to do with the git folder is: Have a local store, always-available.
Have a remote store on my router (sftp, nfs, whatever) to sync with.
Have another local store on my android phone.
Sync PC and phone by using the always-on router fileshare.

I've tried to set up a local git folder by using _git init --bare_ and that seems to work,
but gopass never puts any files there.
[The guide here](https://blog.codecentric.de/en/2019/02/manage-team-passwords-gopass/) is rather confusing to me.
Create a throwaway store, push it somewhere to pull it again and then sync to local.......what?
I can't get my head around getting this to work. I'm trying to switch from KeePass to get rid of all that mono stuff required for it;
but syncing my devices is a must-have.

Can anyone who has mastered the dark and ancient art of _git push-pull-rotate-do-a-barrel-roll-have-a-beer-or-go-insane_ please take me by the hand and guide me through this rather regular and usual use-case, as I am stuck here.....

In case anybody would like to point out, that I have repositories online on github and thus should be able to manage: yes, but I only use the webinterface, as my scripts are small and single-filed, so I never had to use git on its own.....

**Comment by drwulsen** [comment]
Now I've got something after reading through the issues, but it still does not work.....

I've created a new gopass store in ~/testrepo
within ~/testrepo i ran _git init --bare_ and _git config receive.denyCurrentBranch ignore_

Then I've reset my gopass configuration so it would be the "first start" (So I don't have to manually remove repos or stuff).
_gopass clone ~/testrepo_ did clone it into the root store, gopass said.

I've added a new entry, which is shown in _gopass list_
But even after a _gopass sync_ which tells me:`Sync starting ...
[<root>] 
   git pull and push ... OK (no changes)
   importing missing keys ... OK
   exporting missing keys ... nothing to do
   done
All done` Nothing within ~/testrepo has changed. How am I doing it wrong, exactly?

**Comment by AnomalRoil** [comment]
Welcome to Gopass, then.

Let's say your remote is on github and is for example :
`git@github.com:drwulsen/password-store.git`
(Make sure to generate a SSH key on each or your machine and register them
on your Github account, or to use a Yubikey for SSH, otherwise you can also
use the Http remote from Github, but it's less convenient)

To create a password store, you can follow Gopass wizard and then you must :
```
gopass config path
cd /to/the/gopass/password/store/path/withouttheprefix
git status <-- this should display something, but if it's says it's not a
git repository, then you'll need to run git init first
git remote add origin git@github.com:drwulsen/password-store.git
git push
```

Then make sure to follow git instructions (it will probably prompt you to
configure your username and email address for it to work as it should).
Once this is done, gopass should work as expected and sync with your remote
👍🏻

**Comment by drwulsen** [comment]
Dear AnomalRoil,

thank you, thank you, THANK YOU!
You pointed me to the perfect direction.
I figured, that yesterday I actually got it working a few times, but did not realize that :facepalm: 
What one obviously needs to know: A git remote is not a 1:1 reflection of your local repository.
It's not like rsync'ing from A to B.
Today I got it working and that's how I did it, with many thanks to AnomalRoil and [this post by @sinbad](https://github.com/git-lfs/git-lfs/issues/1114#issuecomment-204429045)

**The way to set it up**
- Initialize your local gopass store
(Well, it is a git repository, but I will reference it here as "store" for clarity)
_gopasswd init_ and follow the instructions to set up a local store
- Add your first entry for testing
_gopass new_ and follow the instructions
(For testing, create a website entry for **test.foo**)
- You can check your entry exists as a file in your stores directory structure
_gopasswd config path_ (Example: **/home/myself/.local/share/gopass/stores/root**)
_ls_ the displayed path of the local store, appending "websites"
(Example: **ls /home/myself/.local/share/gopass/stores/root/websites**)
You'll see a directory named **test.foo** exists.
- Create your "remote" repository
Either use a github repo, as suggested above, you can create it in the webinterface of github
Or create a local one: _git init --bare **/home/myself/online-test-repo**_
- Add your git repository as remote "origin" to your local store
(Meaning it will know how to push to and pull from there)
_gopasswd config path_ (Example: **/home/myself/.local/share/gopass/stores/root**)
_cd_ into the displayed path of the local store (Example: **cd /home/myself/.local/share/gopass/stores/root**)
_git status_ returns that it's on branch master and nothing to commit. Thus it's an initialized and valid git repository.
_git remote add origin **/home/myself/online-test-repo**
- Manually push to it the first time
_git push origin master_ (This is necessary to have store and repository in sync for the first time)
After that, a simple _gopass sync_ will be sufficient to push your changes to there (and of course pull changes from there)
**DONE**

**Testing / Verification**
- Create an empty git repository
_git init /home/myself/testdir && cd /home/myself/testdir_
_git pull /home/myself/online-test-repo master
_ls_ will show that directory "websites" is there.
_ls websites_ will prove that **test.foo** is also here.

**The thing I had to get my head around**
- The repository (local or github) is not an actual reflection of your storage.
[This little gem will be remembered for explaining that to me](https://github.com/git-lfs/git-lfs/issues/1114#issuecomment-334653822)
It stores files "commits" within its very own structure, which does not look anything like your storage.
To have your structure re-created, you have to **pull** from a repository,
this translates the github backend structure back into your directory structure and versions of files.
After getting my head around it, this makes sense so much, it's incredibly plain to see.
...and I could have saved some time in using an online github repository for testing.
The github webpage of course parses everything to display your directory structure.
So I could have easily seen after a sync, that my changes got pushed there.

Thanks @AnomalRoil for the help, the issue is solved and I hope my quick guide for the novice will help some others.

**Comment by drwulsen** [comment]
BTW, @gopassw - could you somehow include this in the docs please?
