### ISSUE TITLE
GoPass 1.10.1 can't  reconfigure with gopass-bridge v0.8.0

### ISSUE THREAD

**Issue by ook** [gopasspw/gopass#1631]
### Summary

After gopass upgrade to 1.10.1 (via homebrew) and `gopass-jsonapi configure`, chrome restart, can't get gopass-bridge working

### Steps To Reproduce
* install gopass before 1.10.1
* install and configure gopass-bridge for that version
* upgrade to gopass 1.10.1
* run `gopass-jsonapi configure`
* restart chrome

### Expected behavior
gopass-bridge v0.8.0 should be able to communicate with gopass 1.10.1

### Environment

- OS: Mac OS Catalina 10.15.7
- OS version: `Darwin ook-book.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`
- gopass Version: 1.10.1 (gopass-bridge chrome v0.8.0)
- Installation method: homebrew (gopass-bridge via chrome store)

### Additional context
Traces from my re configuration:
```
☁  ~  gopass-jsonapi --version
gopass-jsonapi version 1.10.1
☁  ~  gopass-jsonapi configure
For which browser do you want to install gopass native messaging? [brave,chrome,chromium,firefox,iridium,slimjet,vivaldi] [chrome]:
Install for all users? (might require sudo gopass) [y/N/q]:
In which path should gopass_wrapper.sh be installed? [/Users/thomas/.config/gopass]:
Native Messaging Setup Preview:
Wrapper Script (/Users/thomas/.config/gopass/gopass_wrapper.sh):
#!/bin/sh

if [ -f ~/.gpg-agent-info ] && [ -n "$(pgrep gpg-agent)" ]; then
	source ~/.gpg-agent-info
	export GPG_AGENT_INFO
else
	eval $(gpg-agent --daemon)
fi

export PATH="$PATH:/usr/local/bin" # required on MacOS/brew
export GPG_TTY="$(tty)"

/usr/local/bin/gopass-jsonapi listen

exit $?


Manifest File (/Users/thomas/Library/Application Support/Google/Chrome/NativeMessagingHosts/com.justwatch.gopass.json):
{
    "name": "com.justwatch.gopass",
    "description": "Gopass wrapper to search and return passwords",
    "path": "/Users/thomas/.config/gopass/gopass_wrapper.sh",
    "type": "stdio",
    "allowed_origins": [
        "chrome-extension://kkhfnlkhiapbiehimabddjbimfaijdhk/"
    ]
}

Install manifest and wrapper? [Y/n/q]:
☁  ~  gopass --version
gopass 1.10.1 go1.15 darwin amd64
☁  ~
```
And still:
<img width="302" alt="Donjons_et_Bananes_–_C_est_pas_du_Jeu_De_Rôle___si___" src="https://user-images.githubusercontent.com/559/97290488-e72b0400-1848-11eb-92b4-6ea223fce98b.png">

**Comment by AnomalRoil** [comment]
@martinhoefling  @Pharb Any ideas? I'm not using neither `jsonapi` nor `gopass-bridge` on my side, so I cannot help and it seems we have at least 3 users impacted.
