### ISSUE TITLE
Update documentation for gopass summon provider usage

### ISSUE THREAD

**Issue by ckolumbus** [gopasspw/gopass#1633]
The documentation for using `gopass` as `summon` provider is outdated. It describes the use of the `gopass` command as a provider. 

`gopass-summon-provider` has been implemented to avoid impact of the `gopass` console output on the `summon` interface.

This new command needs to be used in the description of https://github.com/gopasspw/gopass/blob/master/docs/summon-provider.md

see also #1627

**Comment by AnomalRoil** [comment]
closed by #1658
