### ISSUE TITLE
gopass inserts additional data when adding new secrets on Linux

### ISSUE THREAD

**Issue by tdemin** [gopasspw/gopass#1640]
This issue has been originally discussed as a [chezmoi](/twpayne/chezmoi) issue: twpayne/chezmoi#925, and the original issue might be worth reading for possible extra details.

When using gopass on Linux, gopass seems to insert additional data incompatible with `pass` when using `gopass insert <secretname>`:

```
~ > go/bin/gopass insert test1
Enter password for test1:
Retype password for test1:
Warning: Password is too short
~ > go/bin/gopass show test1
Password: test

~ > pass show test1
GOPASS-SECRET-1.0
Password: test

~ > go/bin/gopass show -o test1
test
~ > go/bin/gopass version
gopass 1.10.0-git+HEAD go1.15.2 linux amd64
<root>     - gpg 2.2.23 -   fs 0.1.0
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs, ondisk
~ > gopass version
gopass 1.10.1 (2020-09-13 00:16:24) go1.15.2 linux amd64
<root>     - gpg 2.2.23 -   fs 0.1.0
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs, ondisk
```

This is reproducible with both gopass built from commit `333a76a06b730c6ebb457fa2adb556a9b857834a` and the [Arch Linux build](https://github.com/archlinux/svntogit-community/blob/packages/gopass/trunk/PKGBUILD) of **v1.10.1** (for reference, I'm using pass **v1.7.3**). The problem is that this [doesn't reproduce on macOS](https://github.com/twpayne/chezmoi/issues/925#issuecomment-719921313) as tested by @twpayne.

The problem with that is this doesn't seem to be compatible with the original `pass` (`pass --help` doesn't list anything that works like `gopass show -o`), and as of now this affects the use of gopass in chezmoi, as chezmoi calls gopass as `gopass show`.

**Comment by AnomalRoil** [comment]
This is caused by the new Mime format that is not compatible with `pass`.
To retain `pass` compatibility, please set `mime` to false in the config: `gopass config mime false`.

We are studying ways to retain pass compatibility while having a nicer format such as Mime to have richer functionalities, but this is a WIP for now, I'm afraid.

The `mime` option was mistakenly enabled by default upon update, we are looking at ways to revert this in the next update.

**Comment by Markus-Be** [comment]
If I set the 'mime' to false, all changes made with the 'mime' enabled are not undone.

Is it possible to search and undo this if I have detected it too late and don't know which entry is affected by this change?

**Comment by AnomalRoil** [comment]
Yes, you can use the `gopass grep GOPASS-SECRET-1.0` after having disabled
the mime config.
(Careful if using a hardware token with touch enabled: it will decrypt all
your secrets to do the grep, so you might want to disable touch to decrypt
first)

**Comment by Kloenk** [comment]
I guess I should change away from gopass then, if it randomly decides to fuck up my password store.

**Comment by RayOei** [comment]
Setting the mime to false also solved an issue with **otpauth** being mangled while saving... (apart from other seemingly weird error messages when saving -  sorry didn't save those).
On MacOS with v1.10.1

But ultimately I can't trust gopass not destroying my secrets at this time 👎

**Comment by AnomalRoil** [comment]
Well, our goal is really to try and not change the secrets, and only parse them during output, but then we wanted to have more flexibility and tried adding the Mime format which defaulted to `true` by mistake and now we are struggling with the aftermath.

We are working on solving these issues, but time is scarce.

**Comment by AnomalRoil** [comment]
Related to #1650 #1600 #1602 #1616

**Comment by AnomalRoil** [comment]
Solved in #1665

**Comment by Radtoo** [comment]
> We are studying ways to retain pass compatibility while having a nicer format such as Mime to have richer functionalities, but this is a WIP for now, I'm afraid.

I _really_ like having an explicit specification for how the secrets are formatted. But why not make it the first YAML line and add a pass compatible mode (enabled by default) where the password can be present on the first line? Or some such.

```
<password optionally on first line if compatible mode is enabled>
---
GOPASS-SECRET-1.0:
- Login: x
- Password: y # if not in compatible mode
- Someothertag: y
```

**Comment by AnomalRoil** [comment]
We ended up removing the Mime type altogether in 1.11.0 and we now have Key-Values and YAML format only.

The YAML format does not (yet?) support multiple YAML document in a stream.

**Comment by Radtoo** [comment]
> We ended up removing the Mime type altogether in 1.11.0 and we now have Key-Values and YAML format only.
I'm behind with my distro's gopass version and in this discussion, apparently. I'll update.
 
> The YAML format does not (yet?) support multiple YAML document in a stream. Please open an issue to discuss formatting if our current format detailed here does not satisfy you:
> https://github.com/gopasspw/gopass/blob/master/docs/commands/show.md#parsing-and-secrets
I believe this is fine. If there are no incompatible formats, there is probably currently no need for supporting them in other YAML documents in a stream. It would just have been my suggestion if you had held on to the incompatible MIME versioned format.

For other uses with multiple documents, "gopass show -n" is likely currently enough - it shows the other documents. Thanks!
