### ISSUE TITLE
Test failing on Alpine Linux 32bit

### ISSUE THREAD

**Issue by Bridouz** [gopasspw/gopass#1645]
### Summary
Trying to upgrade `gopass` version for Alpine Linux
Built for 64bit but 32bit fails on tests (Audit)

```
runtime error: invalid memory address or nil pointer dereference
```
Full builder logs here : 
  - armv7 : https://gitlab.alpinelinux.org/Bridouz/aports/-/jobs/240553
  - x86 : https://gitlab.alpinelinux.org/Bridouz/aports/-/jobs/240549

### 

### Expected behavior
All tests should pass

### Environment
Alpine Linux (Busybox - Musl libc)

**Comment by AnomalRoil** [comment]
It seems we cannot access the log files, any chance you could upload them here?
