### ISSUE TITLE
Problem with gopass-git-credentials configuration

### ISSUE THREAD

**Issue by antonmry** [gopasspw/gopass#1649]
### Summary

The command as stated in the help doesn't work well:

`git config --global credential.helper "!gopass-git-credentials $@" `

It happens after upgrade Fedora (it may be a change in the git command or a bug in git?), it was working well before

### Steps To Reproduce

I execute:

`git config --global credential.helper "!gopass-git-credentials $@" `

But in the .gitconfig the following is created:

> [credential]
>	helper = "git-credentials "

### Expected behavior

It should be:

> [credential]
>	helper = "!gopass-git-credentials $@ "

### Environment

- OS: Fedora 32
- OS version: Linux gali9 5.7.14-200.fc32.x86_64 #1 SMP Fri Aug 7 23:16:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- gopass Version: gopass 1.10.1 (2020-09-19 00:00:00) go1.14.7 linux amd64
- Installation method: dnf

### Additional context

I don't think this is a gopass problem but it may help others using it or even change the help in gopass-git-credentials if that command doesn't work anymore as expected

**Comment by dominikschulz** [comment]
Might be fixed by #1670 but I'm not sure.
