### ISSUE TITLE
Setting `mime:false` in config blanks out `path`, ignores `$PASSWORD_STORE_DIR`, changes other defaults

### ISSUE THREAD

**Issue by OJFord** [gopasspw/gopass#1654]
### Summary

I don't want to define the path in my `config.yml`, so I only added `mime: false` there. (Need that because of #1600).

Afterwards, any `gopass show` instead asked me to run an 'onboarding wizard'. It seems this is because running `gopass config` now shows it has picked up `mime: false` but reset everything else to different defaults than it had chosen when I had no `config.yml`.

### Steps To Reproduce

1. Use pass, have `$PASSWORD_STORE_DIR` set, etc.
1. Install gopass
1. `test "$(gopass config path)" = "path: $PASSWORD_STORE_DIR"` (0)
1. echo 'mime: false' > "$XDG_CONFIG_HOME/gopass/config.yml"
1. `test "$(gopass config path)" = "path: $PASSWORD_STORE_DIR"` (0; it's `""`; other settings also changed)

### Expected behavior
The only config that changes is the `mime: false` we changed in creating `config.yml`.

### Environment

- OS: Arch Linux
- OS version: 5.9.8-arch1-1 
- gopass Version: [gopass version] 
```
It seems you are new to gopass. Do you want to run the onboarding wizard? [Y/n/q]: q
gopass 1.10.1 (2020-09-13 00:16:24) go1.15.2 linux amd64
<root>     -     <none> - git 2.29.2
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs, ondisk
```
- Installation method: Arch package `community/gopass`

### Additional context

`gopass config` without `mime: false` in `config.yml` (before creating it, or after deleting it):
```
autoclip: false
autoimport: true
cliptimeout: 45
exportkeys: true
mime: true
nocolor: false
nopager: false
notifications: true
path: [value of $PASSWORD_STORE_DIR]
safecontent: false
```

`gopass config` with `mime: false` in `config.yml`:
```
autoclip: false
autoimport: false
cliptimeout: 0
exportkeys: true
mime: false
nocolor: false
nopager: false
notifications: false
path:
safecontent: false
```

`autoimport`, `cliptimeout`, `notifications`, and `path` were all changed despite not being specified. Deleting `config.yml` restores them to 'previous defaults'.

Presumably a problem for / would be caught by #1622.

**Comment by AnomalRoil** [comment]
If instead of manually changing the config you set the mime option to false using:
`gopass config mime false`, does it keep the default values? Because it should, and it should write the default value to its config file as well.

**Comment by OJFord** [comment]
Yes, but it writes the entire contents to the config file; as I said I don't want the path in there.

**Comment by AnomalRoil** [comment]
@dominikschulz Do we want to support partial config files?
That is, setting the options that are in the config file and using the default for the rest? It seems currently if the config file is partial the non-specified options will default to their default Go type value.

**Comment by OJFord** [comment]
It would be a problem for newly added config options anyway, wouldn't it?

i.e. if I let `gopass config mime false` write the whole file today, and tomorrow you add a `log_level` option (say), that's not going to have a value in the config file so would have to be handled; it'd seem odd to me if some config entries were required to be specified and others not.

**Comment by AnomalRoil** [comment]
So, this is not really about the `mime` option in the end, it's more about being able to set only one config item and still having the correct default values for the rest.

**Comment by OJFord** [comment]
Sure, I suppose I just needed a concrete example and that was the one that came up for me. But yes, the essence of it is that config options have different defaults when some *other* option is set in config, versus when it isn't.

(I didn't actually test with any others, but yes I assume it happens with others besides `mime`.)

**Comment by dominikschulz** [comment]
We do not support partial config files. And I wonder if that's possible while still remaining backwards compatible.
If we add or remove settings this should be taken care of by our config handling.
But if you produce a partial config manually we won't support that.

**Comment by OJFord** [comment]
Then I suppose the request is for some way of specifying 'use the environment variable' in the config file for path.

Currently it's not possible to set any config option and continue to respect $PASSWORE_STORE_DIR.

**Comment by dominikschulz** [comment]
Yes, makes sense. Maybe we should change the config handling. See the linked issue.

**Comment by OJFord** [comment]
Yup I did see that, it was AR's comment there:
> I guess the issue [here] is probably that we do not correctly handle an empty path in the config.

that prompted me to clarify Yes that is the key thing that bothered me, rather than 'handle partial configs' in a generic sense.

Cheers. 🙂

**Comment by dominikschulz** [comment]
Thanks for the clarification. Now that makes more sense. Let's keep this issue open then to track that specific request.
