### ISSUE TITLE
Editing an existing or adding a new passphrase does not add key info

### ISSUE THREAD

**Issue by rbott** [gopasspw/gopass#1663]
### Summary
When I add a new password to my main password store (which only uses one single GPG ID) or edit an existing one with gopass 1.10.1 on Ubuntu 20.04 I cannot read it afterwards using the Android Password Store app. The error message is in German but tells me that no known private keys were found in the datastream. However, I can still decrypt passwords stored with earlier versions of gopass.

I then used `file` on the .gpg files and found this:
```
$ file .password-store/recently-edited-password.gpg
.password-store/recently-edited-password.gpg: PGP RSA encrypted session key - keyid: 0 0 RSA (Encrypt or Sign) 2048b .

$ file .password-store/slightly-older-password.gpg
.password-store/slightly-older-password.gpg: PGP RSA encrypted session key - keyid: AABBCCDD 12345678 RSA (Encrypt or Sign) 2048b .
```

I know this might be related to the Android Password Store app, but hence the files seem to be generated differently I'd thought I should first check with gopass here.

### Environment
- OS: Ubuntu 20.04
- gopass Version 1.10.1 (official .deb release from Github)
- gpg Version 2.2.19
- Android: 10 / Android Password Store: 1.3.3 / OpenKeychain: 5.5

**Comment by dominikschulz** [comment]
We have made some changes to the secret format which might confuse other password store implementations (and we're looking how to safely roll back this change).

But these are plaintext only changes. They should have no effect on the crypto envelope, so this might actually be a different issue.

**Comment by AnomalRoil** [comment]
Did you set `mime` to false in the config?

**Comment by rbott** [comment]
@AnomalRoil yes, it is set to false. But I have narrowed it down a bit. A while ago, I followed the [DrDuh guide to the YubiKey](https://github.com/drduh/YubiKey-Guide) and used the example `gpg.conf` from the README. This seems to trigger the current behaviour but I have not yet checked which line it is exactly.

I have two different gopass mounts and two different GPG keys. One key is used with mount A and the YubiKey and the other key is used with mount B without a yubikey. The `default-key` listed in `gpg.conf` is the one used with the YubiKey.

However, the problem only occurs on mount B. This is not yet verfied but maybe the `default-key` setting confuses gopass and/or gnupg and creates a file without GPG key information. Which in turn does not matter to gopass/gpg, but to the implementation used by the Android Password Store app.

On a second computer (which only knows about mount B and does not have a specific `gpg.conf`) I can create regular entries which can be decrypted by the Android app just fine.

**Comment by AnomalRoil** [comment]
Are you sure you don't have the `hidden-recipient` (or `-R` flag) option set on your gpg in one case?

If you take the `.gpg` file generated by gopass on machine 1 on a secret in mount A vs a secret in mount B and do a `list-packet` on them, what does it say?

**Comment by AnomalRoil** [comment]
Ah never mind, found it:

https://github.com/drduh/config/blob/master/gpg.conf#L44

**Comment by rbott** [comment]
Oh wow, thanks. Another great example for "don't copy and paste from the internet without checking" :-(
