### ISSUE TITLE
`gopass show -c` process never stops

### ISSUE THREAD

**Issue by freijon** [gopasspw/gopass#1666]
### Summary
I tried running the command described in [setup.md](https://github.com/gopasspw/gopass/blob/master/docs/setup.md#dmenu--rofi-support): `gopass ls --flat | dmenu | xargs --no-run-if-empty gopass show -c`. This apparently launches two gopass commands which run forever.

### Steps To Reproduce
- Execute `gopass ls --flat | dmenu | xargs --no-run-if-empty gopass show -c`
- It will show a message that the clipboard will be cleared after 45 seconds. But after 45 seconds the process keeps running and I have to manually kill it with Ctrl-C.
- Check with `ps ax | grep gopass` that there are still two gopass processes running: `gopass show -c <pass>` and `gopass unclip --timeout 45`

### Expected behavior
45 seconds after the command has been executed all gopass processes should stop.

### Environment
- **OS:** Gentoo Linux
- **OS version:** Linux gentoo-y700 5.10.1-gentoo
- **gopass Version:** gopass 1.10.1 (2020-12-16 05:10:34) go1.15.5 linux amd64
- **Installation method:** app-admin/gopass ebuild

**Comment by AnomalRoil** [comment]
What happens if you run `gopass show -c nameofanentry`  ?
Does it also keep running ?

**Comment by freijon** [comment]
The command starts and keeps running forever. However, there is no message about 45 seconds.

**Comment by dominikschulz** [comment]
@fm2mwvtsp8vqtuy5 Thanks for the detailed explanation. Unfortunately I was able to reproduce. At least on my system (Linux) [killPrecedessors](https://github.com/gopasspw/gopass/blob/master/pkg/clipboard/kill_ps.go#L15) does seem to take care of any lingering processes.

But you are right that we're not using Process.Kill according to documentation, so we'll fix that :+1:

**Comment by fm2mwvtsp8vqtuy5** [comment]
@dominikschulz: I'm glad I could help you and I'm happy to see that you fixed it so quick.
