### ISSUE TITLE
GOPASS_EXTERNAL_PWGEN env var not using external program

### ISSUE THREAD

**Issue by casonadams** [gopasspw/gopass#1669]
### Summary
It appears that GOPASS_EXTERNAL_PWGEN env var isn't doing what I expect it to
and that is to use the external password generator for password generation

### Steps To Reproduce
External password generator: [passg](https://gitlab.com/casonadams/passg)

Test command:
```
GOPASS_EXTERNAL_PWGEN="passg -p" gopass generate test.org/me
```

### Expected behavior
Expect external pwgen to be used

### Environment
- OS: macOS 11
- OS version: Darwin m2.lan 20.1.0 Darwin Kernel Version 20.1.0: Sat Oct 31 00:07:11 PDT 2020; root:xnu-7195.50.7~2/RELEASE_X86_64 x86_64
- gopass Version: gopass 1.10.1 go1.15.5 darwin amd64
- Installation method: brew

**Comment by AnomalRoil** [comment]
You need to use `gopass generate -g external test.org/me` to select the external generator as per the doc: 
https://github.com/gopasspw/gopass/blob/master/docs/commands/generate.md#password-generators

So:
```
GOPASS_EXTERNAL_PWGEN="passg -p" gopass generate -g external test.org/me
```
should work. Can you try it?

**Comment by casonadams** [comment]
Sweet it is working, but I had to change the command to be this.

```
GOPASS_EXTERNAL_PWGEN="passg -p -l" gopass generate -g external test.org/me
```

`passg` didn't like the length without defining `-l`

Thanks!

**Comment by dominikschulz** [comment]
This is actually one of the features I'd consider dropping.
Does using an external password generator have a real value for you? Or is it more like just for fun?

**Comment by AnomalRoil** [comment]
Plus I guess we are already somewhat supporting it through pipes into `gopass insert`. 
One can do an alias to have it handy:
`alias gopassgen="passg -p -l 20 | gopass insert"` 

and then `gopassgen nameofentry` works

**Comment by casonadams** [comment]
Yeah that is a sound solution.  It is nice to use a custom password generator `passg` because it generates easy to read/type strong passwords.  Including passing in a required password length to meet silly password checker guidelines.
