### ISSUE TITLE
gopass *throws away my input*

### ISSUE THREAD

**Issue by colemickens** [gopasspw/gopass#1674]
### Summary

I don't even know what the heck "gopass native password" whatever means, but it is repeatedly resulting in gopass **discarding the input I gave it for my password**.

And has now resulted in me having to recover the password to an account I just got done creating, because, again, **gopass discarded my input**.

I `gopass edit thing` and try to make an entry like I always have. Clear the file, add my password on the first line. But now, I get this afterward:

```
❯ gopass edit thing
Found exact match in 'misc/azdev'
ERROR: Can not parse Gopass native Secret. Retry? [Y/n/q]: n
2020/12/31 18:46:03 malformed secret

```

and everything I had typed was thrown out. I'm just going to find a different tool..

```
gopass 1.10.1+v1.10.1 (v1.10.1) go1.15.6 linux amd64
<root>     - gpg 2.2.24 - git 2.29.2
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs, ondisk
```

**Comment by AnomalRoil** [comment]
This is already fixed on git master, a patch release 1.10.2 is planned soon
that will solve the problem.

We already track this in other issue.

You can "go get" the git master to avoid losing your input and to avoid the
native type you should disable the mime type with:
gopass config mime false

**Comment by colemickens** [comment]
@AnomalRoil thank you for the detailed answer.

**Comment by AnomalRoil** [comment]
This should be fully fixed in our latest release:
https://github.com/gopasspw/gopass/releases/tag/v1.11.0
