### ISSUE TITLE
Go get does not work

### ISSUE THREAD

**Issue by tomposmiko** [gopasspw/gopass#1686]
### Summary

Package cannot be installed on a standard linux system (eg. stock Ubuntu)

### Steps To Reproduce

```
$ go get -v github.com/gopasspw/gopass
github.com/minio/minio-go (download)
cannot find package "github.com/minio/minio-go/v6" in any of:
	/usr/lib/go-1.15/src/github.com/minio/minio-go/v6 (from $GOROOT)
	/home/tompos/go/src/github.com/minio/minio-go/v6 (from $GOPATH)
```
### Environment

- OS: Ubuntu 20.10
- OS version: 
```Linux RF-PC-BUD-036 5.8.0-33-generic #36-Ubuntu SMP Wed Dec 9 09:14:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux```
- gopass Version: latest
- Installation method: gopass repo

**Comment by dominikschulz** [comment]
`gopass` is using Go modules.
You need to set `GO111MODULES=on`, e.g. `GO111MODULE=on go get -v github.com/gopasspw/gopass`.

**Comment by tomposmiko** [comment]
Thanks, that works fine.
