### ISSUE TITLE
Template salted hash function do not allow to specify our own salt

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1687]
### Summary
When using the templating function we can produce SSHA256 or SSHA512 sums of the passwords, but this is only done with random salt at the moment, it is not possible to use our own salt.

### Steps To Reproduce

Use `gopass template edit test` and 
```
Password: {{ .Content }}
SSHA256: {{ .Content | ssha256 }}
```

But giving more than one argument, e.g. `  {{ .Content "mysalt" | ssha256 }}` will fail with:
```
:2:12: executing "Password: {{.Content }}\nSSHA256: {{ .Content \"mysalt\" | ssha256 }}\n" at <.Content>: Content has arguments but cannot be invoked as function
```

### Expected behavior
IMO, it should be possible to choose our salt shall we want to do so.

**Comment by dominikschulz** [comment]
Interesting proposal. I've never used it like that.

This feature comes from a Mailserver setup I've worked on before bcrypt was available. This helper allowed me to use templates to generate SQL queries to create new users. Not very elegant, but effective. The Mailserver would then extract the salt prefix from the hash and use that.

Do you have a concrete use case for a user supplied salt?

**Comment by dominikschulz** [comment]
@AnomalRoil The libaries we use to generate the salted hashes do not support a user supplied salt.

So unless you can provide a good reason for this FR I'm going to close it as wontfix.
