### ISSUE TITLE
Minio needs to be updated to v7

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1691]
We are currently relying on Minio v6, it'd be best to update to the latest v7 released in July 2020 that underwent a full API refactor if we want to be future proof.

Or maybe drop it to avoid the added complexity?
Who is using S3 buckets and these remote stuff on Gopass instead of the classical git workflow?

**Comment by dominikschulz** [comment]
Good find. I guess we can remove that. I'll look into that.
