### ISSUE TITLE
Many items in store ruins listing

### ISSUE THREAD

**Issue by tomposmiko** [gopasspw/gopass#1696]
### Summary

If there are more than 61 items in a store, the `gopass ls` command turns to ugly.
It produces me this output:

```
�<94><9C>�<94><80>�<94><80> 001
�<94><9C>�<94><80>�<94><80> 002
�<94><9C>�<94><80>�<94><80> 003
�<94><9C>�<94><80>�<94><80> 004
�<94><9C>�<94><80>�<94><80> 005
�<94><9C>�<94><80>�<94><80> 006
�<94><9C>�<94><80>�<94><80> 007
�<94><9C>�<94><80>�<94><80> 008
�<94><9C>�<94><80>�<94><80> 009
�<94><9C>�<94><80>�<94><80> 010
�<94><9C>�<94><80>�<94><80> 011
�<94><9C>�<94><80>�<94><80> 012
�<94><9C>�<94><80>�<94><80> 013
�<94><9C>�<94><80>�<94><80> 014
�<94><9C>�<94><80>�<94><80> 015
�<94><9C>�<94><80>�<94><80> 016
�<94><9C>�<94><80>�<94><80> 017
�<94><9C>�<94><80>�<94><80> 018
�<94><9C>�<94><80>�<94><80> 019
�<94><9C>�<94><80>�<94><80> 020
�<94><9C>�<94><80>�<94><80> 021
�<94><9C>�<94><80>�<94><80> 022
�<94><9C>�<94><80>�<94><80> 023
�<94><9C>�<94><80>�<94><80> 024
�<94><9C>�<94><80>�<94><80> 025
�<94><9C>�<94><80>�<94><80> 026
�<94><9C>�<94><80>�<94><80> 027
�<94><9C>�<94><80>�<94><80> 028
�<94><9C>�<94><80>�<94><80> 029
�<94><9C>�<94><80>�<94><80> 030
�<94><9C>�<94><80>�<94><80> 031
�<94><9C>�<94><80>�<94><80> 032
�<94><9C>�<94><80>�<94><80> 033
�<94><9C>�<94><80>�<94><80> 034
�<94><9C>�<94><80>�<94><80> 035
�<94><9C>�<94><80>�<94><80> 036
�<94><9C>�<94><80>�<94><80> 037
�<94><9C>�<94><80>�<94><80> 038
�<94><9C>�<94><80>�<94><80> 039
�<94><9C>�<94><80>�<94><80> 040
�<94><9C>�<94><80>�<94><80> 041
�<94><9C>�<94><80>�<94><80> 042
�<94><9C>�<94><80>�<94><80> 043
�<94><9C>�<94><80>�<94><80> 044
�<94><9C>�<94><80>�<94><80> 045
�<94><9C>�<94><80>�<94><80> 046
�<94><9C>�<94><80>�<94><80> 047
�<94><9C>�<94><80>�<94><80> 048
�<94><9C>�<94><80>�<94><80> 049
�<94><9C>�<94><80>�<94><80> 050
�<94><9C>�<94><80>�<94><80> 051
�<94><9C>�<94><80>�<94><80> 052
�<94><9C>�<94><80>�<94><80> 053
�<94><9C>�<94><80>�<94><80> 054
�<94><9C>�<94><80>�<94><80> 055
�<94><9C>�<94><80>�<94><80> 056
�<94><9C>�<94><80>�<94><80> 057
�<94><9C>�<94><80>�<94><80> 058
�<94><9C>�<94><80>�<94><80> 059
�<94><9C>�<94><80>�<94><80> 060
```
Items are called as `{01..62}`.

### Steps To Reproduce

Add at least 62 items to a store and list it.

### Expected behavior

Nice tree view look.

### Environment

- OS:
Distributor ID:	Ubuntu
Description:	Ubuntu Hirsute Hippo (development branch)
Release:	21.04
Codename:	hirsute
- OS version:
Linux RF-PC-BUD-036 5.8.0-33-generic #36-Ubuntu SMP Wed Dec 9 09:14:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- gopass Version: 1.10.1
- Installation method: dpkg -i ...
-

**Comment by dominikschulz** [comment]
Sorry, can not reproduce locally.

```
./gopass ls foo/
foo/
├── 000
├── 1
├── 10
├── 100
├── 11
├── 12
├── 13
├── 14
├── 15
├── 16
├── 17
├── 18
├── 19
├── 2
├── 20
├── 21
├── 22
├── 23
├── 24
├── 25
├── 26
├── 27
├── 28
├── 29
├── 3
├── 30
├── 31
├── 32
├── 33
├── 34
├── 35
├── 36
├── 37
├── 38
├── 39
├── 4
├── 40
├── 41
├── 42
├── 43
├── 44
├── 45
├── 46
├── 47
├── 48
├── 49
├── 5
├── 50
├── 51
├── 52
├── 53
├── 54
├── 55
├── 56
├── 57
├── 58
├── 59
├── 6
├── 60
├── 61
├── 62
├── 63
├── 64
├── 65
├── 66
├── 67
├── 68
├── 69
```

**Comment by tomposmiko** [comment]
What's your OS env?
What does `/` do at the end of the store? If I add `/`, it does not work:

```
$ gopass ls v/

Error: Entry 'v/' not found
```

gopass mounts output:

```
└── v (/home/tompos/.local/share/gopass/stores/v)
```

**Comment by AnomalRoil** [comment]
I just tested on both Linux (Ubuntu 20.04, gnome terminal, zsh) and Windows, and the listing works on my side on a substore with 65 items as well as on a simple folder with 65 entries.

What are you using as:
- terminal 
- shell
- terminal multiplexer if any

If you have go installed, you could try uninstalling gopass and installing it using `go get` to be on Master tip instead, because we've had a lot of changes in the last 3 months and are a few days short of releasing a new minor release.

**Comment by tomposmiko** [comment]
Sorry, I didn't notice, there was an answer to my comment.

Anyways, this was interesting.
I went to my terminal and was able to reproduce it. Checked with the version installed by 'go get' and got the same.
I use mate-terminal normally, so started gnome-terminal and voila, it provided to nice look, than switched back to mate-terminal and no I cannot reproduce it.
WTF!?

Still testing and looking at it. Will get back if anything useful come up.

**Comment by tomposmiko** [comment]
I think, I nailed it.
The problem wasn't really the number of the items, but it made the terminal scrolling and using less.
My `LESSCHARSET` was set to `latin1`. After changing it to `utf8` the problem seems to be gone.
I close this issue for now and reopen later if needed (hope not).

Thanks a bunch! This tools looks so impressive so far and your support too!
