### ISSUE TITLE
Unable to remove GPG key not in keystore

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1701]
### Summary
When using `gopass recipients rm` to remove an old key, if that key is not in GPG keystore, then it fails to remove it and one has to go and edit the .gpg-id file of their store themself.

### Steps To Reproduce
```
gpg --gen-key
gopass recipients add --store zzz testou
gpg --delete-secret-keys testou
gpg --delete-keys testou
gopass recipients rm --store zzz
```
and select the "empty" recipients in the list displayed by gopass.

This will fail with:
`Warning: Failed to list public key`
`|gpg: error reading key: No public key`
`Error: no key removed`

### Expected behavior
The recipients is removed and the entry re-encrypted with the remaining set of recipients

**Comment by dominikschulz** [comment]
You can use `--force` to skip that check.
