### ISSUE TITLE
Move to Go Git

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1704]
### Summary
It has been previously discussed in #1365 and other issues that we would prefer to not have dependencies on external binaries.
Git is currently such a dependency.

We should probably move away from it by relying on https://github.com/go-git/go-git

**Comment by dominikschulz** [comment]
Warning: This is only possible once there is a green checkmark next to the word "merge" in https://github.com/go-git/go-git/blob/master/COMPATIBILITY.md#supported-capabilities

**Comment by dominikschulz** [comment]
Also we need to ensure that we'd keep supporting [gitremote-helpers](https://mirrors.edge.kernel.org/pub/software/scm/git/docs/gitremote-helpers.html).

**Comment by AnomalRoil** [comment]
That's effectively a big blocker then since I couldn't find an open issue about it.

https://github.com/src-d/go-git/issues/745 used to discuss it before go-git was moved to its new repo, but it seems it wasn't moved to the new repo yet (https://github.com/go-git/go-git/issues/9 is still open)

**Comment by dominikschulz** [comment]
Just checking, go-git still doesn't have merge support. Seems to be either tricky and or boring so nobody wants to fix it :(

**Comment by dominikschulz** [comment]
As long as go-git doesn't have merge support this is not an option. Closing this for the time being since there has been zero movement on that feature since I first looked at it.
