### ISSUE TITLE
Typo in release notes of 1.11?

### ISSUE THREAD

**Issue by thomas-mc-work** [gopasspw/gopass#1705]
### Summary

In the leading paragraph [of the release notes](https://github.com/gopasspw/gopass/releases/tag/v1.11.0) I found:

> … and realized that comparability is more important than we first
thought …

After that you're referring to __compatibility__. I think that's the one that should be here too, isn't it?

**Comment by dominikschulz** [comment]
Yes, indeed. What a lovely typo. Thanks :)

**Comment by thomas-mc-work** [comment]
Now it's _compatability_ instead of compatibility 😏

**Comment by dominikschulz** [comment]
Lol. I think we have these, and others, now covered :)
