### ISSUE TITLE
Invalid exit condition in AskForPass

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1718]
## Current behaviour
We currently return correctly is someone enters the empty password and then enters a valid password, and we return the empty password in that case:
https://github.com/gopasspw/gopass/blob/774eb1d1a9f43ede92b6b6eaca6b28059ef99d64/pkg/termio/ask.go#L175-L177

## Expected behaviour
We should not accept the empty password unless it was entered twice.

**Comment by dominikschulz** [comment]
Yes, this looks like a bug. Good find, thanks.
