### ISSUE TITLE
Cannot remove uninitialised mount

### ISSUE THREAD

**Issue by warden** [gopasspw/gopass#1746]
When you have the config below (my + root) but you delete the "my" store manually, you are stuck when trying to do `gopass mounts rm my` because it complains `my` is uninitialised.
workaround:
```
gopass init --store my --path /Users/warden/.local/share/gopass/stores/my
gopass mounts unmount my
rm -rf /Users/username/.local/share/gopass/stores/my
```

```
$ gopass config
autoclip: false
autoimport: true
cliptimeout: 45
exportkeys: true
nocolor: false
nopager: false
notifications: true
parsing: true
path: /Users/warden/.local/share/gopass/stores/root
safecontent: false
mount 'my' => '/Users/warden/.local/share/gopass/stores/my'

$ gopass version
gopass 1.11.0 go1.15.6 darwin amd64
<root>     - gpg 2.2.27 - git 2.24.0
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs, ondisk

```

**Comment by dominikschulz** [comment]
My workaround would be to edit the config manually. But you're right: this should be fixed.

**Comment by risturiz** [comment]
Hi, what about: 

`gopass init --store --hola`

`mount '--hola' => '/home/pelox/.local/share/gopass/stores/--hola'`
```
gopass mounts remove --hola
Incorrect Usage: flag provided but not defined: -hola
```
This commit is related?
Thanks.

**Comment by dominikschulz** [comment]
I don't think we explicitly want to support stores prefixed with dashes that make them look like flags, but if you properly escape it, this should work.

**Comment by pmoros** [comment]
`gopass mounts remove my_mount` did the trick removing that initialized mount! It trows an error, but still deletes the mount.
