### ISSUE TITLE
Searching path for `gpg` does not respect gnupg/gnupg2 side-by-side installation

### ISSUE THREAD

**Issue by ahesford** [gopasspw/gopass#1757]
### Summary

Many Linux distributions install GnuPG 2 as `/usr/bin/gpg`, but this is not guaranteed. Some offer legacy GnuPG 1 as `gpg` and install v2 as `gpg2`. The GnuPG 2 configure script even provides a flag, `--enable-gpg-is-gpg2`, to accommodate this use case.

Because I suspect most people would prefer defaulting to GnuPG2 when it is available, relying on a path search for `gpg` produces unexpected behavior when distributions install both versions side by side. Regardless of a preference for v1 or v2, the behavior will be unexpected if a user installs only v2 as `gpg2` and `gopass` is unable to find the executable it needs.

The right way to discover the path to GnuPG 2 is to query its `gpgconf` utility, which provides easily parsable output that provides the paths to components of the installation:
```
% gpgconf
gpg:OpenPGP:/usr/bin/gpg2
gpg-agent:Private Keys:/usr/bin/gpg-agent
scdaemon:Smartcards:/usr/libexec/scdaemon
gpgsm:S/MIME:/usr/bin/gpgsm
dirmngr:Network:/usr/bin/dirmngr
pinentry:Passphrase Entry:/usr/bin/pinentry
```

### Steps To Reproduce
Option 1:
1. Install only GnuPG 2 on a distribution that calls its main executable `gpg2`.

Option 2:
1. Install GnuPG 1 *and* 2 on the same distribution.

### Expected behavior
When only GnuPG 2 is available and is called `gpg2`, `gopass` should find the executable. When both v1 and v2 are available, `gopass` should probably prefer v2 unless the user explicitly overrides the preference.

### Environment
Void Linux is one such distribution that has a GnuPG 1 executable at `/usr/bin/gpg` and a GnuPG 2 executable at `/usr/bin/gpg2`.

Any version of `gopass` that includes commit https://github.com/gopasspw/gopass/commit/004eaa4a4c32fe6468404210677f06e9e30e8047 will display the unexpected behavior. I suspect older versions will also show unexpected behavior.

### Recommendations
The process for discovering GnuPG should probably go as follows:
1. If `gpgconf` exists in the path:
    a. Invoke `gpgconf`, capture output
    b. Parse the path to `gpg` as the third field in the record whose first field is `gpg`.
2. Otherwise, use current behavior of looking for `gpg` in the path.

**Comment by dominikschulz** [comment]
Your suggested fix sounds reasonable. Thank you. I'll give it a try.

**Comment by ahesford** [comment]
Thanks, your fix looks like the right approach.
