### ISSUE TITLE
Suggestion / request: make apt repository with *.deb releases.

### ISSUE THREAD

**Issue by jaceq** [gopasspw/gopass#1760]
### Summary
At the moment in debian / ubuntu it's quite a manual process to install gopass. It would be great to have an APT repo we could use on those distros.
Easiest way seems to be using github itself as APT repo as per this example: https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html (but any other APT repo would be ok.)

**Comment by dominikschulz** [comment]
Offering an apt repository is unfortunately much more annoying than it should be.
We did use bintray before but that totally didn't work for us.

You're example looks interesting, but we'd need to include that - or some other approach - into our release process (which is using GitHub Actions and goreleaser). Only if we can do that I'd be willing to offer an apt repo.

**Comment by geigi** [comment]
You could try https://apt-sourc.es website by @rbott. It automatically generates an apt repository from GitHub releases as long as the releases contain a .deb file (which is the case for gopass).
I'm using this myself and it works like a charm :)

**Comment by DEvil0000** [comment]
So someone must trust a third party (a single person) with the gopass binary not beeing modified and not sending your passwords somewhere after a future update?
  
  
   
  
  
   I do not see a repo with the software for that on his github acount.
  
  
   Don't get me wrong here, I like the project. I would use it for non critical packages on non critical systems or I would host it myself for the packages I need to ensure I always get what I ask for. Trusting someone else to host such a critical peace of software however is not exactly what I am looking for.
  
  
   
    Julian Geywitz <notifications@github.com> hat am 17.02.2021 08:51 geschrieben:
   
   
    
   
   
    
   
   
   You could try https://apt-sourc.es website by @rbott. It automatically generates an apt repository from GitHub releases as long as the releases contain a .deb file (which is the case for gopass).I'm using this myself and it works like a charm :)

**Comment by rbott** [comment]
> So someone must trust a third party (a single person) with the gopass binary not beeing modified and not sending your passwords somewhere after a future update? I do not see a repo with the software for that on his github acount. Don't get me wrong here, I like the project. I would use it for non critical packages on non critical systems or I would host it myself for the packages I need to ensure I always get what I ask for. Trusting someone else to host such a critical peace of software however is not exactly what I am looking for.

Yes, you are absolutely right @DEvil0000. Actually, the repository lives over at gitlab.com/rbott right now but is not yet public. I'll try to do some cleanup, add license, readme and development infos and release it either on Github or Gitlab (and let you guys know).
However, that of course does not solve the trust problem as releasing the code does not mean I also run the very same code :-)

**Comment by dominikschulz** [comment]
That project does look nice, thanks @rbott!

But the trust issue is ... an issue.
Not only with this project, but actually with any kind of binary being offered.

Again: I'd love to offer a deb repo, but currently I don't have the capacity to spend much time on that.
Any reasonable suggestion will be considered and if it's reasonably easy to do we will do so.

**Comment by DEvil0000** [comment]
Did you try using aptly.info? This tool works fine for me normally and is quite easy.

**Comment by snassar-podigee** [comment]
Hello. I am late to the party. have you considered using: https://openbuildservice.org/ https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.package_formats.html#id-1.5.6.2.7 - Then it would be your channel to own.

**Comment by dominikschulz** [comment]
Actually this is something I'd still like to address.

**Comment by dominikschulz** [comment]
There is some progress. Maybe I can get it done this week :)
