### ISSUE TITLE
Is there any way to use the up/down arrow keys to highlight the selection.

### ISSUE THREAD

**Issue by 5macro** [gopasspw/gopass#1763]
### Summary
Is there any way to use the up/down arrow keys to highlight the selection? I remember there was a version which could support this before.

### Environment
Mac OS
gopass 1.10.1 go1.15 darwin amd64

**Comment by dominikschulz** [comment]
This feature was removed because it was affected by issues in underlying libraries which we couldn't fix and upstream didn't fix.

So we had to remove it.

If we find stable libraries that support this we can bring that feature back. The infrastructure is still in place.

**Comment by 5macro** [comment]
Make sense
