### ISSUE TITLE
Add Dependabot to our CI

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1765]
### Summary

Dependabot would submit automatically PRs when it detects that one of our dependencies has been upgraded, it allows us to have a clear trace of the dependencies updates and might later allow us to dig further into third party dep security/hardening, since supply chain attacks are becoming more and more of a concern lately in the field.

This issue is there to track its integration into our CI/DI.

**Comment by dominikschulz** [comment]
I've merged the first dependabot PR already!
