### ISSUE TITLE
Sync not working on Windows

### ISSUE THREAD

**Issue by BogdanDarius** [gopasspw/gopass#1788]
### Summary
When I add a key on Linux it works as expected as it gets pushed to remote.
When I add a key on Windows and try to sync I get no changes and nothing gets pushed.

### Steps To Reproduce
gopass sync on windows

### Expected behavior
Push to remote

### Environment
- OS: Windows 10
- OS version: 19042.804
- gopass Version: 1.12.0
- Installation method: from source

**Comment by AnomalRoil** [comment]
Did you install git for Windows and made sure it's in your PATH?

>

**Comment by BogdanDarius** [comment]
> Did you install git for Windows and made sure it's in your PATH?

Yes, I did. I'm able to clone the repo manually, the thing is that when I'm adding a new key and I try to sync, the changes are not detected.

**Comment by BogdanDarius** [comment]
Very strange, now it seems to work...
I was trying to do some debugging and set GOPASS_DEBUG_LOG env variable and now the issue it's gone.

**Comment by AnomalRoil** [comment]
That's strange, but on my side I tested it on Windows again with 1.12.0 and it worked, so it must be have been some local issue that is now solved.

I recommend you to unset the GOPASS_DEBUG_LOG variable, as it could leak some things such as key names (although no password should ever get logged there.)

**Comment by BogdanDarius** [comment]
Already did. Thanks! I'm closing this.
