### ISSUE TITLE
Problem with passwords containing characters matching fmt format specifiers 

### ISSUE THREAD

**Issue by mariusor** [gopasspw/gopass#1793]
### Summary

I have a couple of passwords that have character groups matching the fmt package format specifiers. 
As an example there's `%3U`, which when using go show appears as `!U(MISSING)`.

This problem has appeared with version 1.12.0

### Steps To Reproduce

Create a password containing a string matching a fmt format specifier.

When showing the password with gopass it will be treated as a format specifier that's missing its value.

### Expected behavior

The password should be shown as is.

### Environment

- OS: Linux - Archlinux
- OS version: `Linux myhostname 5.10.15-arch1-1 #1 SMP PREEMPT Wed, 10 Feb 2021 18:32:40 +0000 x86_64 GNU/Linux`
- gopass Version: 
```
gopass 1.12.0 (2021-02-11 21:15:26) go1.15.8 linux amd64
<root>     - gpg 2.2.27 - git 2.30.1
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs
```
- Installation method: From Archlinux's community repository

**Comment by dominikschulz** [comment]
Oh no ... indeed. This is easy to get wrong, and indeed there is at least one location where it is wrong: https://github.com/gopasspw/gopass/blob/master/internal/action/show.go#L170

Will take look at that later and try to get a fix out ASAP.

**Comment by dominikschulz** [comment]
I wonder if we should rename `out.Print` to `out.Printf` to make it obvious that the first parameter is a format string.

**Comment by dominikschulz** [comment]
Thanks for reporting this issue. The fix is ready.
Once we have someone around to review my changes we can cut a patch release.
