### ISSUE TITLE
Allow aborting when presented a list of options

### ISSUE THREAD

**Issue by puck** [gopasspw/gopass#1800]
### Summary

When a numbered list is presenedt to allow selecting one of the available options there is no way to abort the command, other than killing the gopass process. Control-c doesn't affect gopass (although it does appear to be passed to gpg once an option is selected).

### Steps To Reproduce

From your list of secrets, pick a substring that would match more than one secret.

```
gopass show $(substring)
```

Attempt to abort.

You could also use any other command that presents a list, for example gopass recipients add

### Expected behavior

I would expect that control-c would abort gopass, and it would be nice to present an option ('q'?) to abort.
### Environment

- OS: Debian Sid
- OS version: Linux dirk 5.10.0-2-amd64 #1 SMP Debian 5.10.9-1 (2021-01-20) x86_64 GNU/Linux
- gopass Version: 1.11.0+89ad7410443fd56b390c79c3d9f78d307224acd8 (89ad7410443fd56b390c79c3d9f78d307224acd8) go1.14.2 linux amd64
- Installation method: Downloaded .deb and dpkg -i.

**Comment by dominikschulz** [comment]
Hmm, certainly it's an UX issue to some extent.
Using 'q' does work in most cases, but maybe not always. Also we currently don't give a hint that that's an option.

Using ctrl+c is actually supposed to work. But it might not be evaluated until the current input is processed.

So yes, I get your point. Would be nice to improve that.

We should immedeately quit we crtl+c is pressed and we should support aborting with 'q' in every selection.
