### ISSUE TITLE
Clam Anti-virus claims that binary is malware

### ISSUE THREAD

**Issue by HoffsMH** [gopasspw/gopass#1807]
### Summary

clam av seems to think that gopass is or contains malware

```sh
$ clamscan -irv ~/code/go/bin
<...>
Scanning <...>/code/go/bin/pistol
Scanning <...>/code/go/bin/go
Scanning <...>/code/go/bin/gopass
<...>/code/go/bin/gopass: Unix.Malware.Ipstorm-9777197-0 FOUND
<...>
----------- SCAN SUMMARY -----------
Known viruses: 8561400
Engine version: 0.103.1
Scanned directories: 1
Scanned files: 3
Infected files: 1
Data scanned: 38.05 MB
Data read: 35.74 MB (ratio 1.06:1)
Time: 20.227 sec (0 m 20 s)
Start Date: 2021:02:20 18:18:24
End Date:   2021:02:20 18:18:44
```

this is on fresh compile from master at commit `4f87dec1`

I know that this is not a direct issue with the software, however the idea that a binary responsible for managing my passwords might be infected somehow is enough to make me re-consider using it. I tried looking online for any insight as to why clamav seems to think that it is. Can anyone provide some insight as to what is going on here? Should I switch to regular pass for the time being?

### Steps To Reproduce
```
go get github.com/gopasspw/gopass
# install clamav 
clamscan -irv $GOTPATH
```

```
$ uname -a
Linux nile 5.4.95-1-MANJARO #1 SMP PREEMPT Thu Feb 4 00:38:02 UTC 2021 x86_64 GNU/Linux
```
```
$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        20.2.1
Codename:       Nibia

$ gopass version
gopass 1.12.1-git+HEAD go1.16 linux amd64
<root>     - gpg 2.2.27 - git 2.30.1
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs
```

**Comment by dominikschulz** [comment]
Interesting. Not sure how that comes.
Pretty sure this is a false positive.

**Comment by dominikschulz** [comment]
Indeed, (only) ClamAV thinks gopass 1.12.1 is malware. Tested with the release binary.

[<img width="1250" alt="Screenshot 2021-02-21 at 07 50 28" src="https://user-images.githubusercontent.com/1449175/108617836-a075a100-7419-11eb-8fbb-0a21b4968c0d.png">](https://www.virustotal.com/gui/file/e47ed496c5d0d6a11871270afb2b4bdfac40cd882f05e0613bbf348095d35fb0/detection)

Please note that no only ClamAV detects this as malware.
Go binaries have a quite large boilerplate of standard lib code compiled in.
Also gopass does some [things](https://otx.alienvault.com/pulse/5f75fcf20d776be609945292) which might be also done in the [Malware](https://www.intezer.com/blog/research/a-storm-is-brewing-ipstorm-now-has-linux-malware/), e.g. using encryption and ssh.

I'll double check our dependencies, just to be extra sure, and if that yields nothing I'll try to submit a [false positive report](https://www.clamav.net/reports/fp) to ClamAV.

**Comment by HoffsMH** [comment]
Thank you for swift and thorough response, I look forward to seeing the resolution. Great project!

**Comment by dominikschulz** [comment]
[`git bisect`](https://git-scm.com/docs/git-bisect) indicates that `v1.12.1` isn't the first one detected as malware.
The first "bad" commit is dccfbeb0111ea6665d19e1c42979c73fca3d87a3.

This is a commit that introduced the (now deprecated) MIME secret format and moved a lot of code, but otherwise didn't add much new stuff. There was only one dependency addition: `gopkg.in/yaml.v3` (upgraded from v2). I did try to go back to `gopkg.in/yaml.v2` but clamscan still complains so I don't think our dependencies are at fault. It must be something with gopass itself that tricks ClamAV into misclassifying us.

Interestingly our split binaries (e.g. `gopass-jsonapi`) are not detected.

```
$ cat <<EOF >/tmp/clam.sh
#!/bin/bash
go build
clamscan gopass
exit $?
EOF

$ git bisect start
$ git bisect bad
$ git bisect good v1.9.0
$ git bisect run /tmp/clam.sh

[...]

dccfbeb0111ea6665d19e1c42979c73fca3d87a3 is the first bad commit                                                                                          
commit dccfbeb0111ea6665d19e1c42979c73fca3d87a3                                                                                                         
Author: Dominik Schulz <dominik.schulz@gauner.org>                                                                                                        
Date:   Thu Jun 11 16:46:05 2020 +0200                                                                                                                    

    Introduce typed MIME Secrets (#1415)                                                                                                                  
                                                                                                                                                    
    This commit introduces a new MIME-based secrets format that will                                                                                      
    eventually replace any existing secret format.                                                                                                        
                                                                                                                                                    
    Fixes #1310                                                                                                                                           
                                                                                                                                                    
    RELEASE_NOTES=[BREAKING] New secrets format.

[..]
```

**Comment by dominikschulz** [comment]
Submitted a false-positive report to ClamAV.

**Comment by AnomalRoil** [comment]
I tried digging into the detection rules of ClamAV by converting them into Yara rules that should make them easier to read, but I'm afraid it didn't help and I couldn't find the exact rule that's flagging Gopass as a malware. (Which resulted in https://github.com/sec51/clamav-yara/pull/6)

That being said, IPStorm is a Go malware that's using IPFS, it appears, so it's probable ClamAV has a rule that's too sensitive and isn't using the right markers and thus flag our binary as an IPStorm variant because it's Go and is doing a lot of crypto xD

**Comment by xens** [comment]
I'm also facing detections with the Crowdstrike EDR, I don't have much info other than that:

![image](https://user-images.githubusercontent.com/1699826/108726011-419e4d80-7527-11eb-9151-11bed83ec37f.png)

**Comment by dominikschulz** [comment]
I've been digging a little more.

First I tried to understand what actually matched. For that we need to [unpack](https://www.clamav.net/documents/creating-signatures-for-clamav#inspecting-signatures-inside-a-cvd-file) the ClamAV signatures.

```
mkdir /tmp/clamav-sigs
cd /tmp/clamav-sigs/
sigtool --unpack /var/lib/clamav/main.cvd
sigtool --unpack /var/lib/clamav/daily.cld
```

Then we should be able to find the exact signature that matched `Unix.Malware.Ipstorm`:

```
$ grep -h Unix.Malware.Ipstorm * | tee ipstorm.sig
Unix.Malware.Ipstorm-9777197-0;Engine:51-255,Target:6;0&1&2&3&4;646441534e31;646e6f746675;6e6f70747264617461;61736d66747970;476f206275696c64696e663a
```

This single-signature file can be used with `sigtool` to figure out which subsigs matched:

```
$ sigtool --test-sigs=ipstorm.sig gopass
VIRUS NAME: Unix.Malware.Ipstorm-9777197-0
TDB: Engine:51-255,Target:6
LOGICAL EXPRESSION: 0&1&2&3&4
 * SUBSIG ID 0
 +-> OFFSET: ANY
 +-> SIGMOD: NONE
 +-> SUBSIG: 646441534e31
MATCH: ** YES/CHECK OFFSET ** (16 matches at offsets: 9975246 9973831 9973768 6662810 6657015 6637256 6629788 6613452 6595533 6588884 6585924 6585908 6575188 6565810 6565796 6533618)
 * SUBSIG ID 1
 +-> OFFSET: ANY
 +-> SIGMOD: NONE
 +-> SUBSIG: 646e6f746675
MATCH: ** YES/CHECK OFFSET ** (1 match at offset: 7987344)
 * SUBSIG ID 2
 +-> OFFSET: ANY
 +-> SIGMOD: NONE
 +-> SUBSIG: 6e6f70747264617461
MATCH: ** YES/CHECK OFFSET ** (3 matches at offsets: 9727784 6560512 6552619)
 * SUBSIG ID 3
 +-> OFFSET: ANY
 +-> SIGMOD: NONE
 +-> SUBSIG: 61736d66747970
MATCH: ** YES/CHECK OFFSET ** (1 match at offset: 12947813)
 * SUBSIG ID 4
 +-> OFFSET: ANY
 +-> SIGMOD: NONE
 +-> SUBSIG: 476f206275696c64696e663a
MATCH: ** YES/CHECK OFFSET ** (1 match at offset: 12947458)
```

But what does the signature actually mean?

- It's in the file [`daily.ldb`](https://www.clamav.net/documents/creating-signatures-for-clamav#body-based-signatures).
- That contains [logical signatures](https://www.clamav.net/documents/logical-signatures).
- Logical signatures are defined as `SignatureName;TargetDescriptionBlock;LogicalExpression;Subsig0;Subsig1;Subsig2;...`
  - The signature name is `Unix.Malware.Ipstorm-9777197-0`
  - The required [Engine level](https://www.clamav.net/documents/functionality-levels-flevels) is 51 or higher
  - The [target type](https://www.clamav.net/documents/clamav-file-types#Target-Types) is 6, i.e. ELF
  - The `LogicalExpression` is `0&1&2&3&4`, i.e. all subsigs have to match
  - We have 5 subsigs:
    1. 646441534e31
    1. 646e6f746675
    1. 6e6f70747264617461
    1. 61736d66747970
    1. 476f206275696c64696e663a
  - Interestingly all but (b) seem to match (almost) any Go binary I found on my system.
  - At this point I'm somewhat lost as how to map subsig `646e6f746675` at offset `7987344` to a source location.

**Comment by dominikschulz** [comment]
Confirmed false positive.

When I comment [line 69 in `internal/action/binary.go`](https://github.com/gopasspw/gopass/blob/master/internal/action/binary.go#L69) ClamAV does not complain anymore.

**Comment by dominikschulz** [comment]
This was fun :laughing:

**Comment by HoffsMH** [comment]
I'm glad me and my paranoia spawned some entertainment!

**Comment by AnomalRoil** [comment]
> At this point I'm somewhat lost as how to map subsig 646e6f746675 at offset 7987344 to a source location.

I guess you ended up using Ghidra to do the reverse engineering?  Or was there an easier way?

**Comment by dominikschulz** [comment]
I'm sorry to disappoint you, but my reverse engineering skills are not that great.

I went back looking at the bisect results and started manually removing pieces which were touched in the offending CL. Manual bisect if you will. Low tech, but effective 😁
