### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#1808]
We should support [reproducible builds](https://reproducible-builds.org/).

Short how-to: https://blog.filippo.io/reproducing-go-binaries-byte-by-byte/
Restic could be used as an example: https://github.com/restic/restic#reproducible-builds

**Comment by AnomalRoil** [comment]
Seems we had it once upon a time: #495 
Did we "loose" reproducibility, or not? I haven't tested yet.

**Comment by dominikschulz** [comment]
We have added some parameters to our Makefile to allow distros to have reproducible builds of this repo but didn't do anything with it ourselves so far.

I'd like to have some documentation on what users can expect and a way (e.g. Docker) to actually test / use it.
