### ISSUE TITLE
Incorrect showed password if it contains %u

### ISSUE THREAD

**Issue by adrianlzt** [gopasspw/gopass#1812]
### Summary
If the text stored in the secret does contain the string ``%u``, if we ask gopass to show that text, it is replaced with ``%!u(MISSING)``.

Does not happen copying to clipboard.

### Steps To Reproduce
```
➜ gopass edit -c foo--

Put "%uFOO" as password

➜ gopass show foo
Secret: foo--

%!u(MISSING)FOO
```

### Expected behavior
Showing the correct password

### Environment
- OS: archlinux
- OS version: rolling release
- gopass Version: gopass 1.12.0 (2021-02-11 21:15:26) go1.15.8 linux amd64
- Installation method: arch packages

**Comment by dominikschulz** [comment]
This is fixed in 1.12.1. Please upgrade.
