### ISSUE TITLE
Moving entries is weird

### ISSUE THREAD

**Issue by mcnesium** [gopasspw/gopass#1813]
I just experienced a weird behaviour of gopass, when moving a "file" (single entry) into another directory:

First I moved another file into a not-yet existing directory `/www`:

    m@x ~/store   gopass mv old/www/myalias@my.email www/this.site/myalias@my.email

Then I moved the file of the day into that now existing directory `/www` as well:

    m@x ~/store   gopass mv old/www/user31326 www/

Here comes the imho weird behaviour: Now a file `www` has been created in the root directory with the same name as the already existing directory, and gopass knows about it, because it shows this warning:

    m@x ~/store   gopass show www/
    Warning: www/ is a secret and a folder. Use 'gopass show www/' to display the secret and 'gopass list www/' to show the content of the folder
    ********

True story:

    m@x ~/store   gopass list www/
    www/
    └── this.site/
        └── myalias@my.email

Looking at the file system, I found both the `www` directory and the file, obviously with the `.gpg` extension: 

    m@x ~/store   ll
    drwx------  3 mcn mcn 4096 24. Feb 21:16 www
    -rw-------  1 mcn mcn  216 24. Feb 21:18 www.gpg

Then I tried to rename whatever will be renamed:

    m@x ~/store   gopass mv www notwww

Apparently both the file and the directory:

    m@x ~/store   ll
    drwx------  3 mcn mcn 4096 24. Feb 21:26 notwww

But surprise, both of them have only been moved into an *again* newly created directory:

    m@x ~/store   ll notwww/
    drwx------  3 mcn mcn 4096 24. Feb 21:26 www
    -rw-------  1 mcn mcn  216 24. Feb 21:26 www.gpg

The other subdirectory is just where it should be:

    m@x ~/store   ll notwww/www
    drwx------ 2 mcn mcn 4096 24. Feb 21:26 this.site

Now lets see what happens when I move that back out of the `notwww` directory:

    m@x ~/store   gopass mv notwww/www/ www

It creates the `www` directory again and also goes ahead and deletes the now empty `notwww` directory (this is expected behaviour, I know, and it is good that it does that), but there is no additional `www` file:

    m@x ~/store   ll
    drwx------  4 mcn mcn 4096 24. Feb 21:28 www

Where did it go? Lets see what's in the latest `www` directory:

    m@x ~/store   ll www/
    drwx------  2 mcn mcn 4096 24. Feb 21:28 notwww
    drwx------  2 mcn mcn 4096 24. Feb 21:28 this.site

Welcome back, good old `notwww` directory! And thank you for bringing our beloved `www` file:

    m@x ~/store   ll www/notwww/
    -rw------- 1 mcn mcn  216 24. Feb 21:28 www.gpg

This is meant more of a question than a bug report. Is this intended behaviour? I find it a bit surprising.

This is installed from the community repo of Manjaro Linux:

    m@x ~/store   gopass --version
    gopass 1.11.0 (2021-01-12 17:26:03) go1.15.6 linux amd64

**Comment by dominikschulz** [comment]
Thanks for the detailed bug report, I'll need get back to it when I have some more time.

But the general idea is for mv and cp to behave like the Unix commands, so there seems to be at least some issue with the current implementation.

**Comment by dominikschulz** [comment]
I think the first step should be to formalize the expected behavior in a unit or integration test.

Then it should be easy to fix, but without tests this is very prone to breaking again.

**Comment by dominikschulz** [comment]
I'm trying to unpack this step by step.

I've reproduced it until the first faulty behaviour:

```
# for testing don't both with encryption or git
$ gopass setup --crypto plain --storage fs
# generate test data
$ gopass generate old/foo/account1 24
$ gopass generate old/foo/account2 24
$ tree
.
└── old
    └── foo
        ├── account1.txt
        └── account2.txt
$ gopass mv old/foo/account1 www/foo/account1
$ tree
.
├── old
│   └── foo
│       └── account2.txt
└── www
    └── foo
        └── account1.txt

4 directories, 2 files
# so far so good
$ gopass mv old/foo/account2 www/
$ tree
.
├── www
│   └── foo
│       └── account1.txt
└── www.txt

2 directories, 2 files
# boom, this is wrong!
```

I think the last move is where the implementation is wrong.
While we arguablly should support reading from a secret that has the same name as a directory, we should never create such a situation. Especially not when the destination has a file seprator suffix (`/`) at the end.

**Comment by dominikschulz** [comment]
Let's keep this open until it's confirmed to work as expected.

**Comment by mcnesium** [comment]
Looks like I can confirm that this is fixed. Running v1.12.2 on a Debian system I successfully moved single file entries to a directory, both using `www` and `www/` (with a slash).

Thank you for your work! :1st_place_medal:
