### ISSUE TITLE
[Feature Request] gopass ln command

### ISSUE THREAD

**Issue by benneti** [gopasspw/gopass#1820]
It would be convenient to have the option to create symlinks inside the password store.
This would simplify maintenance, i.e. one could have github.com/accountname this will not be used by the git-credentials helper such that when changing secrets one would have to edit two files.
Creating the option to symlink the secret to the correct location would simplify tasks like the outlined one.

(I tried simply creating a symlink for the secret in the password-store but this did not work.)

**Comment by dominikschulz** [comment]
Hmmm, this would be an elegant way to implement aliases and should work with git.

But I don't think it would work with Windows?!

I wonder why it doesn't work OOTB.

**Comment by benneti** [comment]
I guess because I did something weird last time, just tried again and it works.
Maybe the problem was that I replaced an existing PW without first using gopass rm.
Doing it for a previously non-existing file worked.

(What also would be nice if gopass audit would show that these are symlinks)

PS: Thanks for gopass, it is really nice!

**Comment by dominikschulz** [comment]
I've just confirmed that we handle both symlinks and hardlinks (or course) fine.

However we could still consider if adding a `gopass ln`  subcommand would make sense.
Not sure if it's worth the added code. And if we do maybe something like `gopass alias` would be more intuitive?

I'm not sure, but let's keep this issue open. Maybe other want to chime in.

**Comment by benneti** [comment]
I think both alias and ln could be used at the same time like copy and cp.
As it already works I agree that it is not strictly necessary to have the subcommand.

**Comment by nightsparc** [comment]
Would love to have such a feature around!

I used (manually) inserted symlinks in my stores. However, gopass seems to mangle them up in some way? I guess a `gopass fsck` destroyed the links, but I'm not entirely sure. Effectively, the symlinks were replaced with text files containing the link (I guess the symlinks file type was changed from link to regular file?). Cause of this, I stopped using the feature, but misses it. My current workaround is to have deep hierarchies of domains, which are thankfully matched by gopass and the gopass-bridge, but I would really prefer to have a flatter hierarchy here...

> (What also would be nice if gopass audit would show that these are symlinks)
YES! Please! In my case above, `gopass audit` throwed errors for each of the links (so, maybe it was the audit that had destroyed the links?)

> I think both alias and ln could be used at the same time like copy and cp.
Full ack. 

And it would be nice, if a `gopass show` would mark the symlinks in some way - maybe similar to good old `ls` :)

**Comment by dominikschulz** [comment]
We used to explicitly disallow symlinks for no good reason and tried to remove that limitation, but it's possible that some artifacts are still around. Since we never officially supported we never checked that.

But I think we could at least add integration tests and some documentation that we support them.

Still not sure about a new subcommand.

**Comment by nightsparc** [comment]
> But I think we could at least add integration tests and some documentation that we support them.

Functionally, that would be fine for me. However, I really think it would be nice having them visualized in the show command and taken into account for some of the others (namely audit, see above).

> Still not sure about a new subcommand.

Neither am I. Would be a nice convenience function to have around :man_shrugging:
