### ISSUE TITLE
gopass show -o is ineffective

### ISSUE THREAD

**Issue by mcnesium** [gopasspw/gopass#1821]
When you want to really only have the password (e.g. for a script), `gopass show` has the `--password, -o` option:

    m@x ~ gopass help show | grep only
    --password, -o             Display only the password. Takes precedence over all other flags. (default: false)

However, this flag does not do anything, unfortunately. Here is a minimal example:

    m@x ~ gopass generate testpassword 31
    ✅ Password for entry "testpassword" generated
    ✔ Copied testpassword to clipboard. Will clear in 45 seconds.
    2
    Copied to clipboard

    m@x ~ gopass show testpassword 
    Secret: testpassword

    iEg2h6skkaL74iHCwRm92hbtCOLYmcw

    m@x ~ gopass show -o testpassword 
    Secret: testpassword

    iEg2h6skkaL74iHCwRm92hbtCOLYmcw

    mcn@x270 ~ gopass show --password testpassword 
    Secret: testpassword

    iEg2h6skkaL74iHCwRm92hbtCOLYmcw

The actual file instead only contains one line with the password:

    m@x ~ gpg -qd .local/share/passwordstore/testpassword.gpg 
    iEg2h6skkaL74iHCwRm92hbtCOLYmcw

This gopass is installed from [Arch community repo](https://archlinux.org/packages/?q=gopass)

    m@x ~ gopass --version
    gopass 1.12.0 (2021-02-11 21:15:26) go1.15.8 linux amd64

**Comment by dominikschulz** [comment]
Ah, my bad. This might be my fault.

Should be easy to fix.

**Comment by mcnesium** [comment]
thanks for jumping right in! :+1:
