### ISSUE TITLE
can't copy multiline password to clipboard. 

### ISSUE THREAD

**Issue by mhudson-bw** [gopasspw/gopass#1829]
### Environment

- OS: [Ubuntu 20.10]
- OS version: [5.8.0-44-generic #50-Ubuntu SMP Tue Feb 9 06:29:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux]
- gopass Version: [gopass 1.12.0-git+HEAD go1.14.7 linux amd64]
- Installation method: [gopass repo]

**Comment by dominikschulz** [comment]
We define the password field as the first line of a secret. So, yes. This is not supported.
