### ISSUE TITLE
No gpg binary found: mkdir /nonexistent: permission denied

### ISSUE THREAD

**Issue by nunotexbsd** [gopasspw/gopass#1832]
Hello,

I'm trying to update FreeBSD gopass [port](https://www.freshports.org/security/gopass/) from 1.11.0 to 1.12.1 and I verifying a very strange behavior when port do a post-build to create completions:

```
post-build:
.for SHELL in bash fish zsh
        ${WRKDIR}/bin/${PORTNAME} completion ${SHELL} > ${WRKSRC}/${SHELL}
.endfor
```
And it gives the error:

```
/wrkdirs/usr/ports/security/gopass/work/bin/gopass completion bash > /wrkdirs/usr/ports/security/gopass/work/gopass-1.12.1/bash
❌ No gpg binary found: mkdir /nonexistent: permission denied
*** Error code 19

Stop.
make: stopped in /usr/ports/security/gopass
build of security/gopass | gopass-1.12.1 ended at Thu Mar 11 12:09:45 WET 2021
build time: 00:00:58
!!! build failure encountered !!!

```
It works ok with 1.11.0.

Any hints on this issue?

Thanks,

Nuno Teixeira

**Comment by nunotexbsd** [comment]
1.12.0 works fine.

This way I think that something in 1.12.1 is breaking my build.

**Comment by AnomalRoil** [comment]
Did you update to Go 1.16?

**Comment by nunotexbsd** [comment]
yes, go 1.15 doesn't compile it at all.

My particular case, source code is compiled correctly, but the prebuild gopass binary (${GO_WRKDIR_BIN/gopass} can't run and gives the error above.
I'm investigating about it because the error doesn't tell much detail but one thing I discovered is that version 1.12.0 runs prebuild binary fine.

**Comment by AnomalRoil** [comment]
That's really strange. I thought it might be related to #1758 but that was
already in 1.12.0

Do you have a gpg binary on that machine?

Could you test the git tip too? If you're using Go 1.16 I think the master
tip compile but maybe not the 1.12.1 and 1.12.0 since we upgraded to it
after tagging.

**Comment by nunotexbsd** [comment]
Yes, I have git and gpg because of:
`RUN_DEPENDS=    git:devel/git \
                gpg2:security/gnupg`

git tip? what is it?

**Comment by dominikschulz** [comment]
git tip / head, i.e. the latest commit from the gopass repo, not the latest tagged version.

**Comment by nunotexbsd** [comment]
ok, I will try latest commit 84030d5

**Comment by nunotexbsd** [comment]
same error on [poudriere](https://github.com/freebsd/poudriere)

**Comment by nunotexbsd** [comment]
gnupg binaries:
`	/usr/local/bin/dirmngr
	/usr/local/bin/dirmngr-client
	/usr/local/bin/gpg-agent
	/usr/local/bin/gpg-connect-agent
	/usr/local/bin/gpg-wks-server
	/usr/local/bin/gpg2
	/usr/local/bin/gpgconf
	/usr/local/bin/gpgparsemail
	/usr/local/bin/gpgscm
	/usr/local/bin/gpgsm
	/usr/local/bin/gpgsplit2
	/usr/local/bin/gpgtar
	/usr/local/bin/gpgv2
	/usr/local/bin/kbxutil
	/usr/local/bin/watchgnupg
	/usr/local/sbin/addgnupghome
	/usr/local/sbin/applygnupgdefaults

lrwxr-xr-x  1 root  wheel        4  8 mar 21:44 /usr/local/bin/gpg -> gpg2`

**Comment by AnomalRoil** [comment]
Where is this ".post-build" command? I'd like to try and reproduce it.

**Comment by nunotexbsd** [comment]
poudriere full [log](https://termbin.com/g8bc)

Remember that all commands are running in jailed enviroment in poudriere. I can compile it ok on a local FreeBSD shell. But it needs to pass all tests in poudriere.

`# GO_WRKDIR_BIN == WKRDIR/bin
post-build:
.for SHELL in bash fish zsh
        ${WRKDIR}/bin/${PORTNAME} completion ${SHELL} > ${WRKSRC}/${SHELL}
.endfor`

**Comment by nunotexbsd** [comment]
note: log says gopass 1.12.0, but it is using latest commit:
`=> SHA256 Checksum OK for gopasspw-gopass-v1.12.0-84030d5_GH0.tar.gz.`
I forced latest commit tag

**Comment by dominikschulz** [comment]
The error message is bogus. "no gpg binary found" is misleading and mostly just wrong. I'll fix that.

But to understand what's happening here I'll need a debug log.

Can you somehow get us the output of that?

You'll need to set `GOPASS_DEBUG_LOG=/some/file`.

**Comment by dominikschulz** [comment]
I think I found the issue. Will send a PR later.

**Comment by dominikschulz** [comment]
I'd still like to see your debug log, if possible.

**Comment by AnomalRoil** [comment]
Please test with the latest master tip and confirm whether it solved your issue or not.

**Comment by dominikschulz** [comment]
This must have fixed the issue. There is literally no other code path that could lead to this error.

But, yes. Please test it.

**Comment by nunotexbsd** [comment]
Latest commit fixed my poudriere build!
Is there a patch that I could apply to 1.12.1 version? Or should I wait for a new version?

**Comment by dominikschulz** [comment]
We have a bunch of relevant Bugfixes waiting already.

I think we should postpone the ln feature a cut 1.12.2 without it.

@AnomalRoil wdyt?

**Comment by AnomalRoil** [comment]
Agreed, let's cut 1.12.2 now.

**Comment by nunotexbsd** [comment]
thanks for new version!
port on is [way](https://reviews.freebsd.org/D29253)

Cheers,
Nuno Teixeira
