### ISSUE TITLE
Bottled gopass contains unnecessary binaries

### ISSUE THREAD

**Issue by arren-ru** [gopasspw/gopass#1840]
### Summary

Suddenly discovered that my man command does not work and points to unknown man binary which belongs to `Cellar/.../gopass/bin` path

### Steps To Reproduce

Just install bottled gopass version 1.12.2 under BigSur

### Expected behavior

Only gopass binary installed

### Environment

- OS: Mac OS BigSur
- OS version: Darwin borg.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
- gopass Version: 1.12.2
- Installation method: brew install

**Comment by dominikschulz** [comment]
What the ... these are our release helper binaries (changelog, man and release).

Why are they getting installed by the brew formula?

**Comment by dominikschulz** [comment]
Interesting. It looks like there is an [official gopass formula](https://formulae.brew.sh/formula/gopass#default) in homebrew-core.

It does an [`go install ./...`](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gopass.rb#L26) and this pulls in our helpers - which should never end up anywhere as a binary. Our [own formula](https://github.com/gopasspw/homebrew-gopass/blob/master/gopass.rb) seems to do it correctly.

Please report this bug to Homebrew/homebrew-core at https://github.com/Homebrew/homebrew-core/issues.

**Comment by arren-ru** [comment]
Added issue here https://github.com/Homebrew/homebrew-core/issues/73243

**Comment by carlocab** [comment]
It didn't use to. The formula didn't change between 1.11 and 1.12 (other than the version, of course), but the contents of the `bin` directory did. In 1.11:
```
Permissions Size User     Date Modified Name
.r-xr-xr-x   17M carlocab 12 Jan 12:05  gopass
.r-xr-xr-x   14M carlocab 12 Jan 12:05  gopass-git-credentials
.r-xr-xr-x   14M carlocab 12 Jan 12:05  gopass-hibp
.r-xr-xr-x   15M carlocab 12 Jan 12:05  gopass-jsonapi
.r-xr-xr-x   14M carlocab 12 Jan 12:05  gopass-summon-provider
```
In 1.12:
```
Permissions Size User     Date Modified Name
.r-xr-xr-x  1.6M carlocab 11 Feb 14:18  changelog
.r-xr-xr-x   14M carlocab 11 Feb 14:18  gopass
.r-xr-xr-x  3.1M carlocab 11 Feb 14:18  release
```

**Comment by dominikschulz** [comment]
Yes, we have changed some things around.
Accidentially the formula used to work but it was never correct in my opinion.
