### ISSUE TITLE
Gopass is unable to add subkeys of a key individually

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#1841]
But `pass` does.

From #909:

> Problem 1: can’t use the CLI to add different subkeys as recipients
>
> ```
> $ gopass init
> [init] Initializing a new password store ...
> Please select a private key for encrypting secrets:
> [0] gpg - 0x90D516249B728BE6 - Kirill Elagin <kirelagin@gmail.com>
> Please enter the number of a key (0-0, [q]uit) [0]: 0
> [init] Initializing git repository (gitfs) for kirelagin / ...
> Please enter an email address for password store git config []: 
> [init] git initialized at /home/kirelagin/.local/lib/gopass
> [init] Git Email not set
> [init] git configured at /home/kirelagin/.local/lib/gopass
> [init] Git initialized
> [init] Password store /home/kirelagin/.local/lib/gopass initialized for:
> [init]   0x90D516249B728BE6 - Kirill Elagin <kirelagin@gmail.com>
> 
> $ gopass recipients add 'FBE0EC61EDA03749197C34D785D128E1B30E1931!'
> Do you want to add '0x90D516249B728BE6 - Kirill Elagin <kirelagin@gmail.com>' as a recipient to the store ''? [y/N/q]: y
> 
> Error: failed to add recipient 'FBE0EC61EDA03749197C34D785D128E1B30E1931!': Recipient already in store
> ```
> 
> This is clearly a UX problem, since this is something that should work. Compare to pass:
> 
> $ pass init '047A7B2FB0E96F07F9C216DCB3D9F87D907DC8B1!' 'FBE0EC61EDA03749197C34D785D128E1B30E1931!'
>
> and it does exactly what I need. gopass is being smart and, as a result, I could not find any way to init a repo to a specific subkey. Furthermore, since I can’t remove the only recipient, the UI does not allow me to change the recipients list to be made of specific subkeys.

**Comment by dominikschulz** [comment]
Yes, I think this should be supported.

**Comment by dominikschulz** [comment]
I've added a rought draft. If you want have a look and let me know what you think.
But this will require some more work before merging.
