### ISSUE TITLE
gopass generate --clip not copying to clipboard

### ISSUE THREAD

**Issue by silkeh** [gopasspw/gopass#1844]
### Summary

The `--clip` option of the `gopass generate` command no longer works. Using `git bisect` I found that this regression was introduced by #1806.

### Steps To Reproduce

Using a clean build from source (from 877c3d8f or later):

```
$ ./gopass generate -c -f temp/temp 24
✅ Password for entry "temp/temp" generated
Not printing secrets by default. Use 'gopass show temp/temp' to display the password
```

No password is copied to the clipboard.

### Expected behavior

Using a clean build from source (from v1.12.1):

```
$ ./gopass generate -c -f temp/temp 24
✅ Password for entry "temp/temp" generated
✔ Copied temp/temp to clipboard. Will clear in 45 seconds.
Copied to clipboard
```

### Environment

- OS: Solus
- OS version: `Linux enterprise 5.11.6-174.current #1 SMP PREEMPT Thu Mar 11 17:53:06 UTC 2021 x86_64 GNU/Linux`
- gopass Version: 1.12.2, 877c3d8, master
- Installation method: from source

**Comment by dominikschulz** [comment]
[This](https://github.com/gopasspw/gopass/commit/877c3d8f1953d9c6a3a02bb167ce2f7999b321bc#diff-f17a6a5cac28629f2218b31f108b580253bcaa95ce639204a5511df17ef1df28R120) looks suspicious.

**Comment by dominikschulz** [comment]
Thanks for using `bisect` to find the culprit commit. That helped a lot!
