### ISSUE TITLE
Outdated docs or missing feature: "flag provided but not defined: -yes"

### ISSUE THREAD

**Issue by jensklose** [gopasspw/gopass#1858]
### Summary
The documentation mentioned a possibility  to simplify the setup of gopass for your team members, but it doesn't work.
https://github.com/gopasspw/gopass/blob/master/docs/setup.md#batch-bootstrapping 

### Steps To Reproduce

Follow the documentation
```
# First initialize a new shared store and push it to an empty remote
gopass --yes setup --remote github.com/example/pass.git --alias example --create --name "John Doe" --email "john.doe@example.com"
```

### Expected behavior

A new store with remote git should be created.

### Environment
WSL2 ubuntu20.04 bash (gopass installed in this context) 
`gopass 1.12.2+fb02b5ce698047f070362828b5816563a82feec7 (fb02b5ce698047f070362828b5816563a82feec7) go1.16 linux amd64`

Windows10 Powershell Installation from source:
`gopass 1.12.3-git+HEAD go1.16.2 windows amd64`

### Actual behavior
An error was thrown:

```bash
Incorrect Usage. flag provided but not defined: -yes

NAME:
   gopass - The standard unix password manager - rewritten in Go

USAGE:
   gopass.exe [global options] command [command options] [arguments...]

VERSION:
   1.12.3-git+HEAD

```

**Comment by dominikschulz** [comment]
This flag should still be supported. Looks like a bug.
