### ISSUE TITLE
Do not log secrets

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#1883]
When debug logging is enabled we log secrets.

This should not happen. At least not by default.

**Comment by AnomalRoil** [comment]
See also discussion here: https://github.com/gopasspw/gopass/pull/1865#discussion_r602135817

**Comment by dominikschulz** [comment]
I have a plan on how to fix this:

1. Propagate the fact that a string contains secrets (either via context or type switch) to the log method
1. Avoid logging these, possibly we could have another env var to log these as well, if it's really necessary for debugging e.g. secrets parser and such
