### ISSUE TITLE
Is it possible to use age and gpg backends simultaneously?

### ISSUE THREAD

**Issue by kfken** [gopasspw/gopass#1889]
### Summary
I have an existing gpg backed gopass setup that I've been using, and I'd like to have a new store that's age encrypted.  Is it possible to use both?  I created a new store with the steps below, and added a secret to it, but when it decrypted it used my gpg key instead of asking for my age passphrase.

If it's the answer is it's not possible to do, can you think of any workarounds?  Create a new gopass config and point at that instead of my existing config?

### Steps To Reproduce
1. gopass init --path /home/kfken/.age-store --store agepass --crypto age
2. create -s agepass test
3. show test
4. prompted for gpg PIN

### Expected behavior
Expected to be prompted for age passphrase and that's used to decrypt it

### Environment
- OS: Debian
- OS version: `5.10.0-5-amd64 #1 SMP Debian 5.10.24-1 (2021-03-19) x86_64 GNU/Linux`
- gopass Version: 
```
gopass 1.12.4-git+HEAD go1.16.2 linux amd64
<root>     - gpg 2.2.27 - git 2.31.1
agepass    -  age 0.0.1 - git 2.31.1
```
- Installation method: built from source

**Comment by kfken** [comment]
Looking for options that don't' involve completely converting my gopass gpg encrypted secrets to all age secrets for now.  I definitely want to do that, but have been waiting for age yubkiey support.  I may just end up doing a full conversion anyway, but wanted to test out/experiment with a dual setup for the time being.

**Comment by dominikschulz** [comment]
Sure, every mount can use a different Backend.

I think the problem is the `-s` flag to create. That is not supported.

You need to specify the correct path (`gopass create -f age store/test`) or select the correct store when asked.

**Comment by dominikschulz** [comment]
Oh, actually the -s flag should be supported. Strange.

**Comment by dominikschulz** [comment]
Ok, so `gopass create` with `-s` AND a secret name ignores the specified store.
If you omit either `-s` or the name (here: `test`) it will work.

**Comment by kfken** [comment]
> Ok, so `gopass create` with `-s` AND a secret name ignores the specified store.
> If you omit either `-s` or the name (here: `test`) it will work.

Ok, looks like it worked when I did `create -s agepass`.  If I omitted -s, I was prompted for a store, but if I chose `agepass` store, it still used my gpg keys to encrypt.

One other question: is it intentional that if you're in the "shell" environment ( `gopass` is run without args), that the age passphrase is cached?  I wasn't prompted for it again as long as I was in the shell session?

**Comment by dominikschulz** [comment]
Using the gpg store when you select the `agepass` store sounds like a bug. However I did test it locally and couldn't observe anything like that.

The answer to the other question is a clear yes. The REPL (shell) mode was designed for use with the age backend because the gopass agent implementation was so poorly designed (by me) that I had to remove it to not risk security issues there. But without passphrase caching the age backend can be quite annoying to use. This is why we have the REPL shell.

**Comment by kfken** [comment]
> Using the gpg store when you select the `agepass` store sounds like a bug. However I did test it locally and couldn't observe anything like that.
> 

Here's the steps I took:

```
❯ gopass create agetest2
🌟 Welcome to the secret creation wizard (gopass create)!
🧪 Hint: Use 'gopass edit -c' for more control!
[ 0] Website Login
[ 1] PIN Code (numerical)
[ 2] Generic

Please select the type of secret you would like to create (q to abort) [0]: 2
2
🧪 Creating generic secret ...
  [1] Name                                   []: agetest2
  [2] Generate password?                     [Y/n/q]: 
    [a] Human-pronounceable passphrase?      [y/N/q]: 
    [b] How long?                            (q to abort) [24]: 
    [c] Include symbols?                     [y/N/q]: 
    [d] Strict rules?                        [y/N/q]: 
[ 0] <root>
[ 1] agepass

Please select the store you would like to use (q to abort) [0]: 1
1
  [3] Enter zero or more key value pairs for this secret:
    [a] Name (enter to quit)                 []: 
✅ Credentials saved to "agetest2"
✔ Copied agetest2 to clipboard. Will clear in 45 seconds.
❯ gopass show agetest2
```

Then I'm prompted for the PIN for yubikey opengpg slot, after which the new entry is displayed.

```
❯ gopass ls | head -n 10
gopass
├── agepass (/home/kfken/.age-store)
│   └── misc/
│       └── agetest
├── agetest2
```

> The answer to the other question is a clear yes. The REPL (shell) mode was designed for use with the age backend because the gopass agent implementation was so poorly designed (by me) that I had to remove it to not risk security issues there. But without passphrase caching the age backend can be quite annoying to use. This is why we have the REPL shell.

Makes sense, I like the feature.

**Comment by dominikschulz** [comment]
Thanks. This is indeed a bug in how a handle arguments to `gopass create`.
