### ISSUE TITLE
gopass fsck warns about throw-keyids even if it is commented out in gpg config

### ISSUE THREAD

**Issue by pdecat** [gopasspw/gopass#1898]
### Summary

`gopass fsck` warns about `throw-keyids` even if it is commented out in gpg config

### Steps To Reproduce

Add a comment to your gpg config with the `throw-keyids` string:
```sh
grep throw-keyids ~/.gnupg/gpg.conf
#throw-keyids
```
Then run `gopass fsck`:

```sh
gopass fsck
Checking store integrity ...

[] Checking storage backend
]   1 / 556 [Gs                                                                                                                                                                ]   0.18%
[] Compacting storage if possible

[] Checking all secrets in store
] 283 / 556 [Gooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooopass                                                                                ]  50.90%
[] ⚠ gpg option throw-keyids is set. some features might not work.
...
] 561 / 561 [Gooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooopass] 100.00%
[] ⚠ gpg option throw-keyids is set. some features might not work.
```

### Expected behavior

gopass should ignore comments in gpg.conf

### Environment

- OS: Ubuntu 20.10
- OS version: `Linux myhost 5.8.0-48-generic #54-Ubuntu SMP Fri Mar 19 14:25:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- gopass Version: `gopass 1.12.5+1878ea5d (1878ea5d 2021-04-05 07:42:34) go1.16.3 linux amd64`
- Installation method: from source

### Additional context

Related: https://github.com/gopasspw/gopass/pull/1759

**Comment by dominikschulz** [comment]
Yes, it's a pretty simple check that greps for the option, not a full config parser.
Unfortunately gpg doesn't seem offer a proper config interface (at least `gpgconf` doesn't seem to list this option).

So I recommend you just delete the option if the warning is annoying.

**Comment by pdecat** [comment]
Would a PR ignoring commented out lines be accepted?

**Comment by dominikschulz** [comment]
Sure. Right now we do the equivalent of a "grep throw-keyids ~/.gnupg/gpg.conf`.
We could replace that with a simple config parser that does handle comments.

The config format looks very simple, but I haven't dug into the specification, yet.

**Comment by pdecat** [comment]
🚀
