### ISSUE TITLE
fsck reports false-positives when comparing recipients

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#1900]
`gopass fsck` can report false positives if the `.gpg-id` files don't contain full size hashes but either short ones or recipient names.

The [comparison](https://github.com/gopasspw/gopass/blob/master/internal/store/leaf/fsck.go#L104) must first normalize to long hashes before comparing them.

**Comment by YarekTyshchenko** [comment]
Yep, just been bitten by this one:
```
[] ❌ Missing recipients on irc.freenode.net: [yarekt@gmail.com]
Run fsck with the --decrypt flag to re-encrypt it automatically, or edit this secret yourself.

[] ❌ Extra recipients on irc.freenode.net: [FC41BCF0479672265B8D2B64753E1D018EC24F4C]
Run fsck with the --decrypt flag to re-encrypt it automatically, or edit this secret yourself.
```

Not only the fsck message is a little confusing, but re-encrypting the secret does nothing!

**Comment by dominikschulz** [comment]
Please note that my idea was to look up the long hash to whatever is in the `.gpg-id` file - not rewrite that.
