### ISSUE TITLE
create command kills terminal

### ISSUE THREAD

**Issue by xsteadfastx** [gopasspw/gopass#1902]
### Summary
with version v1.2.5 `gopass create` crashes my terminal. i run st (simple terminal). in gnome-terminal it works just fine. 
i get this error:

`X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  20 (RenderAddGlyphs)
  Serial number of failed request:  1942
  Current serial number in output stream:  1965`

it looks like its a problem with the emojis.

i know this is maybe not a real gopass problem... but i have no problems with emojis so far in my terminal... i think maybe someone has an idea about it.

### Steps To Reproduce
`gopass create`

### Environment

- OS: Ubuntu 18.04 
- OS version: 5.4.0-65-generic #73~18.04.1-Ubuntu
- gopass Version: 1.12.5
- Installation method: brew and go get

**Comment by xsteadfastx** [comment]
i just read in the [FAQ](https://git.suckless.org/st/file/FAQ.html) of st that this is a bug in Xft. Can there be a option to disable emojis in gopass maybe?

**Comment by xsteadfastx** [comment]
i can even break it down to this emoji: "🧪". ok... this sucks ;-) i mean not gopass... just st terminal here.

**Comment by dominikschulz** [comment]
Hmm, sorry for that. [`st`](https://st.suckless.org/) is supposed to support UTF-8.
Right now we don't have an option to disable emojis.
Personally I mostly use gopass in a terminal without UTF-8 support and besides producing some empty boxes I've never seen any issues with that.

**Comment by xsteadfastx** [comment]
but this is really not the problem of gopass... its wonderful as it is (even if the no symbols env variable is nice)... its a problem with Xft. i took this problem to move from st terminal to alacritty... finally a reason to try something new :) no problems with gopass create in alacritty.
