### ISSUE TITLE
`gopass rm -r folder foo` deletes folder right away (non interactive)

### ISSUE THREAD

**Issue by plush-plush** [gopasspw/gopass#1906]
### Summary

`gopass rm -r folder` ask for confirmation but `gopass rm -r folder foo` does not.

### Steps To Reproduce

`gopass rm -r folder foo`

### Expected behavior

`gopass rm` without the flag `-f` should reliably prompt for confirmation before deleting anything.

### Environment

- OS: Arch Linux
- gopass Version: 1.12.5
- Installation method: OS package manager pacman

Thank you very much for the work you put into this project.

**Comment by dominikschulz** [comment]
Hmm, this looks like a bug when handling keys.
