### ISSUE TITLE
gopass generate - better help and error messages

### ISSUE THREAD

**Issue by leogott** [gopasspw/gopass#1911]
### Summary

The text shown by command `gopass help generate` is
- difficult to understand and
- doesn't explain the usage of [arguments...] at all.
- Additionally the error messages don't really help either.

### Problem a
`gopass help generate`
> NAME:
>   gopass.exe generate - Generate a new password

better: Generate a new password and **write it into a secret.**
>USAGE:
>   gopass.exe generate [command options] [arguments...]

See below

>DESCRIPTION:
>   Generate a new password of the specified length, optionally with no symbols. Alternatively, a xkcd style password can be generated (https://xkcd.com/936/). Optionally put it on the clipboard and clear clipboard after 45 seconds. Prompt before overwriting existing password unless forced. It will replace only the first line of an existing file with a new password.

I suggest to change it to something more succinct and along the lines of:

**Dialog** to generate a new password and write it into a new or existing **secret.** By default, the new password will replace the first line of an existing secret (unless it's a key-value-pair?). Supports options of `pwgen` and `show` listed below.
>[...]

### Problem b

```
PS > gopass generate example -c
How long should the password be? (q to abort) [24]:
✅ Password for entry "example:-c" generated
Not printing secrets by default. Use 'gopass show example:-c' to display the password.

Error: failed to set key "-c" of "example": entry is not in the password store
```
(Note: This Error message is mostly helpful)
The intention was to generate a password for a new secret, and to immediately copy it to the clipboard.
The operation fails because the `-c` comes after an argument. This may be inobvious to a user (me), as option and argument are words with very similar meaning. Listing the possible arguments in the the Usage would mitigate this

Say: `gopass.exe generate [command options] [secret [key [length ...?]]]`

### Problem c
`PS > gopass generate Account/example.com 16 -c` results in

`Error: password length must be a number`
Again, an option follows an argument. So gopass attempts to generate a password for the key `16` into `Account/example.com` and complains about `-c` not being a number.

It would be very helpful if gopass informed the user of what `generate` recognized as arguments, if any were provided.

### Environment

- OS: Windows 10 Pro
- OS version: 19041.928
- gopass Version: gopass 1.12.5+1878ea5df0c58dadc215342f3a7d024cd8378174
- Installation method: scoop

**Comment by dominikschulz** [comment]
Thank you very much for the detail report and the suggestions.
