### ISSUE TITLE
Automatically add creators gpg key to recipients

### ISSUE THREAD

**Issue by innovate-invent** [gopasspw/gopass#1919]
### Summary
I just created a mount/repo, added another recipient, synced, and had the other person run `gopass recipients`.
It says that my gpg key is missing and they can not create secrets without it.

Manually running `gopass recipients add --store foo my_gpg` worked around this issue, adding my key as a recipient.

### Expected behavior
My gpg key should be automatically included in the recipients upon initialization of the store.

### Environment

- OS: Arch and OSX
- gopass Version: gopass 1.12.5 (2021-03-29 17:27:06) go1.16.2 linux amd64
- Installation method: from the respective package managers

**Comment by dominikschulz** [comment]
This should work. Could you provide a detailed list of steps/command you entered so we can reproduce?

**Comment by innovate-invent** [comment]
I think the key difference might be that I created the repo on github and used `gopass clone` rather than using `gopass init`.

I also had an issue where adding a third recipient, gopass simply failed to copy in their pubkey every time I retried. I eventually had to just do it manually. The recipient did appear in the .gpg-keys list though.

**Comment by dominikschulz** [comment]
I have tested this and couldn't fully reproduce it. But I found some related useability issues that I'm trying to fix. Please let me know if the original issue is still reproducible from HEAD and provided detailed instructions how to reproduce.

**Comment by innovate-invent** [comment]
Were you testing creating a main repo, or a sub-mount?
