### ISSUE TITLE
Gopass not pushing all keys to remote

### ISSUE THREAD

**Issue by mRcSchwering** [gopasspw/gopass#1920]
### Summary

Not all keys seem to be pushed to the remote gitlab repo.

I have used gopass for a few years now on only one machine.
Since, after editing or creating a new key gopass always pushes changes to git, I always thought that the git repo is always up to date.

Recently, I cloned this key store from another computer `gopass clone <repourl>`.
After running `gopass sync` and looking into the keys I noticed that like 50% of keys were missing and there were some keys which I actually deleted long ago.
Then I started browsing the actual repo on gitlab and noticed that it's the same situation on the remote.

I went back to my first machine and did `gopass sync` which then says:

```
Sync starting ...
[<root>] 
   git pull and push ... OK (no changes)
   importing missing keys ... OK
   exporting missing keys ... nothing to do
   done
All done
```

Does anyone have an idea what the problem could be?

#### Edit

I tried adding a new key on machine 1, then sync machine 2, and delete it on machine 2, then sync on machine 1:

```
Sync starting ...
[<root>] 
   git pull and push ... OK (Removed 1 entries)
   importing missing keys ... OK
   exporting missing keys ... nothing to do
   done
All done
```

So, this worked as expected.
But somehow there is this a 50% mismatch of keys on machine 1 and the remote.
`gopass sync` doesnt seem to see this mismatch.

### Environment
On my first machine:

- OS: Ubuntu 20.04.2 LTS
- gopass Version: gopass 1.9.2+e2d1549f452a0df1fc52e42e7d0f654334d7144e (e2d1549f452a0df1fc52e42e7d0f654334d7144e) go1.14.2 linux amd64
- Installation method: via gopass_1.9.2_linux_amd64.deb

**Comment by mRcSchwering** [comment]
## Edit 2

I just went into the `.password-store` on machine 1 and did `git status`.
There are many untracked files and unstaged changes.

1. Can I just manually `add .` and commit or will gopass be confused then?
2. Shouldn't `gopass sync` see these changes?

**Comment by dominikschulz** [comment]
You can always do what you want in the git repo, yes.

Since `gopass sync` will usually only invoke `git` this should be fine.

As for why they are untracked I don't really know. You mention that you've been using that for a long time. In the past we did have some issues with git handling, maybe this was when these files were left untracked. If so it might be a good idea if we make `gopass fsck` check for and possibly correct this situation.

**Comment by mRcSchwering** [comment]
I guess that could have been the problem.

Well, I did `git add /commit/push` and `gopass fsck`. Everything still working, so no problem anymore.
Thx

**Comment by AnomalRoil** [comment]
One thing you might want to check is whether the passwords stored in these
untracked files are correct or not.
Did you have any merge conflicts when pushing these untracked files? If so,
then some passwords might have been overwritten by wrong ones...
If not, then indeed everything should work.
