### ISSUE TITLE
git-credential-gopass not working

### ISSUE THREAD

**Issue by matthias-wright** [gopasspw/gopass#1925]
### Summary

According to the [description](https://github.com/gopasspw/git-credential-gopass/blob/c845a779b0231362175d5c404dcc5f2fc04d20ba/main.go#L65), git-credential-gopass should be configured as follows:
`git config --global credential.helper gopass`

However, when I push something to a private repo after configuration I get the error message:` git: 'credential-gopass' is not a git command. See 'git --help'.`

### Steps To Reproduce
1. Install and init gopass
2. Install git-credential-gopass
3. Run the command: `git config --global credential.helper gopass`
4. Push something to a private repo

### Expected behavior
git-credential-gopass should cache the git credentials.

### Environment

- OS: Ubuntu 20.04.2 LTS
- OS version: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-72-generic x86_64)
- gopass Version: gopass 1.12.6-git+HEAD go1.16.4 linux amd64
- Installation method: `go get github.com/gopasspw/gopass` and `go get github.com/gopasspw/git-credential-gopas`

**Comment by dominikschulz** [comment]
I have to admit I've never used that helper myself.
All my git repos use the ssh support.

Maybe someone who does use it can help here.

**Comment by TM2500** [comment]
Hi
I'm using the git-credentials with gopass at a regular basis.

I tried to reproduce your problem in a clean VM, but failed.

One thing that pops into my mind with that error, is that either `gopass` or `git-credentials-gopass` isn't in your `$PATH`.
