### ISSUE TITLE
gopass show - output broken?

### ISSUE THREAD

**Issue by dR3b** [gopasspw/gopass#1927]
### Summary - Steps To Reproduce
Create a new "Secret" with the following command `gopass insert --multiline <FILE1>`

The content is as follows:

```bash
2fa: 123456789
codes:
  987654321-123456789
  987654321-123456789
ssh-key:
  sshkey
  sshkey.pub
ssh-key-pass:
  123456789
```

Display the new secret `gopass show <FILE1>`

```bash
Secret: <FILE1>

2fa: 123456789
codes:
ssh-key:
ssh-key-pass:
  987654321-123456789
  987654321-123456789
  sshkey
  sshkey.pub
  123456789
```

Why is the output not exactly the same?

### Expected behavior
This output:
```bash
2fa: 123456789
codes:
  987654321-123456789
  987654321-123456789
ssh-key:
  sshkey
  sshkey.pub
ssh-key-pass:
  123456789
```

### Environment
- OS: `Arch Linux`
- OS version: `Linux .... 5.12.3-arch1-1 #1 SMP PREEMPT Wed, 12 May 2021 17:54:18 +0000 x86_64 GNU/Linux`
- gopass Version: `gopass 1.12.6`
- Installation method: `yay -S gopass`

Thanks

**Comment by AnomalRoil** [comment]
My guess is that our parsing thought that this was a so-called "key-value" secret.
Please read:
https://github.com/gopasspw/gopass/blob/master/docs/commands/show.md#parsing-and-secrets

You can disable that on a single call by calling "gopass show -n <entry>" or you can disable it altogether by setting `gopass config parsing false`

**Comment by dR3b** [comment]
Thanks, I have disabled this globally.
