### ISSUE TITLE
gopass show -N argument doesn't exist

### ISSUE THREAD

**Issue by innovate-invent** [gopasspw/gopass#1939]
https://github.com/gopasspw/gopass/blob/ea944f7c5b84b73042ce4a1c32e0f424ccdb2ddb/gopass.1#L31

according to the documentation this argument should exist

```
gopass -v
gopass 1.12.6 (2021-05-11 15:27:04) go1.16.4 linux amd64

gopass show -N 1 ...
Incorrect Usage: flag provided but not defined: -N
```

**Comment by dominikschulz** [comment]
`-N` is a number, e.g. `-1` or `-2`.

**Comment by AnomalRoil** [comment]
Usage is actually:

`gopass show -revision -1 name/of/entry` and it will display the very first revision of that entry, i.e. the entry as it was upon creation.

`gopass show -revision -2 name/of/entry` and it will display the second revision.

Or you can use :
`gopass history name/of/entry` which will list all revisions and show a specific revision using its commit hash (or a shortened version of it):
`gopass show -revision 8af813 name/of/entry`

**Comment by tomkel** [comment]
a little confusing for me because i expected `gopass show --revision -1` to show the newest like `git log -1` does
