### ISSUE TITLE
gopass insert [name] [key] fails to handle multiline YAML entries

### ISSUE THREAD

**Issue by innovate-invent** [gopasspw/gopass#1940]
### Summary
With a secret of the format:
```
pass
key1: |
  text
  moretext
```

inserting a new key will yield
```
pass
key1: |
key2: content
  text
  moretext
```

gopass insert also fails to properly handle inserting multiline YAML strings

even manually adding the entries, gopass show fails to output the content:
```
gopass show secret key1
key1: |
```

### Steps To Reproduce
```
echo "|\n  text\n  moretext" | gopass insert secret key1
echo "content" | gopass insert secret key2

### Expected behavior
The secret should respect the YAML
```
pass
key1: |
  text
  moretext
key2: content
```

### Environment
<!--
Please complete the following information (see note below)
-->

```
uname -a
Linux manjaro 5.11.19-1-MANJARO #1 SMP PREEMPT Fri May 7 17:34:25 UTC 2021 x86_64 GNU/Linux
gopass --version
gopass 1.12.6 (2021-05-11 15:27:04) go1.16.4 linux amd64
```

- Installation method: pacman

<!--
**PLEASE NOTE**

There is a package named gopass in the official Debian repository.
This package is not related to this project in any way. If you
installed gopass from the Debian archives report any bugs in
the Debian BTS.
-->

### Additional context
<!--
Add any other context about the problem here.
-->

**Comment by dominikschulz** [comment]
Hmm, I don't think I've ever tried inserting multi-line keys.
If you want to help fix this contributing a test case would be appreciated.

**Comment by innovate-invent** [comment]
I dug into the code and it appears to be a documentation issue:

https://github.com/gopasspw/gopass/blob/1629395a8269a822c93d5f8892201bbc9ae96f1d/pkg/gopass/secrets/yaml.go#L21-L32

https://github.com/gopasspw/gopass/blob/1629395a8269a822c93d5f8892201bbc9ae96f1d/pkg/gopass/secrets/kv.go#L38-L72

YAML format explicitly requires the "---" or it will be parsed as KV
