### ISSUE TITLE
Please allow `--strict` to be chained with `--symbols`

### ISSUE THREAD

**Issue by skewballfox** [gopasspw/gopass#1941]
### Summary
Right now it seems that `--strict` and `--symbols`/`-s` are mutually exclusive, with strict taking priority. These should have the option to be chained together in order to form passwords that have strictly have one member from each char group, symbols included. 

The reason these should be chained rather than overriding the behavior of `--strict` is there are websites which require uppercase letters, lowercase letters, digits, **and special characters**, just as there are websites that require strict passwords **that do not allow special characters**(for some stupid reason).

the former currently requires continuously generating passwords with the `-s` flag until one meets the requirements. 

### Steps To Reproduce
`gopass generate --symbols --strict any.given.website/user@email`
 
### Expected behavior
a password with a member from each class `a-z`,`A-Z`,`0-9` `!@#$%^&*()-_+=[{]},<.>/?;:'"\`~\\|`

### Environment

- OS: fedora 34
- OS version: 5.12.8-300.fc34.x86_64 #1 SMP Fri May 28 15:20:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- gopass Version: gopass 1.12.5 
- Installation method: copr `daftaupe/gopass`

**Comment by dominikschulz** [comment]
Yes, I agree that this should be supported.
