### ISSUE TITLE
`gopass show` breaks encrypted RSA private keys

### ISSUE THREAD

**Issue by floriankessler** [gopasspw/gopass#1942]
### Summary

`gopass show` breaks encrypted RSA private keys by converting the meta keys in the RSA key's header to lowercase.

### Steps To Reproduce

```bash
# Create encrypted RSA key and store it via gopass
openssl genrsa -des3 -out private.pem -passout pass:foobar 2048
cat private.pem|gopass insert playground/private.pem

# This mangles the RSA key's header to lower case 
gopass show playground/private.pem|head -n6

# openssl chokes on the lower case header
gopass show playground/private.pem|openssl rsa

# The store itself is fine. This will ask -as expected- for the key's passphrase
gpg --decrypt ~/.local/share/gopass/stores/root/playground/private.pem.gpg|openssl rsa
```

### Expected behavior

The expected behaviour is not to touch/mangle the secret at all, so that the output of `gopass show` aligns with the output og `gpg`

```bash
# Should yield the same result. Does not.
gopass show playground/private.pem|head -n6
gpg --decrypt ~/.local/share/gopass/stores/root/playground/private.pem.gpg|head -n6
```

### Environment

- OS: Ubuntu 20.04.2 LTS
- OS version: Linux fkecldtag 5.8.0-55-generic #62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linu
- gopass Version: gopass 1.12.6+v1.12.6 (v1.12.6) go1.16.4 linux amd6
- Installation method: binary release from github

### Additional context

```bash
GOPASS=~/Downloads/gopass-1.12.6

cd ~
rm -rf ~/.config/gopass/ ~/.local/share/gopass/stores/* /tmp/gopass-test

${GOPASS} init

openssl genrsa -des3 -out private.pem -passout pass:foobar 2048
cat private.pem|${GOPASS} insert playground/private.pem

${GOPASS} show playground/private.pem|openssl rsa
gpg --decrypt ~/.local/share/gopass/stores/root/playground/private.pem.gpg|openssl rsa
```

**Comment by AnomalRoil** [comment]
Have you tried using the `-n` flag to disable any kind of parsing on the output?
See:
https://github.com/gopasspw/gopass/blob/master/docs/commands/show.md#flags
and the section about parsing at the end.

My guess is that the parser recognises the
```
Proc-Type: 4,ENCRYPTED
DEK-Info: DES-EDE3-CBC
```
as being key-values and so parses it as a KV secret.

**Comment by floriankessler** [comment]
Hi AnomalRoil,

en point! `gopass show -n playground/private.pem|openssl rsa` works as expected.
Thank you very much!

Still, would it make more sense to **not** have it as default?

- To me -new user - it came as a surprise.
- For existing users it will break scripts.
- what is the use case of of the current default, anyway? 

Best,
Florian

**Comment by AnomalRoil** [comment]
The ability to have "key-value" secrets to be able to use gopass to store URLs, usernames, etc and easily call them is a long time "default". We've changed a bit the logic recently after removing the MIME type and added the `-n` flag to avoid breaking people's scripts too much.

If you really hate it / never use key-values you can change your config to disable parsing by running:
`gopass config parsing false`

Regarding the typical usage pattern:
```
$ gopass new
🌟 Welcome to the secret creation wizard (gopass create)!
🧪 Hint: Use 'gopass edit -c' for more control!
[ 0] Website Login
[ 1] PIN Code (numerical)
[ 2] Generic

Please select the type of secret you would like to create (q to abort) [0]:
0
🧪 Creating Website login
  [1] URL                                    []: test.com
  [2] Login                                  []: Me
  [3] Generate Password?                     [Y/n/q]: y
    [a] Human-pronounceable passphrase?      [y/N/q]: n
    [b] How long?                            (q to abort) [24]:
    [c] Include symbols?                     [y/N/q]:
    [d] Strict rules?                        [y/N/q]:
  [4] Comments                               []: recovery code is PaQgf94hnf857f-35sn
✅ Credentials saved to "websites/test.com/Me"
✔ Copied websites/test.com/Me to clipboard. Will clear in 45 seconds.

$ gopass show -c  websites/test.com/Me url
test.com

$ gopass show websites/test.com/Me username
Me

$ gopass insert websites/test.com/Me api-key
websites/test.com/Me:api-key []: 0u592jlwgfiers0982538u092354egr

$ gopass show websites/test.com/Me api-key
0u592jlwgfiers0982538u092354egr
```
Etc.

This is particularly useful if you're using Gopass with a dmenu or rofi script as described here: https://github.com/gopasspw/gopass/blob/720e908e160acba1fea59248481633cdb3a628ef/docs/setup.md#dmenu--rofi-support
since it allows for auto-typing usernames, urls and passwords easily.

**Comment by floriankessler** [comment]
Hi AnomalRoil,

thank you very much for you timely response!

I do not hate it, I was just taken by complete surprise.
And yes, I should have taken the time and read the documentation.  Still, even in hindsight, I'd interpret `show` more in terms of "dump". You are using it more as a "select"...

Anyway, I'm fine with `show -n`.

Thanks again,
Florian
