### ISSUE TITLE
Setting a gopass remote fails when `defaultBranch = main`

### ISSUE THREAD

**Issue by dim** [gopasspw/gopass#1945]
### Summary

Gopass assumes the main branch to be named `master` which is becoming less and less common (both Github and Gitlab use `main` as the default branch name). 

### Steps To Reproduce

Set the default branch name to `main` (requires Git v2.28+) and run `gopass setup`

```
$ git config --global init.defaultBranch main
$ gopass setup
...
❓ Do you want to add a git remote? [y/N/q]: y
Configuring the git remote ...
Please enter the git remote for your shared store []: git@github.com:myorg/passdb.git
2021/06/21 14:38:37 failed to setup git remote: failed to push to git remote: exit status 1: error: src refspec master does not match any
error: failed to push some refs to 'git@github.com:myorg/passdb.git'
```
### Environment

- OS: Ubuntu 20.04 LTS
- gopass Version: gopass 1.12.6+8d7a311b9273846bbb618e4bd9ddbae51b1db7b8  go1.16.3 linux amd64
- Installation method: binary release, amd64

**Comment by AnomalRoil** [comment]
Mhhh, that's a bit annoying since `main` is becoming common. We'll look into it.

**Comment by bearcatsandor** [comment]
So, for those of us with 'main' as our default branch, how do we work around this? 

It seems like a show-stopper?

**Comment by dominikschulz** [comment]
I have no plans to work on this. But you can use any branch name even if the default is different.

**Comment by dim** [comment]
@dominikschulz sorry, I am obviously not that familiar with the code base, but isn't the fix as simple as changing these 2 lines https://github.com/gopasspw/gopass/blob/master/internal/action/setup.go#L208-L211 by replacing `"master"` with an empty string `""`? Wouldn't `gitfs` then do the right thing via https://github.com/gopasspw/gopass/blob/master/internal/backend/storage/gitfs/git.go#L271?

**Comment by AnomalRoil** [comment]
@dim That actually looks like it. Do you want to submit a PR or shall I?

In the meantime you can still setup your password store using git manually:
```
mkdir -p /path/to/your/new/store
cd /path/to/your/new/store
git init
gopass config path /path/to/your/new/store
```

**Comment by dominikschulz** [comment]
Maybe that's all it takes. But IIRC this assumption is hard coded in a few places and I sonst l didn't want to hunt them down.

**Comment by dim** [comment]
@dominikschulz I briefly grepped the code, it only seems to be used in:

* helpers/postrel/main.go - relates to `github.com/gopasspw/gopass#master`?
* helpers/release/main.go - relates to `github.com/gopasspw/gopass#master`?
* internal/backend/storage/gitfs/git_test.go - using it in tests is fine
* internal/store/leaf/rcs_test.go - using it in tests is fine
* internal/action/setup.go - THAT's the only place I found that needs fixing

**Comment by dominikschulz** [comment]
@dim Ok, let's try it. But I won't have too much time to spend on this going forward. If there is more to this someone else would need to take care.
