### ISSUE TITLE
macOS: git over ssh wrong file permissions

### ISSUE THREAD

**Issue by aymanbagabas** [gopasspw/gopass#1946]
### Summary

Gopass Git is not able to pull/fetch the repository. Git is not able to communicate with the ssh-agent and I keep getting this SSH error every time I try to use a Git related Gopass command. I noticed fixing the permissions fixes the problem. The password store has these permissions, directories `700`, files `600`, and changing them to `755` and `644` respectively fixes the issue.
```
› gopass sync
🚥 Syncing with all remotes ...
[<root>]
   git pull and push ... Skipped (no remote)
[<my-remote-private-repository>]
   git pull and push ... ⚠ Failed to pull before git push: exit status 1: unix_listener: path "/var/folders/v3/5pnzpycs0pzdpytmgfzc7tj80000gn/T//.ssh-1e25961f1d73a0c01e9dc5758de11744b777931d.g4fuPOi40otuQpzO" too long for Unix domain socket
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
❌ Failed to push "<my-remote-private-repository>" to its remote: exit status 128: unix_listener: path "/var/folders/v3/5pnzpycs0pzdpytmgfzc7tj80000gn/T//.ssh-1e25961f1d73a0c01e9dc5758de11744b777931d.PigaO4YBexcHychd" too long for Unix domain socket
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
✅ All done
```

### Steps To Reproduce

Running any command that involves Git ex. `gopass sync`

### Expected behavior

Git under Gopass should be able to access the ssh-agent to be able to communicate with the remote repository since I'm using git+ssh

### Environment

- OS: macOS Big Sur
- OS version: `Darwin Aymans-MacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`
- gopass Version: `1.12.6-git+HEAD go1.16.5 darwin amd64`
- Installation method: `go get github.com/gopasspw/gopass`

**Comment by aymanbagabas** [comment]
As suggested in the FAQ, setting `TMPDIR` didn't help PR https://github.com/gopasspw/gopass/pull/1899. What I ended up doing is using `GIT_SSH_COMMAND` environment variable and aliasing `gopass` to
```
GIT_SSH_COMMAND="ssh -oControlMaster=auto -oControlPersist=600 -oControlPath=/tmp/.ssh-%C" gopass
```

**Comment by AnomalRoil** [comment]
Did you see this: https://github.com/gopasspw/gopass/issues/1896#issuecomment-854193711 ?

Maybe you have some "leftover SSH settings" in your git config?

**Comment by aymanbagabas** [comment]
Interestingly, it turned out that the git password store git config had a long ssh command path which was causing the problem. I still don't know how and why that got set in the config. But changing the ssh command control path to `/tmp/.ssh-%C` in the git config solves the problem
