### ISSUE TITLE
Gopass alters output

### ISSUE THREAD

**Issue by shibumi** [gopasspw/gopass#1947]
### Summary

When storing the following secret:

```
export AWS_ACCESS_KEY_ID=REDACTED
export AWS_SECRET_ACCESS_KEY=REDACTED
export RESTIC_PASSWORD=REDACTED
export RESTIC_REPOSITORY="s3:s3.wasabisys.com/REDACTED"
```

`gopass show <secret path>`

shows the following output:

```
Secret: restic/<path>

export AWS_ACCESS_KEY_ID=REDACTED
export restic_repository="s3: s3.wasabisys.com/REDACTED"
export AWS_SECRET_ACCESS_KEY=REDACTED
export RESTIC_PASSWORD=REDACTED
```

There are several things wrong here:

1. Gopass changes the order of the content
2. Gopass alters the variable name of RESTIC_REPOSITORY (it's suddenly lowercase)
3. It inserts a whitespace after the colon in the string "s3:s3.wasabisys.com/REDACTED"

This behavior is probably dangerous, because the output isn't consistent and breaks automation (for example importing the environment variables via $(gopass show  <path>)

### Steps To Reproduce

Create the secret from above via `gopass edit --create <path>`
Use `gopass show <path>` to show the secret

### Expected behavior

Gopass should **never** alter or modify the output of a secret.

### Environment

- OS:Arch Linux
- OS version:`Linux motoko.shibumi.dev 5.12.12-arch1-1 #1 SMP PREEMPT Fri, 18 Jun 2021 21:59:22 +0000 x86_64 GNU/Linux`
- gopass Version: gopass 1.12.6 (2021-05-11 15:27:04) go1.16.4 linux amd64
- Installation method:  pacman

### Additional context

Full `gopass version` output:

```
gopass 1.12.6 (2021-05-11 15:27:04) go1.16.4 linux amd64
<root>     - gpg 2.2.28 - git 2.32.0
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs
```

**Comment by AnomalRoil** [comment]
My guess is that our parsing thought that this was a so-called "key-value"
secret.
Please read:
https://github.com/gopasspw/gopass/blob/master/docs/commands/show.md#parsing-and-secrets

You can disable that on a single call by calling gopass show -n <entry> or
you can disable it altogether by setting gopass config parsing false

**Comment by shibumi** [comment]
@AnomalRoil  wouldn't it make sense to only parse key/value pairs if the file starts with `---`?

**Comment by dominikschulz** [comment]
No, I'm afraid. We've been there. Long story short: We can't make any assumptions about the content of a secret.

The best we can offer are some command line switches and a config setting.

**Comment by shibumi** [comment]
I understand. Then it is definitely my fault. Closing this.

The answer for the problem is `gopass show -n`

**Comment by shibumi** [comment]
@dominikschulz  mhhh I am just afraid there is one additional problem.
If I use `gopass show -n` it will also show the `Secret: <name>` header.. but I only want the content. Is it save to delete this "Secret" header? Will gopass re-add it?

**Comment by dominikschulz** [comment]
It's not part of the secret. It should only be printed to the terminal. If you redirect the output it shouldn't be there.
