### ISSUE TITLE
`gopass sync` doesn't notice staged, un-commited changes?

### ISSUE THREAD

**Issue by colemickens** [gopasspw/gopass#1962]
Well, this would certainly explain the numerous times I've found myself completely hosed and stranded without a synced password and finding myself having to manually issue git commands to unstick myself.

This is really painful. Even a warning would be helpful.

```
PS C:\Users\colem\.password-store> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   instagram.gpg


PS C:\Users\colem\.password-store> gopass sync
🚥 Syncing with all remotes ...
[<root>]
   git pull and push ... OK (no changes)
   importing missing keys ... OK
   exporting missing keys ... nothing to do
   done
✅ All done
PS C:\Users\colem\.password-store>
```

**Comment by AnomalRoil** [comment]
Agreed, I recently had the same happening to me and wanted to also understand how these were created without being committed as that's also another bug probably.

But I think a warning by both sync and fsck would be definitely useful. I'll have a look at it soon.

**Comment by dominikschulz** [comment]
If this happens it's definitely a bug. A very annoying one. There are certain edge cases and apparently we haven't managed to cover them all.

But warning on sync sounds an good option.

**Comment by dominikschulz** [comment]
In #1972 I have implemented a simple warning when untracked files are found. Let me know if you think that's enough or if we need a better way to inform the user.
