### ISSUE TITLE
[Question] How to generate passwords with symbols to stdout without initializing gopass?

### ISSUE THREAD

**Issue by sgon00** [gopasspw/gopass#1965]
Hi, I am using `gopass` to generate random passwords only. I don't need it to store anything and don't need any other advanced features.

So far, I figure out I can run `gopass pwgen` to generate passwords. But with `gopass pwgen -h`, I don't figure out how to make the password contain symbols. All the passwords in stdout will not contain any symbols.

I tried `gopass generate`, but it prints out error message: `Error: not initialized`. I don't want to initialize gopass. All I want is to generate random passwords to stdout. 

Thanks a lot.

**Comment by dominikschulz** [comment]
`gopass generate` inserts a generated password into a store. So it does need to be initialized.
`gopass pwgen` should work w/o an initialized store as well.

But indeed we don't have a flag to add symbols to pwgen, yet.
