### ISSUE TITLE
Default path config

### ISSUE THREAD

**Issue by mastertinner** [gopasspw/gopass#1967]
### Summary

It would be nice to have a default for the `path` config parameter. I would suggest having it default to `~/.local/share/gopass/stores/root` if the config parameter is not set.

**Comment by dominikschulz** [comment]
What do you mean exactly?
We have a default value for the path.

I assume you're talking about the case when the config exists but the value for path is missing?

**Comment by mastertinner** [comment]
Correct

**Comment by mastertinner** [comment]
I think the default configs for these two cases might be a bit inconsistent in general, no? I just noticed that, if I don't have a config file at all, `notifications` seems to default to `true`. However, if I have a config file which doesn't set the `notifications` parameter, it defaults to `false`.

**Comment by AnomalRoil** [comment]
That's because we don't officially support partial config files that aren't specifying all settings values. So the missing items are initialized to Go's default values instead of Gopass' default ones.

**Comment by dominikschulz** [comment]
Exactly. I'd like to support partial configs with proper default, but I do worry that config parsing might become more complicated than it already is.

Maybe [cue](https://cuelang.org/) might be worth a try.

**Comment by mastertinner** [comment]
I guess that would go into the direction of https://github.com/gopasspw/gopass/issues/1819
