### ISSUE TITLE
[question] Replacing GPG key for user?

### ISSUE THREAD

**Issue by olegbliaher** [gopasspw/gopass#1969]
### Summary
I have a particular user with the email address user@domain.com.

The user first had a "regular" GPG-key, and they later replaced it with a PGP-key attached to a Yubikey. I thought the right way to manage this transition was to run `gopass recipients remove user@domain.com` , followed by `gpg --delete-keys USERSKEYID` , and then run `gpg --import < users-new-key.pub.asc` and `gopass recipients add user@domain.com`.

Unfortunately, this doesn't really reencrypt the passwords. All other users can still access the passwords.

### Steps To Reproduce
`gopass show old-secret`

gives 

```
gpg: decryption failed: No secret key
❌ Decryption failed: exit status 2
```

### Expected behavior
I guess I'd expect gopass to reencrypt all passwords with the existing public keys, and thus to show the password upon running `gopass show`

### Environment
- Debian 10
- 5.10.16.3-microsoft-standard-WSL2
- gopass Version: go1.16.5 linux amd64
- Installation method: gopass repo

I guess I'd like to know if there's a way to reecnrypt the passwords correctly, or if there is some kind of a disaster recovery routine? A work around would be to assign a new email address to that user, but I'm guessing I'm just missing something pretty basic?

### EDIT:
After trying to simply add the new PGP-key via `gopass recipients add NEW_KEY_ID` and resyncing everything (even tried `gopass fsck` a few times I simply get the following error every time I try to decrypt a password:

`Error: empty secret`

It works for other users (who had not changed their GPG-key).

**Comment by AnomalRoil** [comment]
Could this be related to your Gopass having an issue with its `.public-keys` folder? Can you check if you have a dotfile in your store that's still containing the "old" (sub)key fingerprint?

Are you adding a specify "subkey" as recipient or just the master key of your recipient?

Do you have maybe a clash between `gpg` and `gpg2`, where you only updated the one gopass isn't using?

What does `gpg -k --with-subkey-fingerprints user@domain.com` or `gpg2 -k --with-subkey-fingerprints user@domain.com` tell you about the key?

RE: `gopass fsck`, you need to use the `--decrypt` flag if you want fsck to re-encrypt your whole store.
Also, what version of `gopass` are you running?

**Comment by olegbliaher** [comment]
Hi! No dotfiles in `.public-keys`

I think I was adding the master key, not sure though. I just took the ID from `gpg --list-keys` as the email address was already used.
`gpg` and `gpg2` are the same, gpg2 is a symlink to gpg.

`gpg -k --with-subkey-fingerprints user@domain.com` gives me 2 results:

```
pub   rsa2048 2021-08-03 [SC]
      KEYID
uid           [ultimate] Fname Lname <user@domain.com>
sub   rsa2048 2021-08-03 [A]
      KEYID
sub   rsa2048 2021-08-03 [E]
      KEYID

pub   rsa3072 2021-07-16 [SC] [expires: 2031-07-14]
      KEYID
uid           [ unknown] Fname Lname (Fname ) <user@domain.com>
sub   rsa3072 2021-07-16 [E] [expires: 2031-07-14]
      KEYID
```

I want to use to first one (marked with ultimate), not the 2nd one. Both show when I run `gopass recipients` and I cannot remove the first one that is not being used.  (I get `Error: failed to remove recipient "OLDKEYID": recipient not in store`

This makes it a problem for `gopass fsck --decrypt` - 

`❌ Extra recipients on test: [OLDKEYID]`

Sorry, see that I wrote the Go version previously... I'm running gopass 1.12.7.

**Comment by olegbliaher** [comment]
I've now tried adding another user with another email address, and that user can only see new passwords they themselves created. `show` on any other password (either old one or one newly created by another user) gives the following error:

`Error: empty secret`

Could it be that it's a wrong GPG key added to gopass?
