### ISSUE TITLE
Question: Installing gopass using the binary only?

### ISSUE THREAD

**Issue by trallnag** [gopasspw/gopass#1970]
Is it possible to install gopass simply by using the binary build by Go? Just wondering why there is a need for going through OS package managers / deb files and so on

**Comment by AnomalRoil** [comment]
Yes, it's totally possible. You just need a binary meant for your platform, but that's basically what you find in our [Release page](https://github.com/gopasspw/gopass/releases).

Then you just put the binary somewhere on your path and you can even update it by just running `gopass update`

**Comment by trallnag** [comment]
Alright, thanks
