### ISSUE TITLE
gopass insert hangs to commit for lengthy string

### ISSUE THREAD

**Issue by prabhu43** [gopasspw/gopass#1971]
### Summary

gopass insert using echo changes the store and stage the changes in git but not commiting the changes and hangs forever. Even Ctrl+C not working, I have to close the terminal to exit.

### Steps To Reproduce

Working: echo "01234567890123456789" | gopass insert -f STORE/KEY

Not working: echo "012345678901234567890" | gopass insert -f STORE/KEY

### Expected behavior

gopass insert should work for lengthy string

### Environment

- OS: Mac OS X Catalina

- OS version: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64

- gopass Version: 
gopass 1.12.7 (2021-07-02 14:49:12) go1.16.5 darwin amd64
<root>     -  gpg 2.3.1 - git 2.31.1
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs

- Installation method: brew

**Comment by AnomalRoil** [comment]
Ohhh, this might explain how I ended up having the same issue as in #1962.
But it's definitively another bug.

**Comment by dominikschulz** [comment]
Sorry, I can't reproduce the issue.

Are the "Steps to reproduce" complete? Without a trailing path to a secret I get an usage error.

**Comment by prabhu43** [comment]
Hi @dominikschulz , 
I updated the command. I cannot the share the actual key path. And I hope key path will not be the issue.

**Comment by AnomalRoil** [comment]
This is really weird, I couldn't reproduce on Darwnin neither.

Could you maybe try to enable debug info and remove any sensitive information from it and paste it here?

This can be done using the following two env var:

GOPASS_DEBUG | bool | Set to any non-empty value to enable verbose debug output
--|--|--
GOPASS_DEBUG_LOG | string | Set to a filename to enable debug logging

E.g.:
```
echo "012345678901234567890" | GOPASS_DEBUG_LOG=gopass_debug.log gopass insert -f STORE/KEY
```
would create a local file containing the log.

**Comment by prabhu43** [comment]
Hi @AnomalRoil 

I tried the same command with DEBUG enabled. Got this error message in debug log file.

```
2021/08/09 14:35:21.540218 fs/store.go:57	fs.(*Store).Set	Writing $KEY to $FILE_PATH_TO_KEY
2021/08/09 14:35:21.540931 gitfs/git.go:127	gitfs.(*Git).captureCmd	store.gitAdd: /usr/local/bin/git [git add --all --force $KEY] ($FILE_PATH_TO_STORE)
2021/08/09 14:35:21.561579 queue/background.go:87	queue.(*Queue).Add	enqueued task
2021/08/09 14:35:21.562566 gitfs/git.go:127	gitfs.(*Git).captureCmd	store.gitDiffIndex: /usr/local/bin/git [git diff-index --quiet HEAD] ($FILE_PATH_TO_STORE)
2021/08/09 14:35:21.581145 gitfs/git.go:136	gitfs.(*Git).Cmd	CMD: gitDiffIndex [diff-index --quiet HEAD]
Error: exit status 1
Output:
  Stdout: ""
  Stderr: ""
2021/08/09 14:35:21.581328 gitfs/git.go:127	gitfs.(*Git).captureCmd	store.gitCommit: /usr/local/bin/git [git commit --date=1628499921 +00:00 -m Save secret to $KEY: ] ($FILE_PATH_TO_STORE)

```

**Comment by AnomalRoil** [comment]
That's really interesting: Gopass thinks you are trying to add a new key to a given entry. 
Do you have a space in your path and didn't escape it on the cmd line?

**Comment by prabhu43** [comment]
@AnomalRoil From docs of **git diff-index**
```
--exit-code
Make the program exit with codes similar to diff(1). That is, it exits with 1 if there were differences and 0 means no differences.

--quiet
Disable all output of the program. Implies --exit-code.
```

**Comment by AnomalRoil** [comment]
Are you trying to overwrite an existing entry, or are you creating a new entry?

**Comment by prabhu43** [comment]
@AnomalRoil No, the key name does not have spaces, but it starts with dot.
Yes, I am trying to overwrite existing entry

**Comment by AnomalRoil** [comment]
Is that on your root store or on a substore?

**Comment by prabhu43** [comment]
it is on my substore, not on root store

**Comment by prabhu43** [comment]
key name pattern is: STORE_NAME/STRING_WITH_UNDERSCORE/INTEGERS/STRING_WITH_DOTS_AND_STARTS_WITH_DOT

**Comment by AnomalRoil** [comment]
Yeah, the `Error: exit status 1` from gitDiffIndex is expected. I have the same on my setup but cannot reproduce the bug.

I just tried with a substore and such a path...

Do you have a special config in your git config for that substore?
Can you repro the issue on your root store too or is that just on that substore?

**Comment by AnomalRoil** [comment]
How long is your STORE_NAME/STRING_WITH_UNDERSCORE/INTEGERS/STRING_WITH_DOTS_AND_STARTS_WITH_DOT path? Close to 1000 characters?

**Comment by AnomalRoil** [comment]
I could see pre-commit hooks being an issue too, do you have anything like that?

**Comment by prabhu43** [comment]
yes @AnomalRoil . I am using talisman, which is blocking the commit. 
It works now after removing the talisman hooks from that repo. 

Thanks @AnomalRoil
