### ISSUE TITLE
Encrypt the whole store?

### ISSUE THREAD

**Issue by jcguu95** [gopasspw/gopass#1974]
### Summary

This is not a bug report, but a question. 

Is it possible to encrypt the whole password store using gopass API? Currently I have a github repo that holds my password store. However, while my passwords are encrypted, the file structure isn't. Therefore people who have access to my repo would know that I have `N` accounts on `XYZ` site.

(I've set the repo to private, but that doesn't mean 100% safe.)

**Comment by AnomalRoil** [comment]
Yes, that's the goal of the (alpha) `age`-based crypto backend with the "on-disk" storage backend.

See: https://github.com/gopasspw/gopass/blob/master/docs/backends/age.md
and: https://github.com/gopasspw/gopass/blob/master/docs/backends/ondisk.md

See related:
- #1560
- #673

**Comment by jcguu95** [comment]
Then this thread is indeed duplicate. Thanks for the info!

**Comment by dominikschulz** [comment]
Neverthless it's still a very good question. I did some experiments but so far didn't pick up that work again because it does impact the workflow a lot and it breaks compatability with other pass implementations.

In case you have any useful input on this I'm happy to hear you out.
