### ISSUE TITLE
Name clash => No show

### ISSUE THREAD

**Issue by jcguu95** [gopasspw/gopass#1976]
### Summary

Having `/gopass/site/abc.gpg` and `/gopass/site/abc/subaccount.gpg` prevent the former to be shown when calling `gopass ls`.

**Comment by AnomalRoil** [comment]
This is a shadowing case: 
https://github.com/gopasspw/gopass/blob/d00c29a0e8e521eb32e4564998690430dcc7dbbc/docs/commands/list.md#shadowing

Maybe we could change the expected behaviour to a more intuitive "the entry is listed and the repo too"

**Comment by jcguu95** [comment]
Sorry for having missed the detail in the doc. I find this confusing for new users. But if the dev group wants to keep it, I don't have strong opinions anyway. Please feel free to close this issue.

**Comment by dominikschulz** [comment]
Should have been fixed by https://github.com/gopasspw/gopass/pull/2341.
