### ISSUE TITLE
generate memorable password with --strict

### ISSUE THREAD

**Issue by tomkel** [gopasspw/gopass#1984]
### Summary

When you `gopass generate -g memorable` , it produces only lowercase passwords. When combined with `--strict` , uppercase some letters please?

### Steps To Reproduce

`gopass generate -g memorable -s --strict test 15`

outputs like

`alphabet5]soup4,`

### Expected behavior

a password with a member from each class, including uppercase `A-Z`, like `Alphabet5]soup4,`

### Environment

- OS: MacOS
- OS version: Big Sur 11.5
- gopass Version: 1.12.8
- Installation method: brew

**Comment by dominikschulz** [comment]
Sounds good. Maybe someone could contribute this.

**Comment by elijahjpassmore** [comment]
I would like to work on this and have a solution.
