### ISSUE TITLE
Evaluate survey

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#1990]
We should consider replacing most of `pkg/termio` with `github.com/AlecAivazis/survey`.

In terms of License (MIT), dependencies (few) and features (~all we need) it looks good.

**Comment by AnomalRoil** [comment]
Indeed, looks good and it would force a refactoring of the whole UX

**Comment by dominikschulz** [comment]
That sounds almost like a bad thing. Well at least like a lot of work.
But I think we could first give it a try for some less critical parts, e.g. `gopass create`.
And if that doesn't surprise us (bad) then we can consider doing a more holistic implementation.

**Comment by dominikschulz** [comment]
I did look into this a bit and it seems feasible, however we'd either need to keep a wrapper around that lib or we'd loose some of the hard-learned fixes for subtle issues.

However it might be an option for the less critical, more UX-heavy workflows like recipient selection or `gopass create`.
I'll try to adopt it for `gopass create` to see how well it works for us.

**Comment by dominikschulz** [comment]
Looking a little bit further I realized that it doesn't seem to support our nested dialogs. It can still be useful but not as useful as I first though.

Might be a good beginner issue to migrate some of our selection dialogs to this but I won't do it (probably).

**Comment by dominikschulz** [comment]
No progress here and no urgent need to prioritize this.
