### ISSUE TITLE
Allow specifying path to GPG

### ISSUE THREAD

**Issue by viq** [gopasspw/gopass#2003]
### Summary

This is orthogonal to #1757 / #1758 - I'm using https://www.qubes-os.org/doc/split-gpg/ ("kinda like smartcard, but done with VMs and RPC"), and I need to use a wrapper to be able to perform operations that use a key. I generally did that by symlinking `~/bin/gpg` and `~/bin/gpg2` to it, but it doesn't work with `gopass` using `gpgconf` instead of `PATH` to find the executable.

### Steps To Reproduce
Try to use a wrapper script around `gpg2` binary.

### Expected behavior
Ability to override which executable to use.

### Environment

- OS: Fedora 34 (AppVM on QubesOS R4.0)
- OS version: `Linux personal 5.14.9-1.fc25.qubes.x86_64 #1 SMP Fri Oct 1 08:13:33 CEST 2021 x86_64 x86_64 x86_64 GNU/Linux`
- gopass Version: `gopass 1.12.7 (2021-07-26 00:00:00) go1.16.5 linux amd64`
- Installation method: gopass repo

**Comment by dominikschulz** [comment]
I found gpgconf hard to use, poorly documented and not working as expected. We should really support overrides for all information we pull from gpgconf.

**Comment by viq** [comment]
Yay, thank you! \o/
