### ISSUE TITLE
... why do flags change the behavior of commands

### ISSUE THREAD

**Issue by colemickens** [gopasspw/gopass#2018]
### Summary
It's pretty simple, why do flags change the behavior of commands.

Why is there not just explicit commands, one of which always searches, the other of which never searches.

Instead... now `gopass show hotbit` works just fine and `gopass show hotbit --clip` results in `key not found in entry` which kinda just leaves a poor taste in my mouth all around.

Am I holding it wrong? What do others do? Always get the key exactly right? Not care that they're spamming their password and OTP secrets to their screens at any time?

**Comment by colemickens** [comment]
Circling back as I'm hitting this again. I guess was I'm finding here is that `--clip` is being interpreted as a field identifier in this text blob that gopass insists on treating as yaml? Yeah, guess, I really need to prioritize re-evaluating.

**Comment by colemickens** [comment]
This seems intentional, and seems fitting with the direction gopass has been moving in, so I'm just going to close this.

**Comment by AnomalRoil** [comment]
The trick is that for flags to work, you need to put them first, before the entry:
```
gopass show hotbit --clip 
```
doesn't trigger the `--clip` flag, but
```
gopass show --clip hotbit 
```
does.
