### ISSUE TITLE
Setup.md suggests the wrong path to pinentry-mac on apple silicon

### ISSUE THREAD

**Issue by boolanger** [gopasspw/gopass#2020]
### Summary

On Mac OS X,`setup.md` suggests adding the line

> pinentry-program /usr/local/bin/pinentry-mac

 to `gpg-agent.conf`. This is the wrong path for those who installed `pinentry-mac` as an arm binary using brew (on apple silicon).

### Steps To Reproduce
1. Install gopass as suggested in `setup.md`, including running `echo "pinentry-program /usr/local/bin/pinentry-mac" >> ~/.gnupg/gpg-agent.conf`.
2. Clone a password store.
3. Try to decrypt some password by running `gopass show SECRET`.
4. You should get `gpg: public key decryption failed: No pinentry`

### Expected behavior
`setup.md` should suggest adding the correct path to `pinentry-mac`, either by asking the user to run `which pinentry-mac` or by specifying `/opt/homebrew/bin/pinentry-mac` for apple silicon users.

### Environment

- OS: Mac OS X Monterey
- OS version: 12.0.1
- gopass Version: 1.12.8
- Installation method: brew

**Comment by dominikschulz** [comment]
I should get my hands on Apple Silicon for the first time soon. I'll try to reproduce while I set up gopass and update the instructions accordingly.
