### ISSUE TITLE
Support Fossil SCM

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#2022]
We should consider adding support for the fossil SCM.
It has a much simpler model than git and handles a few things ootb which we need to work around with git (e.g. autosync, no staging area, ...): https://fossil-scm.org/home/doc/trunk/www/quickstart.wiki

**Comment by dertuxmalwieder** [comment]
Also, it is much easier to backup a Fossil repository (you’ll just need to copy one file). Being a Fossil user myself, I very much support this feature. :)

**Comment by dertuxmalwieder** [comment]
As announced in #1560 I am currently spending some time trying to make gopass with `age` and Fossil fulfill my needs. Indeed, it is surprisingly nice to use, although it seems to have hard-coded fallbacks:

1. Typing a second `setup` defaults to Git+GPG again,
2. `sync` does not work ("Skipped (no Git repo)", why not just run `fossil sync`?),
3. I have not figured out how to use a remote Fossil repository yet, the first start wizard is rather silent on that.

**Comment by dominikschulz** [comment]
Thanks a lot @dertuxmalwieder 

Please open individual issues for these and we'll try to fix them.

But here it will get lost.
