### ISSUE TITLE
Autoclip on `generate` broken 

### ISSUE THREAD

**Issue by acaloiaro** [gopasspw/gopass#2023]
### Summary
Currently, autoclip on `generate` does not work as I beieve was intended. 

Clip-on-generate currently works by checking whether one of two conditions are met:
1. Is the `-c` flag `true`
2. Is `autoclip` true and is output _being redirected_  

I belive (2.) to be incorrect autoclipping behavior, and discordant with the comment preceding it:

```
// copy to clipboard if:
// - explicitly requested with -c
// - autoclip=true, but only if output is not being redirected
if IsClip(ctx) || (s.cfg.AutoClip && !ctxutil.IsTerminal(ctx)) 
```

As can be seen, the code actually checks that output _is_ being redirected, i.e. the output file descriptor is _not_ a TTY. 

### Steps To Reproduce

1. `gopass config autoclip true` 
2. `gopass generate -f foobar 24`
3. Prints "Not printing secrets by default. Use 'gopass show foobar' to display the password.". Contents of `foobar` will not be copied to clipboard 

*Unexpected behavior*
1. `gopass config autoclip true`
2. `gopass generate -f foobar 24 | cat`
3. Prints "Copied to clipboard". Contents of `foobar` _will_  be copied to clipboard 

### Expected behavior
In the above scenarios, I exect the contents of `foobar` to be copied to the clipboard in the first scenario, but not the second. In other words, the inverse of the actual behavior. 

### Environment
- OS: Ubuntu 20.04
- OS version: 5.13.0-7614-generic #14~1631647151~20.04~930e87c~dev-Ubuntu SMP Thu Sep 16 19:26:07  x86_64 x86_64 x86_64 GNU/Linux
- gopass Version: gopass 1.12.8-git+HEAD go1.17.1 linux amd64
- Installation method: `go install` of latest 

### Additional context
I'm happy to submit a PR for the fix if this is confirmed to be unexpected behavior.

**Comment by dominikschulz** [comment]
Thanks for reporting this. I didn't get a chance to verify it, yet. But this sounds and looks like a logic bug.

Feel free to send a PR.

**Comment by acaloiaro** [comment]
Once I have time to figure out how to write a test for output redirection, I'll submit the PR and test.
