### ISSUE TITLE
Release fails with make msi missing

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#2038]
It looks like #2001 was missing the `make msi` definition, e.g. [here](https://github.com/gopasspw/gopass/runs/4200291702?check_suite_focus=true).

**Comment by AnomalRoil** [comment]
Yeah I thought it wouldn't work directly, but I needed a release to test it. I'll try and fix it next week 👍🏻

**Comment by dominikschulz** [comment]
Did you happen to have this build target somewhere already?

Otherwise we might give [wixpy](https://github.com/sk1project/wixpy) a try.

**Comment by dominikschulz** [comment]
Or maybe [msi-packager]( https://www.npmjs.com/package/msi-packager ) is easier.

**Comment by AnomalRoil** [comment]
Maybe https://github.com/mh-cbon/go-msi could work too...
Or https://wiki.gnome.org/msitools.

Not sure what's the easiest way, but in theory adding a Makefile `msi` entry should get us there already from a CI/CD pov.
