### ISSUE TITLE
Add configuration options for custom clipboard commands

### ISSUE THREAD

**Issue by hashworks** [gopasspw/gopass#2042]
## Problem

*This is not a feature request but a request for discussion. I can implement it myself.*

Currently, `gopass` only handles unclipping for a small set of clipboard managers, for example  [KDE Klipper](https://github.com/gopasspw/gopass/blob/8586105f2704c2d02e515c154c8e0d0c0a2757d5/pkg/clipboard/unclip_linux.go#L20). For other clipboard managers the `unclip` procedure just doesn't work. Some clipboard managers support passwords out of the box (masking them), but `gopass` would need to support the way passwords are added to the clipboard manager.

For example, [GPaste](https://github.com/Keruspe/GPaste):
```bash
$ echo -n "This is a test" | wl-copy
$ gpaste-client
254de975-949b-4d8e-8f71-8ddf566ee97c: This is a test
$ gpaste-client add-password google.com secretString
$ gpaste-client
c6ef91f8-235f-4b6d-b8c7-108acd9c0f77: [Password] google.com
254de975-949b-4d8e-8f71-8ddf566ee97c: This is a test
$ gpaste-client delete-password google.com
$ gpaste-client
254de975-949b-4d8e-8f71-8ddf566ee97c: This is a test
```

## Suggested solution implementation

It would be great if one could specify custom commands for the `clip` and `unclip` procedure.

To archive that, I would add two new optional config options to [`internal/config/config.go`](https://github.com/gopasspw/gopass/blob/master/internal/config/config.go#L19):
* `clipcmd`: `gpaste-client add-password "{.Name}" "{.Password}"`
* `unclipcmd`: `gpaste-client delete-password "{.Name}"`

Both are template strings.

If `clipcmd` is set I would try to execute it in [`pkg/clipboard/clipboard.go`](https://github.com/gopasspw/gopass/blob/master/pkg/clipboard/clipboard.go#L30), if it fails the normal procedures are used.
Same for `unclipcmd`: If it is set I would try to execute it in [`pkg/clipboard/unclip.go`](https://github.com/gopasspw/gopass/blob/master/pkg/clipboard/unclip.go#L28), if it fails the normal procedures are used.

---

Does that sound reasonable?

**Comment by dominikschulz** [comment]
Adding config options is tedious because they need to be maintained and I'm not 100% sold on the names of the options.

But on the other hand I understand clearing the clipboard can be very important and I really like the pretext of your question ("I can send a PR") so I'd say let's do it.

@AnomalRoil any objections?

**Comment by AnomalRoil** [comment]
These options feels a bit like environment variables, I'd say, especially since they are system/environment dependent.

Maybe the default behaviour could be the current behaviour unless these env var are set?

**Comment by shibumi** [comment]
I think both would be useful. Gopass should be able to retrieve configuration settings from the environment via env variables and via a static config file. 

For what do we need templating here?

```yaml
autoclip: false
autoimport: true
cliptimeout: 45
nocolor: false
nopager: false
notifications: true
path: /home/chris/.password-store
safecontent: false
mounts: {}
clipCmd: ["/usr/bin/clipCommand", "flag1", "flag2"]
unclipCmd: ["/usr/bin/unclipCmd", "flag1"]

if clipCmd/unclipCmd are empty.. just fall back to the current workflow.

**Comment by hashworks** [comment]
As a friend of mine mentioned, we can't provide secrets over command arguments anyway – they would leak. Secrets need to be provided by STDIN, name can be the first parameter.

With this [clipboard.go](https://fb.hash.works/79nDrdfn/):
```
$ cat /tmp/test.name
#!/bin/bash
cat /dev/stdin > /tmp/test.stdin
echo "$1" > /tmp/test.name
$ CLIPBOARD_WRITE_CMD="/tmp/test.sh" ./gopass -c example.com
✔ Copied example.com to clipboard. Will clear in 45 seconds.
$ cat /tmp/test.name
example.com
$ cat /tmp/test.stdin
examplePassword
```
