### ISSUE TITLE
Please update deb package gnupg dependency.

### ISSUE THREAD

**Issue by txt-file** [gopasspw/gopass#2049]
### Summary
This issue is similar to #805. Time has passed … gnupg2 is now a dummy transitional package in all upstream supported debian and ubuntu releases.

### Steps To Reproduce
- install any upstream supported debian or ubuntu version
- remove gnupg2 package (as it is a dummy transitional package it shouldn't even be installed)
- `wget https://github.com/gopasspw/gopass/releases/download/v1.13.0/gopass_1.13.0_linux_amd64.deb`
- `sudo dpkg -i gopass_1.13.0_linux_amd64.deb`
- get error:
```
dpkg: dependency problems prevent configuration of gopass:
 gopass depends on gnupg2; however:
  Package gnupg2 is not installed.

dpkg: error processing package gopass (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 gopass
```

### Expected behavior
gopasspw does not depend on a dummy transitional package.

### Environment
- OS: debian, ubuntu
- OS version: all upstream supported
- gopasspw version: 1.13.0
- installation method: gopasspw *.deb file from Microsoft Code releases

**Comment by txt-file** [comment]
### additional information
- https://packages.debian.org/search?keywords=gnupg2
- https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=gnupg2&searchon=names

**Comment by dominikschulz** [comment]
Sounds good. Thanks for making us aware of that.

Do you want a PR?

**Comment by dominikschulz** [comment]
Thanks a lot!
