### ISSUE TITLE
Have a test/GHA to know when to remove hardcoded exceptions in pwrules

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#2057]
We might want to have a negative test that tests that `json.NewDecoder` fails when decoding the buggy entries in the password rules list, so that once it won't fail any more we'll be able to remove the hardcoded exceptions.

Sadly we might not want to download the file each time we run the build / test framework, so maybe it would be best to have a dedicated GHA that runs once in a while (maybe at each release?) to test that the hardcoded exception are still needed? 

That would probably require another helper go program/test, along with a dedicated Github Action.

_Originally in https://github.com/gopasspw/gopass/pull/2052#discussion_r760397168_

**Comment by dominikschulz** [comment]
Actually I think this should be fixed at the source, I have filed https://github.com/apple/password-manager-resources/issues/548 to suggest some improvements to their tooling.

**Comment by AnomalRoil** [comment]
Good point, let's track it here then. In the worst case we can do as proposed above.

**Comment by dominikschulz** [comment]
We don't have a test but the upstream issue was fixed and I removed the workaround.
