### ISSUE TITLE
[Feature request] Add ability to extract specific characters of secrets

### ISSUE THREAD

**Issue by lol768** [gopasspw/gopass#2068]
### Summary

Many websites persist in requesting specific characters of passwords/memorable phrases to be entered

![image](https://user-images.githubusercontent.com/2552726/147364984-7d01edd2-3a53-4020-8b3b-fbbfeb443565.png)

![image](https://user-images.githubusercontent.com/2552726/147365009-b70ab615-78b6-4a81-85ab-b95d774a9ee3.png)

It would be nice to be able to invoke a sub-command to just retrieve a set of characters based on their index from a password.

I'm sure you could do this by e.g. using a bash string substitution or e.g. `head`/`tail` but something like `gopass show bank/memorable :1,5,7` would be super convenient to get the necessary characters out in one go.

**Comment by dominikschulz** [comment]
I haven't seen this before but it looks like amazingly poor UX (counting 17 characters in a word / sentence ... what the ...?!?).

But of course that's not your fault (I hope! 😁 ). If that's indeed a common thing we might be able to ease the pain a bit by providing help.

It's just that positional arguments and the `show` output in general is already pretty overloaded and we need to be careful how we do it. Once that's settled implementation should be mostly trivial.

**Comment by lol768** [comment]
> I haven't seen this before but it looks like amazingly poor UX (counting 17 characters in a word / sentence ... what the ...?!?).

Tell me about it! They all claim it "improves security" too, but it incentivises using something you can remember  🙄

Not sure if it's mainly a UK-centric thing or not, but I'd say a lot of established banks and other "high security" services implement this practice. The dropdowns in particular come from a misguided "well that'll stop a keylogger!" perspective.

> I hope!

I've yet to implement this myself :laughing: 

> It's just that positional arguments and the show output in general is already pretty overloaded and we need to be careful how we do it. Once that's settled implementation should be mostly trivial.

Yeah, I'm not massively tied to it being positional, some sort of option could equally work.. (provided I can remember its name!).

**Comment by AnomalRoil** [comment]
How about using a flag?
My main concern being that the comment flag for that would be _à la_ cut, so either -c or -f both of which we are already using in `show`...

I kinda like the idea of having the :1,2,3 at the end. Would you mind me giving it a go @dominikschulz ?

**Comment by dominikschulz** [comment]
@AnomalRoil Give it a try if you want!
But keep in mind that I haven't made up my mind what syntax I'd prefer (but then this should be easy to change).
