### ISSUE TITLE
hibp: failed to find subtree: not found

### ISSUE THREAD

**Issue by Fale** [gopasspw/gopass#2071]
### Summary
When executing audit `hibp --dumps` an error occurs instead of running it.

### Steps To Reproduce
1. Download the SHA-1 version8 ordered by hash from https://haveibeenpwned.com/Passwords
2. `7z e pwned-passwords-sha1-ordered-by-hash-v8.7z`
3. `gopass audit hibp --dumps /var/home/fale/Downloads/pwned-passwords-sha1-ordered-by-hash-v8.txt`
4. Receive
```
Auditing passwords for common flaws ...

Error: failed to find subtree: not found
```

### Expected behavior
HIBP test to be performed

### Environment
- OS: Linux Fedora 35
- OS version: `Linux x1.fale.io 5.15.11-200.fc35.x86_64 #1 SMP Wed Dec 22 15:41:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- gopass Version:
```
gopass 1.13.0 (2021-12-21 00:00:00) go1.16.11 linux amd64
<root>     -  gpg 2.3.4 - git 2.33.1
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fs, gitfs
```
- Installation method: daftaupe's COPR repository

**Comment by dominikschulz** [comment]
The `hibp` subcommand isn't available anymore in the main binary. Use [gopass-hibp](https://github.com/gopasspw/gopass-hibp).

**Comment by Fale** [comment]
I see, thanks!
I think https://github.com/gopasspw/gopass/blob/master/docs/features.md#using-the-dumps should be changed then ;-)
