### ISSUE TITLE
Gopass `mv` moves fuzzy names even on exact match and doesn't rename directories

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#2079]
### Steps To Reproduce
```
$ GOPASS_HOMEDIR=~/test gop generate comm/test 12 
$ GOPASS_HOMEDIR=~/test gop generate comm/test2 12
$ GOPASS_HOMEDIR=~/test gop generate communication/t1 12
$ GOPASS_HOMEDIR=~/test gop ls
gopass
 ├── communication/
 │          └── t1
 └── comm/
        ├── test
        └── test2
       
$ GOPASS_HOMEDIR=~/test gop mv comm email 
$ GOPASS_HOMEDIR=~/test gop ls
gopass
└── email/
    └── comm/
        ├── test
        ├── test2
        └── unication/
            └── t1
```

### Expected behavior

Should get instead:
```
$ GOPASS_HOMEDIR=~/test gop ls
gopass
 ├── communication/
 │          └── t1
 └── email/
        ├── test
        └── test2
       
```

Notice also that the folder `comm` wasn't renamed but actually moved into a new folder instead.

This is not similar to how Unix's `mv`works, which is what we aim for with `gopass mv` IIRC.

**Comment by dominikschulz** [comment]
I think the `Steps to Reproduce` is slightly off. `email/` should be `comm/` in the first ls output.

But then I think you are right: This looks like a bug :/

**Comment by AnomalRoil** [comment]
Right, I decided to add the first `ls` after having run the rest. Edited.
