### ISSUE TITLE
How to disable gpg passphrase input

### ISSUE THREAD

**Issue by okeedookee** [gopasspw/gopass#2087]
### Summary
The gpg passphrase input window was randomly pops, and complains can not decrypt in a gopass batch mode. Is there a way to disable the gpg passphrase input interaction?

### Steps To Reproduce
Use gopass for a while, then seeing unable to decrypt error from a bash program. I paste the same bash cmd into the same terminal, then will see gpg passphrase was required. After entering the correct passphrase, everything come back to normal. 

### Environment

- OS: CentOS 8
- OS version: Linux Laptop-P50 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- gopass Version: gopass 1.13.0+c574e920b532606894b3e64db059f3e3a838b0c9 (c574e920b532606894b3e64db059f3e3a838b0c9) go1.17.3 linux amd64
- Installation method: curl -s -L https://github.com/gopasspw/gopass/releases/download/v1.13.0/gopass-1.13.0-linux-amd64.tar.gz

**Comment by dominikschulz** [comment]
Gopass is mostly just calling GPG.

**Comment by AnomalRoil** [comment]
This seems like a Gpg-agent caching issue.

Check: https://superuser.com/q/624343/419597
And let us know if that works.

**Comment by okeedookee** [comment]
Is it possible to remove the passphrase? Otherwise gopass can not run in a docker container.

**Comment by AnomalRoil** [comment]
Yeah, that's a PGP thing. Just create a key with an empty passphrase.

**Comment by dominikschulz** [comment]
For GPG: yes.

For age we currently enforce a passphrase for decryption.

**Comment by okeedookee** [comment]
The problem of the pgp phrase is that it is enforcing interactive, not feasible for dockerizing.

**Comment by AnomalRoil** [comment]
That's a PGP issue then, how did you create your PGP key? You can edit your key to remove the passphrase.
