### ISSUE TITLE
Contributing docs are incorrect with respect to Go version required

### ISSUE THREAD

**Issue by twpayne** [gopasspw/gopass#2101]
### Summary

The [pull release checklist in the contributing docs](https://github.com/gopasspw/gopass/blob/61c2e438ac4f8ab0beb3804bc1cb625bc2aad5da/CONTRIBUTING.md?plain=1#L27) states:
> Use that latest stable Go release

However, the current `master` branch of `gopass` uses generics, for example [here](https://github.com/gopasspw/gopass/blob/master/internal/cache/inmem_test.go#L23), which are not part of the latest stable release of Go.

### Steps To Reproduce

Read the contributing docs and then build `gopass` with the latest stable version of Go.

### Expected behavior

The contributing docs accurately describe the requirements for contributors.

### Environment

n/a

**Comment by dominikschulz** [comment]
Sorry for the minor inconvenience. Usually we try to stick to that. This is a temporary condition until Go 1.18 is released.

**Comment by twpayne** [comment]
Thanks, feel free to close this issue.
