### ISSUE TITLE
Gopass `show -o` has misleading error for body-only entries

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#2106]
Assuming we have an entry `x` that only has a body and no password on its first line, e.g.:
```

---
some: data
```
 then running `gopass show -o x` will return: `Error: empty secret`, which could be an issue if a user assume the entire entry is empty and deletes it for example.

But the entry could actually contain for instance a binary blob encoded using `cat file | gopass cat x`, or just a body made of yaml data as in the above.

## Expected behaviour

The error message should probably be different in the case where the `Body` of the entry is non-empty and only the `Password` is empty.
Maybe `Error: empty password, entry has data only in its body, or contains a binary blob accessible with gopass cat.`

**Comment by dominikschulz** [comment]
Good point. Sounds like an easy fix.

Feel free to send a PR or I'll do it later.
