### ISSUE TITLE
Windows installation docs missing GPG installation

### ISSUE THREAD

**Issue by slokhorst** [gopasspw/gopass#2139]
The Windows installation instructions on https://www.gopass.pw/#install are missing the GPG installation.

### Steps To Reproduce
1. Install [Chocolatey](https://chocolatey.org/).
2. Run `choco install gopass`.
3. Run `gopass setup`

```
Error: Failed to initialized store: failed to initialize stores: failed to initialize the root store at "C:\\Users\\Sebastiaan\\AppData\\Local\\gopass\\stores\\root": failed to init crypto backend: no gpg binary found"
```

### Environment
- OS: Windows 10
- OS version: 20H2
- gopass Version: gopass 1.13.1+ebb790ccf21e01e4aa16cb770b6e8356d82133a3 (ebb790ccf21e01e4aa16cb770b6e8356d82133a3) go1.17.6 windows amd64
- Installation method: Chocolatey

**Comment by slokhorst** [comment]
Suggested fix: gopasspw/gopasspw.github.io#13

**Comment by dominikschulz** [comment]
Seems to be fixed now. Thanks!
