### ISSUE TITLE
Is the age backend stable?

### ISSUE THREAD

**Issue by dylangerdaly** [gopasspw/gopass#2149]
### Summary
I'd like to migrate from gpg to an `age` backend, however it's unclear if this backend is stable, I rely on gopass currently.

### Steps To Reproduce
N/A

### Expected behavior
N/A

### Environment
N/A

### Additional context
N/A

**Comment by AnomalRoil** [comment]
It was in #2103 for reference :)

**Comment by dylangerdaly** [comment]
So far so good, the convert function worked great, however, when showing a password it takes some time, about 30 seconds.

Acceptable, but annoying

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by dominikschulz** [comment]
I'd expect age to be much faster than gpg in any regard and would consider this a bug.
If you want we can try to debug this.

Run gopass with `GOPASS_DEBUG_LOG=/path/to/some/file.log` and provide the output, please. It should include timing information.

Ideally you do this with a toy mount so you don't leak any credential names or such.

**Comment by dylangerdaly** [comment]
Sure here's the log

```
2022/03/05 13:37:22.277437 fs/store.go:41	fs.(*Store).Get	Reading Personal/<REDACTED>.age from /home/user/.password-store/Personal/<REDACTED>.age
2022/03/05 13:37:22.278638 age/decrypt.go:18	age.(*Age).Decrypt	no password callback found, redirecting to askPass
2022/03/05 13:37:22.279387 age/askpass.go:62	age.(*askPass).Passphrase	Value for /home/user/.config/gopass/age-keyring.age not found in cache
2022/03/05 13:37:29.811156 age/askpass.go:84	age.(*askPass).Passphrase	Updated value for /home/user/.config/gopass/age-keyring.age in cache
2022/03/05 13:37:45.066779 age/keyring.go:112	age.(*Age).loadKeyring	loaded keyring with 1 valid entries from /home/user/.config/gopass/age-keyring.age
2022/03/05 13:37:45.072354 age/age.go:178	age.(*Age).getNativeIdentities	keyring: [{Name:user Email: Identity:<REDACTED>}]
2022/03/05 13:37:45.093050 secparse/parse.go:20	secparse.Parse	failed to parse as MIME: (elided)
2022/03/05 13:37:45.093144 secrets/yaml.go:95	secrets.ParseYAML	Parsing (elided)
2022/03/05 13:37:45.094168 secparse/parse.go:30	secparse.Parse	failed to parse as YAML: EOF
(elided)
2022/03/05 13:37:45.096936 secparse/parse.go:37	secparse.Parse	failed to parse as KV: EOF
2022/03/05 13:37:45.096993 secparse/parse.go:40	secparse.Parse	parsed as plain: (elided)
2022/03/05 13:37:45.252747 clipboard/clipboard.go:45	clipboard.CopyTo	✔ Copied Personal/<REDACTED> to clipboard. Will clear in 45 seconds.`
```

You can see it goes from 29 - 45, looks like it could be caching issue? I don't have any mounts.

Thank you for helping

**Comment by dominikschulz** [comment]
I need to dive into the code to see what could be happening in there. But at the penultimate line age is already done and should not cause any delay anymore.

**Comment by AnomalRoil** [comment]
Just checking, but you're running on the latest master and not on v1.13, right?

**Comment by dylangerdaly** [comment]
Currently running stable, not master

**Comment by dominikschulz** [comment]
Between the two log lines that depict the Delay there are no age operations.

The only thing that is possibly slow is related to the clipboard.

**Comment by AnomalRoil** [comment]
Notice that we've made significant changes since releasing v1.13 regarding age (actually passage) support, so be careful about the next upgrade.
