### ISSUE TITLE
Unclear usage of convert verb for root store

### ISSUE THREAD

**Issue by adrianbroher** [gopasspw/gopass#2170]
### Summary
From the existing documentation (docs and `--help` output) it is not clear how the root store can be converted to another storage or crypto backend.

### Steps To Reproduce

Leaving out the `--store` parameter leads to:

```
gopass convert --storage gitfs
# ...
2022/03/18 21:35:02 Required flag "store" not set
```

Setting the `--store` parameter to an empty string leads to:

```
$ gopass convert --storage gitfs --store ''
# ...
2022/03/18 21:36:07 unknown backend -1: backend not found
```

Setting the `--store` parameter to the string `root`, `/` or `default` leads to the corresponding:

```
$ gopass convert --storage gitfs --store root
2022/03/18 21:37:40 no such mount point "root"
```

### Expected behavior
When no explicit `--store` is given I would expect that the `convert` verb acts on the root store.

### Environment

- OS: Fedora 34
- OS version: `Linux blackbox 5.16.12-100.fc34.x86_64 #1 SMP PREEMPT Wed Mar 2 20:05:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- gopass Version: `gopass 1.13.1 (2022-02-01 00:00:00) go1.16.13 linux amd64`
- Installation method: Copr repo for gopass

### Additional context

The root store was (probably) created with:

```
gopass init --storage fs
```

but I can't say for sure, as I've set this up years ago. Maybe it was even set up with `pass`.

The root store is located at `~/.password-store`.

**Comment by dominikschulz** [comment]
I agree. It should work as you described. I guess I've never tried to convert a root store and missed that in the implementation. I'll give it a try these days and try to fix it.

**Comment by dominikschulz** [comment]
Looking at the code I noticed that the implementation might be incomplete wrt. recipients, need to check that as well.
