### ISSUE TITLE
gopass ignoring symlink to other directory

### ISSUE THREAD

**Issue by robbat2** [gopasspw/gopass#2173]
### Summary
I have a symlink in `~/.pass/` that points to a separate directory outside the `~/.pass/` directory tree,  and is not shown by `gopass list`. `gopass show ...` does correctly load secrets from it.

The original `pass` does correctly list the secrets that are contained therein.

### Steps To Reproduce
1. Initialize `~/.pass/` & add a secret
2. Initialize `/tmp/demo-pass/` ` & add a secret
3. Symlink `ln -sf /tmp/demo-pass ~/.pass/demo-pass`
4. Try to list everything `gopass list --flat`

### Expected behavior
All of the secrets in both directories should be included.

### Environment
- OS: Gentoo Linux
- OS version: `Linux REDACTED 5.17.0-rc2-x86_64-REDACTED #92 SMP PREEMPT Sun Feb 6 11:39:50 PST 2022 x86_64 AMD Ryzen 7 3700X 8-Core Processor AuthenticAMD GNU/Linux`
- gopass Version: `gopass 1.13.0 (2022-01-18 23:25:13) go1.17.6 linux amd64`
- Installation method: distro package

**Comment by dominikschulz** [comment]
The problem is that Go's `filepath.Walk` does not follow symlinks. We'll need to add that. Without introducing loops or any attack vectors not sure if it's worth it or not.
