### ISSUE TITLE
feature: ssh keys instead of gpg

### ISSUE THREAD

**Issue by decentral1se** [gopasspw/gopass#2185]
### Summary

GPG is unfortunately not easy to use & has accessibility issues. (ack'd in https://github.com/gopasspw/gopass/blob/master/docs/security.md#gnu-privacy-guard). For diverse teams where some folks might *not* be super comfortable with the CLI, it blocks participation. Most people will have an SSH key though, in my experience & those are easier to manage. Looking at https://earthly.dev/blog/encrypting-data-with-ssh-keys-and-golang/ I do wonder, could it be possible to use SSH keys instead to `init` / `insert` / etc.? Maybe it is too radical a switch to be integrated into `gopass` without breaking things... but maybe not!? The only thing I can think of that would be hard to implement is using multiple keys to encrypt passwords, GPG is doing that internally, I believe.

### Steps To Reproduce

N/A

### Expected behavior

N/A

### Environment

N/A

### Additional context

N/A

**Comment by AnomalRoil** [comment]
This is on theory already supported by the age backend since age can rely on ssh (ECC) keys.
Have you tried it?

**Comment by dominikschulz** [comment]
+1

Also: crypto is hard. Even if you're only using it, so I'd try to refrain from rolling our own crypto backend (we did have one, it was deprecated in favor of age) and rely on a portable implementation instead. Another benefit of using age is that this reduces the "lock in" effect, i.e. even if gopass is completely broken you can still decrypt your secrets using the age CLI.

**Comment by decentral1se** [comment]
`passage` does look nice! iiuc then I can use ssh keys instead of age identities...

> https://github.com/FiloSottile/age#ssh-keys

Will try this. I'll close this off I guess, thanks!

**Comment by AnomalRoil** [comment]
Yeah and `gopass` is compatible with `passage` if you initialize your store using the flag `--crypto age`

**Comment by fegger-ducksify** [comment]
Can you provide an example please.
I was able to see  ssh-ed25519 during  gopass init --crypto age.

```
⚠ Hint: Use 'gopass init <subkey> to use subkeys!'
🎮 Please select a private key for encrypting secrets:
[0] age - age1h7la4vjcv24fnyj0m28y8v725kq0kmtfer6jeylneun8slxtnffqawemd6
[1] age - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE2rlBL1QNQaz11Wc501EsKioTg4v/71aXLYJNrn/Q2M
[2] age - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILVhtISILbo9kF2kVa84yNRrDoxm1TL70RV5rhnd5lOl
Please enter the number of a key (0-2, [q]uit) (q to abort) [0]: 1
```

But I get 
```
2023/04/21 16:21:13.498297 age/identities.go:144	age.(*Age).cachedIDRecpipients	identity cache expired
2023/04/21 16:21:13.498367 age/identities.go:25	age.(*Age).Identities	no password callback found, redirecting to askPass
2023/04/21 16:21:13.498374 age/identities.go:34	age.(*Age).Identities	reading native identities from /Users/francois/.config/gopass/age/identities
2023/04/21 16:21:13.498516 age/decrypt.go:56	age.(*Age).decryptFile	read 371 bytes from /Users/francois/.config/gopass/age/identities
2023/04/21 16:21:13.525749 age/askpass.go:102	age.(*askPass).Passphrase	Read value for /Users/francois/.config/gopass/age/identities from cache
2023/04/21 16:21:14.000453 age/decrypt.go:46	age.(*Age).decrypt	Decrypted 371 bytes of ciphertext to 189 bytes of plaintext
2023/04/21 16:21:14.000542 age/identities.go:50	age.(*Age).Identities	read 1 native identities from /Users/francois/.config/gopass/age/identities
2023/04/21 16:21:14.000770 age/identities.go:134	age.(*Age).FindIdentities	ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE2rlBL1QNQaz11Wc501EsKioTg4v/71aXLYJNrn/Q2M not found in ["age1h7la4vjcv24fnyj0m28y8v725kq0kmtfer6jeylneun8slxtnffqawemd6"]
2023/04/21 16:21:14.000785 action/init.go:87	action.(*Action).Init	Failed to initialize store: failed to init store "" at "/Users/francois/.local/share/gopass/stores/root": failed to initialize new sub store: none of the recipients has a secret key. You will not be able to decrypt the secrets you add - stacktrace: failed to init store "" at "/Users/francois/.local/share/gopass/stores/root": failed to initialize new sub store: none of the recipients has a secret key. You will not be able to decrypt the secrets you add

```
