### ISSUE TITLE
Repository migration

### ISSUE THREAD

**Issue by akoufa** [gopasspw/gopass#2209]
Hello. I have a question regarding how to migrate gopass store from a repository to a new one. Like for example let's say I have the store backed by repository A on github and I want to move it to repository B on gitlab.

Is there any command I can use to flawlessly achieve the migration ? Is there anything I have to watch out ?

Thank you in advance

**Comment by dominikschulz** [comment]
This is just a regular git operation, gopass doesn't really provide any help with that but also I'm not sure if that's necessary.

You can just push the repo to the new remote and make it the default.
Do you think we should cover that in our docs?

**Comment by AnomalRoil** [comment]
So the way to go is basically:
```
cd $(gopass config path)
git remote -v
git remote rm origin
git remote add origin git.server.com:Username/password-store.git
git remote -v
git branch --set-upstream-to=origin/master master
git push
```

**Comment by akoufa** [comment]
@AnomalRoil @dominikschulz Thank you both. Yes it would make sense to have this in the documentation. I will try to find some time to add it. Closing the issue now.
