### ISSUE TITLE
targeting the parent directory when moving a secret deletes the secret

### ISSUE THREAD

**Issue by lockejan** [gopasspw/gopass#2210]
### Summary

When attempting to move a secret to the parent directory like so:
`gopass mv foo/bar/baz@example.de foo/bar`

The secret get's completely removed. Gopass doesn't inform the user.

### Steps To Reproduce

1. `gopass generate foo/bar/baz@example.de`
2. `gopass ls foo/`
3. `gopass mv foo/bar/baz@example.de foo/bar`
4. `gopass ls foo/`

### Expected behavior

Gopass removing the folder and placing the secret in it's place.

### Environment

- OS: Mac OS X Monterey
- OS version: 12.3.1  
- `uname -a` 
> Darwin hostname 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
- gopass Version: 
>gopass 1.14.0 go1.18.1 darwin amd64
<root>     -  gpg 2.3.4 - git 2.36.0
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fossilfs, fs, gitfs

- Installation method: via nix , e.g.`nix-env -iA nixpkgs.gopass`

**Comment by dominikschulz** [comment]
Actually you're not moving the file to the parent directory (`foo`) but the current one (`foo/bar`).

Of course it still shouldn't just remove the file.

**Comment by AnomalRoil** [comment]
Was it really deleted and not just shadowed?? 😱

**Comment by dominikschulz** [comment]
Yes. I'd expect most people to use the gitfs backend, but still very undesirable behaviour.
