### ISSUE TITLE
share password by url

### ISSUE THREAD

**Issue by rasperepodvipodvert** [gopasspw/gopass#2212]
how can i  share password for my team if theirs vaults named different?
may be generate url by repo and open with gopass?

**Comment by dominikschulz** [comment]
Today thats not possible. But sounds like something we might consider.

We will need to consider the security implications of doing so.

**Comment by dominikschulz** [comment]
I don't see a good way to proceed with this FR. Every solution I could think of is either brittle or right away dangerous.

So I'm closing this for now. If anyone comes up with a concrete proposal feel free to reopen.
