### ISSUE TITLE
find and remove duplicates

### ISSUE THREAD

**Issue by rasperepodvipodvert** [gopasspw/gopass#2213]
how can i find and remove duplicates? 
Files encrypted and [this](https://ostechnix.com/how-to-find-and-delete-duplicate-files-in-linux/) method doesn't work

**Comment by dominikschulz** [comment]
Did you try `gopass audit`?

**Comment by rasperepodvipodvert** [comment]
Yes, but 
`Detected a shared secret for` search by password or any text in vault file?

**Comment by dominikschulz** [comment]
Please try to clarify what exactly you want to do.

Otherwise I'll have to close this issue.

**Comment by rasperepodvipodvert** [comment]
I have comand to remove all duplicates

**Comment by dominikschulz** [comment]
No sure what's the ask here. I you still consider this important please clarify and re-open.
