### ISSUE TITLE
Update void package (manually?)

### ISSUE THREAD

**Issue by Brixy** [gopasspw/gopass#2217]
### Summary

Void seems to not accept auto-generated changes for package releases. So the pull request for gopass 1.14.0 [was rejected](/void-linux/void-packages/pull/36185).

Are there any plans to open a new pull request manually?

### Additional context

Current gopass version in void is still [1.13.0](/void-linux/void-packages/blob/889582c673185f16422c16d7f9ed4c31791ad17c/srcpkgs/gopass/template)

**Comment by dominikschulz** [comment]
No. We don't have the capacity to do that.
If they don't accept automatic PRs then someone else will have to take care.
