### ISSUE TITLE
bug: fsck argument for secret does not display progress properly

### ISSUE THREAD

**Issue by robbat2** [gopasspw/gopass#2222]
### Summary
- Fsck only checks the entire root or a submount
- If you want to check a subset of secrets, there is no easy way

### Steps To Reproduce
- Have a folder with it's own recipients
- Change the recipients
- Want to fsck just that folder

### Expected behavior
`gopass fsck --decrypt` should take an argument of folder or secret to check.

### Environment
- OS: Gentoo
- OS version: 5.17.1-x86_64-00002-gREDACTED
- gopass Version: 1.13.0
- Installation method: package manager

**Comment by dominikschulz** [comment]
Actually it's supported and for me it did work as expected.

**Comment by robbat2** [comment]
I still think there's an issue somewhere. The counter shows the total number of secrets, not the number in the path.

Here I ran it with a path that had 10 (shared) secrets, but it shows the count for all 438 secrets.
(doesn't have your fsck output fix, but that shouldn't touch this output)

```
gopass  fsck (REDACTED)/
Checking password store integrity ...

[] Checking storage backend
]   1 / 438 [Gs                                                                                                                                               ]   0.23% 
[] Compacting storage if possible

[] Checking all secrets in store
] 224 / 438 [Gooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooopass                                                                       ]  51.14% 
] 225 / 438 [Gooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooopass                                                                       ]  51.37%
```

**Comment by AnomalRoil** [comment]
Confirmed.

**Comment by AnomalRoil** [comment]
It also seems the progress skips to the number of secrets in store before starting and has twice has many secrets.
My store has 424 `.gpg` files and yet it displays:
```
$ gopass fsck
Checking password store integrity ...

[somesubmount] Checking storage backend
]   1 / 844 [Gs                                                                             ]   0.12%
[somesubmount] Compacting storage if possible

[somesubmount] Checking all secrets in store
]   8 / 844 [Gs                                                                             ]   0.95%
[] Checking storage backend
]  11 / 844 [Gs                                                                             ]   1.30%
[] Compacting storage if possible

[] Checking all secrets in store
] 859 / 859 [Gooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooopass] 100.00%
```

**Comment by dominikschulz** [comment]
Yeah, the progress part is a mess.

That needs a little bit of focus time to clean it up.

But I guess we can agree that this is not a serious issue?
