### ISSUE TITLE
env subcommand converts entry name to all upper case when setting them as environment variables

### ISSUE THREAD

**Issue by nirojan** [gopasspw/gopass#2225]
### Summary

Env subcommand converts the entry name to all upper case and sets them as environment variable. This doesn't work with CLI tools that are case-sensitive.

Terraform for example lets you pass values for variables as environment variables and requires them to be prefixed with `TF_VAR_` but rest of the variable name needs to be lower case, i.e. TF_VAR_example_var. More info https://www.terraform.io/cli/config/environment-variables#tf_var_name. As the subcommand sets them all upper case, Terraform doesn't read it as it is case sensitive and instead prompts the user to enter a value for the variable.

### Steps To Reproduce

1. Create a new entry in gopass by running 
```shell
echo "text-goes-here" | gopass insert test/env/TF_VAR_example_var
```
2. Run the following command to view the entry you just created set as environment variable. 
```shell
gopass env test/env printenv | grep TF_VAR
```

### Expected behavior

env subcommand retains the original case when setting the entry name as environment variable. Something like below

```shell
❯ gopass env test/env printenv | grep TF_VAR
TF_VAR_example_var=text-goes-here
```

### Environment

- OS: macOS Monterey
- OS version: Darwin MBP 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
- gopass Version: 1.14.1
- Installation method: brew

### Additional context

Using gopass with age crypto & git backend if that makes a difference. 

Maybe this could be implemented as a flag to env subcommand to keep the case as it is from entry name and leave the current behaviour, so it doesn't break other people's work flows.

**Comment by dominikschulz** [comment]
Oh. That's an odd limitation.
But I think we should support tf.

**Comment by dotcs** [comment]
Thanks @nirojan for your comment. I like the idea and have adjusted the PR accordingly.

```console
$ ./gopass env --help                                                                                                                             130 ↵
NAME:
   gopass env - Run a subprocess with a pre-populated environment

[...]

OPTIONS:
   --keep-case, --kc  Do not capitalize the environment variable and instead retain the original capitalization (default: false)
   --help, -h         show help (default: false)
```

and 

```console
./gopass env --kc test/env printenv | grep -i TF_VAR
TF_VAR_example_var=text-goes-here
```
