### ISSUE TITLE
Any examples of how to use gopass as a library/package?

### ISSUE THREAD

**Issue by z0mbix** [gopasspw/gopass#2233]
### Summary
I have a cli tool that does many things that requires several secrets. It currently uses environment variables to get these secrets, but it would be nice if I could pull them directly from my gopass database.

I've been reading the https://pkg.go.dev/github.com/gopasspw/gopass@v1.14.2/pkg/gopass documentation, but can't figure out how to do this. Can you point me at some examples I can use, if this is even possible.

### Steps To Reproduce
n/a

### Expected behavior
n/a

### Environment
- OS: Mac OS X Monterey
- OS version: [uname -a]
- gopass Version: gopass 1.14.2 go1.18.2 darwin arm64
- Installation method: homebrew

### Additional context
n/a

**Comment by dominikschulz** [comment]
I think gopasspw/gopass-hibp might be a good example.

**Comment by dominikschulz** [comment]
Should be covered by https://github.com/gopasspw/gopass/pull/2238
