### ISSUE TITLE
gopass update from 1.13 - 1.14 broke all age encrypted passwords

### ISSUE THREAD

**Issue by dylangerdaly** [gopasspw/gopass#2235]
### Summary
After upgrading from age 1.13 to 1.14 I can no longer decrypt any of my passwords.

```
[user@vault]~% gopass show Github
⚠ Entry "Github" not found. Starting search...
✅ Found exact match in "Personal/Github"
❌ Decryption failed: failed to decrypt: no identities specified


Error: failed to retrieve secret "Personal/Github": failed to decrypt
```

**Comment by dylangerdaly** [comment]
```
✅ Migrated age backend to new format
```

Migrating to the new backend format fixed this issue.

**Comment by dominikschulz** [comment]
The migration should happen automatically.

I wonder why it didn't work in the first place.

**Comment by dylangerdaly** [comment]
My fault, I bailed out of the migration because I thought it was wanting to re-init the store.
