### ISSUE TITLE
Make gopass optionally work without password protection

### ISSUE THREAD

**Issue by omani** [gopasspw/gopass#2259]
Imagine I have an `AGE-SECRET-KEY-...`. I want to be able to place it as an ENV var so that gopass can read from it. alternatively, I want to be able to place my **cleartext** `AGE-SECRET-KEY-...` in `~/.config/gopass/age/identities`. that is, the identity file is not encrypted by age itself. it is a plain identity file.

basically, I want to get rid of the error message: `"Passphrase can't be empty"` in the setup process.

use case: loading/populating encrypted env vars at runtime (bash exports).

right now Im doing it with my own YAML secret in gopass as KV pairs. I parse it within my .bashrc. didnt know there is `gopass env` until I found out about it while reading through the issues. since it is invisible in the help menu one doesnt know there is an `env` command available. but my setup still requires a passphrase from time to time (until GPG cache expires. not using age backend for my current solution).

if `gopass` will ask me for my passphrase everytime, it will make this goal nearly impossible. dont wanna start messing around with `expect`.

this is a feature request.

any objections or thoughts?

**Comment by dominikschulz** [comment]
Sounds reasonable. I think it's a duplicate, i.e. we have an existing FR for that already.

I did took at the implementation before and didn't figure out a clean solution in the short time I had available.

**Comment by omani** [comment]
actually, I just found out about chezmoi.io. it does exactly what I was trying to achieve manually.

feel free to implement OP. but so far I think Im gonna be happy with chezmoi.

thank you for this beautiful piece of software named gopass.
