### ISSUE TITLE
Mac OS auto completion setup: Operation not permitted

### ISSUE THREAD

**Issue by onesail** [gopasspw/gopass#2274]
### Summary

Instruction to setup autocomplete cause failure on macOS 12

### Steps To Reproduce

```
% sudo mv _gopass /usr/share/zsh/site-functions/_gopass
mv: fastcopy: open() failed (to): /usr/share/zsh/site-functions/_gopass: Operation not permitted
```

### Expected behavior

auto complete setup works

### Environment
- OS: macOS 12.4 Montery
- OS version: Darwin BlackMac.fritz.box 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
- gopass Version: gopass 1.14.3 go1.18.2 darwin arm64
- Installation method: brew

### Additional context

The latest macOS versions protect system directories. Even sudo doesn't help.

**Comment by AnomalRoil** [comment]
Related to #2182 maybe?

> If you get an "operation not permitted" error on the newer Mac OSes (El Capitan+) while
moving the `_gopass` file, use `/usr/local/share/zsh/site-functions/` instead.

**Comment by onesail** [comment]
Thanks, this in fact this solves the issue.

**Comment by onesail** [comment]
closed
