### ISSUE TITLE
Consider adding Tomb as a storage backend

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#2275]
### Summary
We've been asked quite often to provide a way to conceal the file structures (#1560, #673), and I recently noticed that there is a [Tomb extension](https://github.com/roddhjav/pass-tomb) for `pass`.

https://www.dyne.org/software/tomb/
&&
https://github.com/dyne/Tomb

It seems Tomb is basically about creating encrypted, hidden folders, which means it might be a good way to achieve the above and shouldn't require too many changes.

(Or maybe we should just really go back to improving the ondisk backend?)

**Comment by dominikschulz** [comment]
I wonder how that would work. Isn't this "just" a shell script? That looks very much platform dependent.
I'm trying to keep gopass as cross platform as possible. So unless this is very easy to integrate I'd rather try
to take another approach at the fully encrypted ondisk backend.

**Comment by AnomalRoil** [comment]
Agreed, we'd have more flexibility and Tomb comes with annoyingly big dependencies (Veracrypt, etc.). Closing this.
