### ISSUE TITLE
Pop!_OS NO_PUBKEY

### ISSUE THREAD

**Issue by gray380** [gopasspw/gopass#2282]
### Summary

The following message has appeared: 
```
W: GPG error: https://packages.gopass.pw/repos/gopass stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 686E9DE6E1AEFFBE
E: The repository 'https://packages.gopass.pw/repos/gopass stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default
```
### Steps To Reproduce

```
$ curl http://packages.gopass.pw/repos/gopass/gopass-archive-keyring.gpg | sudo tee /usr/share/keyrings/gopass-archive-keyring.gpg
$ cat << EOF | sudo tee /etc/apt/sources.list.d/gopass.sources
Types: deb
URIs: https://packages.gopass.pw/repos/gopass
Suites: stable
Architectures: all amd64 arm64 armhf
Components: main
Signed-By: /usr/share/keyrings/gopass-archive-keyring.gpg
EOF
$ sudo apt update
```

### Environment

- OS: [Pop!_OS 22.04 LTS]
- OS version: [5.17.15-76051715-generic #202206141358~1655919116~22.04~1db9e34 SMP PREEMPT Wed Jun 22 19 x86_64 x86_64 x86_64 GNU/Linux]
- gopass Version: [gopass 1.14.3 go1.18.2 linux amd64]
- Installation method: [gopass repo]

**Comment by dominikschulz** [comment]
I've never used Pop OS. Maybe they don't support the `Signed-By`?

I'd like to give it a try some day. But until then you could try adding the the key to the global apt keyring with apt-key add, if you want.

**Comment by gray380** [comment]
This command works for me:
```bash
wget -O- http://packages.gopass.pw/repos/gopass/gopass-archive-keyring.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/gopass-archive-keyring.gpg
```

**Comment by dominikschulz** [comment]
Hmm, the gpg file should be binary and not need dearmor.

Let me verify this.

**Comment by AnomalRoil** [comment]
I'm currently running Pop!_OS on a laptop in case it needs some testing.

I can confirm the same `wget` is giving out binary data that's not armored, btw.

**Comment by AnomalRoil** [comment]
`curl http://packages.gopass.pw/repos/gopass/gopass-archive-keyring.gpg` on the other hand seems to return nothing.

**Comment by dominikschulz** [comment]
The keyring being binary is working as intended.

See https://wiki.debian.org/DebianRepository/UseThirdParty.

> Repositories MUST be signed with an OpenPGP key. A binary export (gpg --export) of the key SHOULD be available at the root of the repository under the filename deriv-archive-keyring.gpg, where deriv is the a short name for the repository. The file SHOULD NOT be ascii-armored (gpg --export --armor) although a separate armored version MAY be available under deriv-archive-keyring.asc.
