### ISSUE TITLE
gopass  thinks my secrets are empty on ubuntu 18.04 (gpg 2.2.4)

### ISSUE THREAD

**Issue by PiotrCzapla** [gopasspw/gopass#2283]
### Summary
I'm setting up gopass on google colab, I've managed to configure gpg along with preset-password so that I'm able to fetch data from private github repo. So gpg works. 

But gopass thinks it isn't. gopass clone fetches private repo using gpg-agent and then complains that there is no usable keys. If I skip key generation, the decryption fails with message '❌  empty secret'.

Unfortunately debugging is problematic as gopass suppress information in this line:
https://github.com/gopasspw/gopass/blob/d122a9c24b698acf1190f61ce5653d0c04741539/internal/action/setup.go#L231-L234

### Steps To Reproduce
it is obvious from code.

### Expected behavior
gopass informs user why it can't access any keys or there is a way to check that
### Environment
google colab, installed today via direct download from github

**Comment by PiotrCzapla** [comment]
It ssems that gopass is able to read all my keys but for some reason it does not encrypt anything.
```
gopass> show test
❌  empty secret
gopass> show kaggle
kaggle/
├── json
├── passwd
├── username
└── yaml

gopass> show kaggle/json
❌  empty secret
```
 I can't diagnose what is going on as the error is muted here as well here:
https://github.com/gopasspw/gopass/blob/d00a8e1dbba5d3a8b4db19ee54f1734fa184dde4/internal/action/show.go#L166-L169

**Comment by dominikschulz** [comment]
Sorry, I'm not familiar with `google colab` and how to use gopass there. Can you please try to provide some more details?

If you want to get more details out of gopass you can run it with `GOPASS_DEBUG_LOG=/some/file.log` and look inside.

Not everything that gets logged might be suitable for posting it here, but it should give you a clue why gopass thinks the keys are unusable.

Also I don't quite understand how you use GPG to fetch from a private GitHub repo. One is GPG the other is using SSH. Different encryption, different keys.

**Comment by PiotrCzapla** [comment]
Hi @dominikschulz , thank you for having a look.
I've got in to the bottom of the issue. Ubuntu on colab has gpg 2.1.x and my macos has gpg 2.3.7. They are not compatible, as 2.3.7 select new AES block cipher ( ) which is not supported by old gpg , and the old gpg fails without errors outputing nothing. 
Basically I can encode on Ubuntu and decode on OSX but not the otherway around. I've described the issue in more details in my answer: to https://unix.stackexchange.com/questions/697579/gpg-failing-with-no-error-for-one-of-my-encrypted-files/710736#710736

I'm looking for a way to workaround this without downgrading my GPG on macos.

>Also I don't quite understand how you use GPG to fetch from a private GitHub repo. One is GPG the other is using SSH. Different encryption, different keys. 
I'm using gpg-agent ssh mode , where it act as ssh-keyagent to authenticate the connections. It was pain to configure but it is working.

**Comment by PiotrCzapla** [comment]
It seems the only way to fix this is to remove any AEAD algorithms from the key prefs, that way the older and slower MDC  (Modification Detection Code) will be used.

I've updated the  stackexchange answer, with the solution, it is rather long. But  I think it would make sense to a mention of this to setup.md.  As currently the keys generated with this guide cannot be used on platforms with GPG version below 2.3. That includes 1ubuntu 18.04 that is supported for 10 years so until 2028. 

For anyone finding this ticket, the way to fix this is to disable AEAD in your key prefs by running `gpg --edit-key ... ` and then `setpref SHA512 SHA384 SHA256 SHA224 SHA1 AES256 AES192 AES ZLIB BZIP2 ZIP Uncompressed` then `y` then save. Then reencrypt your messages. The easiest way I found was to add a dummy recipient which will reencrypt all your passwords.
```
$ gopass recipients add
[ 0] 0x285CE99FAA64E280 - Piotr Czapla (api key used to decrypt gopass on less secure instances) <me@piotrczapla.com>
[ 1] 0x451EB25D7B6320CE - Piotr Czapla <piotr.czapla@....>

Add Recipient - (q to abort) [0]: 1
1
Do you want to add "0x451EB25D7B6320CE - Piotr Czapla <piotr.czapla@....>" (key "0x451EB25D7B6320CE") as a recipient to the store ""? [y/N/q]: y
Reencrypting existing secrets. This may take some time ...
Starting reencrypt
] 5 / 5 [Goooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooopass] 100.00%

Added 1 recipients
You need to run 'gopass sync' to push these changes
```

**Comment by PiotrCzapla** [comment]
And it would be useful to add some information to the error message: ❌  empty secret  and maybe an entry to faq.md

Something like: ❌  empty secret  (see: see https://gopass.pw/faq.md#empty-secret)

To do so I would change the faq to have multiple headers.  I've put that in to the pull request to show you what I mean.

**Comment by PiotrCzapla** [comment]
I've added pull request #2285  with entry to the faq.md .
