### ISSUE TITLE
Document gopass extension framework for custom commands

### ISSUE THREAD

**Issue by chaorace** [gopasspw/gopass#2290]
This line in the README implies that custom commands should be possible via extensions.

https://github.com/gopasspw/gopass/blob/d6acc7063de4e7ceee717284dd1e4e3009163b5b/README.md?plain=1#L47

However, there is no further documentation either for creating extensions nor registering custom commands anywhere in the repository.

**Comment by chaorace** [comment]
Understood if this isn't a high priority at the moment.

Of course, I'd be very thankful if anyone knows of a good example extension I could reference. If not, perhaps just a link to gopass's extension loader code? All hints are appreciated :heart:

**Comment by dominikschulz** [comment]
This is probably the best example we have right now: https://github.com/gopasspw/gopass-hibp

It's maybe not the kind of "extension" you were expecting. I'll need to write something about the reasoning and how to extend `gopass`.
