### ISSUE TITLE
Allow disabling the default `gopass create` wizard templates

### ISSUE THREAD

**Issue by chaorace** [gopasspw/gopass#2291]
Currently, the two default wizard templates for `gopass create` ("Website login" & "PIN Code (numerical)") seem to always load in as options for the wizard.

It would be nice to have a config option to turn this off so that only custom templates appear as options in that wizard menu. I particularly want this because both stock templates are marked "priority: 0", which forces you to use negative priority values in custom templates if you want them to appear first in the list (important if you want to change the default option).

**Comment by dominikschulz** [comment]
Sounds like a valid feature request. But we'll need to figure out how to handle this cleanly.

**Comment by dominikschulz** [comment]
Would you prefer to configure this per password store or per user?
