### ISSUE TITLE
[feature request] Support gitlab deploy token

### ISSUE THREAD

**Issue by MushiTheMoshi** [gopasspw/gopass#2295]
### Summary

Please provide support to do gopass repo add using gitlab deployment tokens which implies having the user and password in the repository url.

### Steps To Reproduce

gopass git remote add --store=MYSTORE origin https://USER:TOKEN@gitlab.com/MYREPO/MYKEYS.git

### Expected behavior

gopass should be able to clone the repo using above syntax
### Environment

- OS:linux ubuntu 20.04
- OS version: Linux ** 5.4.0-122-lowlatency #138-Ubuntu SMP PREEMPT
- gopass Version: gopass 1.12.6+8d7a311b9273846bbb618e4bd9ddbae51b1db7b8
- Installation method:binary

**Comment by dominikschulz** [comment]
I'd expect gopass to handle any valid Git URL.

Could you provide more details on how you try to set this up and what exactly fails, please?

**Comment by AnomalRoil** [comment]
I think you are missing the `https://` in front:
```
gopass git remote add --store=MYSTORE origin https://USER:TOKEN@gitlab.com/MYREPO/MYKEYS.git
```
should work.

Token auth only works for HTTP auth.

**Comment by MushiTheMoshi** [comment]
true, is working, thank you!
