### ISSUE TITLE
[BUG] Gopass reorder variables and add extra spaces 

### ISSUE THREAD

**Issue by MushiTheMoshi** [gopasspw/gopass#2300]
### Summary

when using cat VARS.txt | gopass insert -f -m STORE/VARS.txt variables are getting reordered and case is changed 
![image](https://user-images.githubusercontent.com/13651419/182589818-2dc37854-390b-40f2-bc64-5f896ba13848.png)

### Steps To Reproduce
```
cat <<EOF > .env 
cat .env
AUTH_PORT=8088
AUTH_URL=0.0.0.0

AUTH_MIDDLEWARE_ENDPOINT=http://SERVICE/v1/endpoint2
CASE_GET_TYPE_ENDPOINT=http://SERVICE/v1/endpoint1
EOF 

cat .env | gopass insert -f -m test.secret
```

### Expected behavior

Gopass don't reorder variables, change casing and add extra spaces
### Environment

- OS:  linux ubuntu 20.04
- OS version: Linux  5.4.0-122-lowlatency
- gopass Version: gopass 1.12.6+8d7a311b9273846bbb618e4bd9ddbae51b1db7b8
- Installation method: binary from tags

**Comment by MushiTheMoshi** [comment]
I have updated to latest version ( and the bug is still there.

Hope you can help me.

Regards.
![image](https://user-images.githubusercontent.com/13651419/182591759-4260de5b-c07b-4a27-b9f3-a64190672353.png)

**Comment by MushiTheMoshi** [comment]
closing as disable parsing fix this issue

**Comment by dominikschulz** [comment]
Yes, I'm afraid this is not something that we can "fix". Some users rely on parsing while others can't use it.

**Comment by MushiTheMoshi** [comment]
thanks for the prompt response, appreciated!
