### ISSUE TITLE
gopass v1.14.4 breaks my script

### ISSUE THREAD

**Issue by aleprovencio** [gopasspw/gopass#2304]
### Summary
Sorry if this issue does not belong here, `gopass`'s last update broke [this script](https://github.com/qutebrowser/qutebrowser/blob/master/misc/userscripts/qute-pass). Although username is filled, password is not. Downgrading `gopass` make it work again.

### Steps To Reproduce
With `qutebrowser`, navigate to an authentication form and issue `spawn --userscript qute-pass --mode gopass`

### Expected behavior
Username and password are filled

### Environment
- OS: [Archlinux]
- OS version: [Linux xps 5.18.16-arch1-1]
- gopass Version: [gopass 1.14.4 go1.18.5 linux amd64]
- Installation method: [pacman]

**Comment by dominikschulz** [comment]
Sorry, but we're not debugging your script for you.

If you manage to narrow down the issue we're happy to help.

**Comment by aleprovencio** [comment]
Yeah sorry about that, I've also opened this [issue](https://github.com/qutebrowser/qutebrowser/issues/7336) and hopefully together we can sort it out.

**Comment by AnomalRoil** [comment]
This is weird, since we didn't really bring any breaking changes to the API, to the commands or to `show`, afaik.
Which version are you downgrading to for it to work again?

**Comment by AnomalRoil** [comment]
Could it be the fact that we are now properly honoring the env var `PASSWORD_STORE_DIR` be the reason why it's now failing on your side?

Is your `gopass config path` the same as the variable `arguments.password_store` in your script?

**Comment by aleprovencio** [comment]
You nailed it @AnomalRoil!

I had stopped using `PASSWORD_STORE_DIR` in favor of configuring the path directly on `gopass` config.

Thanks :)
