### ISSUE TITLE
Removing a recipient does not remove their public key from .public-keys

### ISSUE THREAD

**Issue by dAnjou** [gopasspw/gopass#2315]
### Summary
When people leave the project we'd like to remove them from the gopass store completely.

### Steps To Reproduce
```
gopass recipients remove KEY_ID
```

### Expected behavior
The person's key and all their other data is removed from the store.

### Actual behavior
The person is removed as a recipient from `.gpg-id` but their key stays in `.public-keys`. What's the reason and motivation behind this? We'd like to clean this up, can we simply remove the key files without compromising the integrity of the store?

### Environment

- OS: macOS 12.4
- gopass Version: 1.14.4 go1.18.5 darwin arm64
- Installation method: brew

**Comment by dominikschulz** [comment]
This sounds like a bug.
We should clean up after removing a recipient.
