### ISSUE TITLE
gopass sync might sync twice

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#2319]
```
$ gopass sync
🚥 Syncing with all remotes ...
[<root>] 
   gitfs pull and push ... Skipped (no remote)
✅ All done
🚥 Syncing with all remotes ...
[<root>] 
   gitfs pull and push ... Skipped (no remote)
✅ All done
```

Sync / AutoSync wasn't run in a while so it triggered twice. Need to skip autosync if sync is invoked.

**Comment by marcofeltmann** [comment]
I've seen this happening some times on 1.14.10 as well.
Trying to switch to 1.15.5 and keep an eye on that. :)
