### ISSUE TITLE
apt receives 404 when installing gopass-archive-keyring

### ISSUE THREAD

**Issue by marcofeltmann** [gopasspw/gopass#2326]
### Summary
When I configure Debian according to [documentation](https://github.com/gopasspw/gopass/blob/master/docs/setup.md#ubuntu-debian-deepin-devuan-kali-linux-pardus-parrot-raspbian) the installation `apt install gopass-archive-keyring` fails with a 404 error:

>Fehl:1 https://packages.gopass.pw/repos/gopass stable/main all gopass-archive-keyring all 20220903.19.39
>  404  Not Found [IP: 2606:4700:3031::ac43:cbeb 443]
>E: Fehlschlag beim Holen von https://packages.gopass.pw/repos/gopass/pool/main/g/gopass-archive-keyring/gopass-archive-keyring_20220903.19.39_all.deb 404  Not Found [IP: 2606:4700:3031::ac43:cbeb 443]
>E: Einige Archive konnten nicht heruntergeladen werden; vielleicht »apt-get update« ausführen oder mit »--fix-missing« probieren?

According to the website the available version is `https://packages.gopass.pw/repos/gopass/pool/main/g/gopass-archive-keyring/gopass-archive-keyring_20220904.17.39_all.deb`

Seems like some apt-specific index reports the wrong version or path.

### Steps To Reproduce
On the latest greatest Debian just follow the setup instructions on https://github.com/gopasspw/gopass/blob/master/docs/setup.md#ubuntu-debian-deepin-devuan-kali-linux-pardus-parrot-raspbian
When you try to `apt install gopass-archive-keyring` the reported error occurs.

### Expected behavior
I'd love to have `apt` downloading and installing whatever it was told to download and install from the package repository.

### Environment

| Environment | Information |
| :--- | :------ |
| OS | Debian (nonfree, testing) |
| OS version | Linux gopher-cern.local 5.18.0-4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.16-1 (2022-08-10) x86_64 GNU/Linux |
| gopass Version |1.14.5 go1.19 linux amd64; gpg 2.2.35; gitfs 2.35.1 |
| Installation method | apt | 
| apt Version | apt 2.5.2 (amd64) |

### Additional context
I know that this is neither a source code nor an application error, so it maybe cannot be fixed by the GitHub contributors.
This was my first best guess to get in touch.

I downloaded the real package and `apt install`ed it by hand, so there is no urge right now, but it might help others with this issue to find hints for help. 
Well, for future updates I'd love to have it done automagically via `apt`. :)

**Comment by dominikschulz** [comment]
Confirmed. Let me see what's wrong there.

**Comment by dominikschulz** [comment]
I think I know what's going on and I've tried to push a fix, but I don't have enough time to fully verify it right now.
But I'll try to get this working over the next few days.

**Comment by dominikschulz** [comment]
@marcofeltmann Should be fixed now. Please try to verify.

**Comment by marcofeltmann** [comment]
@dominikschulz Works like a charm! :heart:
