### ISSUE TITLE
Make non-error notifications transient

### ISSUE THREAD

**Issue by Layerex** [gopasspw/gopass#2358]
### Summary

Make non-error notifications transient, so those don't show up in notification tray.

![Screenshot from 2022-09-28 11-32-48](https://user-images.githubusercontent.com/59440032/192734575-32a9cbe1-2af2-4b00-9f7e-0f94ac971fff.png)

How to send a transient notification:

```go
call := obj.Call("org.freedesktop.Notifications.Notify", 0, "gopass", uint32(0), iconURI(), subj, msg, []string{}, map[string]dbus.Variant{"transient": dbus.MakeVariant(true)}, int32(3000))
```

Also, I think, for transient nofiications exposition time should be lowered from 5 seconds to 3 (standart transient notifications in GNOME seem to use this value).

**Comment by dominikschulz** [comment]
I think we can easily do that. Thank you.
