### ISSUE TITLE
Reimport extended keys

### ISSUE THREAD

**Issue by elwerene** [gopasspw/gopass#2369]
### Summary
If a gpg key is extended and the public key updated in .public-keys, gopass does not import the new key if the old(expired) key is already in gpg. 

### Steps To Reproduce
User A: Extend a expired gpg key lifetime with the `expire` command and update the public key.
If a new secret is added by another user(which already has the expired gpg key in the keychain), it will not load the new public key and not encrypt the new secret for user A.

### Expected behavior
Public keys with new expiry dates will get automatically imported.

**Comment by dominikschulz** [comment]
Yes, we don't support that today. We should.

But that needs some new logic to check for expired keys in there. Might be to expensive / annoying to do it all the time, but at least `gopass recipients` should give a hint. And maybe we can add something to check and update them to `gopass fsck`.
