### ISSUE TITLE
Cloning an existing repository during setup doesn't work

### ISSUE THREAD

**Issue by WPettersson** [gopasspw/gopass#2380]
### Summary
Cloning an existing repository during setup doesn't work

### Steps To Reproduce
Have a pre-existing gopass git repository remote that functions (has a non-empty `.gpg-id` file at minimum). In my examples, I'll call this `remote:gopass-store`. This, for me, is a `--bare` git repository and works between two computers, and I'm trying to add a third to this setup.

1. Run `gopass setup`
2. Select private key
3. Enter email address `email@address.com`
4. Say "Yes" to "add a git remote" and enter `remote:gopass-store`

### Expected behavior
Gopass first clones the `remote:gopass-store` repository (if it is empty, git will warn but not error), then adds the email `email@address.com` or GPG identifier to `.gpg-id`, creates a git commit, and syncs this back to the remote.

### Actual behaviour

Gopass creates a new repo, adds `email@address.com` or the GPG identifier to `.gpg-id` and then tries to push to `remote:gopass-store` which obviously fails.

### Environment

- OS: Gentoo stable
- OS version: linux 5.15.69
- gopass Version: 1.14.4 go1.19.1
- Installation method: Gentoo's portage

### Additional context

Reading [setup.go](https://github.com/gopasspw/gopass/blob/1978949c9efb736d16090e04d73f96fbe2bc9b9a/internal/action/setup.go) it looks like it assumes that the root repository will not be shared - it only attempts to join or create if both `remote` and `team` are given. I don't know if this is just an oversight, or if its intentional that the root repository should not be easily shareable. For what it's worth, my use case is that this root store is my personal store, I'm sharing it between two personal laptops and desktop, and I have a `work` store shared with work. I don't have any passwords that I don't want to at least put into one of those stores, so if I make a `personal` team then my root store will be empty. This is slightly annoying, as I'll have to use a prefix to my personal team, which I'd prefer to be prefix-less aka the default.

**Comment by dominikschulz** [comment]
IIRC your assumption is correct, i.e. setup.go assumes to not share the root store.

This is not great UX and we should support your use case better.

Thanks for the detailed description.

**Comment by dominikschulz** [comment]
Actually cloning is left to `gopass clone`. `gopass setup is not intended to support that use-case.

So if you have an existing remote just use `gopass clone <remote>`.
Maybe we should give a hint during setup?

**Comment by WPettersson** [comment]
I no longer have exact errors, but I did try using `gopass clone` first (i.e., without setup) but it would complain either when `gopass clone` is run, or when `gopass list` is run after cloning, that setup had not yet been run. I probably just wasn't using the right flags to clone, though.

**Comment by dominikschulz** [comment]
I just tried it and it did work for me in a clean test setup.

In case you can reproduce please let us know and re-open this issue.
