### ISSUE TITLE
gopass automatically pushes after entering a password.

### ISSUE THREAD

**Issue by BRVN01** [gopasspw/gopass#2382]
### Summary

When I add a password with the command i.e 'gopass insert iduna/test', gopass automatically pushes it (I should do it through 'gopass sync').

### Steps To Reproduce
I'm testing gopass 1.14.0

The installation process:

sudo apt install git gnupg2 rng-tools
wget https://github.com/gopasspw/gopass/releases/download/v1.14.0/gopass_1.14.0_linux_amd64.deb
sudo dpkg -i gopass_1.14.0_linux_amd64.deb

### Expected behavior
I should the push with 'gopass sync' as soon as I intend to push the changes.

### Environment
- OS: Ubuntu 20.04
- OS version: 5.4.0-113-generic
- gopass Version: gopass 1.14.0  go1.18  gpg 2.2.19  git 2.25.1
- Installation method: deb package from git

### Additional context
I set the git configuration:
$ git config --global user.email "jhon@foo.bar"
$ git config --global user.name "jhon"
$ git config --global --add safe.directory /usr/local/access/passwords
$ git config --global core.sharedRepository group

Init store:
$ gopass init --crypto gpgcli --path /usr/local/access/passwords --storage gitfs --store iduna 

Set denyCurrentBranch to ignore:
$ cd /usr/local/access/passwords && git config receive.denyCurrentBranch ignore

For other users:
$ gopass setup --remote file:///usr/local/access/passwords --alias iduna

Debug:
$ cat gopass_debug.log 
2022/10/07 23:38:17.883029 pwrules/aliases.go:52	pwrules.loadCustomAliases	no custom aliases found at /home/jhon/.config/gopass/domain-aliases.json
2022/10/07 23:38:17.884154 config/io.go:44	config.loadConfig	Trying to load config from /home/jhon/.config/gopass/config.yml
2022/10/07 23:38:17.884229 config/io.go:132	config.decode	Trying to unmarshal config into *config.Config
2022/10/07 23:38:17.884401 config/io.go:155	config.decode	Loaded config: *config.Config: &config.Config{AutoClip:false, AutoImport:true, ClipTimeout:45, ExportKeys:true, NoPager:false, Notifications:true, Parsing:true, Path:"/home/jhon/.local/share/gopass/stores/root", SafeContent:false, Mounts:map[string]string{"iduna":"/home/jhon/.local/share/gopass/stores/iduna", "portunus":"/home/jhon/.local/share/gopass/stores/portunus"}, ConfigPath:"", XXX:map[string]interface {}(nil)}
2022/10/07 23:38:17.884417 config/io.go:52	config.loadConfig	Loaded config from /home/jhon/.config/gopass/config.yml: &config.Config{AutoClip:false, AutoImport:true, ClipTimeout:45, ExportKeys:true, NoPager:false, Notifications:true, Parsing:true, Path:"/home/jhon/.local/share/gopass/stores/root", SafeContent:false, Mounts:map[string]string{"iduna":"/home/jhon/.local/share/gopass/stores/iduna", "portunus":"/home/jhon/.local/share/gopass/stores/portunus"}, ConfigPath:"/home/jhon/.config/gopass/config.yml", XXX:map[string]interface {}(nil)}
2022/10/07 23:38:17.884458 root/store.go:34	root.New	created store Store(Path: , Mounts: )
2022/10/07 23:38:17.884474 cache/disk.go:25	cache.NewOnDisk	New on disk cache reminder created at /home/jhon/.cache/gopass/gopass/reminder
2022/10/07 23:38:17.884596 action/commands.go:981	action.(*Action).GetCommands	Backend age added 1 commands
2022/10/07 23:38:17.884616 action/commands.go:977	action.(*Action).GetCommands	Backend gpgcli does not implement commander interface
2022/10/07 23:38:17.884647 action/commands.go:977	action.(*Action).GetCommands	Backend plain does not implement commander interface
2022/10/07 23:38:17.884675 action/commands.go:987	action.(*Action).GetCommands	Backend fs does not implement commander interface
2022/10/07 23:38:17.884691 action/commands.go:987	action.(*Action).GetCommands	Backend fossilfs does not implement commander interface
2022/10/07 23:38:17.884705 action/commands.go:997	action.(*Action).GetCommands	Backend gitfs added 1 commands
2022/10/07 23:38:17.884871 root/init.go:17	root.(*Store).IsInitialized	initializing store and possible sub-stores
2022/10/07 23:38:17.884879 root/init.go:69	root.(*Store).initialize	initialize - /home/jhon/.local/share/gopass/stores/root
2022/10/07 23:38:17.884890 leaf/store.go:49	leaf.New	Instantiating  at /home/jhon/.local/share/gopass/stores/root
2022/10/07 23:38:17.884907 backend/storage.go:78	backend.DetectStorage	Trying gitfs for /home/jhon/.local/share/gopass/stores/root
2022/10/07 23:38:17.884919 backend/storage.go:83	backend.DetectStorage	Using detected gitfs for /home/jhon/.local/share/gopass/stores/root
2022/10/07 23:38:17.886590 leaf/store.go:60	leaf.New	Storage for  => /home/jhon/.local/share/gopass/stores/root initialized as gitfs(2.25.1,path:/home/jhon/.local/share/gopass/stores/root)
2022/10/07 23:38:17.887771 backend/crypto.go:78	backend.DetectCrypto	Trying gpgcli for gitfs(2.25.1,path:/home/jhon/.local/share/gopass/stores/root)
2022/10/07 23:38:17.887810 fs/store.go:108	fs.(*Store).Exists	Checking if .gpg-id exists at /home/jhon/.local/share/gopass/stores/root/.gpg-id: true
2022/10/07 23:38:17.888924 backend/crypto.go:83	backend.DetectCrypto	Using gpgcli for gitfs(2.25.1,path:/home/jhon/.local/share/gopass/stores/root)
2022/10/07 23:38:17.888950 cli/loader.go:26	cli.loader.New	Using Crypto Backend: gpgcli
2022/10/07 23:38:17.889034 cli/gpg.go:57	cli.New	failed to read GPG config: open /home/jhon/.gnupg/gpg.conf: no such file or directory
2022/10/07 23:38:17.890197 gpgconf/binary_others.go:28	gpgconf.detectBinary	gpgconf returned "/usr/bin/gpg" for gpg
2022/10/07 23:38:17.890211 cli/gpg.go:78	cli.New	binary detected as /usr/bin/gpg
2022/10/07 23:38:17.890237 leaf/store.go:66	leaf.New	Crypto for  => /home/jhon/.local/share/gopass/stores/root initialized as &{/usr/bin/gpg [--quiet --yes --compress-algo=none --no-encrypt-to --no-auto-check-trustdb] [] [] 0xc00018dbc0 false}
2022/10/07 23:38:17.890258 root/init.go:74	root.(*Store).initialize	Root Store initialized at /home/jhon/.local/share/gopass/stores/root
2022/10/07 23:38:17.890274 root/mount.go:38	root.(*Store).addMount	addMount - Path: /home/jhon/.local/share/gopass/stores/iduna - Full: /home/jhon/.local/share/gopass/stores/iduna
2022/10/07 23:38:17.890280 leaf/store.go:49	leaf.New	Instantiating iduna at /home/jhon/.local/share/gopass/stores/iduna
2022/10/07 23:38:17.890297 backend/storage.go:78	backend.DetectStorage	Trying gitfs for /home/jhon/.local/share/gopass/stores/iduna
2022/10/07 23:38:17.890313 backend/storage.go:83	backend.DetectStorage	Using detected gitfs for /home/jhon/.local/share/gopass/stores/iduna
2022/10/07 23:38:17.891406 leaf/store.go:60	leaf.New	Storage for iduna => /home/jhon/.local/share/gopass/stores/iduna initialized as gitfs(2.25.1,path:/home/jhon/.local/share/gopass/stores/iduna)
2022/10/07 23:38:17.892544 backend/crypto.go:78	backend.DetectCrypto	Trying gpgcli for gitfs(2.25.1,path:/home/jhon/.local/share/gopass/stores/iduna)
2022/10/07 23:38:17.892581 fs/store.go:108	fs.(*Store).Exists	Checking if .gpg-id exists at /home/jhon/.local/share/gopass/stores/iduna/.gpg-id: true
2022/10/07 23:38:17.893654 backend/crypto.go:83	backend.DetectCrypto	Using gpgcli for gitfs(2.25.1,path:/home/jhon/.local/share/gopass/stores/iduna)
2022/10/07 23:38:17.893690 cli/loader.go:26	cli.loader.New	Using Crypto Backend: gpgcli
2022/10/07 23:38:17.893714 cli/gpg.go:57	cli.New	failed to read GPG config: open /home/jhon/.gnupg/gpg.conf: no such file or directory
2022/10/07 23:38:17.894793 gpgconf/binary_others.go:28	gpgconf.detectBinary	gpgconf returned "/usr/bin/gpg" for gpg
2022/10/07 23:38:17.894808 cli/gpg.go:78	cli.New	binary detected as /usr/bin/gpg
2022/10/07 23:38:17.894825 leaf/store.go:66	leaf.New	Crypto for iduna => /home/jhon/.local/share/gopass/stores/iduna initialized as &{/usr/bin/gpg [--quiet --yes --compress-algo=none --no-encrypt-to --no-auto-check-trustdb] [] [] 0xc00049e480 false}
2022/10/07 23:38:17.894843 fs/store.go:108	fs.(*Store).Exists	Checking if .gpg-id exists at /home/jhon/.local/share/gopass/stores/iduna/.gpg-id: true
2022/10/07 23:38:17.894858 leaf/init.go:18	leaf.(*Store).IsInitialized	store "/home/jhon/.local/share/gopass/stores/iduna" is initialized: true
2022/10/07 23:38:17.894867 root/mount.go:52	root.(*Store).addMount	Added mount iduna -> /home/jhon/.local/share/gopass/stores/iduna (/home/jhon/.local/share/gopass/stores/iduna)
2022/10/07 23:38:17.894874 root/init.go:84	root.(*Store).initialize	Sub-Store mounted at iduna from /home/jhon/.local/share/gopass/stores/iduna
2022/10/07 23:38:17.894880 root/mount.go:38	root.(*Store).addMount	addMount - Path: /home/jhon/.local/share/gopass/stores/portunus - Full: /home/jhon/.local/share/gopass/stores/portunus
2022/10/07 23:38:17.894886 leaf/store.go:49	leaf.New	Instantiating portunus at /home/jhon/.local/share/gopass/stores/portunus
2022/10/07 23:38:17.894904 backend/storage.go:78	backend.DetectStorage	Trying gitfs for /home/jhon/.local/share/gopass/stores/portunus
2022/10/07 23:38:17.894922 backend/storage.go:83	backend.DetectStorage	Using detected gitfs for /home/jhon/.local/share/gopass/stores/portunus
2022/10/07 23:38:17.896017 leaf/store.go:60	leaf.New	Storage for portunus => /home/jhon/.local/share/gopass/stores/portunus initialized as gitfs(2.25.1,path:/home/jhon/.local/share/gopass/stores/portunus)
2022/10/07 23:38:17.897019 backend/crypto.go:78	backend.DetectCrypto	Trying gpgcli for gitfs(2.25.1,path:/home/jhon/.local/share/gopass/stores/portunus)
2022/10/07 23:38:17.897052 fs/store.go:108	fs.(*Store).Exists	Checking if .gpg-id exists at /home/jhon/.local/share/gopass/stores/portunus/.gpg-id: true
2022/10/07 23:38:17.898038 backend/crypto.go:83	backend.DetectCrypto	Using gpgcli for gitfs(2.25.1,path:/home/jhon/.local/share/gopass/stores/portunus)
2022/10/07 23:38:17.898065 cli/loader.go:26	cli.loader.New	Using Crypto Backend: gpgcli
2022/10/07 23:38:17.898081 cli/gpg.go:57	cli.New	failed to read GPG config: open /home/jhon/.gnupg/gpg.conf: no such file or directory
2022/10/07 23:38:17.899174 gpgconf/binary_others.go:28	gpgconf.detectBinary	gpgconf returned "/usr/bin/gpg" for gpg
2022/10/07 23:38:17.899187 cli/gpg.go:78	cli.New	binary detected as /usr/bin/gpg
2022/10/07 23:38:17.899211 leaf/store.go:66	leaf.New	Crypto for portunus => /home/jhon/.local/share/gopass/stores/portunus initialized as &{/usr/bin/gpg [--quiet --yes --compress-algo=none --no-encrypt-to --no-auto-check-trustdb] [] [] 0xc00049ed20 false}
2022/10/07 23:38:17.899224 fs/store.go:108	fs.(*Store).Exists	Checking if .gpg-id exists at /home/jhon/.local/share/gopass/stores/portunus/.gpg-id: true
2022/10/07 23:38:17.899232 leaf/init.go:18	leaf.(*Store).IsInitialized	store "/home/jhon/.local/share/gopass/stores/portunus" is initialized: true
2022/10/07 23:38:17.899240 root/mount.go:52	root.(*Store).addMount	Added mount portunus -> /home/jhon/.local/share/gopass/stores/portunus (/home/jhon/.local/share/gopass/stores/portunus)
2022/10/07 23:38:17.899247 root/init.go:84	root.(*Store).initialize	Sub-Store mounted at portunus from /home/jhon/.local/share/gopass/stores/portunus
2022/10/07 23:38:17.899259 root/init.go:23	root.(*Store).IsInitialized	root store is initialized
2022/10/07 23:38:17.899268 fs/store.go:108	fs.(*Store).Exists	Checking if .gpg-id exists at /home/jhon/.local/share/gopass/stores/root/.gpg-id: true
2022/10/07 23:38:17.899277 leaf/init.go:18	leaf.(*Store).IsInitialized	store "/home/jhon/.local/share/gopass/stores/root" is initialized: true
2022/10/07 23:38:17.899292 action/init.go:37	action.(*Action).IsInitialized	Store is fully initialized and ready to go

All systems go. 🚀
2022/10/07 23:38:17.899324 action/insert.go:106	action.(*Action).insertStdin	Created new plain secret with input
2022/10/07 23:38:17.899352 fs/store.go:108	fs.(*Store).Exists	Checking if /teste5/.gpg-id exists at /home/jhon/.local/share/gopass/stores/iduna/teste5/.gpg-id: false
2022/10/07 23:38:17.899360 fs/store.go:40	fs.(*Store).Get	Reading .gpg-id from /home/jhon/.local/share/gopass/stores/iduna/.gpg-id
2022/10/07 23:38:17.899391 fs/store.go:40	fs.(*Store).Get	Reading .gpg-id from /home/jhon/.local/share/gopass/stores/iduna/.gpg-id
2022/10/07 23:38:17.899419 cli/keyring.go:33	cli.(*GPG).listKeys	/usr/bin/gpg [/usr/bin/gpg --with-colons --with-fingerprint --fixed-list-mode --list-secret-keys 0x4F5FA464EDCA48F2]
2022/10/07 23:38:17.904572 cli/keyring.go:33	cli.(*GPG).listKeys	/usr/bin/gpg [/usr/bin/gpg --with-colons --with-fingerprint --fixed-list-mode --list-public-keys 0x4F5FA464EDCA48F2]
2022/10/07 23:38:17.907178 cli/keyring.go:33	cli.(*GPG).listKeys	/usr/bin/gpg [/usr/bin/gpg --with-colons --with-fingerprint --fixed-list-mode --list-public-keys alice]
2022/10/07 23:38:17.909956 cli/keyring.go:33	cli.(*GPG).listKeys	/usr/bin/gpg [/usr/bin/gpg --with-colons --with-fingerprint --fixed-list-mode --list-public-keys bob]
2022/10/07 23:38:17.912733 cli/encrypt.go:43	cli.(*GPG).Encrypt	/usr/bin/gpg [/usr/bin/gpg --quiet --yes --compress-algo=none --no-encrypt-to --no-auto-check-trustdb --encrypt --trust-model=always --recipient 0x4F5FA464EDCA48F2 --recipient alice --recipient bob]
2022/10/07 23:38:17.916563 fs/store.go:56	fs.(*Store).Set	Writing teste5.gpg to /home/jhon/.local/share/gopass/stores/iduna/teste5.gpg
2022/10/07 23:38:17.916691 gitfs/git.go:133	gitfs.(*Git).captureCmd	store.gitAdd: /usr/bin/git [git add --all --force teste5.gpg] (/home/jhon/.local/share/gopass/stores/iduna)
2022/10/07 23:38:17.919578 queue/background.go:96	queue.(*Queue).Add	enqueued task
2022/10/07 23:38:17.919691 gitfs/git.go:133	gitfs.(*Git).captureCmd	store.gitDiffIndex: /usr/bin/git [git diff-index --quiet HEAD] (/home/jhon/.local/share/gopass/stores/iduna)
2022/10/07 23:38:17.921534 gitfs/git.go:142	gitfs.(*Git).Cmd	CMD: gitDiffIndex [diff-index --quiet HEAD]
Error: exit status 1
Output:
  Stdout: ""
  Stderr: ""
2022/10/07 23:38:17.921569 gitfs/git.go:133	gitfs.(*Git).captureCmd	store.gitCommit: /usr/bin/git [git commit --date=1665185897 +00:00 -m Save secret to /teste5: ] (/home/jhon/.local/share/gopass/stores/iduna)
2022/10/07 23:38:17.926329 leaf/write.go:82	leaf.(*Store).gitCommitAndPush	syncing with remote ...
2022/10/07 23:38:17.926388 gitfs/git.go:133	gitfs.(*Git).captureCmd	store.defaultBranch: /usr/bin/git [git rev-parse --abbrev-ref HEAD] (/home/jhon/.local/share/gopass/stores/iduna)
2022/10/07 23:38:17.927663 gitfs/config.go:128	gitfs.(*Git).ConfigList	/usr/bin/git [git config --list]
2022/10/07 23:38:17.928846 gitfs/config.go:107	gitfs.(*Git).ConfigGet	/usr/bin/git [git config --get remote.origin.url]
2022/10/07 23:38:17.929986 gitfs/git.go:133	gitfs.(*Git).captureCmd	store.gitPush: /usr/bin/git [git pull origin master] (/home/jhon/.local/share/gopass/stores/iduna)
2022/10/07 23:38:17.943253 gitfs/git.go:133	gitfs.(*Git).captureCmd	store.gitLsFiles: /usr/bin/git [git ls-files . --exclude-standard --others] (/home/jhon/.local/share/gopass/stores/iduna)
2022/10/07 23:38:17.944618 gitfs/git.go:133	gitfs.(*Git).captureCmd	store.gitPush: /usr/bin/git [git push origin master] (/home/jhon/.local/share/gopass/stores/iduna)
2022/10/07 23:38:17.960139 leaf/write.go:98	leaf.(*Store).gitCommitAndPush	synced with remote
2022/10/07 23:38:17.960165 queue/background.go:87	queue.(*Queue).run	Task done
2022/10/07 23:38:17.960171 queue/background.go:89	queue.(*Queue).run	all tasks done

**Comment by dominikschulz** [comment]
That's working as intended. The feature is called `autosync`. I can not be turned off currently (we still lack a more flexible config handling that would allow us to easily add and remove config options - the current parser is a bit clumsy).
