### ISSUE TITLE
No replacement for `autosync=False`

### ISSUE THREAD

**Issue by stefanv** [gopasspw/gopass#2387]
It looks as though `autosync` has been removed in in the drive towards zero config.

However, it would be great if there was a flag or similar to disable automatic remote interactions. I (and I'm sure others) like to tell my machine when to talk to the internet.

E.g., would something like `gopass --no-sync ...` be possible? Then I could alias `gopass=/usr/bin/gopass --no-sync`.

**Comment by dominikschulz** [comment]
This is a valid request. We did drop the old `autosync` to reduce the config complexity but did miss out on some use cases.

Essentially we're still trying to come up with a versatible but easy enough config format (like git configs) that covers all of our use cases.

Failing that we might add a (hidden) flag as a temporary measure.

**Comment by stefanv** [comment]
Much appreciated; thank you! :pray:

**Comment by gregdan3** [comment]
Seconding this. I don't mind the automatic syncing, but I was accomplishing this with a cronjob already; the autosync interrupting normal operations with gopass is fairly obnoxious and a way to disable autosyncing would be great.

**Comment by dominikschulz** [comment]
Makes sense. If y'all are OK with a flag that might get dropped (or rather: turned into a no-op) once we have a proper config handler in place that'd be easy to fix.

The proper fix, i.e. rewriting our config handling, will take some more time. The main concern here is that it's pretty disruptive and we need to try really hard to get it right on the first try (and provide & test migration tooling).

**Comment by stefanv** [comment]
That would be a perfectly acceptable stopgap solution for me.

**Comment by gregdan3** [comment]
Same here!

**Comment by stefanv** [comment]
Thank you very much @dominikschulz

**Comment by dominikschulz** [comment]
@stefanv You're welcome. This was a lot of work. If you could give the 1.15.0-rc2 (or later) a try that would be much appreciated.
