### ISSUE TITLE
.gpg-id files with comments not handled correctly

### ISSUE THREAD

**Issue by robbat2** [gopasspw/gopass#2393]
### Summary
`pass` correctly ignores comments in `.gpg-id`, but `gopass` treats them as user IDs and this triggers GPG errors.

### Steps To Reproduce
1. Add a key with a comment to `.gpg-id`, e.g. `# EC9FB...`
2. Try to create/edit an entry
3. Get GPG error about `Invalid user ID`

### Gopass behavior
```
$ gopass edit  gentoo-infra/services/cdn77 
gpg: # EC9FB...: skipped: Invalid user ID
gpg: [stdin]: encryption failed: Invalid user ID
```

### Pass behavior
```
$ pass edit demo-secret
[master 117df28] Edit password for demo-secret using vim.
 1 file changed, 0 insertions(+), 0 deletions(-)
```

### Expected behavior
It should work, just like `pass`.

### Environment
- OS: Gentoo
- OS version: 5.18.REDACTED AMD Ryzen 7 3700X 8-Core Processor AuthenticAMD GNU/Linux
- gopass Version: 1.14.4
- Installation method: package manager

**Comment by dominikschulz** [comment]
Yeah, the recipients file parser is super simple.
Supporting comments sounds reasonable, but it will add some complications if we also want to preserve them across edits.

I don't think we will support trailing comments (e.g. `0xABC # some comment`), only per-line comments.
