### ISSUE TITLE
gopass sync with no_push remote and missing GPG public keys

### ISSUE THREAD

**Issue by prologic** [gopasspw/gopass#2408]
### Summary

I _may_ be doing something wrong here, but when sharing password stores, I often share a password store but essentially in "read-only" mode with a Git push origin of `no_push`. I don't import the GPG keys either as I have no intention of re-encrypting secrets in the "shared" (read-onyl) store.

I _think_ we should detect the `no_push` origin and disable the export/import step and squelt the fatal error that occurs when running `gopass sync`.

### Steps To Reproduce

1. Create two stores
2. Create a pair of GPG keys
3. In the 2nd store, create some secrets encrypted to both GPP keys
4. In the first store, clone and mount the 2nd store with a Git origin of `no_push` (DO NOT import the 2nd GPG key)
5. Run `gopass` sync and observe the behaviour.

### Expected behavior

I expect the export/import step to be skipped and the git pull/push step to be skipped, without error.

### Environment

macOS with latest `goapss`.

**Comment by prologic** [comment]
The work-around is to basically selectively sync stores:

```console
$ gopass sync -s root
```

**Comment by dominikschulz** [comment]
That sounds like a clever, but oddly specific, workaround.
We did have this request before and what we came up with is a readonly option for certain mounts.

See https://github.com/gopasspw/gopass/pull/2395

**Comment by prologic** [comment]
Ahh I see 👌
