### ISSUE TITLE
gopass edit fails if 'vi' is not 'vim'

### ISSUE THREAD

**Issue by ehaupt** [gopasspw/gopass#2412]
https://github.com/gopasspw/gopass/blob/f5067e6d817530b613205d95fce03e9dd6b67812/internal/editor/editor.go#L104-L109

This fails on FreeBSD since FreeBSD's vi is not vim but [nvi](https://www.freebsd.org/cgi/man.cgi?query=nvi) and lacks the option `-i`. There are other Linux distros or *BSD's where this is the case.

See also: [FreeBSD issue #267689](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=267689)

**Comment by dominikschulz** [comment]
Yes, this is a problem.

On the one hand we want to provide a secure by default workflow.

But on the other hand we can't know all possible editors.

What's better: Adding the flags only if we know the editor or only dropping it when we know it won't work?

**Comment by ehaupt** [comment]
> Yes, this is a problem.
> 
> On the one hand we want to provide a secure by default workflow.
> 
> But on the other hand we can't know all possible editors.
> 
> What's better: Adding the flags only if we know the editor or only dropping it when we know it won't work?

I'm all for secure defaults.

How about setting the flags only if `EDITOR` is set to `vim` and print out a warning if another editor is used similar to gpg:

```
gpg: WARNING: unsafe permissions on homedir '/tmp/foo'
```

**Comment by nunotexbsd** [comment]
FreeBSD defaults EDITOR=vi, so it continue to fail with same error.
Changing EDITOR=nvi fixes the problem but will be needed user intervention to change EDITOR variable.

**Comment by ehaupt** [comment]
> FreeBSD defaults EDITOR=vi, so it continue to fail with same error.
> Changing EDITOR=nvi fixes the problem but will be needed user intervention to change EDITOR variable.

Confirmed.

An easy way to test if 'vi' is actually a 'vim' would be:

```sh
vi --version 2>&1 | grep -q "VIM - Vi IMproved" && echo "vi is vim" || echo "vi is no vim"
```

You could use the exit code to decide whether 'vi' has the desired capabilities:

Return code `1`: `vi` is no `vim`:

```sh
vi --version 2>&1 | grep -q "VIM - Vi IMproved"; echo $?
1
```


Return code `0`: `vi` is a `vim`:

```sh
vi --version 2>&1 | grep -q "VIM - Vi IMproved"; echo $?
0
```

@dominikschulz: can you re-open the ticket or should we create a new issue?
