### ISSUE TITLE
"gopass recipients remove" deletes recipients based on email not key id

### ISSUE THREAD

**Issue by RickC37** [gopasspw/gopass#2416]
### Summary
I got a new computer and I thought this is also a good moment to rotate my GPG key.
So I just created a new key.
I asked a colleague to trust my new public key.
After that I was able to decrypt the secrets.

After that I removed my old key form the project.

`gopass recipients remove`

I selected the entry with the old gpg key and the process to reencrypting the secrets started.

After checking the recipients with..

`gopass recipients `

.. I noticed that not just my old key was removed but also my new one 🫤

The only thing both keys had in common was my email.
I have used the same email again.
It is just a new computer, not a new identity.

Therefore I guess the removal logic is using the email and not the key-id as it should be in my POV.

### Steps To Reproduce
had no time to make further tests

### Expected behavior
my new key should stay in the list of recipients and I am still able to decrypt the secrets

### Environment
- OS: Apple M1 Pro 
- OS version: Ventura 13
- gopass Version: gopass 1.14.10 go1.19.3 darwin arm64
- Installation method: brew

### Additional context
zsh shell

**Comment by dominikschulz** [comment]
Sounds like a possible bug in the key selection. Sorry. We should indeed use the key ID, if available.

**Comment by dominikschulz** [comment]
Tried to reproduce this. Without success so far. We're going to need your debug log output.

Please try to reproduce with `GOPASS_DEBUG_LOG=/tmp/gopass.log` set and provide the (sanitize) log output.

**Comment by dominikschulz** [comment]
Actually I was able to reproduce a very similar case. This will need some more investigation.
But I guess in the end the recipients handling just tries to be "too clever".
