### ISSUE TITLE
Gopass rm -rf flag combinations

### ISSUE THREAD

**Issue by tpeacock19** [gopasspw/gopass#2419]
### Summary
Running `gopass rm -rf [password]` returns an error when `gopass rm -r -f [passwd]` does not. Is there any reason why the combined flags are not usable?

This has caused an issue with Proton's credential helper which I've created a PR to separate the flags https://github.com/ProtonMail/docker-credential-helpers/pull/5; However, I don't think that should really be necessary. Unless there is a limitation I'm unaware of, I really do think this command should accept the combined flags.

**Comment by dominikschulz** [comment]
I don't know if the command line lib we're using does support these. If it does and we haven't turned it on we can probably do so. If it doesn't support combined short flags we won't be able to support it. I do consider this nice to have, not a major issue.

**Comment by dominikschulz** [comment]
`urfave/cli/v3` seems to support `UseShortOptionHandling`.

**Comment by tpeacock19** [comment]
Thank you!
