### ISSUE TITLE
gopass edit fails: -c option, 1: The - command is unknown

### ISSUE THREAD

**Issue by ehaupt** [gopasspw/gopass#2424]
In continuation of #2412 the `-c` flag needs to be dropped if `vi` is not a real `vim`.

```sh
$ gopass edit foo
-c option, 1: The - command is unknown
```

**Comment by dominikschulz** [comment]
*sigh* Thanks for the feedback. I'm starting to think that we should maybe just require (a real) vim ...

**Comment by ehaupt** [comment]
> _sigh_ Thanks for the feedback. I'm starting to think that we should maybe just require (a real) vim ...

I understand the sentiment but that would blow up the dependency chain quite a lot.

It's safe to assume that `$EDITOR FILE` will suffice.

If you like to test the FreeBSD port you can quickly spin up a vagrant box. [This](https://app.vagrantup.com/generic/boxes/freebsd13) one should suffice.

Thank **you** for the quick response :smiley_cat:

**Comment by nunotexbsd** [comment]
1.14.11
EDITOR=vi

`gopass edit foo`
```
🚥 Syncing with all remotes ...
[<root>]
   gitfs pull and push ... Skipped (no remote)
✅ All done
✅ Found exact match in "websites/foo.com/foo"
Secret does not exist "foo". Found possible match in "websites/foo.com/foo". Edit existing entry? [Y/n/q]: y
vi: illegal option -- i
usage: ex [-eFRrSsv] [-c command] [-t tag] [-w size] [file ...]
usage: vi [-eFlRrSv] [-c command] [-t tag] [-w size] [file ...]

Error: failed to invoke editor: failed to run vi with /tmp/gopass-edit3796617766/secret file: exit status 1
```

**Comment by nunotexbsd** [comment]
Shouldn't vi options set to {} like nvi?

```"vi":     {"-c", "autocmd BufNewFile,BufRead /dev/shm/gopass* setlocal noswapfile nobackup noundofile viminfo=\"\"", "-i", "NONE", "-n"},
"nvi":    {},
"neovim": {"-c", "autocmd BufNewFile,BufRead /dev/shm/gopass* setlocal noswapfile nobackup noundofile shada=\"\"", "-i", "NONE", "-n"},
"vim":    {"-c", "autocmd BufNewFile,BufRead /dev/shm/gopass* setlocal noswapfile nobackup noundofile viminfo=\"\"", "-i", "NONE", "-n"},
```

IMHO nvi and vi options should be set to {}

**Comment by dominikschulz** [comment]
I was able to reproduce the issue. The test isn't very elegant, but the workflow should now at least work.

**Comment by nunotexbsd** [comment]
Works fine with vi/nvi.

Thanks!
