### ISSUE TITLE
Document website aliases

### ISSUE THREAD

**Issue by varac** [gopasspw/gopass#2453]
### Summary

Please document how to use website aliases. I noticed [Website aliases](https://github.com/gopasspw/gopass/issues/682) which was closed by https://github.com/gopasspw/gopass/pull/1419 but I don't see any documentation to it.

There's `domain-alias.from` mentioned in https://github.com/gopasspw/gopass/blob/master/docs/config.md#configuration-options-1 but I can't make it work.
There's also the `gopass alias` command but i lacks documentation in https://github.com/gopasspw/gopass/tree/master/docs/commands

### Environment

- OS: Arch Linux
- OS version: `Linux zancas 6.0.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 02 Dec 2022 17:25:31 +0000 x86_64 GNU/Linux`
- gopass Version: `gopass 1.14.11 go1.19.3 linux amd64`
- Installation method: Pacman

Thanks !

**Comment by dominikschulz** [comment]
You're absolutely right. At least this needs some examples.
