### ISSUE TITLE
gopass --password, -o do not work on keyed entries

### ISSUE THREAD

**Issue by Daemoen** [gopasspw/gopass#2477]
### Summary
You would expect gopass -o to show a secret only when using the -o flag.  This isn't the case....

### Steps To Reproduce
`gopass edit ladidadida`

paste:
```
username: someuser
password: somesillypassword
totp: otpauth://somesilly&totp
url: http://some-silly.url
```

`gopass show -o ladidadida`

### Expected behavior
`somesillypassword`

### Environment
```
    System Software Overview:

      System Version: macOS 12.6.1 (21G217)
```
```
gopass 1.15.1 go1.19.4 darwin arm64
<root>     -  gpg 2.3.8 -   fs 0.0.0
Available Crypto Backends: age, gpgcli, plain
Available Storage Backends: fossilfs, fs, gitfs
```

installed via brew

**Comment by dominikschulz** [comment]
This was never supported nor did we intend to support this so far (this being: threating a password key any special).
