### ISSUE TITLE
q doesn't abort as advertised

### ISSUE THREAD

**Issue by thatlittleboy** [gopasspw/gopass#2490]
### Summary

The text prompt says "(q to abort)", but when I press "q", gopass proceeds to open up $EDITOR to create a new secret instead.

<img src="https://user-images.githubusercontent.com/30731072/209471110-f065d9e7-2a16-43d5-930f-0f572504a1c7.png" width="400">

### Steps To Reproduce

Exactly as the image shows. Just `gopass edit <query>` where query returns a list of candidate secrets, then press `q`. Then vim (or EDITOR) will pop up prompting me to create a new password/secret.

### Expected behavior

`q` should abort, i.e., don't do anything and exit gopass. Not proceed with creating a secret.

### Environment

- OS:  Mac OS Monterey
- OS version: Darwin [redacted] 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64
- gopass Version: gopass 1.15.2 go1.19.4 darwin amd64
- Installation method: brew

### Additional context

nil

**Comment by dominikschulz** [comment]
That used to work. Let me check what's wrong.
