### ISSUE TITLE
fsck --decrypt re-encrypts all the files even those with no need to touch

### ISSUE THREAD

**Issue by DEvil0000** [gopasspw/gopass#2494]
### Summary
fsck --decrypt reencrypts all the files even those with no need to touch.
I mentioned that allready in #2459 and was told to create a separate issue.

### Steps To Reproduce
gopass fsck --decrypt 

### Expected behavior
should only re-encrypt files where the key changed or such but should ignore files without the need for re-encryption.

### Environment
- OS: fedora 37
- OS version: 6.0.14-300.fc37.x86_64
- gopass Version: master
- Installation method: go install from master used the latest package before
- BTRFS

**Comment by dominikschulz** [comment]
Yes, this is correct. I now understand the issue and I think we have PR #2492 open already they might fix it.
