### ISSUE TITLE
[FR] Investigate ov as a pager

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#2507]
https://pkg.go.dev/github.com/noborus/ov/oviewer could be a good platform independent pager.

**Comment by nunotexbsd** [comment]
Hello,

I have a doubt about ov included upstream on systems that ov is available as a port/package: https://www.freshports.org/textproc/ov/

While I don't know yet how ov is used by gopass, I'm thinking if it should be built or not on gopass port and give an option to use ov external port instead.

Does this make any sense? :)

Thanks
