### ISSUE TITLE
gopass cannot sync on fossilfs

### ISSUE THREAD

**Issue by dertuxmalwieder** [gopasspw/gopass#2516]
Related discussion: #2022

-------------

A gopass store that uses fossilfs cannot synchronize with a remote Fossil repository.

## Reproducing the problem(s):
1. Initialize gopass with Fossil and age: `gopass setup --crypto age --storage fossilfs`
2. Run gopass
3. Type `sync`

###  Expected behavior:
`fossil sync` is run.

```
> fossil help sync
Usage: fossil sync ?URL? ?options?

Synchronize all sharable changes between the local repository and a
remote repository.  Sharable changes include public check-ins and
edits to wiki pages, tickets, forum posts, and technical notes.

If URL is not specified, then the URL from the most recent clone, push,
pull, remote, or sync command is used.  See "fossil help clone" for
details on the URL formats.
```

### Actual behavior:
> fs pull and push ... Skipped (no Git repo) (no changes)

**Comment by dominikschulz** [comment]
That should be easy to support and I thought I already tested this. But possible that it never properly worked. Fossilfs is really very experimental.

**Comment by dertuxmalwieder** [comment]
I know, that’s why I tested. :-)

**Comment by ckolumbus** [comment]
I've run into the same issue... and i'm also interested in using age/fossil combo in order to easily distribute credentials without the overhead (esp avoiding gpg).

**Comment by dominikschulz** [comment]
Looking at the code this should be already supported.

Could you try it again with debug logging enabled, please?
Set `GOPASS_DEBUG_LOG=/some/file.log`.

**Comment by dertuxmalwieder** [comment]
It looks like - at least on Windows - no log is created...?

**Comment by dominikschulz** [comment]
Supporting Fossil isn't as easy as it should be. No matter from which ISP I always get random "this IP is blocked for abuse" errors on fossil-scm.org ... :facepalm:

**Comment by ckolumbus** [comment]
> Supporting Fossil isn't as easy as it should be. No matter from which ISP I always get random "this IP is blocked for abuse" errors on fossil-scm.org ... :facepalm: 

How do you test this? Maybe I can help with alternative test setups.

**Comment by dertuxmalwieder** [comment]
I’m not quite good with tests, sadly.

**Comment by dominikschulz** [comment]
Manual testing is also very valuable, of course!
