### ISSUE TITLE
Reencryption of specific entries.

### ISSUE THREAD

**Issue by Paktosan** [gopasspw/gopass#2517]
I need to reencrypt some files because I missed some updated keys.
While running `gopass fsck --decrypt` fixes that, it also changes every entry for file format and creates a commit for each.
In my case, this results in over 350 commits.
I do not want this, I just want to fix the few files…
`gopass edit` also is no option as it does not reencrypt when I don't change the file content.
It would be great for something like `gopass fsck --decrypt store/folder/entry` to work or to have a `--rencrypt` option with the `edit` command.

**Comment by dominikschulz** [comment]
Don't we already support `gopass fsck <entry>`? Let me check.

**Comment by dominikschulz** [comment]
It does already support a filter argument.

If that doesn't work for you as advertised or if you have another use-case please re-open this issue with more details.

**Comment by Paktosan** [comment]
I was aware of the filter argument for fsck. However, it does not fulfil my need.

Let's say, I have an password store entry `folder/subfolder/entry`.
When I give this as the filter, it does not match. `folder/subfolder` would match.

So it is not possible to select a single entry.

I also just observed that when I use `folder/subfolder` as filter, fsck changes permissions on a file like `folder/subfolder2/entry`.
While the issue is valid, it must not touch that entry as it is not in the scope of the filter.

I also forgot to mention the version of gopass I am on. It is 1.15.2
