### ISSUE TITLE
`gopass cat` does not work properly

### ISSUE THREAD

**Issue by revengel** [gopasspw/gopass#2518]
`gopass cat path/to/key`

gopass <= 1.15.2
command works well - show file content

gopass 1.15.3

`gopass cat path/to/key`

We get the output the same as the result of the command

`gopass show -f path/to/key`

**Comment by dominikschulz** [comment]
That should still work like it did with 1.15.2.

Let's try to dig in and see what broke ...

**Comment by dominikschulz** [comment]
I can't reproduce right now, but I think we might have written invalid lower-case CTE headers for a while. I'll add a workaround for that as well.
