### ISSUE TITLE
Missing $HOME/.ssh causes gopass decryption to error out

### ISSUE THREAD

**Issue by jmpolom** [gopasspw/gopass#2525]
### Summary
If `~/.ssh` is missing from the user's home directory and the store uses the age encryption backend, showing a secret will fail citing inability to open a file in `$HOME/.ssh`.

### Steps To Reproduce
1. In a testing environment, `rm -rf $HOME/.ssh` or `rm -rf ~/.ssh` or attempt from within a containerized environment missing this directory by default.
2. Run `gopass show -f secret_name`
3. Enter password/PIN if asked
4. Results:
    ```
    [root@3737b5f66ec4 ~]# gopass show -f secret_name
    Enter your PIN: 
    ❌ Decryption failed: open /root/.ssh: no such file or directory
    
    
    Error: failed to retrieve secret "secret_name": failed to decrypt
    ```
5. Recipients info:
    ```
    [root@3737b5f66ec4 ~]# gopass recipients
    Hint: run 'gopass sync' to import any missing public keys
    gopass
    └── age1<...>
    ```

### Expected behavior
gopass gracefully skips over the missing file in `$HOME/.ssh` and moves on to attempt decryption with age keys, only producing an error after and if all decryption methods have been exhausted.

### Environment
- OS: Fedora 36 host, Fedora 36 container
- OS version: `Linux 3737b5f66ec4 6.1.6-100.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 14 17:00:40 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- gopass Version: `gopass 1.14.3 go1.18.3 linux amd64`
- Installation method: Fedora package repositories

### Additional context

Without evaluating the code at play here, it is possible the root cause of this issue lies with an upstream go package.

**Comment by dominikschulz** [comment]
Oh, this is an old version.

We already fixed this.
