### ISSUE TITLE
gopass edit gives Error: no results found

### ISSUE THREAD

**Issue by meaz** [gopasspw/gopass#2531]
### Summary
To add a secret, I used to do `gopass edit /path/to/secret`.
For some reason, it doesn't work anymore. I get `Error: no results found` when doing so.
The way I found to have it work is to do `gopass edit -c /path/to/secret`.

So my questions are:
- Why doesn't that work anymore? When you `gopass --help` you still can see `edit, set Edit new or existing secrets`
- `gopass --help edit` shows `--create, -c Create a new secret if none found (default: false)`: how can I change this to true by default?

### Steps To Reproduce
`gopass edit /path/to/secret`

### Expected behavior
Create the secret and open the editor to edit it.

### Environment
- OS: Arch
- gopass Version: 1.15.3

**Comment by dominikschulz** [comment]
Yes, this was changed at some point. I did always like to use `edit` to create new entries, too.
But there was some push to not make it create new entries by default.

I think it could easily be a config option.
