### ISSUE TITLE
domains that have a rule with a `Maxlen` of `0` generate a 16-character password even if a specific length is provided

### ISSUE THREAD

**Issue by sudoforge** [gopasspw/gopass#2536]
```
➜ gopass generate google.com 64
An entry already exists for google.com. Overwrite the current password? [y/N/q]: y
⚠ Using password rules for google.com ...
How long should the password be? (min: 8, max: 0) (q to abort) [0]: 64
✅ Password for entry "google.com" generated
Not printing secrets by default. Use 'gopass show google.com' to display the password.


➜ pass show -o google.com | wc -m
16
```

However, using `--force` works around this bug.

```
➜ pass generate --force google.com 64
✅ Password for entry "google.com" generated
Not printing secrets by default. Use 'gopass show google.com' to display the password.


➜ pass show -o google.com | wc -m
64
```

---

Traveling, but will take a look later. Let me know if you need more info.

**Comment by dominikschulz** [comment]
Thanks for reporting this and for the instructions to reproduce.
I can reproduce and it's quite buggy, indeed.

- If given a length on the command line it shouldn't ask for a length again
- I **think** user input should take precedence, but we **might** want to emit a warning to warn users of using a passwords that's possibly too long

**Comment by sudoforge** [comment]
> If given a length of the command line it shouldn't ask for a length again

Agreed.

> I **think** user input should take precedence, but we **might** want to emit a warning to warn users of using a passwords that's possibly too long

I think emitting a _warning_ (not blocking or asking for confirmation, just an info/warn message) is a fine idea (maybe with a config option to disable them?), but only if we have a defined maximum length in the rule for the given domain. In this case, `google.com` has a rule with a `Maxlen` of `0`, which I've historically understood as "we don't know the maximum limit for this domain". I've also experienced quite a few rules that are incorrect (sorry, I haven't kept a list of these or bothered to go and update the rules, but I'll remember to do this in the future), which is why I personally think the user's input should _definitely_ take precedence, and why I'd want to disable the warning message (because I'd personally see it as excess noise).
