### ISSUE TITLE
Failed to git commit: git is not initialized

### ISSUE THREAD

**Issue by lefuturiste** [gopasspw/gopass#2543]
### Summary

When initializing the gopass store, I get an error "Failed to git commit"

```
$ go pass init
🍭 Initializing a new password store ...
🔑 Searching for usable private Keys ...
⚠ Hint: Use 'gopass init <subkey> to use subkeys!'
❌ Failed to git commit: git is not initialized
❌ Failed to export missing public keys: some keys failed
```

### Steps To Reproduce

`gopass init`

### Expected behavior

That I get no errors

### Environment

- OS: Arch linux
- OS version: `Linux hostname 5.15.90-1-lts #1 SMP Tue, 24 Jan 2023 12:46:03 +0000 x86_64 GNU/Linux`
- gopass Version: `gopass 1.15.3 go1.19.5 linux amd64`
- Installation method: `pacman community package`

**Comment by lefuturiste** [comment]
Ok my bad I have to use `gopass setup` instead of `gopass init`

**Comment by dominikschulz** [comment]
Actually `gopass init` should also work ...

**Comment by dominikschulz** [comment]
This seems to be more of a cosmetic error (but still a bug).

I can mostly reproduce this, i.e. `gopass init` works as expected, the store is in a good state afterwards but I do still get the annoying error message. Will fix that.

**Comment by lefuturiste** [comment]
Thanks
