### ISSUE TITLE
Automatically push, but don't automatically pull/sync.

### ISSUE THREAD

**Issue by sudoforge** [gopasspw/gopass#2551]
### Summary

I use `gopass` from one primary machine, and use a mobile device as a "read-only client". Because of this workflow, I like the automatic push functionality provided by `core.autosync`, but I do not like the automatic syncing with all remotes feature provided by the same configuration option.

I propose splitting `core.autosync` into two configuration options:

* `core.autopush` to control whether or not to push after a new commit is made
* `core.autosync` to control whether or not to automatically sync with all remotes

**Comment by sudoforge** [comment]
I forgot to mention that I know this can currently be accomplished through setting `core.autosync = false` and configuring `{create,delete,edit}.hooks`, but this feels non-optimal due to the configuration overhead.

**Comment by ckolumbus** [comment]
IMHO this should be configurable per mounted store.
