### ISSUE TITLE
Fish is marked as a required dependency on Fedora

### ISSUE THREAD

**Issue by stigok** [gopasspw/gopass#2553]
### Summary

`fish` is marked as a required dependency on Fedora.

### Steps To Reproduce

```
# dnf install gopass
```

### Expected behavior

`fish` should not be a required dependency.

### Environment

- OS: Fedora 37
- OS version: `Linux myhost 6.1.9-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Feb  2 00:21:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- gopass Version: 1.15.2-1.fc37
- Installation method: `dnf`

**Comment by dominikschulz** [comment]
Isn't that something for the Fedora bug tracker?

**Comment by stigok** [comment]
It seems you're right. I made an assumption that the packaging for the distros was also happening here. I'll open a case over there and link it in when available.
