### ISSUE TITLE
`gopass update` fails to validate GPG signature

### ISSUE THREAD

**Issue by dkaslovsky** [gopasspw/gopass#2559]
### Summary
gopass version 1.15.3 fails to update to 1.15.4 when running `gopass update` with the following error:
```
Error: Failed to update gopass: signature verification failed: failed to validated detached GPG signature: openpgp: signature made by unknown entity
```

### Steps To Reproduce
Run `gopass update`.

### Expected behavior
`gopass update` is able to install the latest version of gopass.

### Environment

- OS: macOS Ventura 13.2.1, M1 ARM, also happening on an Intel-based macOS running the same OS version
- OS version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023
- gopass Version: gopass 1.15.3 go1.19.4 darwin arm64
- Installation method: gopass repo

**Comment by dominikschulz** [comment]
Yeah, the point is ... I don't think we can fix this now.

The old key expired before we shipped a new one. So 1.15.3 still comes with the old, expired key only.
We can't use the expired key for signing or verification anymore, so 1.15.4 is signed with the new one.

Going forward we will need to start shipping the new key a few months before the old one expires ... :/

**Comment by dkaslovsky** [comment]
@dominikschulz Thanks for the answer. No worries and that makes sense. I should have mentioned in my initial comment how much I appreciate `gopass` and the time you spend maintaining it. `gopass` is a tool I use every day and I recommend it to anyone who is considering their password manager options. Thank you for all that you are doing!
