### ISSUE TITLE
fsck always returns missing recipients

### ISSUE THREAD

**Issue by aleprovencio** [gopasspw/gopass#2572]
### Summary

Running `gopass fsck` returns this error, even after running the suggested `gopass fsck --decrypt`:

```
failed to check "path/site.com/user":
[fatal] [non-fatal] Missing recipients on path/site.com/user: [key-in-fingerprint-format]
Run fsck with the --decrypt flag to re-encrypt it automatically, or edit this secret yourself., Run fsck with the --decrypt flag to re-encrypt it automatically, or ed
it the secret path/site.com/user yourself.
```

I'm already added in the recipients list, but I noticed that that my key on `.gpg-id` is on the short format (0xXXXXXXXXXXXXXXXX) rather than the fingerprint.

I'm unsure whether this is related to https://github.com/gopasspw/gopass/issues/1900

### Steps To Reproduce

- create a new password store
- create a new secret
- run `gopass fsck`

### Expected behavior

No errors, at least on the second run of this command

### Environment

- OS: Archlinux
- gopass Version: 1.15.4
- Installation method: pacman

**Comment by relves** [comment]
Same here. And I don't know if it makes any difference but I'm using the 0xXXXXXXXXXXXXXXXX!  (the additional '!' on the end).

**Comment by aleprovencio** [comment]
I've finally had time to come back to this, and the issue was that old one of having `throw-keyids` set on my `gpg.conf`.

I'm unsure on why `gopass fsck` has not warned me about this, but anyways, glad this was sorted out.

Hope it helps you too @relves

**Comment by relves** [comment]
Thanks @aleprovencio, you called it.  All fixed here now as well. Greatly appreciated!
