### ISSUE TITLE
`gopass -c` fails on Xorg/X11 if `wl-clipboard` is installed alongside `xclip`

### ISSUE THREAD

**Issue by pdecat** [gopasspw/gopass#2577]
### Summary

Using `gopass -c` fails on X11 if `wl-clipboard` is installed alongside `xclip`:

```
# gopass show -c somesecret

Error: failed to write to clipboard: failed to write to clipboard: exit status 1
```

### Steps To Reproduce

* open an X11 session
* install xclip and wl-clipboard, e.g.: `sudo apt install xclip wl-clipboard`
* try `gopass -c somesecret`

### Expected behavior

* gopass should use xclip on X11 and wl-clipboard on Wayland.

### Environment

- OS: Ubuntu Lunar Lobster (23.04 beta)
- OS version: `Linux myhost 6.1.0-16-generic #16-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 24 14:37:30 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- gopass Version: `gopass 1.15.4 go1.20 linux amd64`
- Installation method: from source

### Additional context

For context, I recently (re-)tried to switch from Xorg to Wayland on Ubuntu, so I installed `wl-clipboard` to make `gopass -c ` work there. But after a week of testing, I had to switch back because of performance degradation and usability issues with several applications and Gnome extensions I depend on.

**Comment by dominikschulz** [comment]
Thanks for the report. This sounds like a setup we definitely should support properly.

**Comment by dominikschulz** [comment]
I think this should work, at least I couldn't reproduce and the clipboard library we're using seems to handle this [correctly](https://github.com/atotto/clipboard/blob/master/clipboard_unix.go#L52).

Feel free to add more details if you want, but so far I can't reproduce.
