### ISSUE TITLE
gopass generate with a custom template results in "empty secrets" Error

### ISSUE THREAD

**Issue by stites** [gopasspw/gopass#2586]
### Summary
gopass generate with a custom template adds a newline before the template. This causes the entry to look empty

### Steps To Reproduce
```
$ gopass templates edit foo             # although happens for .pass-template
$ # set template as {{ .Content }} on first line (or accept the defaults)
$ gopass generate foo/bar/baz 10
$ gopass -c foo/bar/baz
Error: empty secret. see https://go.gopass.pw/faq#empty-secret
```

### Expected behavior
output of `gopass -c foo/bar/baz` is:
```
✔ Copied foo/bar/baz to clipboard. Will clear in 45 seconds.
```

### Environment
- OS: NixOS-22.11
- OS version: `Linux maclane 6.1.24 #1-NixOS SMP PREEMPT_DYNAMIC Thu Apr 13 14:55:40 UTC 2023 x86_64 GNU/Linux`
- gopass Version: `gopass 1.15.5 go1.20.3 linux amd64`
- Installation method: nixpkgs-unstable package overlay. [Derivation is here](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/tools/security/gopass/default.nix).

### Additional context
None I can think of

**Comment by dominikschulz** [comment]
Hey @stites I tried to reproduce this today, but for me this works as expected.
I did exactly what you listed in the "Steps to Reproduce" and I end up with the expected content.

**Comment by stites** [comment]
Hmmmm... Okay. I will try replicating this on a mac (and maybe on ubuntu) to see if it is an issue. This can be considered closed until then. 

One question: can you tell me how to reset the root template? Since working with templates, I now always get an empty newline (and this is possibly related to the issue at hand).

Thank you!

**Comment by stites** [comment]
I finally got around to testing this. it turns out that my script is doing something a little more complicated than the above steps, but I'll need some more time to investigate.

Quick preview: I am writing a script to account for two workflows: in one I am producing a dynamic username at `websites/example.com/example@myemail.com` and in the other I am moving this dynamically created email login as a field of `websites/example.com` (via `login = {{ .Name }}`). Somewhere in there a wire is getting crossed and I'm observing this issue on both NixOS and OSX.
