### ISSUE TITLE
gopass insert/show with nested YAML keys

### ISSUE THREAD

**Issue by AxelRHD** [gopasspw/gopass#2615]
I'm just starting with gopass. 

Is there the possibility to get and set nested YAML keys with the CLI or do I have to edit the entry with `gopass edit`?

Thanks.

**Comment by shemeshg** [comment]
I confirm I have the same problem, when nested fields exists, it adds same field with same name, and rip the nested one

```
macos@macoss-Mac-mini ~ % gopass show FAST/tempThing
Secret: FAST/tempThing

field1: shalomBobo
fields type:
  field1: url

macos@macoss-Mac-mini ~ % echo gogoKing|gopass insert FAST/tempThing field1
macos@macoss-Mac-mini ~ % gopass show FAST/tempThing
Secret: FAST/tempThing

field1: shalomBobo
fields type:
field1: gogoKing


macos@macoss-Mac-mini ~ %

macos@macoss-Mac-mini ~ % echo 3rd|gopass insert FAST/tempThing field1
macos@macoss-Mac-mini ~ % gopass show FAST/tempThing
Secret: FAST/tempThing

field1: shalomBobo
fields type:
field1: 3rd



```

**Comment by dominikschulz** [comment]
@shemeshg I can't reproduce your issue. Feel free to open another issue with more details.

@AxelRHD Editing nested keys is not directly supported. Please use `gopass edit`.
