### ISSUE TITLE
Make gopass sync optional

### ISSUE THREAD

**Issue by stephan-devop** [gopasspw/gopass#2616]
### Summary
I want to be able to stop gopass from syncing when running `gopass show`. 
For example: `gopass --nosync show mysecret`

### Steps To Reproduce
When I run gopass for the first time (for example in a new docker container) then gopass will sync automatically. This can take a long time as network connections are involved. Afterwards, a file `~/.cache/gopass/gopass/reminder/autosync` is created. The next run does not autosync unless a certain time has elapsed. But when an ephemeral user runs gopass then it will always autosync as these files do not exist. I'd like to switch off this behaviour with a command line switch.

I need this for the [ansible passwordstore lookup plugin](https://docs.ansible.com/ansible/latest/collections/community/general/passwordstore_lookup.html) to work properly. 

- OS: Debian
- OS version: bullseye
- gopass Version: gopass 1.15.4 go1.19.5 linux arm64
- Installation method: debian repo  https://packages.gopass.pw/repos/gopass

**Comment by dominikschulz** [comment]
I think it would be reasonable to provide a flag to override whatever is set in the config per invocation.
