### ISSUE TITLE
Option to only show sync notifications if something has changed or on error

### ISSUE THREAD

**Issue by Flowdalic** [gopasspw/gopass#2618]
### Summary
`gopass sync` currently triggers a notification unconditionally. This easily becomes noisy. Personally, I prefer to be not bothered whenever sensible. 

Please consider adding a, or multiple, configuration option(s) so that `gopass` sync only shows a notification
- if something has changed
- if the sync operation failed with an error

**Comment by dominikschulz** [comment]
Yeah, that sounds reasonable.
