### ISSUE TITLE
Non-interactive setup 

### ISSUE THREAD

**Issue by gus4rs** [gopasspw/gopass#2619]
I am working with ansible playbooks to automatically setup machines with gopass, is there a way to do

```
gopass setup --crypto=age --storage=fs 
```

Non-interactively, providing the passphrase as a parameter?

**Comment by dominikschulz** [comment]
`setup` is meant to be interactive while `init` should be non interactive.

But I haven't verified recently if there is feature parity.

**Comment by AnomalRoil** [comment]
After #2960
`gopass init --crypto=age --storage=fs AGE-SECRET...`
does work almost fully non-interactively if providing a native identity and 
`gopass init --crypto=age --storage=fs AGE-PLUGIN... age1pluginname...`
should also work for plugins (we cannot derive the recipient from a plugin secret directly, it needs to be provided).

It still does prompt for password for the `identity` keyring file tho, which can only be avoided once #2108 will have been implemented.

**Comment by AnomalRoil** [comment]
This now works on `master` as documented here, using `gopass init`:
https://github.com/gopasspw/gopass/blob/master/docs/backends/age.md#getting-started

It'll be in the next release @gus4rs
