### ISSUE TITLE
1.15.6 fails to build

### ISSUE THREAD

**Issue by nunotexbsd** [gopasspw/gopass#2629]
### Summary

Fails to build via go.mod:
```
# github.com/kbinani/screenshot
vendor/github.com/kbinani/screenshot/screenshot.go:11:10: undefined: GetDisplayBounds
vendor/github.com/kbinani/screenshot/screenshot.go:17:9: undefined: Capture
```
and stops at:

```
<snip>
github.com/gopasspw/gopass/internal/hook
github.com/gopasspw/gopass/internal/store/root
github.com/gopasspw/gopass/internal/create
*** Error code 1
```
### Environment
FreeBSD 13.2 amd64 / go 1.20

**Comment by dominikschulz** [comment]
We did have some issues and I had to re-tag 1.15.6. I'll double check later if all refs were correctly pushed.
I'm sorry for the trouble, but the correct tag should build correctly on FreeBSD.

**Comment by AnomalRoil** [comment]
I guess maybe the proper way would be to retract v1.15.6 and release v1.15.7 instead to make sure to avoid any such issues?

**Comment by dominikschulz** [comment]
Yes, we should have a 1.15.7 once we are sure that we can avoid such a hickup.

But I still wonder why they were seeing this issue.

**Comment by dominikschulz** [comment]
Yes, correct. Updated my comment :)

Does the port use automation?
I wonder if it tried to use the broken tag right after it was pushed.
The hash currently pointed at by the v1.15.6 tag should build on FreeBSD, I think.

**Comment by nunotexbsd** [comment]
Port is using GO_MODULE= github.com/gopasspw/gopass that fetches deps auto for a specific version.

**Comment by nunotexbsd** [comment]
> Does the port use automation? I wonder if it tried to use the broken tag right after it was pushed. The hash currently pointed at by the v1.15.6 tag should build on FreeBSD, I think.

Port is fetching:
`SHA256 (go/security_gopass/gopass-v1.15.6/v1.15.6.mod) = af319dd543d55e1f1c300fd6ce60503bd4a2587159b0fa1807e9b9af5280e320`

Same error.

**Comment by nunotexbsd** [comment]
Hello,

I've found a way to get go.mod from a specifix tag (https://github.com/gopasspw/gopass/commit/8c666a93d844015cca992be0ab0c39992bb096ed) to test build.

A newbie question: How do I get a proper yyyymmddhhmmss modversion tag?

GO_MODULE= github.com/gopasspw/gopass@vX.0.0-yyyymmddhhmmss-abcdefxyz
GO_MODULE= github.com/gopasspw/gopass@vX.0.0-yyyymmddhhmmss-8c666a93d

Thanks

**Comment by AnomalRoil** [comment]
Using `go mod tidy` usually

**Comment by nunotexbsd** [comment]
Good news!

v1.15.6-3-g8c666a93 [1] fixes build using go module method.

`GO_MODULE=      github.com/gopasspw/gopass@v0.0.0-20230801080807-8c666a93d844
`
( 20230801080807 TS is from commit 8c666a93
`Date:   Tue Aug 1 10:08:07 2023 +0200`

[1] `git describe --tags 8c666a93`

Thanks all!
