### ISSUE TITLE
gopass doesn't build on s390x and ppc64le anymore

### ISSUE THREAD

**Issue by ptrcnull** [gopasspw/gopass#2638]
### Summary
gopass seems to be depending on `github.com/gen2brain/shm` as a transitive dependency since 1.15.6, but the library uses code that's very architecture-specific and not available on s390x or ppc64le

### Steps To Reproduce
- `go build` on ppc64le

### Expected behavior
it builds

### Environment
- OS: Alpine Linux edge
- OS version: 6.1.43-0-lts
- gopass Version: 1.15.6 or later
- Installation method: source

**Comment by dominikschulz** [comment]
I'm surprised to see users on `s390x` or `ppc64le` but I've always tried to keep `gopass` working (or at least: compilable) on all Go supported archs.

I'll take this and make sure we have a test that cross-compiles to all supported archs on pull requests to avoid introducing arch dependent code.

And then we either need to guard offending features with build tags or we can't merge them.
