### ISSUE TITLE
fsck should support a filter path and/or --store options

### ISSUE THREAD

**Issue by DEvil0000** [gopasspw/gopass#2641]
### Summary
fsck --decrypt should support a filter path and/or --store options
in a big store with a lot of mounts fsck is a bit painfull.
it should support --store to select the mount to run on
it should in addition support a filter by path (was not working for me with --decrypt)

tested with 1.15.4 i think

**Comment by dominikschulz** [comment]
For me running `fsck` with a path works as expected. We can add a store option, but once that's in please check if that all works as expected and report back if not.
