### ISSUE TITLE
Store is undeletable if store name is accidentally ended with `/`

### ISSUE THREAD

**Issue by p4perf4ce** [gopasspw/gopass#2669]
### Summary
Accidentally created a new store with `--store name/` instead of `--store name` making it undiscoverable by `gopass`. This will require the user to manually delete the mount point in the `config` file.

### Steps To Reproduce

1. Initialize the password-store with `[a-zA-Z]+\/`
2. gopass ls will show the mount as `STORE_NAME` without `/` but you can't do anything with it. Note that the actual path `/` is replaced with `-`. E.g., `/home/username/.local/share/gopass/STORE_NAME-`

### Expected behavior

If the name is illegal, it shouldn't be created.

### Environment

- OS: Darwin 22.6.0: Wed Jul  5 22:17:35 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8112 arm64
- OS: Linux 5.15.90.1-microsoft-standard-WSL2 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- gopass Version: gopass 1.15.8 go1.21.1 darwin arm64
- Installation method: brew (MacOS & Ubuntu 22.04 WSL)

### Additional context

Remove the things in `.config/gopass/config` can workaround this issue.

**Comment by dominikschulz** [comment]
Good point. Indeed. This is clearly missing some input validation. We'll add that.
