### ISSUE TITLE
Remaining store after `gopass` uninstall

### ISSUE THREAD

**Issue by alexxtasi** [gopasspw/gopass#2676]
### Summary

Not sure it's a bug or my misunderstanding ...
After cleaning all passwords and also `gpg` keys, I uninstalled `gopass` in order to install again and start over.

### Steps To Reproduce

1. delete passwords (`gopass delete ...`)
2. uninstall `gopass`
3. remove `./local/share/gopass` directory
4. remove all `gpg` keys and create new ones
5. install `gopass` again from Solus repos
6. run `gopass list` just to check ... before `init` and then this error message appears :
```
~ $ gopass list
❌ Failed to initialize mount /run/media/user/Kingston/gopass (/home/user/.local/share/gopass/stores/-run-media-user-Kingston-gopass). Ignoring: failed to init sub store "/run/media/user/Kingston/gopass" at "/home/user/.local/share/gopass/stores/-run-media-user-Kingston-gopass": password store /run/media/user/Kingston/gopass is not initialized. Try gopass init --store /run/media/user/Kingston/gopass --path /home/user/.local/share/gopass/stores/-run-media-user-Kingston-gopass
gopass
```

### Expected behavior

To initialize `gopass` without the error.

### Environment

- OS: `Solus (Gnome)`
- OS version: `Linux emu 6.5.5-258.current #1 SMP PREEMPT_DYNAMIC 0 x86_64 GNU/Linux`
- gopass Version: `gopass 1.15.7 go1.20.7 linux amd64`
- Installation method: `Solus repo`

### Additional context

This Kingston store is something I created at the first run, just for testing `gopass`. Not sure if I followed the right procedure.

- How can I get rid of this store ?
- How can `gopass` find this again after removing `./local/share/gopass` directory ?
- Is there another place where `gopass` stores settings, so I can delete it ?

regards

**Comment by tjex** [comment]
It sounds like you haven't removed the config file. By default located at `$HOME/.config/gopass/config`. This file will have at least the `mount` section, pointing gopass to where password stores should be. As you've deleted the password store, when you are running the fresh gopass installtion, it is still reading the old config file and thinking there should be a password store at `.../Kingston/gopass`. 

Just delete the config file (or move it elsewhere as a backup if you need to transfer some entries from it to the new config file), and then procede.

**Comment by alexxtasi** [comment]
thanks very much @tjex !!
Removing `$HOME/.config/gopass/` did the trick.
