### ISSUE TITLE
apt packages - no description given

### ISSUE THREAD

**Issue by fetwar** [gopasspw/gopass#2695]
### Summary
Some (possibly all) of the gopass apt packages have no description, making it a bit harder to identify the correct gopass packages to install via `apt` for debian based systems, compounded by the fact that there is another `gopass` repo by default.

### Steps To Reproduce
Follow [gopass setup documentation for apt](https://github.com/gopasspw/gopass/blob/master/docs/setup.md#ubuntu-debian-deepin-devuan-kali-linux-pardus-parrot-raspbian) install.

Summary of steps (for full instructions see the docs)
1. Install gpg keyring
2. Add apt repository entry for `gopass.sources`
3. `sudo apt update`
4. `apt search gopass`
5. Package descriptions should display as 'no description given'

Output of `apt search gopass`:
```
Sorting... Done
Full Text Search... Done
git-credential-gopass/stable 1.15.5 amd64
  no description given

golang-github-aviau-gopass-dev/lunar,lunar 1.5.0-1 all
  pass implementation in Go - dev package

golang-github-gopasspw-pinentry-dev/lunar,lunar 0.0.2-2 all
  Pinentry client in Go (library)

golang-github-howeyc-gopass-dev/lunar,lunar 0.0~git20190910.7cb4b85+dfsg.1-1 all
  getpasswd for Go

gopass/stable 1.15.8 amd64
  no description given

gopass-archive-keyring/stable 20231008.9.40 all
  Auto-generated aptd metadata for gopass

gopass-hibp/stable 1.15.5 amd64
  no description given

gopass-jsonapi/stable 1.15.5 amd64
  no description given

gopass-summon-provider/stable 1.15.5 amd64
  no description given

upass/lunar,lunar 0.3.0-1.1 all
  console UI for pass
```

Output of `apt search gopass --full`
```
Sorting... Done
Full Text Search... Done
git-credential-gopass/stable 1.15.5 amd64
  no description given

golang-github-aviau-gopass-dev/lunar,lunar 1.5.0-1 all
  pass implementation in Go - dev package
  gopass is a Pass (http://www.passwordstore.org/) implementation in Go.
  .
  Password management should be simple and follow Unix philosophy. With
  gopass, each password lives inside of a gpg encrypted file whose filename
  is the title of the website or resource that requires the password. These
  encrypted files may be organized into meaningful folder hierarchies,
  copied from computer to computer, and, in general, manipulated using
  standard command line file management utilities.
  .
  This package is not gopass.pw (similar project with the same name).
  .
  This package contains the go source files.

golang-github-gopasspw-pinentry-dev/lunar,lunar 0.0.2-2 all
  Pinentry client in Go (library)
  Pinentry client in Go

golang-github-howeyc-gopass-dev/lunar,lunar 0.0~git20190910.7cb4b85+dfsg.1-1 all
  getpasswd for Go
  Retrieve password from user terminal or piped input without echo.
  Caution: Multi-byte characters not supported!

gopass/stable 1.15.8 amd64
  no description given

gopass-archive-keyring/stable 20231008.9.40 all
  Auto-generated aptd metadata for gopass

gopass-hibp/stable 1.15.5 amd64
  no description given

gopass-jsonapi/stable 1.15.5 amd64
  no description given

gopass-summon-provider/stable 1.15.5 amd64
  no description given

upass/lunar,lunar 0.3.0-1.1 all
  console UI for pass
  upass is a curses-based (more specifically urwid) interface for pass, the
  standard Unix password manager.  It provides a simple, but powerful view of
  the password store and can copy passwords or extended information to the
  clipboard interactively.
  .
  pass is the standard unix password manager, to be found in the pass package.
  .
  There is another implementation of a curses interface, gopass.pw, but it
  is a complete reimplementation. In contrast, upass simply wraps the standard
  pass implementation.
```

### Expected behavior
Output of easily distinguishable package descriptions to aide install of correct packages.

### Environment
- OS: `Ubuntu 23.04 (Lunar)`
- OS version: `Linux 6.2.0-34-generic #34-Ubuntu SMP PREEMPT_DYNAMIC Mon Sep  4 13:06:55 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
- gopass Version: `n/a`
- Installation method: `n/a`

### Additional context
Please note that the issue is with the packages within repository https://packages.gopass.pw/repos/gopass repository

Output after removing gopass.source, updating and performing `apt search gopass` again:
```
Sorting... Done
Full Text Search... Done
golang-github-aviau-gopass-dev/lunar,lunar 1.5.0-1 all
  pass implementation in Go - dev package

golang-github-gopasspw-pinentry-dev/lunar,lunar 0.0.2-2 all
  Pinentry client in Go (library)

golang-github-howeyc-gopass-dev/lunar,lunar 0.0~git20190910.7cb4b85+dfsg.1-1 all
  getpasswd for Go

gopass/lunar 1.5.0-1 amd64
  pass implementation in Go

upass/lunar,lunar 0.3.0-1.1 all
  console UI for pass
```

**Comment by dominikschulz** [comment]
Good catch. We're using Goreleaser to build these packages. It should be possible to customize their description: https://goreleaser.com/customization/nfpm/

**Comment by dominikschulz** [comment]
@fetwar Feel free to take a look at my PR and suggest changes.

**Comment by fetwar** [comment]
I've had a look at the PR and left my thoughts :)

I know that `gopass-hibp`, `gopass-jsonapi`, `gopass-summon-provider` are in different git repos, just @ me there to get me to have a quick look at them if you'd like @dominikschulz.

I think that the biggest issue to resolve is identifying which packages are related to the right version of gopass, so keeping something identifying in the package descriptions 1st line should exponentially help with that.

Thanks for opening a PR so quick, this package looks great and I am keen to try it out more with my team.
