### ISSUE TITLE
`core.notifications = false` not working in mounts

### ISSUE THREAD

**Issue by AnomalRoil** [gopasspw/gopass#2721]
> Not only this, but I have `core.notifications = false` set, but I've started getting notifications (clipboard copy, clear, etc)
>
>_Originally posted by @tjex in https://github.com/gopasspw/gopass/issues/2673#issuecomment-1779264183_
            

I have confirmed this to be the case for mounts: it seems we are currently not properly handling substore and their config when we are fetching config FromContext.

**Comment by AnomalRoil** [comment]
@tjex can you confirm this is impacting you on a substore / mounts and not on your root store config?

e.g. you've set it using `gopass config --store yourmount corenotifications false`?

**Comment by dominikschulz** [comment]
I wonder how useful it is to set notification settings per substore. But we should still handle per-store configs correctly.

**Comment by tjex** [comment]
@AnomalRoil sorry for the late reply. I don't actually have any substores / mounts. Only the one root.
