### ISSUE TITLE
Feature Request: Wizard type multiline / editor

### ISSUE THREAD

**Issue by maarek** [gopasspw/gopass#2795]
### Summary

Support a new entry type in the creation wizard that will open the $EDITOR for long multi-line strings similar to the insert functionality but following the wizard template flow.

**Comment by AnomalRoil** [comment]
Doesn't our template feature allow for that already?
https://github.com/gopasspw/gopass/blob/master/docs/features.md#password-templates

**Comment by AnomalRoil** [comment]
Sorry, I meant to link to the Wizard's template, not the other ones:
https://github.com/gopasspw/gopass/blob/master/docs/commands/create.md#templates

**Comment by maarek** [comment]
Sure, I am interesting in storing secured notes in gopass as I am migrating from my password manager Bitwarden. You can use string and get a single line input, but it's a little awkward with large multiline payloads and requires that you paste it in rather than write it. Then I have to go in and ensure the formatting is correct.

The alternative would be to `insert -m <path>` which would open up the $EDITOR and allow me to create a password such as:
    
    note: 1234
    5678
    9101
    etc

**Comment by AnomalRoil** [comment]
Oh, I see. Does `gopass edit -c new/entry/name` suffices for your needs?

**Comment by maarek** [comment]
Yes, there are ways to work around it. But as a feature, this would be nice so that I could create fluid wizard templates for my team's input of data in a consistent way.
