### ISSUE TITLE
gopass attempts to make GPG key despite there being one already

### ISSUE THREAD

**Issue by apprehensions** [gopasspw/gopass#2809]
### Summary
When running `gopass setup`, `gopass` attempts to make a new GPG key, despite there already being one present.

### Steps To Reproduce
1. Make OpenKeychain key, and import it as normal
2. See it is present under `keyboxd` section in `gpg --list-secret-keys`
3. `gopass setup`

### Expected behavior
I can use the key from OpenKeychain and get on with my day.

### Environment

- OS: Linux
- OS version: `6.7.6-0-edge`
- gopass Version: `gopass 1.15.11-git+HEAD go1.22.0 linux amd64`
- Installation method: `go install`

**Comment by filipe-esr** [comment]
Trying to troubleshoot the same issue. Generated GPG Key and executed `gopass init`, it did not found the Key.

Environment:
- macOS Sonoma 14.4.1
- gopass 1.15.13 go1.22.2 darwin arm64
- gpg version: gpg (GnuPG) 2.4.5
- installations via `brew`

**Comment by apprehensions** [comment]
I actually managed to fix this issue on my own minutes after opening it due to it being it a duplicate issue.

**Comment by apprehensions** [comment]
I believe the solution was to change your trust level to maximum or 5 on your gpg key.
