### ISSUE TITLE
Feature request: configuration option to disable logo in notification

### ISSUE THREAD

**Issue by apprehensions** [gopasspw/gopass#2810]
Hi, i would like to request a small feature in which it is a boolean to disable the logo when sending D-Bus notifications.

The logo is ugly.

**Comment by dominikschulz** [comment]
Which logo? The icon?

**Comment by apprehensions** [comment]
The notification sent by gopass has a icon attached to it - that one.

**Comment by dominikschulz** [comment]
That is an oddly specific feature request, but I have no fundamental concerns.
I'm just wondering if we need to cater for such niche requests at the expense of having more maintenance overhead.

**Comment by apprehensions** [comment]
I'll do it then.
