### ISSUE TITLE
Public keys are not exported into mounted stores

### ISSUE THREAD

**Issue by Adirelle** [gopasspw/gopass#2830]
### Summary

When adding recipients to a mounted store, their keys are not exported into the `.public-keys` directory of the target store.

### Steps To Reproduce

0. (Optional: set GOPASS_HOMEDIR and PASSWORD_STORE_DIR to point to empty directories to avoid interference from existing configuration and stores)
1. Create a new root store : `./gopass init`
2. Create and mount a new substore : `./gopass mounts add -c substore ./substore`
3. Add a recipient to the substore : `./gopass recipients add --store=substore SOME_KEY_ID`
4. Observe that the key has not been exported into the substore : `ls ./substore/.public_keys`

### Expected behavior

Public keys are exported into the `.public_keys` directory of the target store.

### Environment

- OS: Ubuntu 22.04 in WSL2
- OS version: `Linux orgrimmar 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- gopass Version: gopass 1.15.11 go1.22.1 linux amd64 (e390f25aa74a888e066d64470cd03fe2f220942f)
- Installation method: from source

**Comment by dominikschulz** [comment]
This should work. I will try to reproduce, but in the meantime you might want to run gopass with `GOPASS_DEBUG_LOG=/tmp/gopass.log` set in the shell and check the log for `updating exported keys`.

And the value of `gopass config core.exportkeys` would be intresting as well.

**Comment by Adirelle** [comment]
The value of `core.exportkeys`:

```console
$ ./gopass config core.exportkeys
true
```

And here is the full log : [gopass-log.txt](https://github.com/gopasspw/gopass/files/14626957/gopass-log.txt)

**Comment by Adirelle** [comment]
Interestingly, `core.exportkeys` for the mounted store seems to be disabled by default:

```console
$ ./gopass config --store=substore core.exportkeys
```

**Comment by Adirelle** [comment]
Here is a script that I use to consistently reproduce the bug:
[test_mount_export_keys.txt](https://github.com/gopasspw/gopass/files/14627075/test_mount_export_keys.txt)

I could not fully automatize it though. One have to answer to some prompts.

**Comment by Adirelle** [comment]
Here a script that I use to consistently reproduce the bug with a fresh gopass built from master :  
[test_mount_export_keys.txt](https://github.com/gopasspw/gopass/files/14627105/test_mount_export_keys.txt)

**Comment by dominikschulz** [comment]
Ah, so it happens on a mounted substore?

That might be a problem with the default value of core.exportkeys in substores. Thank you, that is helpful.
