### ISSUE TITLE
Windows Defender detects 1.15.12 as malware

### ISSUE THREAD

**Issue by s1shed** [gopasspw/gopass#2842]
### Summary
Attempting to run gopass 1.15.12 with the latest Windows updates results in Defender quarantining the file `gopass.exe`.

![image](https://github.com/gopasspw/gopass/assets/8793762/f14c618f-6ee0-40c4-a3c6-92c2efef73a9)

### Steps To Reproduce

1. Download `gopass-x64-windows-1.15.12.msi` with the sha256 hash of `7df382ebd7ca99689ae97d19c17658cc01e668640fc85f5d68b57363b75a771b` from the releases page.
2. Install gopass 1.15.12 with the msi package. 
3. Attempt to run gopass

This can also be reproduced installing 1.15.12 with choco and winget. 

### Expected behavior
Gopass runs, just as 1.15.11 does.

### Environment
- OS: Windows 11
- OS version:  10.0.22631 N/A Build 22631
- gopass Version: 1.15.12
- Installation method: The amd64 msi from https://github.com/gopasspw/gopass/releases/tag/v1.15.12/. 

### Additional context

Virustotal does not show that Microsoft detects this as a virus, but Windows Defender still flagged it as [Trojan:Win32/Bearfoos.A!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FBearfoos.A!ml&threatid=2147731250)

![image](https://github.com/gopasspw/gopass/assets/8793762/a5f4aa18-7559-4ab0-b343-075565b335a9)

**Comment by dominikschulz** [comment]
Yes, this is annoying. Sorry. I'm not sure if there is anything we can do about it. I guess Bearfoss.A is written in Go and this is a false positive 😢

**Comment by dominikschulz** [comment]
It looks like there might be a process to flag FPs with MS: https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide#part-4-submit-a-file-for-analysis

**Comment by dominikschulz** [comment]
That was surprisinly easy. I've filed an false positive report with MS. Let's see how that goes.

**Comment by dominikschulz** [comment]
> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications. The detection has been removed.

This looks promising. I do not have a Windows machine available to verify right now, but it should be fixed.
