### ISSUE TITLE
[Question] Is there anyway to add a pin before showing the password

### ISSUE THREAD

**Issue by rjshrjndrn** [gopasspw/gopass#2886]
When using `gopass -c` in linux, especially in an unlocked machine. Are there any way to add a secret pin, like a 4 digit pin, after which the password can be copied.

**Comment by dominikschulz** [comment]
We rely on the crypto backend (e.g. GPG or age) for this. If you configure GPG to cache your passphrase it won't ask again until it's expired. But this can be changed.
