### ISSUE TITLE
gopass fsck --decrypt should mention filename where decryption fails

### ISSUE THREAD

**Issue by darix** [gopasspw/gopass#2898]
### Summary

currently only it only shows the gpg error message that decryption failed.

also it might be helpful to summarize all filenames in the end which couldnt be reencrypted.

### Steps To Reproduce

run `gopass fsck --decrypt` with an entry which you cant decrypt

### Expected behavior

I get a list of files that cant be reencrypted

### Environment

- OS: openSUSE Tumbleweed
- gopass Version: 1.15.13
- Installation method: openSUSE package

**Comment by dominikschulz** [comment]
@darix For easier reproducibility please provide the full error message.

**Comment by darix** [comment]
how about this simple idea:

when ever you call gpg and the process fails. you have the filename you passed to gpg in the error message?

**Comment by dominikschulz** [comment]
It still depends on it's called exactly so we can properly pass and format the filename.
I can add it to the debug log, but that will require extra steps to show up.

If you'd prefer to have it in the regular output please do provide the requested information.
