### ISSUE TITLE
gopass setup should validate empty email

### ISSUE THREAD

**Issue by jcrben** [gopasspw/gopass#2949]
### Summary
At least if you're using the gpg backend, it needs an email otherwise it spits out a message like this:

```
2024/09/25 18:53:46 failed to check private keys: failed to create new private key: 
failed to create new private key: 
failed to run command: '/usr/bin/gpg [/usr/bin/gpg --batch --gen-key]': 
"gpg: Generating a RSA/RSA key pair\ngpg: -:8: missing argument\n" - exit status 2
```

Probably obvious to most, but still better to give a friendly validation error.

### Steps To Reproduce
See above

### Expected behavior
Refuse to proceed with empty email and gpg backend?

### Environment

- OS: Ubuntu 24.04
- OS version: Linux lenovo-legion 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- gopass Version: gopass 1.15.14 go1.22.5 linux amd64
- Installation method: manual .deb file

**Comment by zenc0derr** [comment]
Hi @jcrben , Are u working on this issue?

**Comment by jcrben** [comment]
no

**Comment by gagandeepp** [comment]
@jcrben  interested , please assign

**Comment by jcrben** [comment]
@gagandeepp I can't assign, maybe @AnomalRoil or @dominikschulz can assign

**Comment by gagandeepp** [comment]
@jcrben 
![Screenshot 2024-10-07 at 6 14 55 PM](https://github.com/user-attachments/assets/6de77b38-566a-421b-b529-4ca40acdd8dd)

I am able to setup without email as mentioned in the screenshot

**Comment by gagandeepp** [comment]
@dominikschulz can you please see my comments above?

**Comment by jcrben** [comment]
You selected 2, try just hitting enter to go with the default (0).

I just replicated it on a fairly clean Ubuntu 24.04 machine (Framework laptop). 

Steps:
*  brew.sh install per instructions
* brew install --build-from-source gopass
* gopass setup
* hit enter a few times

![image](https://github.com/user-attachments/assets/a4310ab4-182c-4f6e-b5cd-c03fc2872526)

**Comment by gagandeepp** [comment]
@dominikschulz  Please review
