### ISSUE TITLE
Gopass command before setting up gopass

### ISSUE THREAD

**Issue by sarojregmi200** [gopasspw/gopass#2963]
### Summary
It is not a bug, but thought it might help make this project a tiny bit better. I tried setting up the gopass today and installed it successfully and tried to run gopass by running `gopass` binary. And it says it is not yet setup to setup type `gopass init` and then exits the process. 
I think it can be improved. 
![Screenshot 2024-10-06 at 17 41 35](https://github.com/user-attachments/assets/23ef9153-9cf5-417c-8ff4-12faa5c7d022)

### Steps To Reproduce
- install gopass.
- Type gopass in your terminal and see (you should not have it already configured).

### Better behavior
Gopass is not yet setup in your system do you want to set it up? A small message like this will be a smoother onboarding experience for those who are setting it up for the first time.

### Environment
Local, personal pc.

- OS: [Arch linux]
- gopass Version: [1.15.14]
- Installation method: [pacman]

 
>I have just started using the project and have searched for similar issue but have not found one it is what I think is a goodway and what I felt while getting the error message.

**Comment by dominikschulz** [comment]
Thanks for the report. But I'm afraid I don't fully understand how you'd like it to change.

We already provide a hint on what to do (`gopass setup`).
Could you maybe provide an example of how a more welcoming error message could look like?

**Comment by sarojregmi200** [comment]
Sure.

It would be great if it just continued, rather than exiting the program.
Saying something like.
**"Do you want to continue to setup? yes(y) no(n)".**

Something like this will better improve the flow of the program.
