### ISSUE TITLE
Gopass binary data support

### ISSUE THREAD

**Issue by nicolas-g** [gopasspw/gopass#2967]
### Summary
According to the website https://www.gopass.pw/ , binary data support is coming soon!
```
Store binary data
With gopass you can store more than just simple passwords. You are able to store any kind of data as binary to the password store. 
Coming soon!
```

I'm just creating this issue in order to track when encryption for binary data support will be available.

**Comment by dominikschulz** [comment]
Wo do have that actually. But we will need to update the documentation. Thanks for filing this.

**Comment by nicolas-g** [comment]
> Wo do have that actually. But we will need to update the documentation. Thanks for filing this.

That is awesome, I would love to start using this ASAP :)

**Comment by nicolas-g** [comment]
> Wo do have that actually. But we will need to update the documentation. Thanks for filing this.

any updates?

**Comment by TM2500** [comment]
I think https://github.com/gopasspw/gopass/blob/master/docs/features.md#support-for-binary-content & docs/commands/cat.md is still valid.

**Comment by nicolas-g** [comment]
Thank you
