### ISSUE TITLE
Gopass to use a specific gpg version ?

### ISSUE THREAD

**Issue by nicolas-g** [gopasspw/gopass#2968]
### Summary
On a MacOS I have different version binaries of gpg installed ( 2.4.5 &  2.2.41).
whenever I run gopass, I see a warning using the older version (2.2.41)

### Steps To Reproduce
```shell
gopass show mysecret
gpg: WARNING: server 'gpg-agent' is older than us (2.2.41 < 2.4.5)
gpg: problem with fast path key listing: IPC parameter error - ignored

Secret: mysecret

xyz
```
See Additional context bellow for more details.

### Expected behavior
No WARNING...

### Environment

- OS: macOS 14.6.1 23G93 arm64
- OS version: Darwin MBP23.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6031 arm64
- gopass Version: gopass 1.15.14 go1.22.5 darwin arm64
- Installation method: brew

### Additional context

My gpg and gpg-agent version is 2.4.5
```shell
 which gpg
/opt/homebrew/bin/gpg

gpg --version
gpg (GnuPG) 2.4.5
libgcrypt 1.10.3

which gpg-agent
/opt/homebrew/bin/gpg-agent

gpg-agent --version
gpg-agent (GnuPG) 2.4.5
```

However there is also a gpg2 older version is 2.2.41
```shell
whicih gpg2
/usr/local/MacGPG2/bin/gpg2

gpg2 --version
gpg (GnuPG/MacGPG2) 2.2.41
```

In my PATH I have first `/opt/homebrew/bin` and `/usr/local/MacGPG2/bin` second...
How can I force gopass to use the gpg instead of gpg2 which is an older version ?

```shell
$ gpgconf
gpg:OpenPGP:/opt/homebrew/Cellar/gnupg/2.4.5_1/bin/gpg
gpgsm:S/MIME:/opt/homebrew/Cellar/gnupg/2.4.5_1/bin/gpgsm
keyboxd:Public Keys:/opt/homebrew/Cellar/gnupg/2.4.5_1/libexec/keyboxd
gpg-agent:Private Keys:/opt/homebrew/Cellar/gnupg/2.4.5_1/bin/gpg-agent
scdaemon:Smartcards:/opt/homebrew/Cellar/gnupg/2.4.5_1/libexec/scdaemon
dirmngr:Network:/opt/homebrew/Cellar/gnupg/2.4.5_1/bin/dirmngr
pinentry:Passphrase Entry:/opt/homebrew/opt/pinentry/bin/pinentry
```

**Comment by nicolas-g** [comment]
> How about to set `GOPASS_GPG_BINARY` for that?

Thank you for the suggestion @kachick , unfortunately still the same warning:

```shell
$ export GOPASS_GPG_BINARY=/opt/homebrew/bin/gpg
$ gopass show mysecret
gpg: WARNING: server 'gpg-agent' is older than us (2.2.41 < 2.4.5)
gpg: problem with fast path key listing: IPC parameter error - ignored

Secret: mysecret

xyz
```


The warning seems to be regarding gpg-agent and not specifically for the gpg binary ... I couldn't find in the documentation any environment variable specifically for gpg-agent ... Maybe something worth to support and add ?

**Comment by kachick** [comment]
Sorry for made the noise, I overlooked your log indicates gpg-agent. :bow: 

I'm a beginner of gopass, however if I'm facing same problem in macOS and zsh toolset, I'll start to debug from adding `setopt no_global_rcs` in .zshenv.

**Comment by nicolas-g** [comment]
@kachick it seems the issue was resolved by running `gpgconf --kill all` ...

can you try that and let us know if this fixed the issue for you as well ? then we can close the ticket.

**Comment by kachick** [comment]
Thank you, I'm okay for closing :+1:

**Comment by cornelius-99** [comment]
I'm having the same problem and the solutions above didn't help.

```shell
$ echo $GOPASS_GPG_BINARY
/home/cornelius/.local/share/devbox/global/default/.devbox/nix/profile/default/bin/gpg

$ which gpg
/home/cornelius/.local/share/devbox/global/default/.devbox/nix/profile/default/bin/gpg

$ gpg --version
gpg (GnuPG) 2.4.5
libgcrypt 1.10.3
...

$ gpgconf
gpg:OpenPGP:/nix/store/3z0lkq6lsjlsdnc3drlxph91c6jvh36d-gnupg-2.4.5/bin/gpg
gpgsm:S/MIME:/nix/store/3z0lkq6lsjlsdnc3drlxph91c6jvh36d-gnupg-2.4.5/bin/gpgsm
keyboxd:Public Keys:/nix/store/3z0lkq6lsjlsdnc3drlxph91c6jvh36d-gnupg-2.4.5/libexec/keyboxd
gpg-agent:Private Keys:/nix/store/3z0lkq6lsjlsdnc3drlxph91c6jvh36d-gnupg-2.4.5/bin/gpg-agent
scdaemon:Smartcards:/nix/store/3z0lkq6lsjlsdnc3drlxph91c6jvh36d-gnupg-2.4.5/libexec/scdaemon
tpm2daemon:TPM:/nix/store/3z0lkq6lsjlsdnc3drlxph91c6jvh36d-gnupg-2.4.5/libexec/tpm2daemon
dirmngr:Network:/nix/store/3z0lkq6lsjlsdnc3drlxph91c6jvh36d-gnupg-2.4.5/bin/dirmngr
pinentry:Passphrase Entry:/nix/store/3z0lkq6lsjlsdnc3drlxph91c6jvh36d-gnupg-2.4.5/bin/pinentry

$ gpg-agent --version
gpg-agent (GnuPG) 2.4.5
libgcrypt 1.10.3
Copyright (C) 2024 g10 Code GmbH
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$ gopass show -o mysecret
gpg: WARNING: server 'gpg-agent' is older than us (2.4.4 < 2.4.5)
mysecret
``` 

I would be thankful if someone has an idea what could be wrong
