### ISSUE TITLE
Imported secrets exposing password: fields with safecontent=true

### ISSUE THREAD

**Issue by dragon788** [gopasspw/gopass#408]
I imported a number of secrets from another provider using one of the official `pass` scripts, but rather than inserting the secrets as the first line, they are tagging them as `password: mySecretPassword` and though this appears to get copied correctly by `gopass show -c` it is NOT being hidden from outputting to the terminal. 

If I were to do it, I'd do something like read the file and parse it as an "ini" style config if we always expect a key-value pair other than the first line, and just handle the first line as "password" if there isn't a `: ` on the line, and then treat any key named "secret" or "password" or maybe a configurable list of "super-secret" items, so those should be replaced in the output with eg "DO NOT PRINT" when the safecontent flag is enabled. (Putting the replacement text into the output could make unit testing easier if you want to assert a secret isn't in the output without having to unwrap a bunch of objects.)

I also noticed even though I followed the directions it captured some of the characters as HTML entities and not the real character, glad I noticed that before I locked myself out of many things. Will go report that bug elsewhere if I can find a bug tracker for it.

**Comment by dominikschulz** [comment]
- You can use `gopass show -c secret key` to copy the content of a structured key to the clipboard
- As we already support YAML in secrets I'd be *super* hacky and error prone to support ini-style secrets as well. I don't think we're going to do that.
- I'm not a fan of hiding arbitrary keys just because some people think they are super sensitive.
- We could add a user-customizable list of keys where the value would be hidden by default, but I'm not sure if the added complexy is worth the net result.

**Comment by dragon788** [comment]
Ah, I haven't looked at enough of the secrets that I imported to pick up that it was yaml, that's a much better format.

My line of thought was that in some cases you might be storing a multi part secret where there is a password and an auth token or private key to the same service, and creating and managing two separate entries for one service might be cumbersome, especially if it is involved in a breach or something like the ROCA vulnerability where somebody could use a private key to alter data or change account information. That's why I thought having a 'skip output if key matches entry in this list' might be handy.

**Comment by dominikschulz** [comment]
Right now we just output the whole unaltered body on `gopass show`. Hiding certain keys would add some complexity there, but it can be certainly done. However this won't work if the output isn't valid YAML.

I'm too busy to work on this at the moment, but I think there is a good chance we'd accept a proper PR.

**Comment by AnomalRoil** [comment]
Is this something we still want to do @dominikschulz ?  
If we still want to do it, I could take a look.

I could easily do it for the new KV secret type and the yaml type thanks to the MIME header by adding a header entry containing the "keys" (for KV or yaml) that are considered "private"/"secret". It wouldn't be supported for plaintext secret where it would behave as it does currently (consider the first line of the body as being the secret)

**Comment by dominikschulz** [comment]
I'm still not seeing a strong necessity for this, but I'm still willing to accept a clean PR implementing this feature.
With the new secret types it should be possible to have a clean implementation after all.

But I'd like to avoid introducing additional config options (these tend to get confusing / annoying over time).
But if these are contained within a secret, that could be clean and maintainable.

**Comment by dragon788** [comment]
I do really like the idea of using a private/secret metadata field that could be queried to see what shouldn't be printed during a `gopass show` if using it for general KV storage as well as secrets.
