### ISSUE TITLE
Ubuntu PPA repository

### ISSUE THREAD

**Issue by nike38rus** [gopasspw/gopass#424]
This is awesome tool, I looked for something like this for ages!
Is there any chances that you'll set the PPA repository for Ubuntu so users like me can mirror it and use it in their companies?

**Comment by dominikschulz** [comment]
Actually I've never looked into setting up a PPA so far.

I think we can do that, but it's not super high priority.

**Comment by nike38rus** [comment]
May be you can use [packagecloud](https://packagecloud.io) like someone did that for prometheus in https://github.com/lest/prometheus-rpm?

**Comment by martinhoefling** [comment]
I've set up ppas before, so I can help with it if desired. It might also make sense to take a look at https://build.opensuse.org/. Here, one could build for different linux distributions, not just ubuntu.

**Comment by dominikschulz** [comment]
I've created and maintained Debian Policy compliant debs and private package repositories in the past but due to the overhead involved in building a _proper_ Debian package I'm not keen on doing this again. If anyone wants to help in providing proper Debian / Ubuntu packaging that would be very welcome.

As soon as we got the Debian Packaging metadata I can build and upload the artifacts to a launchpad PPA.

When it comes to building RPMs I'm completely lost. Tried once, failed and never got any motivation to try again. So if anyone want's to have gopass package as an RPM we'd definitely need help.

**Comment by nike38rus** [comment]
I have some experience of creating RPM specs and packages so I think it's not a problem.

How can I help you with creating RPM repo or just spec files? Should I create repo somewhere like packagecloud, create specs and set up CI and give all credentials to you?

**Comment by dominikschulz** [comment]
I think we should start with the packaging metadata. At least for debian there are different opinions on where to put those. The policy manual assuemes that a package maintainer isn't also the upstream maintainer, thus they prefer to have the packaging in a different repo than the upstream code.

But we could just place the packaging metadata / spec files in this repo.

If you agree just open an PR.

Once we are happy with the packaging metdata we'll look into hosting options. I'd prefer to host this on our infrastructure, but only if the maintenance overhead for the repo metadata isn't too big.

**Comment by nike38rus** [comment]
@dominikschulz I see that you're already has .deb and .rpm packages in `https://github.com/justwatchcom/gopass/releases` section. In case of RPM repo, you can put all *.rpm packages in one directory and run `createrepo` tool inside of it and all metadata will be generated so you just need to export this directory through any web-server that you're like. 
Also there is a `dpkg-scanpackages` tool for creating `Packages.gz` that contains APT repo metadata.
Both of this solutions suitable for building your own self-hosted package repository.

**Comment by dominikschulz** [comment]
@nike38rus Thanks for the hints, didn't work with `createrepo` or `dpkg-scanpackages` so far, but at least for the Debian Repo I think you need the source package / `.changes` files. We don't have those as we currently don't build _proper_ Debian packages but just _fake_ ones using `fpm`.

**Comment by nike38rus** [comment]
Maybe you should take a look at [github-changelog-generator](https://github.com/skywinder/github-changelog-generator) gem? It can generate changelogs based on tags, PRs and issues

**Comment by dominikschulz** [comment]
Ok, `dpkg-scanpackages` is a trivial Perl program. I've integrated it's features into our release workflow. Please see https://github.com/justwatchcom/gopass/blob/master/docs/setup.md#using-the-gopass-repository for usage intructions.

As for RPM I really don't have any intention to spend any time on that. My past experiences with RPM based distributions and packaging have been so bad that I don't intent to repeat that, but of course we'd accept any contribution in this area.

Does the APT repo solve the original issue or does someone still see any use of an PPA?

**Comment by nike38rus** [comment]
@dominikschulz you can create RPM repo with `createrepo` in the same way as you created APT repo with `dpkg-scanpackages`. You just need to place all *.rpm packages in some directory and run `createrepo --update /path/to/this/directory` and that's it! You can install this tool from `universe` repository if you're using Ubuntu on your server

**Comment by dominikschulz** [comment]
@nike38rus Unfortunately it's not as easy as that. First you need to create the repo metadata, than you need to setup the hosting, make sure everything is properly signed, integrated into our release workflow, test it on an RPM system, document it and later on maintain it. A lot of work.

**Comment by nike38rus** [comment]
Well, that's not worked for me, but I think it's because of my company's corporate proxy access rules (your main domain provides kinda video streaming service and that's prohibited). 
And that's why I asked for PPA repository...
Anyway, I'll try to use this repository from my home and leave the comment here

**Comment by daftaupe** [comment]
Hello,

I'm interested by gopass, I've built the last release there : https://copr.fedorainfracloud.org/coprs/daftaupe/gopass/ with this spec file : https://gitlab.com/daftaupe/gopass-rpm/blob/master/SPECS/gopass.spec

If anyone is interested and want to test, I would appreciate.

**Comment by daftaupe** [comment]
I've updated the copr repo to latest release : 1.6.2 by the way.

**Comment by dragon788** [comment]
If the project is completely open source you can usually get a repo setup via Bintray with a free plan to offer packages in RPM/Deb/etc flavors and their system handles the metadata and everything for you when you publish a new version.

https://www.jfrog.com/open-source/
https://bintray.com/docs/usermanual/formats/formats_debianrepositories.html
https://bintray.com/docs/usermanual/formats/formats_yumrepositories.html

**Comment by dragon788** [comment]
You could also look at [fpm](https://github.com/jordansissel/fpm) for generating the actual packages if you don't want to dive into the nitty-gritty details.

**Comment by dragon788** [comment]
@dominikschulz if you need any help with the above let me know, I'm just ramping up on my use of gopass and hope to publish a how-to on using it with the browser extension on ChromeOS devices in developer mode for a secure password solution that isn't fully reliant on the browser and 3rd party cloud providers.

**Comment by dominikschulz** [comment]
@daftaupe Thank you very much for the RPM SPEC file. If I find some time I'll have a look and try to integrate it into our release workflow. No promises, though.

@dragon788 Looking forward to the how-to. Actually we're already using fpm to build the existing RPM and deb packages. We've also got an Debian Repo, but due to missing experience and test environments we didn't setup any kind of yum repo so far. Bintray may be an option for the future.

**Comment by daftaupe** [comment]
@dominikschulz no worries, I'll try to keep it updated along the release of new versions of gopass and publish the rpm on my copr repo at the same time.

**Comment by martinhoefling** [comment]
@dominikschulz can we close this or is anything missing here?

**Comment by dominikschulz** [comment]
We still don't publish RPM to bintray, but I think we can close this issue anyway. Thanks!
