### ISSUE TITLE
Fix integration tests on windows

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#443]
Right now the integration tests (`make test-integration`) fail on windows (at least on AppVeyor).

**Comment by lewisdiamond** [comment]
Do you need help debugging and testing on Windows? I have created a VM and I'm trying to set it up internally for people who use Windows.

**Comment by dominikschulz** [comment]
Yes, please. We made some (poorly documented) progress on windows but I'm not completely sure about the current state.

**Comment by lewisdiamond** [comment]
Where do you hang out usually? IRC? I'd be willing to do some PRs to fix the issues I'm facing but since I haven't done much in go I may need some pointers on gopass' architecture.

**Comment by Project0** [comment]
still some issues, as far i can see most is related to wrong paths or failed mock inits: https://ci.appveyor.com/project/Project0/gopass?fullLog=true

**Comment by Project0** [comment]
one issue we run into (in pkg/fsutil/fsutil_test.go), will be fixed with go 1.11 : https://github.com/golang/go/issues/24441#issuecomment-377984978

**Comment by martinhoefling** [comment]
Integration tests will be introduced via #1171
