### ISSUE TITLE
Don't smart-match when using `gopass search`

### ISSUE THREAD

**Issue by adius** [gopasspw/gopass#453]
I'm often using something like `for secret in (gopass search evernote); echo $secret; gopass $secret; echo ''; end` to check out several secrets at once, but if there is only one match it breaks the whole command, as it immediately shows the content like this:

```sh
gopass search evernote
Found exact match in 'evernote.com/username'
<content>
<more content>
```

I would rather want it to only display the name. `gopass evernote` already provides the smart search functionality ...

**Comment by dominikschulz** [comment]
Yes, this sounds reasonable. I'll see if I can come up with any arguments why we wouldn't do this, if I can't find any I'll adjust the current behaviour.

**Comment by ad-si** [comment]
Hi @dominikschulz, this behavior seems to be reintroduced! Is this intended, or is it a regression bug?

**Comment by dominikschulz** [comment]
It's definitely not intended. I'll try to reproduce it.

**Comment by dominikschulz** [comment]
@ad-si Sorry, but I'm unable to reproduce with a current master build.

**Comment by ad-si** [comment]
@dominikschulz This is stil an issue, and it's quite annoying 😅.

Both `gopass search` and `gopass find` directly show the match if there is only one.
Can we please change it to only list the name? 😭

**Comment by ad-si** [comment]
This is my workaround script:

```bash
#! /usr/bin/env bash

for secret in $(gopass list --flat | rg "$@")
do
  echo -e "\n===== $secret ====="
  gopass "$secret"
  echo -e "\n"
done
```

**Comment by raphink** [comment]
I'd really like to be able to use `gopass` programmatically without magic search. Could this be reopened please?

**Comment by dominikschulz** [comment]
Sure thing, but I still can't reproduce it :/

**Comment by richarddb** [comment]
If I've understood the OP's request, and @raphink's comment: This gets my vote for a change. I want to use gopass programmatically; so an option such as `gopass show --password --strict path/name` would be very useful, rather than the fuzzy search. A return code != 0 could then indicate that an exact match was not found.
