### ISSUE TITLE
Username in "primary" area of clipbord

### ISSUE THREAD

**Issue by golderweb** [gopasspw/gopass#477]
It would be nice to have also the value of a field called "user", "username", "login" or related in the clipboard when calling `gopass -c`.
For xservers the so called "primary" area could be used for this purpose and the username could be inserted by clicking the mousewheel instead of copy it separately.

**Comment by dominikschulz** [comment]
Sounds interesting. Feel free to create a PR.

**Comment by dominikschulz** [comment]
I had a look at this and I don't see an easy, cross platform way to do this. If you have a good idea feel free to open an PR.

**Comment by mkaito** [comment]
What you describe are called X cut buffers, and predate the modern clipboard concept by a fair bit. They are, as the name suggests, specific to X, and will probably not be supported by even Wayland.

**Comment by golderweb** [comment]
I solved this for me with a bash function as wrapper around gopass
```bash
# Load gopass bash completion
source <(gopass completion bash)

gopassc() {
  gopass -c $1
  gopass show -f $1  | egrep -o "(user|login|username):\s(.+)$" | sed -Ee 's/(user|login|username):\s//g' -e 's/$//g' | xsel
}
complete -F _cli_bash_autocomplete gopassc
```

**Comment by mkaito** [comment]
I did something like that when I wrote my own password manager, before someone pointed out to me "you know, that looks *exactly* like `pass`.

I thought it would be useful and clever, but it turns out that I hardly ever used it.

**Comment by nilskuhn** [comment]
I would like to have an option to copy the username to the "normal" clipboard area instead of the password via a separare flag. 
Maybe `-u, --username`: `gopass show -u <mypass>`.
That was what I was using from time to time in keepass (my previous password manager).
