### ISSUE TITLE
Gopass consuming a lot of ressources and being slow

### ISSUE THREAD

**Issue by kolaente** [gopasspw/gopass#494]
Since I upgraded to gopass 1.6.2, it takes about two minutes to show me the "gopass: Encrypting secret for these recipients:"-dialog when manually editing a secret via `gopass set secret`. Until then, gopass consumes about 32% CPU and about 1 GB of RAM (see screenshot). I dont think this is the intended behavior.

![bildschirmfoto vom 2017-12-06 11-18-49](https://user-images.githubusercontent.com/13721712/33657202-d06617de-da78-11e7-8685-9e7d0acdc97e.png)

Gopass version: gopass 1.6.2 (3cd42aa331ac2a65d2e6554d120a701f404ef266) go1.9 linux amd64
GPG Version: gpg (GnuPG) 1.4.20
My system: 
```
OS: elementary OS 0.4.1 loki
Kernel: x86_64 Linux 4.10.0-37-generic
CPU: Intel Core i7-7500U CPU @ 3.5GHz
GPU: Mesa DRI Intel(R) HD Graphics 620 (Kabylake GT2) 
RAM: 4960MiB / 7903MiB
```

I really love the tool, have been looking a while for something like this!

**Comment by dominikschulz** [comment]
Uh, this may be due to the recipient parsing. Need to investigate.

**Comment by kolaente** [comment]
In this case I was only encrypting for one recipent, maybe this is of interest.

**Comment by dominikschulz** [comment]
I can't reproduce this, yet.

Could you please provide some more info?

1. run `GOPASS_DEBUG=true gopass set <secret>`
2. run `gpg -k | grep pub | wc -l`

Of course you can/should mask all sensitive information in there. For 2. a rough number is enough (no need to disclose exact numbers).

**Comment by kolaente** [comment]
1.:
```bash
GOPASS_DEBUG=true gopass set <secret>
[DEBUG] Loaded config: &{Root:0xc42007f860 Mounts:map[] Version:1.6.2 XXX:map[]}
[DEBUG] Loaded config from /home/kolaente/.config/gopass/config.yml: &{Root:0xc42007f860 Mounts:map[] Version:1.6.2 XXX:map[]}
[DEBUG] gpg.Decrypt: /usr/bin/gpg2 [/usr/bin/gpg2 --quiet --yes --compress-algo=none --no-encrypt-to --no-auto-check-trustdb --decrypt /home/kolaente/.password-store/<secret>.gpg]
[DEBUG] GetRecipients(web/shodan) - idfile: /home/kolaente/.password-store/.gpg-id
gopass: Encrypting web/shodan for these recipients:
[DEBUG] gpg.listKeys: /usr/bin/gpg2 [/usr/bin/gpg2 --with-colons --with-fingerprint --fixed-list-mode --list-public-keys 064001388788A70C6E99FCA4F40E70337AB24C9B]

 - [Key with name]

Do you want to continue? [Y/n]: y
[DEBUG] gpg.Encrypt: /usr/bin/gpg2 [/usr/bin/gpg2 --quiet --yes --compress-algo=none --no-encrypt-to --no-auto-check-trustdb --encrypt --output /home/kolaente/.password-store/<secret>.gpg --trust-model=always --recipient 064001388788A70C6E99FCA4F40E70337AB24C9B]
[DEBUG] store.gitAdd: /usr/bin/git [git add --all web/shodan.gpg]
[DEBUG] store.gitDiffIndex: /usr/bin/git [git diff-index --quiet HEAD]
[DEBUG] Output of '/usr/bin/git [git diff-index --quiet HEAD]': ''
[DEBUG] store.gitCommit: /usr/bin/git [git commit -m Save secret to <secret>: Edited with /usr/bin/editor]
[master 92a69ad] Save secret to <secret>: Edited with /usr/bin/editor
 1 file changed, 0 insertions(+), 0 deletions(-)
 rewrite <secret>.gpg (100%)
```

2.: 
```bash
3
```

Maybe because gopass is using `gpg2` instead of simply `gpg`?

**Comment by dominikschulz** [comment]
@kolaente Unfortunately I haven't been able to reproduce this. Using gpg2 is definitely fine, since most of our users use gpg2 and there have been no other reports like this. Unless you are able to provide further information we will probably not be able to resolve this.

**Comment by kolaente** [comment]
mhhhh... what further information do you need?
