### ISSUE TITLE
Support for reencrypt

### ISSUE THREAD

**Issue by jerger** [gopasspw/gopass#525]
as longterm password-store users we've build around some make extensions over plain password store for handling keys, bash-autocompletion and multi-stores (https://github.com/DomainDrivenArchitecture/password-store-for-teams). Two things I miss after reading your documentation:

* do you support reencryption (e.g. if new members join a team)?
* I found the key-import but do you offer a key-publish also?

BR - gopass is really cool :-)

**Comment by dominikschulz** [comment]
- Running `gopass recipients add` or `gopass recipients remove` will automatically reencrypt the whole store
- Adding a recipient will automatically export his key to `.gpg-keys/<ID>`

**Comment by jerger** [comment]
cool - thanx :-)

**Comment by nylocx** [comment]
I hope it is ok to bring such an old issue up again.
I have another use case that requires a command to reencrypt all or a specific secret in a store.
I use the wonderful iOS app [pass for ios](https://github.com/mssun/passforios) to use pass on my iPhone. It currently does not support encryption with multiple public keys (but it is being worked on in https://github.com/mssun/passforios/issues/338). Anyways there might be other clients facing the same problem. So I would like to have a way to fix the secrets encrypted with just a single key. Currently I have to remove a recipient and then readd the same recipient and this way doing the reencryption twice (once for removal and ones for adding).
It would be nice to just have a `gopass reencrypt --store some_store` command. I guess I could come up with some script doing this directly via gpg encrypt/decrypt, but providing the command should not be very hard, as reencryption is already implemented.

PS: Thanks for the great work, I really love gopass.

**Comment by martinhoefling** [comment]
I reopened it for now but it needs sb who has time to implement it.

**Comment by martinhoefling** [comment]
Stupid question regarding your usecase: does `gopass fsck` add your missing recipients? I've tested it here and it seems to work. Maybe that should be documented somewhere.

**Comment by nylocx** [comment]
I just checked and you are right, I totally missed that functionality. The only thing that is strange is if I do: `gopass fsck --store private` I get an error saying:
`Incorrect Usage: flag provided but not defined: -store`

**Comment by martinhoefling** [comment]
Ok, I am keeping this open for improving the documentation.

**Comment by Paktosan** [comment]
I hope it's okay to dump this in this issue and not open a new one.
I need to reencrypt some files because I missed some updated keys.
While running `gopass fsck --decrypt` fixes that, it also changes every entry for file format and creates a commit for each.
In my case, this results in over 350 commits.
I do not want this, I just want to fix the few files…
`gopass edit` also is no option as it does not reencrypt when I don't change the file content.
It would be grat for something like `gopass fsck --decrypt store/folder/entry' to work or to have a `--rencrypt` option with the `edit` command.

**Comment by dominikschulz** [comment]
@Paktosan I think that's a valid request. But different from this issue. Please open a new issue instead.
