### ISSUE TITLE
[Usability] Suggestions for more intuitive configuration parameters

### ISSUE THREAD

**Issue by tobi-wan-kenobi** [gopasspw/gopass#569]
Maybe that's just personal, but I find double negotiations in configuration parameters confusing (i.e. `nocolor = false`). The same is achieved by `color = true` (and having `true` as default).

Since https://github.com/justwatchcom/gopass/blob/master/docs/security.md lists "Sensible Defaults" as a design goal, I thought I'd humbly submit this as a suggestion for improvement.

**Comment by dominikschulz** [comment]
Definitely a good idea. Having a good useability is one of our major goals and making the config understandable is part of that. We had a few iterations over our config to make it easier, but over time it tends to gravitate towards ease of implementation over ease of use and we need to revisit that from time to time to correct for that.

**Comment by tobi-wan-kenobi** [comment]
Thanks for the quick (and positive) response!

My suggestion would be to keep the current parameters as fallback (for backwards compatibility), but to not expose them via the UI anymore:

nocolor -> color
noconfirm -> confirm
nopager -> pager

I will have a quick look at the code, but as I don't know Go at all, I doubt I can come up with a PR :-(
