### ISSUE TITLE
Request for documentation - how backup and mobile/laptop workflow

### ISSUE THREAD

**Issue by oren** [gopasspw/gopass#579]
I am reading the [features](https://github.com/justwatchcom/gopass/blob/master/docs/features.md) page and so far I love gopass. thank you for working on such an important project!

There are two parts of documentation that I believe are missing:
1. How to backup things (data store, gpg keys, or anything else that is needed)
1. How to setup a workflow for both a laptop and a phone. I understand that only android is supported at the moment and it's being done using this [android app](https://play.google.com/store/apps/details?id=com.zeapo.pwdstore&rdid=com.zeapo.pwdstore) and also with github repo (or maybe git is enough) but it is not clear what are the steps to do that 

Can someone share the two points above? having this written down somewhere would be very valuable and will increase the adoption of gopass especially among less technical users.

**Comment by martinhoefling** [comment]
[Pass for IOS](https://github.com/mssun/passforios) works perfectly with a single store/repo.
