### ISSUE TITLE
Evaluate go-app-paths

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#639]
github.com/muesli/go-app-paths looks interesting. Could remove some complexity from our codebase.

**Comment by muesli** [comment]
I've started working on it here: https://github.com/muesli/gopass/commit/7020c5b913d24e451a496466bfcee765c48f66ce

(needs rebasing, desperately)

**Comment by dominikschulz** [comment]
Thanks! Any chance that you continue working on this? Would be very nice.

**Comment by muesli** [comment]
Yes, I absolutely plan on finishing this.

It does not come without implications for gopass users though: on Windows the default path for the password store would change (as it should, really). I wonder if you consider this platform important enough that it would warrant a migration path in code? I wouldn't mind if we don't provide one :smile:

**Comment by dominikschulz** [comment]
@muesli Friendly ping :)

**Comment by dominikschulz** [comment]
No progress and we seem to have a solid implementation now.
