### ISSUE TITLE
GPG passphrase fail, password disappears

### ISSUE THREAD

**Issue by rendaw** [gopasspw/gopass#652]
Here's roughly what happened:
```
$ gopass rm a/b
Are you sure you would like to delete a/b? [y/N]: y

Error: Can not delete 'a/b': failed to commit changes to git: failed to run command /usr/bin/git [git commit -m Remove a/b from store.]: exit status 128
$ gopass show a/b
Entry 'a/b' not found. Starting search...

Error: no results found
```

And in my password store:

```
$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	deleted:    a/b.gpg
```

When prompted for my pin I canceled and I assume whatever GPG was trying to do also failed.

Version
```
gopass 1.6.10 (2018-01-21 15:53:49) go1.9.2 linux amd64
```

Apologies if this is totally off base, this is the first thing I did in gopass :P.  Out of curiosity, is my password store now in a state that will break future operations?

**Comment by dominikschulz** [comment]
This looks like an issue with your git setup. gopass configures git for signing commits and this seem to have failed. We're considering to remove this commit signing as it causes more harm than good.

You'll want to `git commit` any pending changes inside your password store to get back to a "clean" state. If you keep having trouble commiting you might want to unset the gpgsign git option with `git config --local commit.gpgsign false`

**Comment by rendaw** [comment]
Thanks, that sounds like a reasonable solution.

Just in case it got buried, my goal was to abort the deletion by canceling the GPG passphrase entry.  Since canceling/GPG unlock can always fail (cancel, wrong passphrase, smart card missing, etc), I think abandoning the commit (`git checkout .` or something) if GPG exits with an error might be a desirable behavior.

Passphrase success:
```bash
$ gpg --local-user me@example.com --sign -o /dev/null test.txt
$ echo $?
0
```

Passphrase failure:
```bash
$ gpg --local-user me@example.com --sign -o /dev/null test.txt
gpg: signing failed: End of file
gpg: signing failed: End of file
$ echo $?
2
```

I'm not sure how git handles GPG errors, I would hope something's returned in the exit status code.

**Comment by dominikschulz** [comment]
Ok, reverting the repo to the last known good state may be a good idea but it may also lead to data being lost in some cases. I'll think about this a little more. Maybe we can do something about it.
