### ISSUE TITLE
Wizard UI broken

### ISSUE THREAD

**Issue by schmunk42** [gopasspw/gopass#665]
My wizard look like this:

![bildschirmfoto vom 2018-02-21 19-39-26](https://user-images.githubusercontent.com/649031/36510186-815fb61e-1762-11e8-9768-26cfb7d092a1.png)

- Arch Linux
- zsh 5.4.2 (x86_64-unknown-linux-gnu)
- gopass 1.6.10 (2018-01-21 15:53:49) go1.9.2 linux amd64

**Comment by dominikschulz** [comment]
Sorry, but I can't reproduce this.
Could you quickly try to run the wizard in another shell (bash or zsh without customizations)?

**Comment by schmunk42** [comment]
bash without custom font, does not look better...

![bildschirmfoto vom 2018-02-22 11-59-29](https://user-images.githubusercontent.com/649031/36534838-0b2d9946-17c8-11e8-92f3-59ecf3c9f579.png)

Also, when I try to select something via cursor keys the wizard immediately fails with

    Error: failed to run onboarding wizard: user aborted

Character encoding is set to UTF-8

**Comment by schmunk42** [comment]
Found someting .... my default setting is

```
echo $TERM
xterm-256color
``` 

when I set it to

```
export TERM=linux
```

the interactive part looks fine.

**Comment by toubib** [comment]
Same as  schmunk42 here: broken with (default) xterm-256color,  ok with  xterm-color.

**Comment by dominikschulz** [comment]
The problem is most probably in one of the TUI libraries `gopass` is using (`gocui`, `termbox-go`).
I wonder if we can work around this by setting `TERM=xterm-color` on startup.

**Comment by schmunk42** [comment]
What works for me also, is:

    alias gopass='TERM=xterm-color gopass'

in `.bashrc`.

**Comment by gburtini** [comment]
After a recent update, mine now looks like this too. I can confirm setting the `TERM` variable did fix it.

**Comment by kelveden** [comment]
I was bitten by the Arch rolling updates too. Workaround from @schmunk42 works perfectly though. Before stumbling across this issue, I did tinker with a few other terminal emulators and found a couple that weren't affected: [terminology](https://www.enlightenment.org/about-terminology) (presumably because it is EFL-based rather than xterm-based) and [rxvt-unicode](https://wiki.archlinux.org/index.php/rxvt-unicode).

**Comment by metalmatze** [comment]
Yes. I've seen this before too.
But now it seems like it is resolved. At least for me.

**Comment by dominikschulz** [comment]
Hmm, would be nice to a get a confirmation for the others affected by this, since I was never able to reproduce it.

**Comment by ayekat** [comment]
Minor nitpick: urxvt's default `TERM` is (and should be) `rxvt-unicode-256`. I assume your issues are due to forcing `TERM` to a specific value (which is generally discouraged), because I cannot reproduce this issue on Arch Linux, with urxvt.

**Comment by kelveden** [comment]
@dominikschulz I can confirm that it's still producing the original problem - gopass 1.6.11.

**Comment by dominikschulz** [comment]
In #789  we updated the terminal libs, so this might be fixed.

**Comment by dominikschulz** [comment]
I'm closing this for now. Just raise another issue if this comes up again.

**Comment by toubib** [comment]
The bug is fixed for me now, thank you.
