### ISSUE TITLE
Implement encrypted path backend

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#673]
I'd like to provide an encrypted path backend, like [encFS](https://github.com/vgough/encfs/). The general idea would be to encrypt each filename with a stream chipher based on a password.

This wouldn't work very well for teams (they'd have to share the same path-encryption-password), but for individuals wanting to protect their secret names this would be a nice feature.

**Comment by benpye** [comment]
I wonder if there would be any way to make this work for teams.

Would a map file possibly be a solution? It would simply contain the mapping between the random names and the plaintext names, this file would then be encrypted in the same way as the secrets themselves. You would need one map file next to each `.gpg-id` file. This would make gopass pretty incompatible with pass but would stick with the principle of storing the data in such a way that it can be read without (go)pass.

**Comment by techieshark** [comment]
Would support for Keybase's encrypted git repos serve the same purpose?

**Comment by benpye** [comment]
It would kinda help but doesn't really solve it for me. I like to A. host my repo locally (I run a gitolite server for some stuff) and B. I use Password-Store on Android. If I could encrypt a single folder then sure, that wouldn't be available on my phone but that's a better tradeoff that having to split my password database.

**Comment by dominikschulz** [comment]
This was partly fixed with #1366 already.
