### ISSUE TITLE
Implement fully encrypted container backend

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#674]
I'd like to provide a fully encrypted backend that is operating only within an encrypted container. It should include everything from storage, to revision control and encryption. Something like full encrypted SQLite or BoltDB would be nice, but in pure-Go and without any unencrypted temporary files.

**Comment by azak-azkaran** [comment]
Maybe that would [badger](https://github.com/dgraph-io/badger) would be interesting for your use case.
I personally came across it while looking for something similar and it has encryption at rest, described [here](https://dgraph.io/blog/post/encryption-at-rest-dgraph-badger/)

**Comment by dominikschulz** [comment]
Not going to happen.
Still looking into #673 which would cover 99.9% of this FRs use cases.
