### ISSUE TITLE
Website aliases

### ISSUE THREAD

**Issue by AuspeXeu** [gopasspw/gopass#682]
Your recommendation is to organise credentials like the following example.

`google.com/username`

However, for websites like google, there are several domains that accept the same credentials. For now I would have to duplicate my credentials like this.

```
google.com/username
youtube.com/username
google.co.uk/username
google.de/username
```
Is there a feature I missed that allows aliasing of credentials?

**Comment by dewey** [comment]
That seems to be a pretty small edge case with Google. Wouldn’t it make more sense to just store it as google/username in this case?

**Comment by AuspeXeu** [comment]
Well that is definitely possible, yes. However when combined with the chrome extension link in the docs, it will not automatically provide the correct credentials, no?

**Comment by mxhob1** [comment]
I think that ideally browserpass-ce should authenticate the key as soon as you activate the extension (via keybinding or the extension button) then check url: fields in each file to determine what files are applicable for the current url you are at.

Naturally, this solution is a bit bulkier than the current way the extension reads the file structure and would also only work if all files were signed against a single master key.

As far as the issue itself goes, this inverse of this is storing multiple credential sets for a single site (such as multiple email accounts).

**Comment by AuspeXeu** [comment]
I just started using gopass and hence am not familiar with it at all. How would I add additional fields to password files?

**Comment by AnomalRoil** [comment]
This is probably possible using `os.Symlink`, actually. I should double check if it supports relative symlinks, but I guess it does.

Maybe we could add a `-s` flag to the `cp` action which would create such relative symlinks... But then it would probably be best to leave the responsibility to the user to not delete the target of such symlinks. I don't know if this is fine or not.

Also it would require to do a few more checks in the Move and Remove actions, but it shouldn't be worse than handling directories (which is already done.)

**Comment by dominikschulz** [comment]
Technically we could support symlinks, but I think it would create quite some overhead in terms of implementation effort and probably also lead to some confusion. If someone wants to work on a PR, fine. But for me this isn't something on the short term roadmap.

**Comment by martinhoefling** [comment]
I came across the same issue. For git and unix, symlinks are fine. Windows seems to be a bit mixed (depending on version and git version). Anybody with more experience on Windows? I'll keep an eye on the issue and will maybe implement it later on if nobody else wants.

**Comment by dragon788** [comment]
Some versions of Windows support symlinks but it requires explicitly turning on the feature I believe and would definitely require some robust unit tests to ensure symlinked secrets are readable when running on Appveyor after doing a build and install.
