### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by AuspeXeu** [gopasspw/gopass#686]
Do you guys plan to localize gopass? :)

**Comment by dewey** [comment]
Why did you close it? I thought it was actually an interesting idea and with something like https://github.com/nicksnyder/go-i18n probably not too complicated (just tedious) as we don't have so many user facing strings. Not sure if there's demand for it though.

**Comment by AuspeXeu** [comment]
Well ... I thought this might make the project a bit to bloated and should rather be considered in a GUI frontend that someone might want to make in the future.

**Comment by falschparker82** [comment]
Also think this is rather interesting, however the fact that we're also using third party applications like GPG or Git might make this more complicated and/or partial.

**Comment by dominikschulz** [comment]
I don't think I'm going to work on i18n anytime soon, but if someone wants to do that'd be OK.

As `gopass` is already (or rather: still) pretty technical requiring console, GPG and sometimes git skills I don't expect too much users who are not capable of reading english and would prefer a native language interface.

**Comment by dominikschulz** [comment]
Sorry, not going to happen before an eventual 2.0 release.
