### ISSUE TITLE
Further autocompletion

### ISSUE THREAD

**Issue by AuspeXeu** [gopasspw/gopass#712]
I don't quite know how autocompletion works but would it be possible to have autocompletion for the following examples:

Domain:
gopass generate goo[gle.com]
username/eMail:
gopass generate google.com/exa[mple@me.com]

The domains could be taken from what already exists in the folder structure and the same for the email/usernames.

**Comment by dominikschulz** [comment]
If you can come up with a suiteable heuristic, this could be done.

Whenever you press `TAB` the completion script should eventuall call `gopass ... --generate-bash-completion` which will invoke the [`BashCompletion` func](https://godoc.org/github.com/urfave/cli#BashCompleteFunc) for the given subcommand, usually [`pkg/action.Complete`](https://godoc.org/github.com/justwatchcom/gopass/pkg/action#Action.Complete).

In your case the commands should look like this:
* `gopass generate goo<TAB>` -> `gopass generate goo --generate-bash-completion`
* `gopass generate google.com/exa<TAB>` -> `gopass generate google.com/exa --generate-bash-completion`

So if you can come up with an implementation that reads `c.Args()[0]` inside the `BashCompletion` func you implement this. You'll have access to the whole store and can use it to list other entries and infer the information from there.
