### ISSUE TITLE
use gopass as git credential helper

### ISSUE THREAD

**Issue by veecue** [gopasspw/gopass#740]
Hi,
I want to use gopass as a backend to automatically store my git credentials.
As an inspiration, there is [pass-git-helper](https://github.com/languitar/pass-git-helper)
According to this [page](https://git-scm.com/docs/api-credentials), I would propose the following:
- Write a parser/compositor for the [git-credential format](https://git-scm.com/docs/git-credential)
- Add a new command `git-credential` with the subcommands `get`, `store` and `erase`, which parses the input credential, matches it against a stored password and calls the specific action
Does anyone have any other suggestions? I would be willing to work on an implementation

Cheers,
veecue

**Comment by dominikschulz** [comment]
Your PR has been merged. Thanks a lot!
