### ISSUE TITLE
insert doesn't commit

### ISSUE THREAD

**Issue by danilobuerger** [gopasspw/gopass#750]
When doing a `gopass insert` it doesn't actually commit to the repository. See the following:

```
❯ gopass -version
gopass 1.6.11-git+HEAD go1.10.1 darwin amd64

❯ gopass config
root store config:
  askformore: false
  autoclip: true
  autoimport: true
  autosync: true
  cliptimeout: 45
  editrecipients: false
  nocolor: false
  noconfirm: false
  nopager: false
  notifications: true
  path: gpgcli-noop-fs+file:///Users/danilo/.password-store
  safecontent: false
  usesymbols: false

~/.password-store master
❯ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

~/.password-store master
❯ gopass insert test
Enter password for test: 
Retype password for test: 
Warning: Password is too short
gopass: Encrypting test for these recipients:
# REMOVED #
Do you want to continue? [Y/n/q]: Y
Pushed changes to git remote

~/.password-store master*
❯ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	test.gpg

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by danilobuerger** [comment]
using gopass at 22845cb92644548e8ee393513776c2361405b3ed

**Comment by dominikschulz** [comment]
Thanks a lot for the detailed bug report.

It clearly shows that gopass is assuming that it should not use git for this password store:
`path: gpgcli-noop-fs+file:///Users/danilo/.password-store`

This would start with `gpgcli-gitcli-fs` if it was using git.
So the question is whether you initialized a new password store or if you just upgraded gopass and use it with an existing store. Both cases should work and default to git, but this info would help me narrow it down a little.

**Comment by danilobuerger** [comment]
@dominikschulz Thanks for taking a look. So that was the only thing I forgot to mention. Before the commands mentioned above I did:

```
gopass clone git@REMOVED
```

Nothing else. I would expect that gopass clone sets this up properly, no?

**Comment by dominikschulz** [comment]
Ok, thanks. That will help us debug this. Probably a bug in the refactored code since the last release.

**Comment by dominikschulz** [comment]
I noticed the same issue but wasn't unable to pin it down a to cause, yet.
Somehow sometimes the RCS backend gets switched from `gitcli` to `noop`.
Will keep an eye on this.

**Comment by nathanbakhuijzen** [comment]
Is there a way to manually set the path variable to
`path: gpgcli-gitcli-fs+file:///Users/nathanbakhuijzen/.password-store`?

Setting it manually doesn't seem to work for me. I am using gopass `1.7.2` as well.
```
$ gopass config path gpgcli-gitcli-fs+file:///Users/nathanbakhuijzen/.password-store

Error: Error setting config value
```

**Comment by dominikschulz** [comment]
You can only set the path through editing the config directly. Usually it's at `$HOME/.config/gopass/config.yml`.
