### ISSUE TITLE
Windows: Creating local store fails with invalid path

### ISSUE THREAD

**Issue by dl1ely** [gopasspw/gopass#753]
Windows 10 Pro, using the onboarding wizard, during the creation of a local store (after key generation), the following error occurs:
```
Error: failed to run onboarding wizard: failed to init local store: failed to init store '' at 'gpgcli-gitcli-fs+file://gpgcli-gitcli-fs+file//C:%5CUsers%5CDE00173%5C.password-store': failed to initialize store: failed to write recipients file: mkdir \\C:: The specified path is invalid.: failed to write recipients file: mkdir \\C:: The specified path is invalid.
```
`gopass config` shows:
```
path: gpgcli-gitcli-fs+file://gpgcli-gitcli-fs+file//C:%5CUsers%5CDE00173%5C.password-store
```

Is that value right? First there is a "file://" part which looks ok again, but the part after that looks broken.
I then had a look at `config.yml`, and there i see (only relevant part quoted):
```
root:
    path: gpgcli-gitcli-fs+file://C:%5CUsers%5CDE00173%5C.password-store
```
This looks more valid. But why is the `gopass config` output broken? I also tried wrapping the `path` in `config.yml` in `"`, but that did not change the value of `path` in the `gopass config` output.

The problem seems to be in some kind of (broken) duplication of parts of the paths. `config.yml` looks okayish, but the resulting config value looks broken (duplicated parts and `file//` instead of `file://`).

I also tried setting the path to only the part after `file://`, because i suspected the `gpgcli-gitcli-fs+` part was added programatically, but that lead to an `No gpg binary found: failed to init root store: need path` error.

Any ideas what is going wrong here?

**Comment by dominikschulz** [comment]
Thank you very much for reporting this issue. This may be related to some path conversions for the Windows platform. Unfortunately I still don't have access to a Windows test instance, but I'll try to reproduce on Linux or Mac.

These are probably multiple issues (wrong config output, wrong mkdir args, gpg binary not found), but I'll look into it.

**Comment by dl1ely** [comment]
I would be happy to support with testing on windows, unfortunately i have no deeper knowledge of go. I took a quick look into the codebase, but could not identifiy a problem spot-on.
If i can help somehow, let me know.

**Comment by dl1ely** [comment]
What does the part in front of the first `file://` mean anyway? Is gitcli right? I wanted to setup a local store on my harddrive.

**Comment by dominikschulz** [comment]
Since the last release gopass gained support for pluggable storage, crypto and SCM backends. These are encoded in the path URI, e.g. `gpgcli-gitcli-fs+file://` means it's using the CLI implementations for GPG and Git and direct filesystem access. Other backends exist as well, see [docs/backends.md](https://github.com/justwatchcom/gopass/blob/master/docs/backends.md).

**Comment by GandalfIX** [comment]
I had the same issue: I got it solved by replacing the URL encoded characters in the "path" entry with their characters again.
So changing `path: gpgcli-gitcli-fs+file://C:%5CUsers%5CDE00173%5C.password-store` to `path: gpgcli-gitcli-fs+file://C:/Users/DE00173/.password-store`

**Comment by dl1ely** [comment]
Yes, i can confirm this solves the problem. I even have a space in my username that encodes to %20, and replaced that with the literal space in config.yml, but it still works fine although "gopass config" shows it as %20. But the slashes are displayed right now (not URL-encoded).

**Comment by lewisdiamond** [comment]
@dominikschulz 

Regarding access to a windows machine. I use qemu+kvm (or use https://virt-manager.org/) with a VM downloaded from there: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

First `unzip` the file, (yes, it's a zip of a .ova, which is a compressed tarball).
Second `tar -xvf whatever.ova`
Third (optional but better), convert the `.vmdk` to a .qcow2 using `qemu-img convert -f vmdk -O qcow2 [source].vmdk [target].qcow2`

**Comment by dominikschulz** [comment]
@lewisdiamond Thanks, that could actually work for my setup. Will try.

**Comment by kumamonishe** [comment]
>>I had the same issue: I got it solved by replacing the URL encoded characters in the "path" entry with their characters again.
So changing path: gpgcli-gitcli-fs+file://C:%5CUsers%5CDE00173%5C.password-store to path: gpgcli-gitcli-fs+file://C:/Users/DE00173/.password-store

Where exactly should I change this path?
