### ISSUE TITLE
Clipboard timer is not reset

### ISSUE THREAD

**Issue by AuspeXeu** [gopasspw/gopass#758]
When using the -c option to copy a password to the clipboard, a timer of 45s is set. If I call gopass with -c again within these 45s, this timer should be reset. At the moment it still expires 45 seconds after the first call to gopass.

**Comment by dominikschulz** [comment]
Thank you for reporting this issue.

What exactly is your observed behaviour?

`gopass` is supposed to pass an hash of the clipboard content it wrote to a child process which will sleep the requested amount of time, compare the actual clipboard content with the hash and silently quit if the clipboard content changed in between.

You should only every see gopass overwriting the clipboard too early if you copy the same secret multiple times.
Is that your problem?

**Comment by AuspeXeu** [comment]
Hah, that is actually the case. I basically needed the password a second time and wanted to extend it's 'lifetime' by just calling gopass with -c again :)

**Comment by dominikschulz** [comment]
Ok, that is a valid use case. Let me see what we can do there ...
