### ISSUE TITLE
Support for custom password generators

### ISSUE THREAD

**Issue by asymmetric** [gopasspw/gopass#764]
It would be great if `gopass generate` could accept input from a custom password generator, e.g. `diceware`.

I use `diceware` to generate passphrases, à la ["correct horse battery staple"](https://www.xkcd.com/936/).

**Comment by dominikschulz** [comment]
We already support these kind of passwords: https://github.com/justwatchcom/gopass/blob/master/commands.go#L406

Is this the only thing you're asking for or do you really need a generic way to interface with external password generators?

**Comment by asymmetric** [comment]
@dominikschulz Ah, thanks for that, hadn't noticed it. Is it mentioned somewhere in the features/documentation? Cause I couldn't find it there. (Admittedly, I'm still using `pass` and was considering switching to your `gopass`)

Anyway, that's is pretty much the only reason why I wanted to use an external generator.

I wonder though if it wouldn't make sense to accept input from external password generators anyway, in order to reap the benefits of other projects (e.g. `diceware`) that have already invested efforts in this space.

**Comment by dominikschulz** [comment]
We need to check the documentation, this feature may be missing.
If anyone wants to implement support for external password generators, that should be easy.
