### ISSUE TITLE
gopass find includes symlinks

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [gopasspw/gopass#787]
As the pass itself and buggy tree,
```
% gopass find linux
...password-store
├── IT
│   └── linux.org.ru.gpg
└── shops
    ├── amazon.ca.gpg -> amazon.gpg
    ├── amazon.co.uk.gpg -> amazon.gpg
    ├── amazon.com.gpg -> amazon.gpg
    ├── amazon.de.gpg -> amazon.gpg
    ├── ebay.ca.gpg -> ebay.gpg
    ├── ebay.co.uk.gpg -> ebay.gpg
```

**Comment by c-e-p-x-u-o** [comment]
```gopass find linux``` must not show amazon

**Comment by c-e-p-x-u-o** [comment]
Real output:
```
% gopass find linux
/home/sergio/.password-store
├── IT
│   └── linux.org.ru.gpg
└── shops
    ├── amazon.ca.gpg -> amazon.gpg
    ├── amazon.co.uk.gpg -> amazon.gpg
    ├── amazon.com.gpg -> amazon.gpg
    ├── amazon.de.gpg -> amazon.gpg
    ├── ebay.ca.gpg -> ebay.gpg
    └── ebay.co.uk.gpg -> ebay.gpg
```

Expected output:
```
% gopass find linux
/home/sergio/.password-store
└── IT
    └── linux.org.ru.gpg
```

**Comment by Destructive-Dragon** [comment]
Why does it show amazon? I can't reproduce this issue :<

**Comment by c-e-p-x-u-o** [comment]
As amazon is a symlink.

**Comment by c-e-p-x-u-o** [comment]
It's tree bug
https://lists.zx2c4.com/pipermail/password-store/2018-April/003256.html
https://lists.zx2c4.com/pipermail/password-store/2018-April/003257.html

**Comment by dominikschulz** [comment]
gopass doesn't use tree.

**Comment by c-e-p-x-u-o** [comment]
So it's another bug. Anyway, could you reproduce it?

**Comment by dominikschulz** [comment]
I'm afraid I wasn't able to reproduce it.

**Comment by c-e-p-x-u-o** [comment]
I'm sorry. It's bug of 1.2.0-1 from debian sid
All works fine with 1.7.2

**Comment by falschparker82** [comment]
@c-e-p-x-u-o - note that the Debian package is a completely independent version of gopass from Alexandre Viau: https://salsa.debian.org/debian/gopass

It does not have anything to do with https://github.com/gopasspw/gopass

**Comment by dominikschulz** [comment]
In fact we aware of this naming conflict and have been in contact with the Debian maintainer of the other gopass package in Debian. Unfortunately we could not reach any compromise that would have made this situation obvious to users.

I'd suggest you raise an issue the Debian BTS to ask for clarification.

**Comment by c-e-p-x-u-o** [comment]
The note should be on the main page.

**Comment by dominikschulz** [comment]
@destructive-dragon Good idea, but we don't have an issue template, yet.
I'll add one.
