### ISSUE TITLE
Debian repo release

### ISSUE THREAD

**Issue by nikolay-turpitko** [gopasspw/gopass#797]
It seems to me that https://www.justwatch.com/gopass/releases/binary-amd64/Release wasn't updated with new v1.7 realease, it's timestamp is still in January. While I see a new version package in the repository via web interface, apt refuses to update it. Could you please take a look? Thanks.

**Comment by dominikschulz** [comment]
Thanks for raising this issue. The Debian Repo situation is a little annoying at the moment. I plan to look into some alternatives soon.

Meanwhile I'll try to fix the existing repo.

**Comment by Beanow** [comment]
In that light, revisiting snaps might be an option. #16

**Comment by dominikschulz** [comment]
Personally I don't get the point of snaps (so far). But if someone wants to contribute, feel free.

**Comment by nikolay-turpitko** [comment]
There is already Debian repo deployment script in the project. It's simpler to fix it (I hope), rather than urge users to use completely different packaging option.

BTW, there are many "good" alternatives beside snaps: AppImage, flatpak, docker, nix, linuxbrew and other similar things, you name it. They are all equally good from technical point of view, but there is common problem with them - they are not `brew` of Mac world. Every one of them contains only 2.5 packages which are not in official Debian repositories, not stable and hardly tested (because of luck of community). So, no, it's not an option for me (as Debian/Ubuntu user), I'd rather compile package from sources myself, than will use several different package managers on the single Debian system (and I will have to, if I start to use any of them, because neither of them provide a complete solution at the moment). So, please, keep supporting Debian repo. All other options are up to you.

**Comment by dominikschulz** [comment]
We'll keep supporting Debian packages for sure!
I'm currently looking into hosting the packages with bintray and adding this to our (semi-automated) release workflow.

We'll also keep supporting `brew` for MacOS. I don't think snap is important for us, but if someone disagrees and creates a proper PR we can support that, too. There was a snap PR in the past but I wasn't able to successfully build a gopass snap package with the scripts/documentation in that PR so I wasn't to able to merge it back then. If someone creates a working PR we will re-evaluate it.

**Comment by dominikschulz** [comment]
We've implemented preliminary Bintray support in our release workflow and will continue to extend and polish this with the next releases. This way we should be able to keep our Debian Repo always up to date.

**Comment by espoelstra** [comment]
I switched to the new repo and got the 1.8.0-alpha release (which also seems to have some workflow breaking bugs for us). Oddly I couldn't "see" the 1.7.2 release that is also there and on my initial attempt to manually download to downgrade I discovered that there is a `:` getting adding before the deb package name in the URL that was causing issues.

Right now I'm working through what broke in the change from 1.6.10 to 1.8 and whether it came up in 1.7.2 or not and will file appropriate bugs as necessary.

**Comment by dominikschulz** [comment]
The new repo only contains any new releases. I will try to backfill the old ones eventually.

Please be sure to file individual issues for any breaking bugs you encounter. Thanks!

**Comment by nikolay-turpitko** [comment]
@dominikschulz 

I'm not re-opening this issue, it's just a question. I'm curious is it difficult to make through into official Debian repository? I've seen some old version in "unstable" and "testing", but no new updates and seems no progress into "stable". What blocks it? Is it some requirement from Debian side or lack of resources or project is just not too stable yet. Personally I would prefer to stick to the current version (1.7.x) as it has everything I currently need and works for me. Now I'm a bit worry about possible breaking updates )). Especially, because I had to switch to `go get`, while you were migrating onto new repo ('cause I experienced issues with keys and repo availability during unattended OS installation). I'm considering to switch back to repo usage, but would prefer a bit outdated version, but from official repo. Not "that outdated", though )), 'cause I get used to yaml metadata function in the json API.

So, if anything can be done from the community side to make it into official Debian repo, please let us know. I'm not experienced in that matters, but probably someone of us, users, would be able to help. Thanks!

**Comment by dominikschulz** [comment]
@nikolay-turpitko Thanks for asking. In fact I think it might be almost impossible to get this gopass into any official Debian/Ubuntu distribution. Because in fact there is a completely different password manager with a similar name packaged as gopass in Debian already. It was uploaded some time after we announced gopass to the public (there may have been an ITP before that, but we failed to find it when researching for possibly conflicting names).

So if someone is very experienced with the complicated Debian policies regarding package naming and conflict resolution and has a lot of endurance he or she might be able to help.

The best recommendation I give right now is to raise an issue in the Debian and/or Ubuntu Bugtrackers and complain about this there, because then it will come attention to the people who could actually do something about this.

**Comment by nikolay-turpitko** [comment]
@dominikschulz Thanks for explanation. I haven't realized that these are two completely different packages. I thought it's the same but older version. Yeah, now I see, it's probably complicated indeed. Name conflict can be, probably, resolved, if you package it as `gopasspw` (as you recently renamed git repo), but I don't know much about other policy, regarding similar functionality. Raising an issue I would try, though I have couple of issues both on Debian and Ubuntu unanswered from March )).  There is something wrong with their mailing/notification system setup, preventing it to send notifications originated from my email account. (OK, I know what's wrong, but it is irrelevant here - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=754809, my email provider prevents them to use my email address, when they trying to send notifications, and I receive spam prevention alerts, don't know what can I do about it, though). So, if someone else will rise an issue, I'll add my +1.
