### ISSUE TITLE
`Gopass git --store store-name pull` not working

### ISSUE THREAD

**Issue by muskand** [gopasspw/gopass#815]
### Summary
I am using the command `Gopass git --store stare-name pull` to pull from a specific password store.
This used to work fine until 1.6.11 release but on 1.7.2 release, this doesn't seem to work.
It says, -store flag is used but not defined.

### Steps To Reproduce
run this command for a non-default store.

### Expected behavior
It should pull from the store repo

### Environment
- OS: Mac OS High Sierra
- OS version: Darwin Kernel Version 16.7.0
- gopass Version: 1.7.2
- Installation method: brew

**Comment by dominikschulz** [comment]
Thank you very much for reporting this issue. We'll investigate.

**Comment by muskand** [comment]
Sure. Thanks.

**Comment by dominikschulz** [comment]
I was able to reproduce your issue, but actually it's not strictly a bug.

The correct usage is:
`gopass git pull --store stare-name`
NOT
`gopass git --store stare-name pull`

i.e. "--store" is only defined a flag for the `git pull` subcommand, not the `git` subcommand.

You may have been confused by gopass no longer defaulting to `origin master` when no remote and branch are specified. This will be fixed.

**Comment by muskand** [comment]
`gopass git --store store-name pull` worked as of 1.6.x
We had working code that stopped working after the update.

**Comment by dominikschulz** [comment]
This is very interesting. I'll try to reproduce with an 1.6.x release.

**Comment by dominikschulz** [comment]
Ok, my bad. You're right. Unfortunately there is no (easy) way to fix this.
Starting with 1.7 we introduced pluggable backends which handle git commands in code instead of just passing them straight to an executeable.

**Comment by muskand** [comment]
So basically this was a breaking change in 1.7
It would be helpful if it was mentioned as a breaking change.
But thanks for clarifying it, anyway.
For now, we'll stick to v1.6 until a fix is deployed in v1.8.

**Comment by dominikschulz** [comment]
I'm sorry. We try to mention all possibly breaking changes in the release notes, but 1.7. was a big release and some things might have been missed or weren't obvious.
