### ISSUE TITLE
Git error message when adding new password

### ISSUE THREAD

**Issue by blinry** [gopasspw/gopass#828]
### Summary
When adding a password, the gpg file is created correctly, and can be retrieved, but gopass outputs this message after reading information about the website and user (`<path>` redaction by me):
```
Error: failed to set 'websites/<path>': failed to add 'websites/<path>.gpg' to git: exit status 1
```

### Steps To Reproduce
- create a new local gopass store
- add a password

### Expected behavior
The new gpg file is added to the Git repository.

### Environment
Arch Linux, kernel version 4.16.12-1
```
gopass 1.7.0 (2018-05-23 19:10:44) go1.10.2 linux amd64
[<root>] Crypto: gpg 2.2.7
[<root>] RCS: git 2.17.1
[<root>] Storage: fs 0.1.0
```
Installed from the official Arch Linux "community" repository.

### Additional context
My home directory is versioned with Git, so there's a `~/.git` directory. `~/.password-store/.git` exists, as well, and contains two commits:
```
* <hash> (HEAD -> master) Add current content of password store
* <hash> Configure git repository for gpg file diff.
```

What can I do to help debug this further?

**Comment by dominikschulz** [comment]
Could you please try to re-run your commands with `GOPASS_DEBUG=true` set?
This should output any command run, so we may be able to see what went wrong.

**Comment by blinry** [comment]
Good call. Here's what happened:

```
[DEBUG] store.gitAdd: /usr/bin/git [git add --all websites/foobar.com/test.gpg] (/home/seb/.password-store)
The following paths are ignored by one of your .gitignore files:
websites/foobar.com/test.gpg
Use -f if you really want to add them.
```

This is because my `~/.gitignore_global` contains the following ignore rules:

```# compiled source:
*.com
*.class
*.dll
*.exe
*.o
*.so
```

So all URLs with .com domains can't be added without `-f`. I would suggest using `-f` by default to avoid this behaviour.

**Comment by dominikschulz** [comment]
Thanks for checking, I would have never guessed that. Good explanation.

I'll think about '-f', not sure right now. If we don't any downsides it will be an easy fix.
