### ISSUE TITLE
Recipient display is broken if no email is set on gpg key

### ISSUE THREAD

**Issue by martinhoefling** [gopasspw/gopass#829]
### Summary

Gopass recipient display does not show any useful information if key has no email address associated with. This has been fixed previously in #650 and probably broke in the opengpg refactoring of 1.7.

### Steps To Reproduce

```
$ gopass recipients

...
│   └── 0xE3E9DA7A5556A032 -  <>
├── 0x2E212EA32352884F -  <>
├── 0x824F3FC98999E0C7 -  <>
├── 0xE3E9DA7A5556A032 -  <>
...
```

### Expected behavior

The Name and comment should be shown instead. No mail though.

### Environment
```
gopass 1.7.2 (39fb91ab96c8ba59b67c33d6b938a474dcbb5000 2018-05-28 14:56:55) go1.10.2 darwin amd64
[private] Crypto: gpg 2.2.7
[private] RCS: git 2.17.1
[private] Storage: fs 0.1.0
[shared] Crypto: gpg 2.2.7
[shared] RCS: git 2.17.1
[shared] Storage: fs 0.1.0
[<root>] Crypto: gpg 2.2.7
[<root>] RCS: git 2.17.1
[<root>] Storage: fs 0.1.0

```

**Comment by martinhoefling** [comment]
@dominikschulz any ideas? I did a short dive and ended up in "FormatKey" that probably causes the issue.

**Comment by dominikschulz** [comment]
That's a little hard to debug from my end.
`FormatKey` invokes `findKey` which falls back to an "Fingerprint-only" fake key object.
Running with `GOPASS_DEBUG=true` should show the GPG commands executed. If these fail to retrieve the actual keys the output may be truncated.
