### ISSUE TITLE
`gopass jsonapi` return code always zero

### ISSUE THREAD

**Issue by zsau** [gopasspw/gopass#834]
`gopass jsonapi` doesn't seem to return a useful status code. At least for messages like `{"type":"getLogin","entry":"..."}`, it returns zero (success) even when the entry does not exist or the decryption failed.

**Comment by martinhoefling** [comment]
It actually uses an error message as described here: https://github.com/gopasspw/gopass/blob/master/docs/jsonapi.md#error-response Does that answer your question?

**Comment by zsau** [comment]
I don't see why gopass couldn't still exit with a nonzero status in those cases. Not doing so definitely violates the principle of least surprise for me.

**Comment by martinhoefling** [comment]
Ah, now I got it. Yes, this would be possible. At least I did not find anything in the docs that prevents using it as native messaging host app. I am not if and how this works out with multiple messages, which can in principle be handled by a native messaging host app. Do you have any specific use case for the error code?

**Comment by zsau** [comment]
Initially I was thinking it would make native messaging interop more straightforward, but it seems like the promise returned by `browser.runtime.sendNativeMessage` doesn't actually reject in the event of a nonzero exit code. So I guess it's just about CLI ergonomics at this point, which isn't nearly as important as I can't think of why a CLI caller of `gopass` would bother with the JSON API.

And if sending multiple messages to the same invocation of `gopass jsonapi listen` is a possible feature (though I don't think it works ATM?), then the status code issue becomes much less clear-cut anyway. Given that the presence of the `error` key can be used for that (as you pointed out), I'm happy to close the issue in that case.

**Comment by martinhoefling** [comment]
@zsau thx for your hints, again something learned.
