### ISSUE TITLE
Bintray debian repository is not signed

### ISSUE THREAD

**Issue by bpicode** [gopasspw/gopass#835]
### Summary

The [debian repos](https://dl.bintray.com/gopasspw/gopass/dists/jessie/) are missing a `Release.gpg` file. It causes `apt-get update` to issue a warning and `apt update` to fail with exit code 100.

Logs:

```
E: The repository 'https://dl.bintray.com/gopasspw/gopass xenial Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Steps To Reproduce

Minimalistic docker
```
FROM ubuntu:xenial
RUN apt-get update
RUN apt-get install -y wget apt-transport-https
RUN wget -q -O- https://api.bintray.com/orgs/gopasspw/keys/gpg/public.key | apt-key add -
RUN echo "deb https://dl.bintray.com/gopasspw/gopass trusty main" | tee /etc/apt/sources.list.d/gopass.list
RUN apt update
```

### Expected behavior

Signature present. Clean `apt update`.

### Environment

- OS: ubuntu
- OS version: xenial
- gopass Version: 1.7.2
- Installation method: gopass repo

**Comment by dominikschulz** [comment]
Thanks a lot for reporting this issue!

The repository metadata on bintray seems to be incomplete. Will investigate.

**Comment by dominikschulz** [comment]
Not sure what happened, but after running the release process it seems to work. I'm not familiar with the bintray semantics, i.e. what happens if you push partial releases. But when we issue a proper release it looks good.
