### ISSUE TITLE
Default value should be used in config when not set

### ISSUE THREAD

**Issue by belak** [gopasspw/gopass#844]
### Summary
On my work laptop, the user that's been configured has a different name from my personal laptop, so the `root: path:` setting which was generated does not work. I tried removing it, but when I run gopass I get the error: `No gpg binary found: failed to init root store: need path`

### Steps To Reproduce
- Remove the value for `path` from the root config.
- Run a gopass command

### Expected behavior
Running gopass commands should use the default values if they're not set in the config. Because my password store is at ~/.password-store on all my machines, gopass commands should work without setting the path.

### Environment

- OS: macOS High Sierra
- OS version: Darwin sea-42-laptop.internal 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
- gopass Version: gopass 1.7.2-git+HEAD go1.10.1 darwin amd64 <root> - gpg 2.2.7 - git 2.17.0 - fs 0.1.0
- Installation method: built manually from `c36481bb9703c2d3b8918ab941c9e679a78ad638`

### Additional context
N/A

**Comment by dominikschulz** [comment]
Thanks for reporting this issue. I agree that this is not optimal. We'll see how we can make it use a sensible default value.

**Comment by belak** [comment]
Thanks for the quick response! Works great! Are there any plans to do this for all config values, or do you plan to stick with only the path?

**Comment by dominikschulz** [comment]
The plan is to fall back to safe defaults for any config option in case it's not set.
