### ISSUE TITLE
Split packages into pkg and internal

### ISSUE THREAD

**Issue by dominikschulz** [gopasspw/gopass#849]
> The special internal package in Go 1.5+ disallows imports from packages
> that you don't expect people to import. This allows greater flexibility
> to refactor etc. later with certainty that the packages aren't used
> elsewhere.

https://github.com/ianlewis/memcached-operator/commit/cb52d334d90e8eca354c4970763a7e219730f187

### Summary

gopass utilizes a lot of packages to implement it's features. They are all equally exposed to outside consumers. Unfortunately this sometimes leads to confusion and breakage, e.g. #845 

We should consider splitting the packages into `external API` packages in `pkg` and `internal API` packages in `internal`.

**Comment by dominikschulz** [comment]
@n3ph WDYT?

**Comment by n3ph** [comment]
Sounds reasonable to me so far. This would lead to a more stable and clean interface for other implementations.

**Comment by dominikschulz** [comment]
Defining and implementing the API will be tracked in #1379.
