### ISSUE TITLE
Fsck appears to look for files in mounts using their absolute paths (not relative to the mountpoint).

### ISSUE THREAD

**Issue by amc90** [gopasspw/gopass#852]
### Summary
Fsck appears to look for files in mounts using their absolute paths (not relative to the mountpoint).

Running "gopass fsck" 1.7.2-git+HEAD I get output like:

Error: fsck found errors: fsck failed on sub store it: failed to check it/sort_me/Some Secret Name: failed to decode secret it/sort_me/Some Secret Name: Entry is not in the password store: Entry is not in the password store: failed to decode secret it/sort_me/Some Secret Name: Entry is not in the password store: Entry is not in the password store: failed to check it/sort_me/Some Secret Name: failed to decode secret it/sort_me/Some Secret Name: Entry is not in the password store: Entry is not in the password store: failed to decode secret it/sort_me/Some Secret Name: Entry is not in the password store: Entry is not in the password store

Picking through the debug output I see:

[DEBUG] fs.Get(it/sort_me/Some Secret Name.gpg) - /home/user/.password-store-it/it/sort_me/Some Secret Name.gpg
[DEBUG] File it/sort_me/Some Secret Name.gpg not found: open /home/user/.password-store-it/it/sort_me/Some Secret Name.gpg: no such file or directory
[DEBUG] Stacktrace: Entry is not in the password store

"it" is a "gpgcli-gitcli-fs+file:///home/user/.password-store-it" mountpoint, though:
#gopass mounts
gopass (/home/user/.password-store)
├── it (/home/user/.password-store-it)
└── web (/home/user/.password-store-web)

Fsck should therefore be looking at /home/user/.password-store-it/sort_me/Some Secret Name.gpg

I suspect that this is going to be easy to reproduce, but I can sanitize debug output if necessary.

Thanks

**Comment by dominikschulz** [comment]
Thanks a lot for reporting. Will have a look.
