### ISSUE TITLE
Release links on https://www.justwatch.com/ do not work

### ISSUE THREAD

**Issue by murriel** [gopasspw/gopass#861]
### Summary
Release links to download binaries on https://www.justwatch.com/gopass do not work. The links are specified under the "Install" section of the site, as follows: 

-  In the commands for Debian and Ubuntu installation https://www.justwatch.com/gopass/releases/1.7.0/gopass-1.7.0-linux-amd64.deb
- Under the link for other binaries
https://www.justwatch.com/gopass/releases/1.7.0/

When clicking the link, the following page displays: 

Oops, page not found. :(

I am still able to access the releases directly from GitHub.

**Comment by varac** [comment]
Same for the debian repository:

```
Err:7 https://www.justwatch.com/gopass/releases/binary-amd64 ./ Release                                                                              
  404  Not Found [IP: 35.186.248.180 443]

```

**Comment by varac** [comment]
Oh, just found out the debian repo location has changes, see https://github.com/gopasspw/gopass/blob/master/docs/setup.md#ubuntu--debian-1 for the new one.

**Comment by dominikschulz** [comment]
Thanks for reporting this and sorry for the confusion. We're still not completely finished with moving the gopass website - will try to wrap that up today.

**Comment by dominikschulz** [comment]
Done
