### ISSUE TITLE
Version 1.8.1 not in repository yet?

### ISSUE THREAD

**Issue by domkle** [gopasspw/gopass#871]
### Summary
On the repository https://dl.bintray.com/gopasspw/gopass the latest version of gopass 1.8.1 is not available yet. Atleast the gopass-1.8.1-linux-amd64.deb version I was looking for was not there yet.
I installed the software manually now, so no problem there, but I'd be happy to use the repository in the future :)

**Comment by compuguy** [comment]
Version 1.8.2 is also not in the repository, as of this comment.

**Comment by dominikschulz** [comment]
Yes, I'm afraid but the (new) release workflow is still a little buggy. Will try to fix that with the next release (or maybe earlier).

**Comment by compuguy** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Any updates on this?                                                                                                                                                                        Sent via the BlackBerry Hub for Android

**Comment by puck** [comment]
Looks like 1.8.3 didn't fix the work flow - it is missing as well.

**Comment by moritzheiber** [comment]
It is indeed. The bot closed #896, so let's focus on resolving this issue with this bug here.

**Comment by dominikschulz** [comment]
Yes, indeed. I'm afraid, but I didn't have much time to work on the tooling in a while.
Still on my backlog, but any help is appreciated.

**Comment by moritzheiber** [comment]
FYI, this appears to be fixed with 1.8.4?

**Comment by dominikschulz** [comment]
1.8.4 should be OK, but the release process hasn't improved much.
