### ISSUE TITLE
Use '~' in config.yml

### ISSUE THREAD

**Issue by mcanevet** [gopasspw/gopass#872]
It would be great to use `~`in the `config.yml` file so that it uses relative resolution instead of absolute resolution. The idea behind this is to be able to commit the config file in a git repository and deploy it on different machines where homedir can be different.
I tested by replacing `/home/<foo>` with `~` in the config file and it works fine. The only thing is that everytime I change configuration, the `~` is replaced back by `/home/<foo>`.

**Comment by mcanevet** [comment]
@dominikschulz any thought on this?

**Comment by dominikschulz** [comment]
Well, we should support this. The current implementation is overly strict. Now someone just needs to have time to work on this ;)
