### ISSUE TITLE
Optionally create password stores as git submodules instead of clones

### ISSUE THREAD

**Issue by mcanevet** [gopasspw/gopass#873]
When managing its home directory as a git project it would be great if gopass could optionally create git submodules so that we can easily commit the whole gopass configuration (`~/.config/gopass/config.yml + ~/.password-store*).

**Comment by espoelstra** [comment]
I'm not sure if this makes sense given how easy it is to clone a set of existing password stores and managing the config is something that should be done in a user's dotfiles not inside the password-store repository, otherwise you get into a chicken and egg situation.

**Comment by mcanevet** [comment]
@espoelstra maybe the configuration file could contain the remote url for each mount so that we could have a command that could recreate the `~/.password-store*` directories. The thing is that I could add `~/.config/gopass/config.yml` to my dotfiles repo, but I'd still miss the information of the remotes.

**Comment by dominikschulz** [comment]
Interesting idea, feel free to work on that. I'm not keen on working with git submodules again ;)

**Comment by mcanevet** [comment]
Actually if the config file contains the remote url, maybe there is no need for submodules. Gopass could automatically clone the repo if it does not exists.

**Comment by dominikschulz** [comment]
That sounds reasonable. We can probably do that.

**Comment by mcanevet** [comment]
This would be great. This featuer plus #872 would allow to manage the config file in one's dotfile git repo and reconstruct all password stores dynamically without having to run gopass clone.

**Comment by dominikschulz** [comment]
We'll look into it. #872 might be a little tricky because we assume to work with absolute paths in a lot of places and this might take some effort to untangle.
