### ISSUE TITLE
gopass won't work when .password-store is symbolic link

### ISSUE THREAD

**Issue by torfmaster** [gopasspw/gopass#885]
### Summary
gopass doesn't find secrets when .password-store is a symbolic link.

### Steps To Reproduce
 - Move .password-store to another location. Create a symbolic link with the same to that location.
 - use 'gopass create' to create a new secret
 - use 'gopass ls' to find that secret -> it won't appear
 - delete the symbolic link
 - move .password-store back
 - use 'gopas ls' to find the new secret -> it wil appear

### Expected behavior
There should be no difference whether the password store is a symbolic link or not.

### Environment

- OS: [e.g. Mac OS X High Sierra, Ubuntu 18.04, Windows 10, ...]
- OS version: 
```
4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- gopass Version: 
```
gopass 1.8.1-git+HEAD go1.10.1 linux amd64
```
- Installation method: 'go get'

**Comment by dominikschulz** [comment]
This is supposed to work. Will try to reproduce.
