### ISSUE TITLE
`gopass -c git` calls `gopass git` instead of searching for git in the password store

### ISSUE THREAD

**Issue by tagirb** [gopasspw/gopass#887]
### Summary

`gopass -c git` calls `gopass git` instead of searching for git in the password store

### Steps To Reproduce

```
$ gopass -c git
NAME:
   gopass git - If the password store is a git repository, execute a git command specified by git-command-args.

USAGE:
   gopass git command [command options] [arguments...]

COMMANDS:
     init    Init git repo
     remote  Mangage git remotes
     push    Push to remote
     pull    Pull from remote

OPTIONS:
   --help, -h  show help
```

### Expected behavior

Normal search behavior is expected:
```
$ gopass -c git
Entry 'git' not found. Starting search...
```

### Environment

- macOS 10.13.5
- Darwin mbp-tba 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
- gopass 1.8.2 (10b7d6f172a8a99f9d8176a45b847b16b622bc04 2018-06-29 07:39:27) go1.10.3 darwin amd64
- brew

**Comment by dominikschulz** [comment]
This is expected behavior. If you want to search for/show reserved command strings you need to use the long form, i.e. `gopass show git`

**Comment by tagirb** [comment]
Tnx, closing.
