### ISSUE TITLE
Document how command `git-credential` works

### ISSUE THREAD

**Issue by worldofpeace** [gopasspw/gopass#891]

**Comment by veecue** [comment]
I'd suggest to add a subcommand that directly executes `git config --global credential.helper '!gopass git-credential $@'` (the command is already stated in the description (see `gopass help git-credential`) and maybe link the git credential manpage.

**Comment by veecue** [comment]
I'm on it, hope I'll finish it today

**Comment by worldofpeace** [comment]
Thanks @veecue :sparkle:
