### ISSUE TITLE
Option to name file after using create

### ISSUE THREAD

**Issue by bobbybroadcast** [gopasspw/gopass#894]
`gopass create` places files in one of a couple subdirectories with its own naming scheme; for example in "websites/user@domain.com". 

Is there a way to disable this? I don't see any option to name the file myself, for example "domain.com" or "domain.com/user".

**Comment by dominikschulz** [comment]
Right now this is not supported, but I agree this might be useful.
We can probably add that easily.

**Comment by dragon788** [comment]
@bobbybroadcast if you use `gopass generate your/desired/path/user@service` it will create the entry for you or prompt you to overwrite if it exists. What is `create` intended to do differently?

**Comment by bobbybroadcast** [comment]
@dragon788 `gopass create` has a step-by-step where it allows you to add username and comments during creation. The issue is that it will assign the path and name based on your choice. For example, should you choose website, `gopass create` automatically will place it into `websites/DOMAIN/USER`. This assumes the user wants that naming scheme. It would be helpful if we could assign path/name during creation, or better yet, an option for it to behave the way `gopass generate` does.

**Comment by dominikschulz** [comment]
The idea of the `gopass create` command is to provide strict guideance for users who don't have strong opinions about the naming scheme and just want to create an entry.
The lower level commands still exist and provide full control over naming and placement.

If you have any good idea on how to improve the UX let me know, i.e. could you please provide an example on how you'd like the create command to behave?

**Comment by bobbybroadcast** [comment]
The advantage of `gopass create` is that it allows the user to generate a password and enter the username with one command. For example, If I don't want to have that naming scheme `websites/site/username@site.com`, I then have to rename it using `gopass mv`, adding an additional step. If I use `gopass generate xxxxxxx`, I then have to use `gopass edit` to add username, adding an additional step.

I'd like to be able to name the file the same way `gopass generate` does, and still be able to, with a single command, enter the username the way I would with `gopass create`. This is because I do not use the `domain/username` naming scheme.
