### ISSUE TITLE
tty() function does not work on NetBSD

### ISSUE THREAD

**Issue by iquiw** [gopasspw/gopass#895]
### Summary

[tty()](https://github.com/gopasspw/gopass/blob/v1.8.2/pkg/backend/crypto/gpg/cli/utils.go#L53) tries to read symbolic link of `/proc/self/fd/0`.
It is not a symbolic link on NetBSD, but a character special file.  So `GPG_TTY` is not set.

Also, I think OpenBSD has problem too as it does not provide procfs.

### Steps To Reproduce

Similar to #350.
`GPG_TTY` is not set and pinentry-curses does not show prompt.
Then `Failed to decrypt` error happens.

### Expected behavior

`GPG_TTY` is set before gpg is executed.
Workaround is to set `GPG_TTY=$(tty)` manually.

### Environment

- OS: NetBSD
- OS version: NetBSD 8.0_RC2
- gopass Version: 1.8.2
- Installation method: gopass repo

**Comment by iquiw** [comment]
One option is to use `ttyname()` function by C FFI.

Another option is to leave the configuration to user's hand, as `gpg-agent` [manual](https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html#Invoking-GPG_002dAGENT) (the following quote) says.

> You should always add the following lines to your .bashrc or whatever
> initialization file is used for all shell invocations:
>
>        GPG_TTY=$(tty)
>        export GPG_TTY

**Comment by dominikschulz** [comment]
So ... you think we should make `tty()` a noop on NetBSD and rely on the user setting `GPG_TTY`?
We can do that, but I don't think I can test this change.
Could you provide an PR?

**Comment by iquiw** [comment]
I sent a PR for this, but Travis build did not pass. I have no idea how to fix the build for now.

**Comment by iquiw** [comment]
I'm currently considering the following options.

* (a) Call `/usr/bin/tty` command to get ttyname.
* (b) Do not use stdin for `gpg` command so that `pinentry-curses` can find ttyname from stdin.
* (c) Document `GPG_TTY` is required to be set for using `pinentry-curses` on non-Linux platform.
* (d) Leave as is. FAQ describes about `GPG_TTY`.

I think (a) should work on most Unix platforms including macOS. (b) might not be an option as it requires temporary file.

**Comment by dominikschulz** [comment]
(a) SGTM. I'd like to keep the way it is for Linux, but that's easy with build tags.

**Comment by iquiw** [comment]
So the following is OK?

`tty()` returns

* Symlink target of `/proc/self/fd/0` for `linux`
* Output of `/usr/bin/tty` command for `!linux,!windows`
* Empty string for `windows`

**Comment by dominikschulz** [comment]
Yes, that sounds about right.
