### ISSUE TITLE
Latest release is missing from the Debian/Ubuntu bintray repository

### ISSUE THREAD

**Issue by moritzheiber** [gopasspw/gopass#896]
### Summary
It would appear the latest releases are missing from the Debian/Ubuntu Bintray repository. [The only version available is 1.8.0](https://dl.bintray.com/gopasspw/gopass/pool/main/g/gopass/). It would be good to have the latest release (1.8.2) available through the repository as well.
### Environment
- OS: Ubuntu 18.04

**Comment by martinhoefling** [comment]
Related to #871 ?

**Comment by dominikschulz** [comment]
We'll try to fix the bintray release workflow.

**Comment by compuguy** [comment]
@martinhoefling Yes it is. The latest build, 1.8.2 is also not in the repo.

**Comment by compuguy** [comment]
I believe this issue is still vaild.

**Comment by moritzheiber** [comment]
It is, but it's also being tracked in #871
