### ISSUE TITLE
Exit with error code when ls with filter yields no results

### ISSUE THREAD

**Issue by knuton** [gopasspw/gopass#897]
### Summary
It would be handy if `gopass ls filter` would exit with a non-zero status code if there are no results. This allows to query for the existence of an entry without actually decrypting any secrets.

### Steps To Reproduce
Run `gopass ls some-nonexistent-prefix`. Check `$?` and see code `0`.

### Expected behavior
`echo $?` yields a non-zero code.

(I am running gopass 1.6.11-git+HEAD go1.9.5 linux amd64, but according to release notes this has not been changed.)

**Comment by dominikschulz** [comment]
Thanks for raising this issue.
I agree with you, we should change the exit code to `ExitNotFound`.
