### ISSUE TITLE
Add Chocolatey package

### ISSUE THREAD

**Issue by lyze237** [gopasspw/gopass#900]
### Summary
https://chocolatey.org/ is a really awesome windows package manager. It would be nice to have gopass in there as well!

This would mean that we could install it automatically in scripts, update it automatically and other things.

### Environment
- OS: Windows 10
- gopass Version: latest

**Comment by lyze237** [comment]
I have created a choco package which you can find here: https://chocolatey.org/packages/gopass/1.8.2

It would be kinda awesome if it could be included officially!

**Comment by dominikschulz** [comment]
@lyze237 Thanks for reporting this and creating the package! I don't really have access to a Windows development setup. So if you could help us with that, that'd be cool.

How could we include this officially?

**Comment by lyze237** [comment]
Alright, I've setup a rss feed so it notifies me whenever you release a new version. With that I should be able to publish a new version of the choco package in <24h.

> How could we include this officially?

Maybe mention it in the setup that it's available?

**Comment by metalmatze** [comment]
@dominikschulz what is the current state of windows support in overall?
If there's something available via chocolatey we can add this to the website, but should really mention that it is still experimental.

**Comment by dominikschulz** [comment]
Windows seems to work for some people ... that's all I know. We should definitely add a reference to the choco package to the docs, yes.

**Comment by lyze237** [comment]
Yeah I’m using it also since I’ve created this issue.

So far i haven’t noticed any weird things except a really small one. I’ll open a issue later today for that but everything else works really well (except the initial config error somebody else made a issue about already)

**Comment by dragon788** [comment]
@lyze237 are you using Appveyor or TravisCI to perform automated building and running of tests or just doing it by hand for now?

**Comment by lyze237** [comment]
I'm just building it manually on my pc.

https://gitlab.com/lyze237-choco/gopass
