### ISSUE TITLE
gopass should support adding OTP URIs to existing secrets

### ISSUE THREAD

**Issue by sudoforge** [gopasspw/gopass#901]
### Summary

`gopass otp` can currently _read_ `otpauth://` URIs, but can not insert new ones for any given secret. 

### Additional context

Currently, the workflow for adding an OTP code (such as a TOTP code) requires the user to run `gopass edit <secret>` and manually type out `otpauth://totp/foo@example.com?secret=123123123123123123123123`.

This is cumbersome. It would be great to be able to append TOTP URIs from `otp` subcommand, such as with `gopass otp insert <secret>`, which would prompt the user for the necessary information (the actual `secret` property's value).

**Comment by dominikschulz** [comment]
Thank you for raising this issue. I agree that this would be nice to have.
Unfortunately I rarely use this feature myself and don't have much time to spare at the moment.
So if anyone would open a PR that, that'd be great. Otherwise it will take a while to see some progress here.

**Comment by sudoforge** [comment]
I'll see if I can make time for this in the coming weekends.

**Comment by sudoforge** [comment]
I'll be working on this as soon as my eyes recover from surgery.

**Comment by basedtho** [comment]
any progress on this?

**Comment by sudoforge** [comment]
I am no longer using `gopass`, but encourage this feature to be picked up.

**Comment by AnomalRoil** [comment]
This will be possible once #1681 will be merged, by doing :

`gopass insert <secret> otpauth`
and providing simply : `//totp/foo@example.com?secret=123123123123123123123123` as a value for the key `otpauth`.

Does that work for you or should the process be more streamlined?

**Comment by AnomalRoil** [comment]
Using `echo otpauth://totp/foo@example.com?secret=123123123123123123123123 | gopass insert -a secret` also works.

**Comment by AnomalRoil** [comment]
If someone feels we should really ease the use of the OTP URIs, please feel free to reopen.
