### ISSUE TITLE
Renaming to _native_host.exe results in segmentation violation

### ISSUE THREAD

**Issue by martinhoefling** [gopasspw/gopass#902]
### Summary

Renaming gopass.exe to gopass_native_host.exe should execute gopass with `jsonapi listen` arguments by default.

### Steps To Reproduce

Steps to reproduce the problem

$ echo '{"type":"queryHost","query":"github.com"}' | ./test-client | /tmp/native_host.exe

[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x10223fcba]

goroutine 1 [running]:
github.com/gopasspw/gopass/pkg/store/sub.(*Store).List(0x0, 0x1026a7940, 0xc4202accc0, 0x0, 0x0, 0xc4202ce5c0, 0x3, 0xc420046a70, 0xc420046a00, 0xc4202b0018)
	/private/tmp/gopass-20180629-24249-6x53ht/gopass-1.8.2/src/github.com/gopasspw/gopass/pkg/store/sub/list.go:17 +0x3a
github.com/gopasspw/gopass/pkg/store/root.(*Store).Tree(0xc4202ac990, 0x1026a7940, 0xc4202accc0, 0x102472540, 0xc4202ab310, 0x0, 0x0)
	/private/tmp/gopass-20180629-24249-6x53ht/gopass-1.8.2/src/github.com/gopasspw/gopass/pkg/store/root/list.go:56 +0x1ad
github.com/gopasspw/gopass/pkg/store/root.(*Store).List(0xc4202ac990, 0x1026a7940, 0xc4202accc0, 0x0, 0xc4202ab310, 0x0, 0x0, 0x16, 0xc420163a78)
	/private/tmp/gopass-20180629-24249-6x53ht/gopass-1.8.2/src/github.com/gopasspw/gopass/pkg/store/root/list.go:18 +0x43
github.com/gopasspw/gopass/pkg/jsonapi.(*API).respondHostQuery(0xc420163bd8, 0x1026a7940, 0xc4202accc0, 0xc4202b4210, 0x2a, 0x2a, 0x0, 0xc42000e010)
	/private/tmp/gopass-20180629-24249-6x53ht/gopass-1.8.2/src/github.com/gopasspw/gopass/pkg/jsonapi/responses.go:50 +0xcf
github.com/gopasspw/gopass/pkg/jsonapi.(*API).respondMessage(0xc420163bd8, 0x1026a7940, 0xc4202accc0, 0xc4202b4210, 0x2a, 0x2a, 0x0, 0x5)
	/private/tmp/gopass-20180629-24249-6x53ht/gopass-1.8.2/src/github.com/gopasspw/gopass/pkg/jsonapi/responses.go:32 +0x335
github.com/gopasspw/gopass/pkg/jsonapi.(*API).ReadAndRespond(0xc420163bd8, 0x1026a7940, 0xc4202ac9c0, 0xc420163c00, 0x102415aa4)
	/private/tmp/gopass-20180629-24249-6x53ht/gopass-1.8.2/src/github.com/gopasspw/gopass/pkg/jsonapi/api.go:26 +0xd8
github.com/gopasspw/gopass/pkg/action.(*Action).JSONAPI(0xc4202f9f10, 0x1026a7940, 0xc4202ac9c0, 0xc420324000, 0xc4202ac9c0, 0xc420163c80)
	/private/tmp/gopass-20180629-24249-6x53ht/gopass-1.8.2/src/github.com/gopasspw/gopass/pkg/action/jsonapi.go:26 +0x97
main.setupApp.func2(0xc420324000, 0xc420324000, 0xc420163c67)
	src/github.com/gopasspw/gopass/app.go:54 +0xd8
github.com/gopasspw/gopass/vendor/github.com/urfave/cli.HandleAction(0x1024b12e0, 0xc4202b8400, 0xc420324000, 0xc4202af560, 0x0)
	/private/tmp/gopass-20180629-24249-6x53ht/gopass-1.8.2/src/github.com/gopasspw/gopass/vendor/github.com/urfave/cli/app.go:501 +0xc8
github.com/gopasspw/gopass/vendor/github.com/urfave/cli.(*App).Run(0xc4202fc000, 0xc4200301b0, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/gopass-20180629-24249-6x53ht/gopass-1.8.2/src/github.com/gopasspw/gopass/vendor/github.com/urfave/cli/app.go:268 +0x60c
main.main()
	src/github.com/gopasspw/gopass/main.go:64 +0x2d7

### Expected behavior

Result message to be displayed

### Environment

Windows / OSX High Sierra

gopass 1.8.2 (10b7d6f172a8a99f9d8176a45b847b16b622bc04 2018-06-29 07:39:27) go1.10.3 darwin amd64

See #899 for windows report

**Comment by dominikschulz** [comment]
@martinhoefling Was this fixed by #905? This issue sounds like another `forgot-to-call-init` bug.

**Comment by martinhoefling** [comment]
Yes, will be closed by #903
