### ISSUE TITLE
Two factor authentication on github

### ISSUE THREAD

**Issue by dieguezz** [gopasspw/gopass#906]
### Summary
When enabling two factor authentication on github, i get an error on sync
![ufycjcc - imgur](https://user-images.githubusercontent.com/1161455/43491055-594dee22-9523-11e8-9841-d9deb001b50a.png)

### Steps To Reproduce
`gopass sync`

### Environment
- OS: Mac OS X High Sierra,
- OS version: Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
- gopass Version: 
gopass 1.8.2 (10b7d6f172a8a99f9d8176a45b847b16b622bc04 2018-06-29 07:39:27) go1.10.3 darwin amd64
<root>     -  gpg 2.2.8 - git 2.18.0 -   fs 0.1.0
- Installation method: brew

**Comment by moritzheiber** [comment]
Two ways of solving this:

1. Use SSH for cloning the repository instead.
2. Add a [personal access token](https://github.com/settings/tokens) and use it as a password.

This error isn't specific to gopass, it's how you use GitHub with 2FA enabled.
