### ISSUE TITLE
Feature Request: Suppress gpg warnings via config flag

### ISSUE THREAD

**Issue by mumblez** [gopasspw/gopass#907]
### Summary
Prior to this latest release (1.8.2) I could export and reference a different user's gpg directory and run gopass, e.g. 
```
export GNUPGHOME=/some/other/user/.gnupg
gopass some/secret

gpg: WARNING: unsafe ownership on homedir '/some/other/user/.gnupg'
superDuperSecret
```
I have this in some initialisation scripts when setting up a couple servers before handing it off to designated users for the service(s).

Since this release I now get a gpg warning, (ownership permissions of gpg directory), which breaks my scripts :(
Unfortunately I can't suppress this with gpg arguments, e.g. --no-tty, --batch, --quiet

As a workaround, I copy the service / user's gnupg directory and export that for my initialisation scripts, would be great if we could suppress all gpg warnings with a config flag.

### Environment
- OS: Debian Stretch
- gopass Version: 1.8.2
- Installation method: tagged release (binary)

**Comment by dominikschulz** [comment]
You should be able to add extra GPG Options by setting e.g. `GOPASS_GPG_OPTS="--no-tty"`.

Does that work for you?

**Comment by mumblez** [comment]
Tried that, I still get the warning unfortunately.
It outputs the warning to stderr, then shows the password and exit's cleanly.
If I pipe the command `2>/dev/null` then the warning is suppressed and output is clean for scripts.

**Comment by metalmatze** [comment]
I guess this is more a gpg problem, isn't it?
We could try setting some flags from gopass, but that's it.
@mumblez Can you try to replicate this from gpg directly and see what flags help? Thanks

**Comment by mumblez** [comment]
for security I guess it's better to keep the warnings, it's just that part of the appeal of gopass is that it's a cli tool and scriptable, it's no biggy to amend my scripts to avoid gpg warnings.
