### ISSUE TITLE
1.8.2 commit missing from tagged release

### ISSUE THREAD

**Issue by Foxboron** [gopasspw/gopass#908]
### Summary
The commit for the `1.8.2` release (10b7d6f172a8a99f9d8176a45b847b16b622bc04) is missing from the tagged release it seems.
Causes mild confusion for users as the compiled `1.8.2` version would still tell you it's `1.8.1`. Also looks like there are some missing code changes.

**Comment by dominikschulz** [comment]
Uh, I'm sorry. Seems to be a slight mishap during the last release.

**Comment by Foxboron** [comment]
Np's :)

**Comment by Foxboron** [comment]
There hasn't yet been a release.
