### ISSUE TITLE
..

### ISSUE THREAD

**Issue by OmneBonum** [gopasspw/gopass#910]
### Environment

- OS: [e.g. Mac OS X High Sierra, Ubuntu 18.04, Windows 10, ...]
- OS version: [uname -a]
- gopass Version: [gopass version]
- Installation method: [e.g. from source, brew, gopass repo]

**Comment by tclass** [comment]
What're you trying to say?

**Comment by metalmatze** [comment]
No response, closing. Please reopen if something comes up.
