### ISSUE TITLE
fsck progress incorrect

### ISSUE THREAD

**Issue by muesli** [gopasspw/gopass#911]
### Summary
When running `gopass fsck` the progress bar shows an incorrect amount of total items to be checked. On my system it actually checks 420 objects, even though it estimates only 418 in total:

```
420 of 418 objects checked [###################################################################>] 100.00%
```

### Steps To Reproduce
I'm not yet sure if this is an issue with my `.password-store` or a general counting issue with `gopass fsck`.

**Comment by dominikschulz** [comment]
Thanks for reporting this issue. We should try to fix this eventually, but I don't think it's too bad ;)

**Comment by muesli** [comment]
I agree, it's certainly no showstopper. I haven't had time to look into it myself, but I'll try to get to it this week.

**Comment by martinhoefling** [comment]
@muesli how many stores do you have mounted? Just one?

**Comment by muesli** [comment]
@martinhoefling Correct!

**Comment by muesli** [comment]
Silly bot. Still valid :smile:

**Comment by dominikschulz** [comment]
Cleaning up old and low prio bugs.
This doesn't seem to warrant much attention.
If it's still an issue feel free to send a PR to fix, otherwise I'm going to ignore it.

**Comment by muesli** [comment]
Frankly I find that a bit odd. It's still a reproducible bug and it's certainly not invalid. What's the harm of keeping valid tickets around?

**Comment by dominikschulz** [comment]
Sorry, I'm trying to keep the bug backlog manageable.
At the moment it's hard to see if a bug is still worth paying attention to.
Feel free to reopen if you can verify with a recent release.

**Comment by dominikschulz** [comment]
Sorry, my bad. I could actually reproduce the issue.
It's not really fixed, but at least hidden.
