### ISSUE TITLE
Copy to clipboard does not work under Termux (Android Terminal emulator/Linux environment)

### ISSUE THREAD

**Issue by aral** [gopasspw/gopass#913]
The copy to clipboard functionality does not work under [Termux](https://termux.com/) (an Android Terminal emulator/Linux environment).

This is because the [Clipboard for Go](https://github.com/atotto/clipboard) dependency does not have Termux support.

**Comment by aral** [comment]
Termux support will be implemented once the following pull request is accepted into Clipboard for Go: https://github.com/atotto/clipboard/pull/33 and Gopass updates its dependency to the release that has the patch in it.

**Comment by dominikschulz** [comment]
Thanks a lot. I never tried it on termux. Will update the dependencies once that pr is merged.

**Comment by dominikschulz** [comment]
The reference PR is still in review.
Please ping me once it's merged.

**Comment by aral** [comment]
Thanks for checking, @dominikschulz – just asked if there’s anything else I can do on the PR.

**Comment by aral** [comment]
A quick update: The upstream fix has been merged :)

**Comment by dominikschulz** [comment]
Thanks, will update the dependencies to pull in the fix.

**Comment by dominikschulz** [comment]
Should be fixed already.
We're pinned to v0.1.2 (which includes the fix) of the dependency.
