### ISSUE TITLE
Fundamental usage of gopass

### ISSUE THREAD

**Issue by novakboskov** [gopasspw/gopass#914]
### Summary
I already use gopass on one of my laptops and want to set it up on another one.
What is the basic workflow?

If it's already covered somewhere in the docs, please direct me there. I didn't manage to find it.

### Steps To Reproduce
On a new machine I already did:
- generate gpg
- `gopass clone path/to/my/pass/repo`
- `gopass sync`

### Expected behavior
Even though I can see all the secrets, `gopass show path/to/secret` fails with: `gpg: decryption failed: No secret key`, which is kind of expected since the secret is encrypted using the private key from another machine.

What should I do so as to gain access to all the secrets made on another machine?
Is `gopass` even made to support such a scenario?

### Environment
- OS: Arch Linux
- OS version: Linux 4.14.63-1-lts
- gopass Version: gopass 1.8.2-git+HEAD go1.10.3 linux amd64
- Installation method: `go get`

**Comment by eduncan911** [comment]
First time lurker, so excuse the interruption from an outsider's opinion...  But what you describe, and how `gopass` works is with PGP keys.

If you encrypted a store with a private key on one machine, that store can only be opened using that same private key.  No exceptions.

However, and the reason I am lurking here which I like, `gopass` allows you to add multiple users it seems.  

So you have two options...

**Option 1)** Use the same private key on all machines.  You can export your private key from the other machine with:

    gpg -a --export-secret-keys > my-gpg-private-key.asc

And on your other machine, you can import it with:

    gpg --import < my-gpg-private-key.asc

TIP: Read up on Subkeys.  It complicates an already overly complicated PGP setup.  However, once you grasp the concept of expiring subkeys, while keeping your private keys on an air-gapped machine, you'll really start to appreciate how versatile PGP really is.

**Option 2)** Add additional users.  

I haven't used `gopass` yet (still reading in it and will test drive it this week and next).  However, to add any user to PGP you first need their Public key.  

First, export your Public key from your new computer:

    gpg -a --export your@email.com > my-new-pub-key-on-another-machine.pub.asc

Then you'll need to copy it to your OLD machine and import the public key:

    gpg --import < my-new-pub-key-on-another-machine.pub.asc

You should now have two keys installed on your OLD machine.  One pub/private key set from your original setup.  And now a new public key-only user, from your new machine.  You can verify this with:

    gpg --list-keys

Now that you have two users on your old machine, you'll need to add the user to your `gopass` storage.  

There's where I'll have to stop as I haven't done that yet.  You'll need to read the `gopass` docs to target additional users with your password store.  But it looks simple enough:

```
# https://github.com/gopasspw/gopass/blob/master/docs/features.md#managing-recipients
$ gopass recipients
gopass
└── 0xB5B44266A3683834 - Gopher <gopher@golang.org>

$ gopass recipients add your@email.com
```

**Comment by dewey** [comment]
That's a great write up, thanks. If OP verifies that it works like that for him we could add it to the https://github.com/gopasspw/gopass/blob/master/docs/faq.md - seems like something people will have to go through from time to time.

**Comment by dominikschulz** [comment]
Thanks a lot @eduncan911.
Would be amazing if you could turn that into a PR!

**Comment by eduncan911** [comment]
I'm more than happy to add it to a set of FAQs.  However, I think it needs to be verified first.  I'm still working on my setup across machines.

Also, there are two perspectives here... One from a user trying to use the same store across multiple computers.  The other perspective is to add additional users.

I can add multiple FAQs (I do a lot of technical writing for my clients).  But let me verify everything first.

**Comment by martinhoefling** [comment]
The gopassbridge web extension allows creating new entries.

**Comment by dominikschulz** [comment]
@eduncan911 Would be great if you could contribute some documentation. Technical writing is nothing I'm particular good at.
