### ISSUE TITLE
openBSD: os.Atimespec undefined

### ISSUE THREAD

**Issue by jungle-boogie** [gopasspw/gopass#915]
### Summary

```
$ go get -u github.com/gopasspw/gopass
# github.com/gopasspw/gopass/vendor/gopkg.in/src-d/go-git.v4
gopath/src/github.com/gopasspw/gopass/vendor/gopkg.in/src-d/go-git.v4/worktree_bsd.go:15:36: os.Atimespec undefined (type *syscall.Stat_t has no field or method Atimespec)
```

### Steps To Reproduce

go get -u github.com/gopasspw/gopass

### Expected behavior

A successful build of gopass

### Environment
```
$ gopass -v
gopass 1.8.1-git+HEAD go1.10.1 openbsd amd64
```

```
$ go version
go version go1.10.1 openbsd/amd64
```

openBSD x64 -current

**Comment by jungle-boogie** [comment]
Any ideas on how I can compile gopass on my openBSD machines?

**Comment by dominikschulz** [comment]
Thanks for reporting this issue.
I'm sorry for that. Unfortunately I don't have access to an OpenBSD system right now to debug.
I'll try to update the go-git package.

Maybe we should use build tags for certain experimental features (like go-git) to reduce the amount of potential breakage there ...

**Comment by mschoenlaub** [comment]
Just for reference: https://github.com/src-d/go-git/issues/843

**Comment by jungle-boogie** [comment]
Anyone know how to proceed with this?

**Comment by jungle-boogie** [comment]
I just noticed you're building for a whole bunch of OS':
https://github.com/gopasspw/gopass/releases/tag/v1.8.5

I'm assuming you're cross compiling to get OpenBSD builds? Are the same error message not generated when attempting to cross compile?

**Comment by jungle-boogie** [comment]
huh, I don't get the same message as before when trying to build.

```
$ gopass version
It seems you are new to gopass. Do you want to run the onboarding wizard? [Y/n/q]: n
gopass 1.8.5-git+HEAD go1.12.7 openbsd amd64
<root>     - gpg 2.2.12 - noop 0.0.0 -   fs 0.1.0
Available Crypto Backends: gpgcli, openpgp, plain, xc
Available RCS Backends: gitcli, noop
Available Storage Backends: fs, inmem
```

I'll say this was overcome by other events!
