### ISSUE TITLE
Feature Request: Diceware (xkcd) style password generation

### ISSUE THREAD

**Issue by Gigahawk** [gopasspw/gopass#916]
### Summary
Allow generating word based passwords similar to [this xkcd](https://xkcd.com/936/).

A golang library for this can be found at https://github.com/sethvargo/go-diceware

**Comment by dewey** [comment]
If you already using a password manager that automatically generates secure passwords why would you need to support a method that's mostly useful for people who don't use password managers and want to memorize passwords?

I think that would be encouraging the wrong behavior.

**Comment by Gigahawk** [comment]
It's mostly for accounts/situations where I have a computer with my password manager and I need to login on some other computer.

Ideally you wouldn't want to send the password over some IM service and it's easy to screw up typing an unmemorable password. A word-based password is much easier to instantly commit to short term memory.

**Comment by dominikschulz** [comment]
Thanks for raising this issue.
That is already supported by the -x flag.
