### ISSUE TITLE
Performance decrease with the latest version

### ISSUE THREAD

**Issue by nilskuhn** [gopasspw/gopass#923]
### Summary
General performance decreased with the latest version. I am using gopass a lot and that's really annoying :(
![performanceleakgopass](https://user-images.githubusercontent.com/1001134/45342828-65f85080-b59f-11e8-83c0-132a8a877f12.gif)

Unfortunately I can't say which version introduced the decrease because I did a `go get` yesterday and before I used the version I initially installed for a long time. I would say that was about 4 to 5 months from now. The previous, fast version didn't had the check marks in the output and the console wizard to chose one of the found passwords didn't had the boxes on top and bottom of the screen if that helps.

### Steps To Reproduce
Install latest version from source via `go get github.com/gopasspw/gopass`. The performance to get a password to the clipboard is too slow. Maybe that just happens if one uses many passwords in different stores with different recipients. I didn't tested that.

### Expected behavior
The password should be copied to the clipboard much faster. In the previous version I used there was no remarkable delay.

### Environment
- OS: 
![image](https://user-images.githubusercontent.com/1001134/45342172-668fe780-b59d-11e8-9204-b66bd10638fc.png)
- OS version: 
    
        Linux 4.15.0-32-generic #35~16.04.1-Ubuntu SMP Fri Aug 10 21:54:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- gopass Version: `gopass 1.8.2-git+HEAD go1.10.3 linux amd64` (now)
- Installation method: from source via `go get github.com/gopasspw/gopass`

### Additional context
I am using gopass with several stores. Each with different recipients and with several hundreds of entries overall I guess.

**Comment by metalmatze** [comment]
I've read a [discussion](https://github.com/prometheus/prometheus/pull/4568#issuecomment-419405220) about Go 1.11 new tracing capabilities and we could add these with a lot of effort to gopass.

https://golang.org/doc/go1.11#trace
https://golang.org/pkg/runtime/trace/#hdr-User_annotation

Maybe that should show some slow parts. With a lot of stores I simply expect IO to be the main time consuming part, but that's just a gut feeling.

**Comment by dominikschulz** [comment]
That's a very good idea. I'll try to have a look.

**Comment by briancheldelin** [comment]
This was affecting my workflow greatly so I looked a little into this problem. After profiling I noticed that the program was spending a very large amount of time walking the /proc directory from the github.com/gopasspw/gopass/pkg/clipboard.killPrecedessors() function. 

https://github.com/gopasspw/gopass/blob/909c8ac88bb11b15eee7392924c5a497d50d202f/pkg/clipboard/clipboard_others.go#L41-L42

The performance issue goes away when you remove the call to this function. 

https://github.com/gopasspw/gopass/blob/909c8ac88bb11b15eee7392924c5a497d50d202f/pkg/clipboard/clipboard_others.go#L27

This function was introduced from this commit: https://github.com/gopasspw/gopass/commit/a3d6a23e1ba8675d859fd181da0c42dc87b1d428

I hope this information helps. Cheers!

**Comment by dominikschulz** [comment]
@briancheldelin Thanks, that helps a lot. I'll have a look.

**Comment by blinry** [comment]
I'm also having this problem – would love to see a decreased delay in the future! :)
