### ISSUE TITLE
Add possibility to copy username to clipboard

### ISSUE THREAD

**Issue by nilskuhn** [gopasspw/gopass#925]
### Summary

I would like to have an option to copy the username to the clipboard instead of the password via a separare flag.

I would like to contribute by myself, but I am actually new to the project and would appreciate any comments on whether this is something contributers would also like to see (and so would merge).

### Additional context

Flag could be `-u, --clip-username`. Other suggestions welcome.

Username would be determined from body of secret. We could use a regex to find the key of the username. Could be something like `user|login|username|UserName` (as mentioned in [this thread](https://github.com/gopasspw/gopass/issues/477)).

Workflow if username could be determined successfully:

                $ gopass show -u payp 
                Entry 'payp' not found. Starting search...
                Found exact match in 'path/to/entry/paypal'
                ✔ Copied username of path/to/entry/paypal to clipboard. Will clear in 45 seconds.

If username doesn't exist resp. it could not be determined from body of secret:

                $ gopass show -u payp
                Entry 'payp' not found. Starting search...
                Found exact match in 'path/to/entry/paypal'
                ✗ Username of path/to/entry/paypal could not be determined.

**Comment by metalmatze** [comment]
The current convention in gopass and pass is to have the username at the end of the path. So with your example from above that would lead to `gopass show -u paypal/username`. 
I don't see a way to actually have this being done automatically from the secret body right now, as I expect most people don't store their username in the secret itself.

Hence, I'm not sure if this flag will help much, as the current situation with storing the username has a no real standard and is up to the user to decide.

**Comment by nilskuhn** [comment]
Ok, I didn't realized that convention so far. All my password stores are imported keepass files and the import script I used created a key/value pair for the username automatically in the body of the secret.

                my-password
                UserName: my-username

But one could use the username determined from the body and if that isn't possible or existing one could return the last part of the secrets path.

**Comment by dominikschulz** [comment]
You should be able to implement your desired behaviour in [`action.showHandleOutput`](https://github.com/gopasspw/gopass/blob/master/pkg/action/show.go#L89).
As it doesn't interfere with existing behaviour I don't see a reason why we wouldn't merge it if the PR looks good.

**Comment by dragon788** [comment]
Another option I've been using successfully is storing the username inside the entry in the yaml `username: myuser`, and then querying it with `gopass show -c path/to/entry username`. I believe gopass supports inserting yaml via `insert` or editing the entry and adding `---` below the first line that is the password.

**Comment by nilskuhn** [comment]
That's interesting! Wasn't aware, that it's possible to copy yaml content to clipboard.
Although it would be quite a bit of work for me to transfer all the usernames and I think most further pass based tools like browser plugins wouldn't be able to use usernames from yaml. 
Apart from that I agree that this would be secure and good solution.

**Comment by espoelstra** [comment]
@nilskuhn Actually gopass-bridge does use the usernames from yaml I believe. Depending on your current secret layout if you are storing them as `UserName: username` you may just be able to add a `---` after the first line to get `gopass show secret/site/path UserName` to print out your secret. With the latest version of `gopass` it appears the Yaml `---` divider might not even be necessary?

**Comment by dominikschulz** [comment]
Correct, gopass now supports simple key value as well as fully fledged yaml.
