### ISSUE TITLE
Enhance editing existing secrets

### ISSUE THREAD

**Issue by nilskuhn** [gopasspw/gopass#927]
### Summary

Editing an existing entry is a bit inconvenient at the moment, I think. If I don't know the exact path of the secret to edit, first I have to search for the path via `find` and then I could edit it copying the printed path and open that path via `edit` command.

### Expected behavior

It would be nice if `edit` command would open same wizard than `show` if the given secret name isn't unique instead of opening an empty editor to create a new secret (which isn't what most users want to do if they type `gopass edit <secret-xy>`, I assume). From within the wizard it should be possible to switch to vim (or whatever your console editor of choice is) for one of the listed secrets via a keyboard shortcut.

I would like to have that possibility to edit one of the listed secrets from within the wizard even if it was opened via `show` command. So we don't have to implement different variants of the wizard, imho.

**Comment by metalmatze** [comment]
I'm not aware that this is a wanted inconsistency, is it @dominikschulz?
Please go ahead and create a PR if you want to improve situation. ☺️

**Comment by dominikschulz** [comment]
Thanks for creating this issue. Actually this is something I wanted to change for some time, too.
It's quite annoying and shouldn't be hard to fix.
Maybe I can work on that soon ...

**Comment by nilskuhn** [comment]
It would be nice to have the opportunity to edit an entry listed in the wizard even if I opened it via `gopass show` command. So in addition to the existing options 
```
<↑/↓> to change the selection, <→> to show, <←> to copy, <s> to sync, <ESC> to quit
``` 
I would like to have an option `<e> to edit` which is always there.

The only difference in the wizard whether it was opened via `show` or `edit` should be the default action which happens if I am hitting enter.

**Comment by dominikschulz** [comment]
Sure, we can probably do that.
