### ISSUE TITLE
Feature Request: Audit should suggest updating old passwords

### ISSUE THREAD

**Issue by Bekreth** [gopasspw/gopass#928]
There should be a configuration option to remind users to update there passwords.  During the audit, a check should be made to verify the age of a password and potentially recommend updating it.

**Comment by dominikschulz** [comment]
So you want to be reminded to change "old" passwords after a certain time?

**Comment by metalmatze** [comment]
Seems like a good idea. The open question is how to define old. That probably needs to be a config option or command flag.

**Comment by Bekreth** [comment]
Yes.  Either it be a globalized config where any password that's more than X-days old should be updated, or maybe even have it be an option during password generation that a given password might have its own expiration date.  This would be helpful for highly sensitive data that should have its password updated rather regularly

**Comment by cljoly** [comment]
I would be interested in implementing this. I see two possible levels and would start with *Level 1*, if you agree.

## Level 1: Simple last commit date

We would basically go through each file, check the last modification date (i.e. the last commit date with the git backend) and report it if it is older than X day (or some other criteria like after a certain date, etc).

## Level 2: Go deeper and really check the password

What I describe above has a flaw.

Suppose on 2019-01-01, I add the entry `Account/test` with content
```
mySuperPassword
```

and on 2019-03-01, I edit it to get
```
mySuperPassword
---
user: me@my.email
```
then *Level 1* would detect the password as changed on 2019-03-01, even though it is older than that (created on 2019-01-01).

Detecting this would require a sort of git blame or own implementation of diffing between file.

## Beyond: refinements

There may be further refinements.

1. I don’t know how renaming would be detected for instance.
2. We could extend this to other fields (`url:`, `user:`, …).

**Comment by cljoly** [comment]
ping @dominikschulz @metalmatze :grin:

**Comment by metalmatze** [comment]
To begin with I'd keep it simple and just make something work based on the file modified date, then we can still talk about improving later on. :)

**Comment by cljoly** [comment]
Ok, I will start working on it next week-end probably.
