### ISSUE TITLE
Inconsistent "help" pages

### ISSUE THREAD

**Issue by Bekreth** [gopasspw/gopass#933]
Within the CLI, there are several command where the documentation between "gopass [COMMAND] --help" are vastly different than "gopass help [COMMAND]". Most notably with "gopass help mounts".   The documentation should be brought into alignment, or possibly one of these help pathways should be gotten rid of in favor of having only one way to read up on help pages.

**Comment by dominikschulz** [comment]
Nice find, thanks. Will have a look.

**Comment by dominikschulz** [comment]
I had a brief look and realised that the help pages are generated by the CLI library we use and thus not that easy to change.

If there are specific improvements you'd like to see feel free to open a PR.
