### ISSUE TITLE
audit does not terminate on fresh install

### ISSUE THREAD

**Issue by pille** [gopasspw/gopass#934]
### Summary
running ```audit``` after a fresh install with 0 secrets does not terminate and there's no CPU usage.

### Steps To Reproduce

1. install gopass
2. initialize password-store
3. ```% gopass audit```                                          
```Checking 0 secrets. This may take some time ...```

### Expected behavior
terminate (immediately)

### Environment
```gopass 1.6.11 go1.10.3 linux amd64```

**Comment by dominikschulz** [comment]
Can't reproduce with current master build.

**Comment by pille** [comment]
you're right. can't reproduce with current v1.8.2.
i was using an outdated version, since the ebuild is out of date: https://github.com/Dr-Terrible/go-overlay/issues/109
