### ISSUE TITLE
Problem init second store

### ISSUE THREAD

**Issue by reinerj** [gopasspw/gopass#942]
### Summary
Hello,

I had already reported a problem that the wrong key is selected again and again. As already described in my other ticket we have a second problem. 

We can initialize a store with gopass init. If we want to add a second one we get the problem that the public key cannot be found. 

We have the following situation. 

We have a GIT server on which different repositories have been created which should also be initiated by Gopass. 

The first one works without problems with gopass init.

What exactly would the second command be to add a second repo with gopass? Maybe there is an error from our side. 

For example, what I had just tried again:

gopass init reiner@xxxxx.com --store xxxx-internal --path gpgcli-gitcli-fs+file:///Users/reinerjung/.password-xxxxx-internal ssh://git@xxxxx.com:2222/xxxxx-intern.git   

I had already asked on the IRC but the suggestion from there had not led to success. 

### Steps To Reproduce
Add a second sub repo when a first one was done with the wizard

### Expected behavior
A second repo could be initialized and mounted 

### Environment
Client 

- OS: Mac OS Mojave 
- OS version: 10.14
- gopass Version: 1.8.2
- Installation method: brew

Server

- OS Ubuntu 18.04
- Gitolite (We did try it also with Gitlab) 
- Git Server 2.17.1

**Comment by dominikschulz** [comment]
You are trying to initialize an additional store, not clone an existing one from a Git remote, correct?

**Comment by dominikschulz** [comment]
Ok, thanks. Understood. The syntax for this operation is currently not very user friendly. We might want to add a helper for that.

**Comment by reinerj** [comment]
Thanks for the quick response. In my case I am no sure it would work with the helper as I still have this problem with the key selection. When you could lt me know how I can run this command manually I am more then happy to try it out. 

Thanks
Reiner

**Comment by reinerj** [comment]
Hi,

the first part work but the second part fail

gopass git remote add --store xxxx-intern ssh://git@xxxxx.com:2222/xxxxx-intern.git

Error: Usage: gopass git remote add <REMOTE> <URL>
