### ISSUE TITLE
Windows:  The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by rhnewtron** [gopasspw/gopass#950]
### Summary
when startion gopass on Windows 10 I get:

```
failed to check dir \\C:\Users\$USERNAME\.password-store\.git: CreateFile \\C:\Users\$USERNAME\.password-store\.git: The filename, directory name, or volume label syntax is incorrect.
```

### Steps To Reproduce
run "gopass" 1.8.3 on Windows 10

### Expected behavior
Should run :)

### Environment

- OS: Windows 10 (1709)
- gopass Version: 1.8.3
- Installation method: extract binary from releases page

**Comment by martinhoefling** [comment]
@rhnewtron Can you post your gopass config? I tested the most recent release and a current build on windows 10 and did not encounter any problems.

**Comment by dominikschulz** [comment]
Not reproducible.
