### ISSUE TITLE
gopass recipients not showing subfolder id's

### ISSUE THREAD

**Issue by rhnewtron** [gopasspw/gopass#954]
### Summary
When using the subfolder ID feature (.gpg-id file in subfolder of repo), gopass recipients does not show this hierarchy of keys. This is not nice, as audibility is somehow limited.

### Steps To Reproduce
* Initialize a password db with some keys on the top level
* create a .gpg-id file in a subfolder with another key
* run ```gopass revipients```

### Expected behavior
Hierarchy like this

```
gopass
├── PROJECT (/home/vagrant/.password-store-PROJECT)
│   ├── 0xaaaaaaaaaaaaaaaaaa - user1
│   ├── 0xbbbbbbbbbbbbbbbb - user2
│   └── 0xcccccccccccccccccccc - user3
|     |-----| SUBFOLDER
|             |--- 0xdddddddddddddddd - user4
└── 0x11111111111111111 - userN
```

### Environment
Centos7
gopass 1.8.3

**Comment by dominikschulz** [comment]
Yes, indeed. Keeping this pinned until someone can take a turn on this.
