### ISSUE TITLE
Make install failing while building from tag v1.8.2

### ISSUE THREAD

**Issue by mtrovo** [gopasspw/gopass#956]
### Summary
I'm getting the following problem while trying to build gopass pointing my repo to the tag v1.8.2 (latest release right now).

```
make install
-n >> BUILD, version = 1.8.2/10b7d6f1, output = gopass
# github.com/gopasspw/gopass
github.com/gopasspw/gopass/vendor/golang.org/x/crypto/blake2b.supportsAVX2: relocation target runtime.support_avx2 not defined
github.com/gopasspw/gopass/vendor/golang.org/x/crypto/blake2b.supportsAVX: relocation target runtime.support_avx not defined
make: *** [gopass] Error 2
```

The reason I'm using this specific version is because I'm trying to build it from the source using the [formula provided on homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gopass.rb), which is configured to fetch the package from tag v.1.8.2.

Installing from the pre build packages work fine.

Building from the source using the current master works fine as well, is there a way to generate a new release to address this problem?

### Steps To Reproduce
- Checkout a clean copy of the repo
- `git checkout v1.8.2`
- `make install`

### Expected behavior
A fresh version of gopass is generated from the sources and installed locally.

### Environment
- OS: Mac OS X High Sierra
- OS version: Darwin MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
- gopass Version: v1.8.2
- Installation method: from source

**Comment by muesli** [comment]
Updating the dependency should fix this issue.

**Comment by dominikschulz** [comment]
Thanks @muesli, will try.

**Comment by muesli** [comment]
@dominikschulz I agree, would be good to have that in 1.8.3 fairly asap, because as of now the latest gopass release doesn't build with the latest Go version anymore.

**Comment by martinhoefling** [comment]
I have checked `make install from master`
```
make install
go: downloading github.com/dominikschulz/github-releases v0.0.2
-n >> BUILD, version = 1.8.6/e9a5a4b3, output = gopass
 [OK] 
>> bash completion, output = bash.completion [OK] 
>> fish completion, output = fish.completion [OK] 
>> zsh completion, output = zsh.completion [OK] 
 [OK] 
-n >> INSTALL, version = 1.8.6
 [OK] 
```

Seems to work now
