### ISSUE TITLE
editing an entry with search creates a new entry instead of editing existing one

### ISSUE THREAD

**Issue by mdeous** [gopasspw/gopass#957]
### Summary
When editing an entry, if the exact entry name isn't provided, `gopass` will search for matching ones. Selecting one of the search results and modifying the content creates a new entry (named after the passed argument) instead of modifying the content of the selected one.

### Steps To Reproduce
- `gopass generate Test/testentry`
- `gopass generate Test/other-testentry`
- `gopass edit test`
- Select `Test/testentry` in the search results
- Edit the content and save the entry

&rarr; A new `test` entry has been created with the edited content, and `Test/testentry` content is left untouched

### Expected behavior
- The item selected in the search results should be saved with the new content
- No new item should be created

### Environment
- OS: Ubuntu 18.04
- OS version: 4.15.0-36-generic
- Go version: 1.10.1
- gopass Version: gopass 1.8.2-git+HEAD
- Installation method: `go get`

**Comment by dominikschulz** [comment]
Aww, thanks. Missed that when adding the search feature to edit. Will have a look.
