### ISSUE TITLE
Add an option to generate additional passwords in a given file (multi-line)

### ISSUE THREAD

**Issue by lewisdiamond** [gopasspw/gopass#962]
For example
`gopass generate google.com/my_account`
`gopass generate --append google.com/my_account`
would result in a file with the following content
```
FIRST_RANDOM_PASSWORD
SECOND_RANDOM_PASSWORD
```
This would simply make it easier to generate random security questions answers

**Comment by dominikschulz** [comment]
Thanks for the suggestion.

What works right now is using the K/V feature like this:

```
gopass generate google.com/my_account
gopass generate google.com/my_account question1
```

However we might consider adding `--append` as well. It would be a small change.
But it might be confusing to have multiple unlabelled entries in one secret.

Thoughts?

**Comment by lewisdiamond** [comment]
Nah if that's already support I'll close this.
However, I think this should be documented as it doesn't show up in the docs or the cli help.
