### ISSUE TITLE
Nested bash-completion not working

### ISSUE THREAD

**Issue by benyanke** [gopasspw/gopass#963]
### Summary
Given a tree of passwords deeper than 2, the bash completion fails.

### Steps To Reproduce
Setup the following theoretical tree:

- personal/site1/pw1
- personal/site1/pw2
- personal/site2/pw1
- personal/site2/pw2
- work/site3/pw1
- work/site3/pw2

Then go through the following steps:

```
gopass per[tab]
gopass personal[tab][tab]
```

### Expected behavior
Expected behavior here is a listing of command options, as well as a listing of `site1` and `site2` so that you can quickly. Instead this autocompletion only goes one deep, forcing the user to manually type the rest of the path.

### Environment

- OS: KDE Neon (Ubuntu 18.04)
- OS version: Linux [hostname] 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- gopass Version: gopass 1.8.2-git+HEAD go1.10.1 linux amd64
- Installation method: go get

<!--

**Comment by dominikschulz** [comment]
Thank you for reporting this issue. This is definitely supposed to be working.
There have been some changes to the autocompletion recently which might have broken this.
I'll try to have a look soon.

**Comment by n3ph** [comment]
Hit's us today. Very annoying - Especially when having a lots of entries in the password store..
```console
18:22 n3ph@mag-xps ~ ✔  gopass | wc -l 
827
18:23 n3ph@mag-xps ~ ✔  
```

As I have no clue what version I was using before, I would probably need to try version by version downwards to get back the completion for the tree.. 

Please increase the priority for this issue...

**Comment by benyanke** [comment]
@n3ph Agreed - I have to go back to `pass` frequently for this feature (Thankfully it's easy to go back and forth between the two on a terminal).

**Comment by benyanke** [comment]
I wish I knew more about completion, otherwise I'd help out.

**Comment by AnomalRoil** [comment]
The Zsh autocompletion is actually 100% independent of the `cli` package and the `action.Complete`.
For Zsh, we are using the so-called "autoloaded completion file", which is generated using a template and the `gopass list --flat` command. 

I am not familiar with bash, but the Zsh completion works quite well now. You should give it a try, it even autocompletes folders when inserting new passwords. :smiley: 
By the way, if you aren't already using [dmenu or rofi along with xdotool to auto-type passwords](https://github.com/gopasspw/gopass/blob/master/docs/setup.md#dmenu--rofi-support), you should give it a try, just add a keybinding such as alt-v that runs the commands and you'll see, it's a life-changer.

I can try to give bash a look maybe next week, but if you have already an idea how to fix it, you should go ahead @dominikschulz since the Zsh completion won't be affected at all as long as we still have `gopass list --flat`.

**Comment by dominikschulz** [comment]
@AnomalRoil thank you very much for this information. That sounds great. I will try to give bash another look, but any help with that is highly appreciated.

**Comment by pdecat** [comment]
Same issue here after updating.

The commit that breaks this is https://github.com/gopasspw/gopass/commit/af794f63fe66e959f9ec30121e4d1bc3a90239d0:

```
# git checkout af794f63fe66e959f9ec30121e4d1bc3a90239d0
Previous HEAD position was 2415d23 Use valid crypto backend for key selection (#889)
HEAD is now at af794f6 Limit bash completion to current scope (#930)
# go install
# gopass show websites[TAB] websites/[TAB] websites/[TAB] websites/[TAB] websites/[TAB] ^C
```
```
# git checkout af794f63fe66e959f9ec30121e4d1bc3a90239d0~
Previous HEAD position was af794f6 Limit bash completion to current scope (#930)
HEAD is now at 4c05308 Update setup documentation. Add macOS related commands. (#924)
# go install
# gopass show websites/[TAB]
websites/accounts.xxxx.xxxx/xxxx@xxxx.com      websites/xxxx.io/xxxx@xxxx.com                  websites/xxxx.xxxx.fr/xxxx@xxxx.org
websites/xxxx.com/xxxx@xxxx.org        websites/xxxx.xxxx.org/xxxx                    
```

**Comment by pdecat** [comment]
It does break that.
I've been tinkering with this a little but did not find a complete solution yet: https://github.com/pdecat/gopass/commit/88482815c498d0bfb68fc1aa17a7c132fef81cec

```
# gopass w[TAB]ebsites/ w[TAB]ebsites/[TAB]
websites/accounts.xxxx.xxxx/xxxx@xxxx.com      websites/xxxx.io/xxxx@xxxx.com                  websites/xxxx.xxxx.fr/xxxx@xxxx.org
websites/xxxx.com/xxxx@xxxx.org        websites/xxxx.xxxx.org/xxxx
```

Also adding the following changes to `_gopass_bash_autocomplete()` help but makes it less than optimal:

```
diff --git a/pkg/action/completion.go b/pkg/action/completion.go
index e29da21..cb586ba 100644
--- a/pkg/action/completion.go
+++ b/pkg/action/completion.go
@@ -97,9 +97,10 @@ set -A complete_gopass -- $PASS_LIST %s
 func (s *Action) CompletionBash(c *cli.Context) error {
        out := `_gopass_bash_autocomplete() {
      local cur opts base
-     COMPREPLY=()
+        COMPREPLY=()
+        compopt -o nospace
      cur="${COMP_WORDS[COMP_CWORD]}"
-     opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )
+     opts=$( ${COMP_WORDS[0]} ${cur} --generate-bash-completion )
      local IFS=$'\n'
      COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
      return 0
```

**Comment by dafta** [comment]
This has been broken for a while. Maybe it would be best to revert it and work on #926 instead of keeping it and working on fixing bash completion so that people's workflow doesn't need to change while it's broken.

**Comment by dominikschulz** [comment]
@dafta I agree, I try to take care of this soon.
