### ISSUE TITLE
Add `--store` argument to insert command

### ISSUE THREAD

**Issue by balasankarc** [gopasspw/gopass#964]
### Summary

Currently there is no way to specify the store while inserting a secret. Though `gopass create` supports it, using `create` forces one to use one of the five predefined types of secrets, thus forcing a specific directory structure on the user.

`gopass insert digitalocean.com/username1` does what is needed, and creates the directory structure as expected. But it uses the default password store. What is required is to create the digitalocean directory inside a different store, say `personal`, so the directory structure will be `~/.password-store-personal/digitalocean/username1`. 

Using `gopass create --store personal` and selecting `Website` as secret type causes the directory structure to be `~/.password-store-personal/websites/digitalocean/username1`. There is no way to skip the `websites` portion there.

**Comment by balasankarc** [comment]
Just realized I can do `gopass insert personal/digitalocean/username1` and it will auto-detect the store. That was not intuitive, especially when there is an explicit `--store` argument available.

Maintainers, feel free to close this issue. But, personally I feel `--store` could be made explicit and/or docs could be added.

**Comment by dominikschulz** [comment]
Thanks for reporting this issue. I see the UX implications here and we'll certainly consider how we can improve this.

**Comment by zioalex** [comment]
I also would like the option to specify the store to use.

**Comment by jverhoelen** [comment]
But what would it be for since the store detection can already be done via the secret path? I personally like how it is organized currently. Or shall it be possible to have a path multiple times if it is contained in different stores?
