### ISSUE TITLE
ZSH completion is broken due to bad quoting in commands.go

### ISSUE THREAD

**Issue by doronbehar** [gopasspw/gopass#966]
### Summary
I assume [`commands.go`](https://github.com/gopasspw/gopass/blob/00de84a305286f6d5983261372d8cd0b6a2fdea9/commands.go) is responsible for automatically generating ZSH completion. Here:
https://github.com/gopasspw/gopass/blob/00de84a305286f6d5983261372d8cd0b6a2fdea9/commands.go#L538
The word `FILE` is quoted with `` ` `` and when ZSH parses the completion function it tries to evaluate the command `FILE` which (usually) doesn't exist.

### Steps To Reproduce

```
$ gopass otp -<tab>
zsh: command not found: FILE
zsh: command not found: FILE
zsh: command not found: FILE
```

### Expected behavior

```
$ gopass otp -<tab>
Completing no arguments
Completing option
Completing corrections
--clip  -- Copy the time based token into the clipboard
--qr    -- Write QR code to FILE
```

### Environment

- OS: Arch Linux
- OS version: `Linux NUC 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux`
- gopass Version:
```
gopass 1.8.2 (2018-08-03 20:31:47) go1.10.3 linux amd64
<root>     - gpg 2.2.10 - git 2.19.1 -   fs 0.1.0
```
- Installation method: Arch Linux community repository.

### Additional context

This issue is completely unrelated to #585 which should be closed IMO since it is obvious the user who opened it is not familiar with ZSH's completion system.

It's very easy to work around this issue by creating a file name `_gopass` in your `$fpath` where `FILE` is not quoted there.

**Comment by metalmatze** [comment]
Thanks. I can reproduce this on my systems. Would you mind creating a PR for this?

**Comment by doronbehar** [comment]
Kindly, but I still think this should be reported upstream to where the library that configures the command line options - [`github.com/urfave/cli`](https://github.com/urfave/cli)?

**Comment by metalmatze** [comment]
I think we switched to a self maintained version at some point:
https://github.com/gopasspw/gopass/blob/master/pkg/completion/zsh/template.go

**Comment by doronbehar** [comment]
BTW just out of curiosity in Go development, why don't you use submodules with links to your own forks?

**Comment by metalmatze** [comment]
This should give you a few more details:
https://github.com/golang/dep/issues/1240

Go is actually moving away from `vendor/` and dep again. [Go modules](https://github.com/golang/go/wiki/Modules) is the thing for the future. But lets not get too much off topic here. Happy to help elsewhere. :wink:

**Comment by dominikschulz** [comment]
IMHO git submodules are somewhat broken and the useability and the tool support is really bad. Also Go Modules might be the way to go in the future.
