### ISSUE TITLE
Gopass git setup

### ISSUE THREAD

**Issue by christian-heusel** [gopasspw/gopass#968]
### Summary
Tl;dr **git** behavior in the initial setup

### Steps To Reproduce

`gopass` uses the 3rd Mail of my GPG-key for commits

### Expected behavior

It uses the primary mail or just applys my global git config

### Environment

- OS: `Arch Linux`
- OS version: `Linux pioneer 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux`
- gopass Version: `gopass 1.8.2 (2018-08-03 20:31:47) go1.10.3 linux amd64`
- Installation method: https://aur.archlinux.org/packages/gopass-git/

### Additional context

```
chris@pioneer ~ » gopass recipients
gopass
├── MyStore (/home/chris/.password-store-MyStore)
│   └── 0xA3AA55C37A759E7C - Christian Heusel <chris@mathphys.stura.uni-heidelberg.de>
└── 0xA3AA55C37A759E7C - Christian Heusel <chris@mathphys.stura.uni-heidelberg.de>

chris@pioneer ~ » gpg --list-keys Christian                                                                                                                                                                 
uid           [ultimate] Christian Heusel <christian@heusel.eu>
uid           [ultimate] Christian Heusel <c.heusel@stud.uni-heidelberg.de>
uid           [ultimate] Christian Heusel <chris@mathphys.stura.uni-heidelberg.de>
```

**Comment by dominikschulz** [comment]
I agree that we should default to the global git config if there is one. Should be easy to detect.

However if there is none, I'm not sure if we can select the "first" sub id. Afaik they are unordered, or aren't they?

**Comment by TheEbolaDoc** [comment]
Well in all the searches they appear sorted by the date of creation, but I think you are right that there is no "real" order ... :smiley:

**Comment by dominikschulz** [comment]
The `golang.org/x/crypto/openpgp` package provides a `map[string]*Identity` which is unordered.
The on-disk keyring is probably stored in order of creation, but this isn't available through this interface.

**Comment by TheEbolaDoc** [comment]
But wouldnt it make sense to ask the user which one he wants to use if multiple identities are provided? :)
Thanks for all the input tho :+1:

**Comment by dominikschulz** [comment]
Using the global git config if it exists is definitely we should do.
Also we may ask the user to select an identity. If someone wants to do it, go ahead.

**Comment by christian-heusel** [comment]
Hey @dominikschulz, I just want to say thank you! ❤️  I really really appreciate that you took the time to make this work and the countless hours of work you put into `gopass` in general! 😃

**Comment by dominikschulz** [comment]
Thanks a lot. Our users feedback is very important to me. So any kind of feedback absolutely helps to drive this project forward.

Please give the feature a try once you get a chance to and report back if anything doesn't work as expected.
