### ISSUE TITLE
windows: "failed to retrieve secret: Failed to decrypt"

### ISSUE THREAD

**Issue by colemickens** [gopasspw/gopass#972]
### Summary
I can't seem to get `gopass` to open anything on Windows.

### Steps To Reproduce
1. Install `gopass` by downloading the exec and putting in on the PATH.
2. Manually clone existing repo.
3. Fix the config, since the Windows path handling is buggy and neither of the open PRs are merged.
   a) And note, this must be done manually because all `gopass config path <whatever>` commands fail, no matter what format you use for `<whatever>`. (I should file a separate bug.)
4. Try to open a password entry.

### Expected behavior
1. It works. GPG can access my card, all SSH scenarios work, and gopass is parsing the store correctly, so everything is in place.

### Environment

- OS: Windows 10
- OS version: Fall update 2018
- gopass Version: 1.8.2 10b7d6 go1.10 windows amd64
- Installation method: gopass official release.

`gpg --card-status` shows my card, as expected.

**Comment by pmoros** [comment]
I had the same issue with GPG in Windows installed through choco... for some weird reason GPG creates two folders, one in C:\Users\myuser\.gnupg and the other in C:\Users\myuser\AppData\Roaming\gnupg I noticed that in the second one the privates keys were missing, so I copied them from the first folder and it worked!
