### ISSUE TITLE
Agent

### ISSUE THREAD

**Issue by colemickens** [gopasspw/gopass#973]
Are there any docs anywhere for what `gopass agent` does or is used/useful for?

**Comment by dominikschulz** [comment]
This is an experimental custom Agent that can cache credentials much like the GPG or SSH agents do. It's useful if you want to test the pure-Go crypto backends.

This should be added to the docs, though.

**Comment by blinry** [comment]
Hi, new gopass user here! :) Like @colemickens, I also have no idea what gopass-agent does, and would love to see some documentation for it! Thanks!
