### ISSUE TITLE
gopassbridge on Windows does not know git $PATH

### ISSUE THREAD

**Issue by Spass1966** [gopasspw/gopass#984]
![screenshot 9](https://user-images.githubusercontent.com/8585623/48507834-4b677f80-e84d-11e8-9bd7-6179fb2cc653.png)

On attempting to create any new secret, the message shown in screenshot appears. `gopass` itself knows the path of git. Git itself comes from a bog-standard install from git-scm.com

**Comment by taohansen** [comment]
I suppose not. Let me know if I can perform any tests on my end.
