### ISSUE TITLE
gopass audit incorrect on binary secrets

### ISSUE THREAD

**Issue by astromechza** [gopasspw/gopass#991]
### Summary

Since `gopass binary` stores the encoded secret in the "body" of the entry, `gopass audit` detects all the binary secrets as being empty and all whitespace.

I think either the audit needs to look at the body as well, or `gopass binary` should be storing the encoded secret in the password line (one line of base64) and not in the "body" lines.

This is also why `gopass show` ignores the safecontent settings for binary entries.

### Steps To Reproduce

```
$ gopass init -s test
$ echo hello | gopass binary cat test/one
$ echo world | gopass binary cat test/two
$ echo world | gopass binary cat test/two-copy
$ gopass audit test
Detected a shared secret for:
	- test/two-copy.b64
	- test/two.b64
	- test/one.b64
Password is empty or all whitespace:
	- test/two-copy.b64
	- test/two.b64
	- test/one.b64
```

### Expected behavior

Expected no whitespace warnings, and expected a single shared secret for two and two-copy.

### Environment

```
gopass 1.8.2 (10b7d6f172a8a99f9d8176a45b847b16b622bc04 2018-06-29 07:39:27) go1.10.3 darwin amd64
<root>     - gpg 2.2.10 - git 2.17.2 -   fs 0.1.0
```

**Comment by AstromechZA** [comment]
I assume this is because the base64 encoded content _could_ be multiline (split into 80-columns). In that case `gopass audit` could behave differently on b64 secrets.

**Comment by dominikschulz** [comment]
Thanks for reporting this issue.

Your reasoning sounds good, we'll try to fix that.

**Comment by dominikschulz** [comment]
Audit should ignore binary secrets.
Or actually any secret without an explicit password set.
