### ISSUE TITLE
'Unknown switch' error on Windows using Cmder/ConEmu

### ISSUE THREAD

**Issue by theothermatt** [gopasspw/gopass#993]
### Summary
When running `gopass` in Windows 7 using the Cmder console emulator (which itself uses ConEmu), a window pops up twice, saying the same thing each time:

Window title:  `ConEmu 180528 [32]`
Window contents:
```
Unknown switch specified:

--version

Visit website to get thorough switches description:
https://conemu.github.io/en/ConEmuArgs.html

Or run 'ConEmu.exe -?' to get the brief.
```

Gopass works fine in the standard Windows 7 terminal and mintty provided by Git.

### Steps To Reproduce
1.  Install Cmder.
2.  Install Git for Windows to provide both git and gpg
3.  Download gopass binary for Windows and install.  Edit %PATH% accordingly.
4.  Run gopass in Cmder.

### Expected behavior
Windows/dialog boxes shouldn't appear everytime gopass is run.

### Environment

- OS: Windows 7
- OS version: 6.1 (Build 7601: Service Pack 1) as reported by `winver`
- gopass Version: 1.8.3 (amd64)
- Installation method: Download of gopass binary from releases page.

**Comment by iquiw** [comment]
Tracked this.

On ConEmu, `PATH` environment variable has `Somwhere\ConEmu\ConEmu` as its component and there exists `Somwhere\ConEmu\ConEmu.exe` also.

In `searchPath()` function (`pkg/backend/crypto/gpg/cli/gpg_windows.go`), `bin` value is empty string and `exec.LookPath("")` returns `Somwhere\ConEmu\ConEmu.exe`.

**Comment by iquiw** [comment]
@dominikschulz @theothermatt This should be fixed in master.
